### ISSUE TITLE
1.875m Battery has wrong node size

### ISSUE THREAD

**Issue by help137** [PorktoberRevolution/ReStocked#1001]
The 1.875M battery (2.5K Stackable) has size 1 nodes, where all other 1.875m parts have size 2 nodes. Using it with size 1 nodes causes extreme wobblyness at the connection.

**Comment by Poodmund** [comment]
Should be resolved with https://github.com/PorktoberRevolution/ReStocked/commit/77106d0a22270d274131ec43b1e033c9604ffeca. All resolved the same issue with some other ReStock+ 1.875m diameter parts.
