### ISSUE TITLE
mk2landercan rear hatch is facing sideways

### ISSUE THREAD

**Issue by JonnyOThan** [PorktoberRevolution/ReStocked#1008]
This causes the kerbal to spawn facing sideways for a frame before they grab the ladder.   It also caused me quite a headache with the FreeIva hatch logic :p

![image](https://github.com/PorktoberRevolution/ReStocked/assets/9804078/a89938d0-63d3-4152-b11d-1786f0dd7c8b)

![image](https://github.com/PorktoberRevolution/ReStocked/assets/9804078/7e70a7d9-b26c-44db-b328-e04a09cd786f)
 (normally the +Z axis should be facing the part)

**Comment by Poodmund** [comment]
For future reference; the Mk2-Lander/Common/airlock/airlock.001/collider:airlock node needs to be rotated as follows:

X: 90
Y: 0
X: -180

**Comment by ChrisAdderley** [comment]
Fixed in e631438, will be in next version
