### ISSUE TITLE
Position of 1.875m engines from Restock+ in the tech tree

### ISSUE THREAD

**Issue by Alex-1248** [PorktoberRevolution/ReStocked#1012]
If Making History is not installed and Restock+ is installed, 1.875m engines are located much further in the tech tree than their corresponding fuel tanks. I'm not sure, but it seems to me that some engines should be moved to the left. For example, Caravel and Schnauzer have similar characteristics to Bobcat and Cheetah respectively, so they could be moved to the same tech nodes.

**Comment by Poodmund** [comment]
The Caravel and Schnauzer Restock+ engines are not supposed to be direct replacements of any of the Making History engines as such, as there are 4 Making History engines at this size and only 2 in Restock+. The idea was to try and actually put these engines somewhere, and spec them as such, to fill niches in the vanilla KSP line-up.

> ... the overall the idea of the RS+ MH engines is to try to make a set of 1.875m engines out of the MH stuff versus trying to ape (sic) them.
