### ISSUE TITLE
Restock Plus is duplicating parts. 

### ISSUE THREAD

**Issue by douglasdtlltd** [PorktoberRevolution/ReStocked#1016]
The Pug and Valiant engines are dupilcated in the editor. Each engine has just two versions, one with no variants, and another with 6 variants. 

Using the lastest version of restock, plus and modulemananger.

**Comment by Poodmund** [comment]
Sounds like you're using another mod that adds Porkjets parts to the game: https://forum.kerbalspaceprogram.com/topic/172232-112x-missinghistory-v193-handy-parts-to-complement-making-history/

**Comment by Poodmund** [comment]
Closed, as not a bug.
