### ISSUE TITLE
Wheesley and Whiplash engines dont show up.

### ISSUE THREAD

**Issue by inojakal** [PorktoberRevolution/ReStocked#1018]
**Describe the bug**
When using ReStock, the 2 above jet engines arent appearing in my game. have uninstalled the mod and they came back, reinstall and they went back to being unusable. can drop them into the builder, but they then appear as red circles and can no longer be interacted with. looking in the assets folder they dont appear to have any textures in there.

**Screenshots**
(https://steamuserimages-a.akamaihd.net/ugc/2515906492599255910/CEF2E8A549BCFC24B89E9E9CBE75B450CF473521/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false)

**List of mods installed:**
 - Restock
 - Restock+

**Comment by inojakal** [comment]
I tried doing the whitelist method to allow it to load from stock with the following:
Squad/Parts/jetEngineBasic
Squad/Parts/jetEnginesTurbo
this worked for the whiplash engine but not the wheesley engine

**Comment by drewcassidy** [comment]
Please include a log

**Comment by drewcassidy** [comment]
Closing due to lack of information
