### ISSUE TITLE
Oscar A tank packed volume 180L s/b 80L

### ISSUE THREAD

**Issue by Krazy0** [PorktoberRevolution/ReStocked#1025]
**Describe the bug**
Based on Oscar B packed volume of 160L, the Oscar A should be 160/2 = 80 L but it's 180 L. Seems like a typo. 
Changing to 80L shouldn't break existing saves because it would be smaller volume not larger.

**List of mods installed:**
KSP v1.12.5 Win
Restock/ Restock+ v1.5.0
dozens of others (hopefully irrelevant)

**Comment by Poodmund** [comment]
Will get set to 85L.
