### ISSUE TITLE
Incorrect dragcube of 1.875m decoupler/separator

### ISSUE THREAD

**Issue by Synchris2-0** [PorktoberRevolution/ReStocked#1026]
**Describe the bug**
The dragcube of the 1.875m decoupler and separator is identical to the dragcube of the 1.25m decoupler, leading to a lot of drag when these parts are used inline with other 1.875m parts (fuel tank and/or heat shield)

**Screenshots**

Below is a comparison of the dragcube between the 1.875 decoupler, separator and the 1.25m decoupler.
![dragcube_comparison](https://github.com/user-attachments/assets/65a97f1e-7e27-4271-8e7a-025a39ad4191)

The values are identical, showing a circular area of 1.22 despite the diameter being clearly different.

For example, here are the dragcube values of a 1.875m fuel tank
![fueltank_dragcube](https://github.com/user-attachments/assets/3373f4c4-dcfb-4d02-af71-128558a818c8)

Its vertical areas (2.77 on the YP and YN faces) are much closer to the actual value of the area of a 1.875m diameter disk (~2.7611).

**List of mods installed:**
 - Restock
 - ReStockPlus
 - ModuleManager

**Comment by Poodmund** [comment]
Good spot, this is only the case when Making History is not installed as we do not affect the stock drag cubes in that case, but I have confirmed that the RS+ configs were using the 1.25m drag cubes. I have resolved these to use the 1.875m drag cubes from Making History.
