### ISSUE TITLE
Invalid pieces if add-on is not installed

### ISSUE THREAD

**Issue by Kriss1670** [PorktoberRevolution/ReStocked#1034]
I use Steam KSP version to synchronize my game between my desktop and laptop computer. I installed Restock+ by mistake on my desktop and since there, all the vessels created have a mention "Invalid pieces" on my laptop (on which Restock+ is not installed). I saw that the add-on is not supposed to break stored vessels but this is not the case for me.

**Comment by Poodmund** [comment]
If you installed Restock+ on your desktop instance, put parts on your vessels from Restock+, and then tried to load those vessels on your laptop instance which does not have Restock+ installed, then this is the expected behaviour.
