### ISSUE TITLE
Heat Shield (1.25m & 2.5m) - Texture Issues

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#118]
There are some texturing issues on the 1.25m and 2.5m Heat Shield parts, both experiencing the same issues on both parts.

Classic Variant: Underside not textured
Black Variant: Whole model is untextured
Unpainted/Red Variant: Underside not textured

See screenshots for reference

![untitled-1](https://user-images.githubusercontent.com/10106634/50616135-20a9b700-0edf-11e9-915b-b546cc1d3171.png)
![untitled-2](https://user-images.githubusercontent.com/10106634/50616136-20a9b700-0edf-11e9-8195-289343aeb7c5.png)
![untitled-3](https://user-images.githubusercontent.com/10106634/50616137-20a9b700-0edf-11e9-8b99-272ec0c07dda.png)
![untitled-4](https://user-images.githubusercontent.com/10106634/50616138-20a9b700-0edf-11e9-9ff2-ba5f469ade7b.png)

Same behaviour in KSP 1.5.1 and 1.6.0 on the Master branch distribution as of 25th Dec. 2018 commits.

**Comment by ChrisAdderley** [comment]
I'm pretty sure this is just the KSP tga load bug... meaning that you just sometimes have tgas fail to load.
From a pristine `master` pull:
![screenshot17](https://user-images.githubusercontent.com/5642064/50621716-846eb880-0ebc-11e9-95e4-be226b0d9f7d.png)
![screenshot18](https://user-images.githubusercontent.com/5642064/50621717-846eb880-0ebc-11e9-8dbe-309c63fd9498.png)

This will go away once I switch to dds but I'm tweaking textures too frequently to deal with batching it all now.

**Comment by Poodmund** [comment]
It is indeed. Forced a regeneration of the database and the issued cleared.
