### ISSUE TITLE
LV-N Atomic Rocket Motor shroud half is not loading in as 'Disabled' correctly on stock .craft files.

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#121]
When you load in a stock .craft file that has an LV-N Atomic Rocket Motor, with both shroud halves set to disabled in stock, when ReStock is installed one shroud half is not loading in as 'Disabled' correctly.

Reproduction Steps:

- Craft a stock 1.6.0 craft file with a LV-N Atomic Rocket Motor and disable both shroud halves with ReStock installed.
- Install ReStock and load the craft file in the Editor that has a LV-N Atomic Rocket Motor that has both shroud halves disabled on the .craft file.
- Upon craft load in, only the 'ShroudA' (I think) shroud is correctly toggled as 'Disabled' but the 'ShroudB' is incorrectly loading as 'Enabled'.

How it appears in Stock 1.6.0

![untitled-1](https://user-images.githubusercontent.com/10106634/50743444-e9eddc80-120f-11e9-8429-a70240db9c65.png)

How it appears in Stock 1.6.0 with ReStock installed

![untitled-2](https://user-images.githubusercontent.com/10106634/50743456-f83bf880-120f-11e9-98d2-f3a178381a17.png)

Here is a stock craft file with a LV-N Atomic Rocket Motor that has both shroud halves disabled in the .craft file: https://kerbalx.com/download/craft/6708

**Comment by ChrisAdderley** [comment]
Fix was implemented in 6eadf94 of the `command-pods` branch.

**Comment by Poodmund** [comment]
Just tested this with the changes from the command-pods branch and it is resolved.
