### ISSUE TITLE
Context Menu In Editor Glitch

### ISSUE THREAD

**Issue by 51ngular1ty** [PorktoberRevolution/ReStocked#122]
After updating to 1.6 and the most recent ReStocked build I have noticed some strange behavior in the editor with nearly all of the engines.  
As you can see in this image when the part is right clicked the screen is spammed with a part variant selector and after it is closed you have to exit the editor and re-enter to be able to use the context menus again. The engines also do not appear in the staging menu.  They do however work just fine outside of the editor.
![screenshot7](https://user-images.githubusercontent.com/2055883/50753711-7a301f80-1218-11e9-82a9-e1e40df3a156.png)

I suspected that the issue had something to do with the shrouds so I made an edit to the swivel and reliant patch adding !MODULE[ModuleJettison] {} to them and it appeared to fix the issue with them. It did not however fix it with any of the 2.5 parts. 

Additionally I am getting a huge amount of NRE spam in my log related to FXModuleAnimateThrottle and UIPartActionVariantSelector.

[KSP.log](https://github.com/PorktoberRevolution/ReStocked/files/2731734/KSP.log)
[output_log.txt](https://github.com/PorktoberRevolution/ReStocked/files/2731762/output_log.txt)

If you would like anything else from me please let me know.

And ,as always,  thank you and your collaborators for sharing the beautiful art. It is all coming along wonderfully.

**Comment by blowfishpro** [comment]
Not related to Restock directly.  It’s a know issue with KSP 1.6 that ModuleManager makes worse in certain ways.  Rest assured it’s being looked at.  If you really need to make it work, you can let KSP load to the main menu, quit, the load it again (alternately I think quick reloading through ModuleManager’s menu will also fix it).  Do this every time you modify GameData.

**Comment by ChrisAdderley** [comment]
Yeah luckily (or not so luckily as we're waiting for fixes), this has nothing to do with us.
