### ISSUE TITLE
Size 2 Nose Cone attachment not centered

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#123]
The Protective Rocket Nose Cone Mk7's attachment node isn't centered causing it to misalign with the part it's attached to. You can see in the picture below that it's off to the left a bit compared to the white tank below it. I tested with multiple tanks and all showed the same result

![screenshot2](https://user-images.githubusercontent.com/22890228/50777506-a7002900-1250-11e9-8c38-87ae6cfb67e6.png)

**Comment by ChrisAdderley** [comment]
Fixed in b647efb

**Comment by Poodmund** [comment]
Resolved as per the above commit:

![untitled-1](https://user-images.githubusercontent.com/10106634/51074627-40787200-1679-11e9-9ae8-25ecaf129f12.png)

**Comment by TykoTek** [comment]
Looks great. confirmed  :)
