### ISSUE TITLE
Illuminators not strong enough

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#124]
They need to be tuned to be the same as stock. In addition I don't think the correct layers are set.

**Comment by ChrisAdderley** [comment]
Fixed in b647efb

**Comment by Poodmund** [comment]
Mk1 has more focused intensity and Mk2 has a wider, diffused spread as expected.

![untitled-1](https://user-images.githubusercontent.com/10106634/51074799-5e46d680-167b-11e9-93f6-56a145e4245f.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/51074800-6272f400-167b-11e9-990c-7eed30fe2d58.png)

They seem okay to me but as a balance consideration, more input would be appreciated.

**Comment by ChrisAdderley** [comment]
All I did was ported the numbers from stock, so should just be fine now.
