### ISSUE TITLE
Spark Engine shroud

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#125]
The shroud generated when you attach a part below the Spark isn't working correctly.

The Boat tail and the Compact variants don't have a shroud at all.

The 0.625 variant has a shroud but it doesn't extend down to part attached below it:
![screenshot0](https://user-images.githubusercontent.com/22890228/50945628-666bff80-144a-11e9-8d95-ec224f7deedf.png)

**Comment by ChrisAdderley** [comment]
First two are behaving as expended, but yeah it looks like it's too short

**Comment by ChrisAdderley** [comment]
Fixed in b647efb

**Comment by Poodmund** [comment]
![untitled-1](https://user-images.githubusercontent.com/10106634/51074860-399f2e80-167c-11e9-8d16-dd33d918c6a0.png)

Shroud height is resolved. 0.625m variant does have shroud whereas the Boat-tail and Compact do not.

Is it, or would it, be possible to let the compact variants have the shroud that the normal variants do but have them disabled by default when that variant is chosen? There are instances, I expect, when you may want to use a Compact variant but also retain the shroud. I guess this would require a plugin?

**Comment by TykoTek** [comment]
Fix confirmed.

It would be nice if the shroud were an option for compact and boat-tail, but if it's complicated to enable I'm not going to lose any sleep over it.

**Comment by ChrisAdderley** [comment]
Posted a poll in the discord about this, if it's done here it should be done for all engines which is not insignificant in terms of work and is another issue.
