### ISSUE TITLE
Clamp O tron is too narrow

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#126]
Somehow, the base of the 1.25m docking port is not 1.25m, it's more like 1.2.

**Comment by ChrisAdderley** [comment]
Fixed in b647efb

**Comment by Poodmund** [comment]
Resolved in above commit.

![untitled-1](https://user-images.githubusercontent.com/10106634/51074944-10cb6900-167d-11e9-8426-8c0b0c08aa43.png)

The Mk1-3 Command Pod has a very slight wider lip at the top compared to the Docking Port but its so minor I would not be worried about it at all.

![untitled-2](https://user-images.githubusercontent.com/10106634/51074956-29d41a00-167d-11e9-81af-a23d9263bfb1.png)
