### ISSUE TITLE
RCS Tank FL-R1 gap in tank

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#127]
The upper rim of the FL-R1 tank is separated from the rest of the tank just enough you can see the blue sky through the gap.

![image](https://user-images.githubusercontent.com/22890228/51033169-5130c700-1557-11e9-880c-e111d803efe4.png)

This is kind of a nit because that portion is totally covered when another tank is snapped on top of it, but wanted to be thorough.

**Comment by ChrisAdderley** [comment]
Nope it's a pretty valid complaint!

**Comment by ChrisAdderley** [comment]
Fixed in b647efb

**Comment by Poodmund** [comment]
Resolved in the above commit, I can no longer see through the mesh.

![untitled-1](https://user-images.githubusercontent.com/10106634/51074982-791a4a80-167d-11e9-9ac6-19104ecb12c8.png)

**Comment by TykoTek** [comment]
Confirmed. Closing issue
