### ISSUE TITLE
FL-A10 Adapter Nodes 

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#128]
The top and bottom nodes on the FL-A10 adapter are off.

The top node is too high causing separation with the part above. The bottom node is not centered.

![image](https://user-images.githubusercontent.com/22890228/51048042-d67ba200-157e-11e9-85f4-f80ff792f979.png)

**Comment by ChrisAdderley** [comment]
Is this a regression? I feel like I fixed this one before!

**Comment by TykoTek** [comment]
I was surprised too. I've been trying to do a quick "snap parts together" test for all new parts and didn't catch this before

**Comment by ChrisAdderley** [comment]
There's a good chance I reintroduced it when adding all the colour variants in, there was lots of construction dust at that point. Once I'm done with the command pods I will be spending some normalization/bugfix time on master...

**Comment by ChrisAdderley** [comment]
Fixed in b647efb

**Comment by TykoTek** [comment]
Damn.. @Poodmund woke up before I did...

Confirmed fixed
