### ISSUE TITLE
skipper's actuators need actuation - only in big version

### ISSUE THREAD

**Issue by riocrokite** [PorktoberRevolution/ReStocked#130]
for now they are static with 2.5m version, compact version works fine

+ placement for one upper arm of actuator is off center (big version), should be fixed itself when actuation works
![image](https://user-images.githubusercontent.com/9766897/51064941-89411400-1602-11e9-996a-f72ba998f899.png)

**Comment by ChrisAdderley** [comment]
What is "big version"? 2.5m? boattail?

**Comment by ChrisAdderley** [comment]
Fixed in b647efb

**Comment by Poodmund** [comment]
Seems slightly off-centred for the Boat-Tail and 2.5m variants still using the master branch post-commit of https://github.com/PorktoberRevolution/ReStocked/commit/b647efb14fbe6755c0ceac5d0960f35acdb8f809

![untitled-1](https://user-images.githubusercontent.com/10106634/51075151-c4355d00-167f-11e9-9321-ee22a61a906d.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/51075152-c8617a80-167f-11e9-9393-c88766fe022b.png)

**Comment by ChrisAdderley** [comment]
Fixed in 32e48a9

**Comment by Poodmund** [comment]
Just looked at this with https://github.com/PorktoberRevolution/ReStocked/commit/32e48a90d5377a4f9b0fa1e146d580a69a568024 and I'm getting the same positioning as shown in my previous screenshots using https://github.com/PorktoberRevolution/ReStocked/commit/b647efb14fbe6755c0ceac5d0960f35acdb8f809

![untitled-1](https://user-images.githubusercontent.com/10106634/51084947-3d898a00-172a-11e9-89f7-d13c0bb2549b.png)

It is just on the actuator shown in the screenshot above and only on the Boat-Tail/2.5m variant.

**Comment by ChrisAdderley** [comment]
And finally ed6d142
