### ISSUE TITLE
mainsail - rotate upper arm actuators

### ISSUE THREAD

**Issue by riocrokite** [PorktoberRevolution/ReStocked#131]
![image](https://user-images.githubusercontent.com/9766897/51063130-e97f8800-15f9-11e9-9fff-39c670010d9c.png)

**Comment by ChrisAdderley** [comment]
Only an error is it is rotated incorrectly. Title adjusted

**Comment by ChrisAdderley** [comment]
Fixed in b647efb. Applied to skipper too.

**Comment by Poodmund** [comment]
Seemingly resolved with https://github.com/PorktoberRevolution/ReStocked/commit/b647efb14fbe6755c0ceac5d0960f35acdb8f809 

![untitled-1](https://user-images.githubusercontent.com/10106634/51075224-a0264b80-1680-11e9-810a-fcf157f3f30e.png)

Would appreciate a second opinion.
