### ISSUE TITLE
mainsail - small texturing error near the turbopump

### ISSUE THREAD

**Issue by riocrokite** [PorktoberRevolution/ReStocked#132]
![image](https://user-images.githubusercontent.com/9766897/51063111-d8367b80-15f9-11e9-8d1e-a420929596ee.png)

**Comment by ChrisAdderley** [comment]
Fixed in b647efb. Technically a model issue.

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/b647efb14fbe6755c0ceac5d0960f35acdb8f809

![untitled-1](https://user-images.githubusercontent.com/10106634/51075245-dd8ad900-1680-11e9-96d2-dcaf6fbf1431.png)
