### ISSUE TITLE
Upgrade gold foil endcaps to be reflective

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#136]
Upgrade the ends of the Hitchiker and the Mobile Lab to use the new reflective shader

**Comment by ChrisAdderley** [comment]
Added first pass with 9884e35

**Comment by Poodmund** [comment]
I've tested the foil in various conditions which can be seen here with descriptions as to the enviroment at which the shots were taken: https://imgur.com/a/jLQezbc

The shots with an intense, direct source of light look very good, however, when there is a soft, ambient light the foil gets a bit soft and blueish as can be seen from the pad at midday.

**Comment by ChrisAdderley** [comment]
Improvements and tweaks in 32e48a9
