### ISSUE TITLE
MK2 Can door animation doesn't work

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#137]
And I have no idea why.

**Comment by TykoTek** [comment]
There isn't a menu option for it in the right-click menu either.

![image](https://user-images.githubusercontent.com/22890228/51075414-e8714980-163f-11e9-9584-9c611ef0917e.png)

**Comment by ChrisAdderley** [comment]
Yes that's exactly the problem (I guess if you wanted to get technical the animation does work fine)

**Comment by ChrisAdderley** [comment]
Fixed in 32e48a9
