### ISSUE TITLE
Mesh Gap in Mk2 Lander Can (Rover Variant)

### ISSUE THREAD

**Issue by benjee10** [PorktoberRevolution/ReStocked#138]
<img width="1024" alt="screen shot 2019-01-12 at 15 45 36" src="https://user-images.githubusercontent.com/18337483/51075422-10ce6780-1683-11e9-9806-3d1e847fa8e6.png">

**Comment by ChrisAdderley** [comment]
Hopefully all cleaned up in 32e48a9
