### ISSUE TITLE
Rocket Engines

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#14]
- .625m
  - LV-1 R 'Spider'
    - [x] Model
    - [x] Texture
    - [x] Integration
  - LV-1 'Ant'
    - [x] Model
    - [x] Texture
    - [x] Integration
  - LV-1 R 'Spider'
    - [x] Model
    - [x] Texture
    - [x] Integration
  - 48-75 'Spark'
    - [x] Model
    - [x] Texture
    - [x] Integration
  - 24-77 'Twitch'
    - [x] Model
    - [x] Texture
    - [x] Integration
  - OMS-10 'Puff'
    - [x] Model
    - [x] Texture
    - [x] Integration
  - Separatron I
    - [x] Model
    - [x] Texture
    - [x] Integration
- 1.25m
  - Flea SRB
    - [x] Model
    - [x] Texture
    - [x] Integration
  - Hammer SRB
    - [x] Model
    - [x] Texture
    - [x] Integration
  - Thud SRB
    - [x] Model
    - [x] Texture
    - [x] Integration
  - Kickback SRB
    - [x] Model
    - [x] Texture
    - [x] Integration
  - LV-T30
    - [x] Model
    - [x] Texture
    - [x] Integration
  - LV-T45
    - [x] Model
    - [x] Texture
    - [x] Integration
  - LV-909
    - [x] Model
    - [x] Texture
    - [x] Integration
  - LV-N
    - [x] Model
    - [x] Texture
    - [x] Integration
  - Vector
    - [x] Model
    - [x] Texture
    - [x] Integration
  - Thud
    - [ ] Model
    - [ ] Texture
    - [ ] Integration
- 2.5m
  - Mainsail
    - [x] Model
    - [x] Texture
    - [x] Integration
  - Skipper
    - [x] Model
    - [x] Texture
    - [x] Integration
  - Poodle
    - [x] Model
    - [x] Texture
    - [x] Integration
  - Twin Boar
    - [x] Model
    - [x] Texture
    - [x] Integration
- 3.75m
  - Mammoth
    - [x] Model
    - [x] Texture
    - [x] Integration
  - Rhino
    - [x] Model
    - [X] Texture
    - [x] Integration

**Comment by Vladimir-csp** [comment]
It's sad that integrated tank in LV-909 does not work.
Variants support mass changes BTW.
...but not resources AFAIK.

**Comment by blowfishpro** [comment]
Correct, the stock variants system does not support resource switching.

**Comment by ChrisAdderley** [comment]
Closed and moved to individual tickets.
