### ISSUE TITLE
KR-2L+ Rhino upper actuators rotate when working

### ISSUE THREAD

**Issue by riocrokite** [PorktoberRevolution/ReStocked#140]
![image](https://user-images.githubusercontent.com/9766897/51076954-ab3ca400-169f-11e9-88f5-dd05df3aaf98.png)

it's best to reproduce using SAS and changing direction so you can see slower movement of actuators and their rotation in their Z-axis. Wouldn't be noticeable but AO bake is rotating as well. In the pic AO shadow bake in the left actuator rotated 90 degrees.

**Comment by ChrisAdderley** [comment]
This is the same issue from the poodle, they can't be constrained correctly so they are flipping. This tends to be accentuated on straight gimbal pistons like these. Best I can do is try to remove the AO.

**Comment by ChrisAdderley** [comment]
Mitigation applied in 32e48a9

**Comment by Poodmund** [comment]
Video review as of https://github.com/PorktoberRevolution/ReStocked/commit/32e48a90d5377a4f9b0fa1e146d580a69a568024: https://youtu.be/A6Dz2Flsnkg

Note the bendy plumbing on the compact variant to the side. 😄 Some nice hand-wavium technology going on here.

**Comment by ChrisAdderley** [comment]
Looks good now!
