### ISSUE TITLE
Terrier - compact variant always has fairing

### ISSUE THREAD

**Issue by blowfishpro** [PorktoberRevolution/ReStocked#142]
It's there regardless of whether something is attached below it.  I think ModuleJettison only supports a single jettison transform.

**Comment by Poodmund** [comment]
Resolved as of https://github.com/PorktoberRevolution/ReStocked/commit/104383865e6cb0ee2c7c5b722d00263bb9f7db6d

![untitled-1](https://user-images.githubusercontent.com/10106634/51085403-3c5b5b80-1730-11e9-86f3-04433b9529a0.png)
