### ISSUE TITLE
RE-I5 "Skipper" Engine - 2.5m Variant Collider issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#143]
I think that the 2.5m variant of the Skipper's collider is using the collider from the Boat-Tail variant. When right clicking the empty space around the 2.5m variant you can actually open up the PAW for it and a Kerbal seems to collide with thin air when trying to move around the engine space. See videos below:

https://youtu.be/2Lsx7w4G1xs

https://youtu.be/dxUU_xeObGw

**Comment by ChrisAdderley** [comment]
Not really... you see, the stock collider looks like this...
![skippercol](https://user-images.githubusercontent.com/5642064/51088288-a8c76200-1712-11e9-9888-3edd3ac41a25.PNG)
