### ISSUE TITLE
Mk2 Lander Can - Lander variant IVA side windows showing outside but some parts of doors

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#144]
I appreciate there are issues with the stock IVA in this regards too but figured it'd be worth opening the issue here in case it is ever decided to be resolved in ReStock.

The Lander variant IVA view shows the outside environment out the side windows but does show the side compartment doors, when closed and open. See screenshots below:

![untitled-1](https://user-images.githubusercontent.com/10106634/51085628-251e6d00-1734-11e9-8f0a-85d8f14fa044.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/51085634-35364c80-1734-11e9-8e0c-4c24a94c07cf.png)

![untitled-3](https://user-images.githubusercontent.com/10106634/51085636-39fb0080-1734-11e9-8244-6d0cbc1e6971.png)

![untitled-4](https://user-images.githubusercontent.com/10106634/51085638-3d8e8780-1734-11e9-8086-47d5a071fe56.png)

**Comment by ChrisAdderley** [comment]
Ah... I forgot to make the "plug"

**Comment by ChrisAdderley** [comment]
#311 adds a new mesh component to block the hole

**Comment by Poodmund** [comment]
https://github.com/PorktoberRevolution/ReStocked/pull/311 resolves this issue.
