### ISSUE TITLE
Mainsail and Skipper variants default to Boat-Tail, should default to 2.5m variant

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#145]
To maintain consistency throughout the parts range, all engines up to this point, when selected from the parts list in the Editor, default to the 'Diameter Size' variant i.e. 0.625m, 2.5m etc. except for the Mainsail and Skipper which default to Boat-Tail as the first listed variant in the list.

I would suggest the following going forward to maintain consistency:
- Diameter Size
- Optional Diameter Sizes
- Boat-Tail
- Compact

See screenshot below showing various other engines with their default variants compared to the Mainsail and Skipper:

![untitled-1](https://user-images.githubusercontent.com/10106634/51085753-9874ae80-1735-11e9-8394-75c43bee7d2d.png)

**Comment by ChrisAdderley** [comment]
Sure.

**Comment by ChrisAdderley** [comment]
ed6d142

**Comment by Poodmund** [comment]
https://github.com/PorktoberRevolution/ReStocked/pull/148

Opened pull request to re-order the variants for both engines to get the in line with all the others. Once resolved this can be closed. 😄
