### ISSUE TITLE
Mk1 Lander Can top and bottom nodes not centered

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#146]
Both top and bottom nodes are off-center causing other things snapped to them to not align properly.

![image](https://user-images.githubusercontent.com/22890228/51089465-76bdfc00-1722-11e9-81c2-d7d630e8e69c.png)

![image](https://user-images.githubusercontent.com/22890228/51089472-86d5db80-1722-11e9-9173-81cfe7412ff7.png)

**Comment by ChrisAdderley** [comment]
Fixed in c296d8e

**Comment by TykoTek** [comment]
Fix confirmed
