### ISSUE TITLE
SRB Gimbals from ReStock Plus

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#150]
The patch adding gimbals to the four stock SRBs isn't working. The config looks okay and I'm not using better SRBs. Was this disabled?

**Comment by ChrisAdderley** [comment]
I'll take a look

**Comment by ChrisAdderley** [comment]
Ok, so the two larger SRBs are fine... the two smaller have been broken since 1.5 happened with the new SRB models. I did discover some bugs with the two larger SRBs though which I have fixed along with this problem in 6760c4a.

**Comment by TykoTek** [comment]
Confirmed fixed in 6760c4a
