### ISSUE TITLE
Probe Cores rotated to different orientations

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#163]
Where possible it would be easier if all the part badges were aligned to "up" to help with visual orientation of craft. In the pic below you can see the Mk1 Lander Can with the hatch in the "up" direction. The RGU matches that as does the HECS. 

The HECS2 and the OKTO cores are not though. Their badges are on the "side" instead.

![screenshot16](https://user-images.githubusercontent.com/22890228/51261463-28e50600-1965-11e9-990b-4af150498f42.png)

**Comment by ChrisAdderley** [comment]
Fixed with 5ac8514

**Comment by Poodmund** [comment]
Screenshot as per https://github.com/PorktoberRevolution/ReStocked/commit/5ac85141bdcb1dc73cc787991d6e10fbf594349c. These parts are all oriented in their default rotation orientation coming directly from the parts list selection.

![untitled-1](https://user-images.githubusercontent.com/10106634/51562351-8dcabf80-1e81-11e9-962c-46a09ee9d84d.png)

The only thing I could suggest now is the QUBE to also be rotated through 90 degrees possiby as per the above discussion.

**Comment by ChrisAdderley** [comment]
QUBE rotated in 485710e

**Comment by TykoTek** [comment]
Confirmed that all are oriented in the same way except for HECS2 - which is intentional.

Closing this
