### ISSUE TITLE
Inner ring of 1.25m and 2.5m fairings has some flat shading that should be smooth

### ISSUE THREAD

**Issue by blowfishpro** [PorktoberRevolution/ReStocked#166]
I think every side of these cylinders is flat

![image](https://user-images.githubusercontent.com/10545461/51298750-a008b180-19da-11e9-8e93-cb75a2e09217.png)

**Comment by ChrisAdderley** [comment]
Fixed with 5ac8514

**Comment by Poodmund** [comment]
Screenshots of 1.25m and 2.50m fairing adapters using https://github.com/PorktoberRevolution/ReStocked/commit/5ac85141bdcb1dc73cc787991d6e10fbf594349c

![untitled-1](https://user-images.githubusercontent.com/10106634/51561785-0761ae00-1e80-11e9-997e-01b2a186aae2.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/51561788-0af53500-1e80-11e9-8674-f515a4a21c29.png)

Screenshots are for reference purposes. @blowfishpro 	can you please review?

**Comment by blowfishpro** [comment]
Yep, appears to be fixed now
