### ISSUE TITLE
Corgi flamout FX only occuring on one engine bell

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#185]
The FX that runs at flameout seems to only be present in one of the engine bells for the Corgi, see video: https://youtu.be/OWQNAufFV3s

**Comment by ChrisAdderley** [comment]
Addressed in #221 by removing the FX, couldn't figure out what was wrong.

**Comment by woeller** [comment]
Better none than one. I reviewed this and it's ok without the fx.
