### ISSUE TITLE
Pods

### ISSUE THREAD

**Issue by IronCretin** [PorktoberRevolution/ReStocked#2]
- Mk1 Command Pod *- Porkjet*
  - [ ] Model
  - [ ] Texture
  - [ ] Integration
- Mk1-2 Command Pod
  - [ ] Model
  - [ ] Texture
  - [ ] Integration
- Mk1 Lander Can
  - [ ] Model
  - [ ] Texture
  - [ ] Integration
- Mk2 Lander-can *- Benjee*
  - [ ] Model
  - [ ] Texture
  - [ ] Integration
- PPD-12 Cupola Module
  - [x] Model
  - [x] Texture
  - [x] Integration
- EAS-1 External Command Seat
  - [ ] Model
  - [ ] Texture
  - [ ] Ingame
- Hitchhiker Module
  - [x] Model
  - [x] Texture
  - [x] Integration
- Mobile Processing Lab
  - [x] Model
  - [x] Texture
  - [x] Integration

**Comment by ChrisAdderley** [comment]
Closing and moving to tickets
