### ISSUE TITLE
LV-909 shading issues

### ISSUE THREAD

**Issue by blowfishpro** [PorktoberRevolution/ReStocked#20]
I think these areas should be smooth?  The part on the nozzle is for all 3 variants whereas the part above is only on the compact variant.

![image](https://user-images.githubusercontent.com/10545461/43351077-bd1314a6-91c1-11e8-962d-045c253d006f.png)

**Comment by ChrisAdderley** [comment]
Should be fixed in 35380eff09de8b9e015c384d56018bc61fd33ec1
