### ISSUE TITLE
Engine Colliders (compact variant especially)

### ISSUE THREAD

**Issue by blowfishpro** [PorktoberRevolution/ReStocked#21]
I can understand if we need to keep the stock colliders for the default variant, but for the compact variants they're too big (it's hard to place something next to the engine for instance).

Appears to affect the LV-T30, LV-T45, LV-909. and 48-7S

**Comment by ChrisAdderley** [comment]
35380eff09de8b9e015c384d56018bc61fd33ec1 adds new colliders for these parts in boattail/compact mode
