### ISSUE TITLE
CR-7 R.A.P.I.E.R. Engine

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#215]
The ugliest aero model. 
- [x] Model 
- [x] Unwrap
- [x] Texture
- [x] Effects
- [x] Integration

**Comment by Kradgger** [comment]
Might I suggest taking inspiration from the ol' reliable 'Porkalike Rapier' from hoojiwana.

https://forum.kerbalspaceprogram.com/index.php?/topic/128224-11-porkalike-rapier-12-20-apr/

It's fit very well with the other jets, which if there are no plans on replacing those it'll be a good thing.

Maybe contact hoojiwana and implement it with new FX like you guys did with the Porkjet LV set?

**Comment by ChrisAdderley** [comment]
Using similarly is exactly what is planned, though there is a small quality Delta that I'd like to address.

**Comment by Poodmund** [comment]
I second the notion that Hooj's inclusion of the small Ramjet burners in the model is basically what takes the model from dumb to ingenious.
