### ISSUE TITLE
Fuel Cell Array

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#217]
It's nastier
- [x] Model 
- [x] Unwrap
- [x] Texture
- [x] Integration

**Comment by ChrisAdderley** [comment]
I had a request from Snark to add builtin compatibility for IndicatorLights activity monitor if possible - I think this just maps to a emissive light somewhere.

**Comment by theonegalen** [comment]
He has some emissive lights that are included with his mod. He uses MODEL nodes in the config to add them to stock parts. I think what he wants is for the light that shows up there not to have to be moved depending on whether or not restock is installed.

**Comment by drewcassidy** [comment]
I’ll see what I can do about that. Worst case we (or he) include a compatibility config to move the MODEL node

**Comment by ChrisAdderley** [comment]
Yeah, i was just thinking that it'd be nice to design the model with a small emissive light that could be repurposed by IL.

**Comment by theonegalen** [comment]
I like it.
