### ISSUE TITLE
ADPT-2-3 fuel tank variants don't work.

### ISSUE THREAD

**Issue by GregroxMun** [PorktoberRevolution/ReStocked#218]
![An image showing the white 2.5/3.75m adaptor with variant set to orange texture](https://i.imgur.com/bEJvzCw.png)

The 2.5-3.75m *fueled* adaptor's variants are not functional, however the structural adaptor's variants *do* work.

**Comment by ChrisAdderley** [comment]
These definitely worked at some point so I'll look into what happened.

btw - welcome to the pre-alpha testing team :D

**Comment by Kradgger** [comment]
> These definitely worked at some point so I'll look into what happened.
> 
> btw - welcome to the pre-alpha testing team :D

Can confirm it worked before the recent ReStock+ 375 merge. That branch had its own nameless, descriptionless, variantless version. So maybe a bad merge between old master and 375+ branch?

**Comment by ChrisAdderley** [comment]
I suspect the older model from the 3.75m + branch is now being used, which does not have the subobjects needed for the variant switching. A simple re-export will take care of this, git isn't super great at handling art files.

**Comment by woeller** [comment]
> 
> 
> Addressed in #221

Can confirm that it works
