### ISSUE TITLE
Oscar-b LFO quantity incorrect

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#222]
Currently it's LF 6.6 Oxidizer 22

If it's supposed to be half an Oscar C it should be
LF: 5.4
Oxidizer: 6.6

**Comment by ChrisAdderley** [comment]
As discussed, increasing based on FL-T800 size standard. An OscarB has 18 units of fuel total now (8.1/9.9) and the others follow from that, as of 19a0caf.

**Comment by TykoTek** [comment]
Tested and confirmed
