### ISSUE TITLE
Golden HECS mirrored underside mesh

### ISSUE THREAD

**Issue by JadeOfMaar** [PorktoberRevolution/ReStocked#224]
![improper mirroring](https://cdn.discordapp.com/attachments/298532796077703168/539463148361613312/Honeyview_screenshot168.jpg)
The mesh of the underside of this probe core (right) should have been rotated about an axis, not mirrored. Since there is text, it too is mirrored. Additionally, the button numbers could do with rotation too. A sharp-eye'd player would have the temptation to tilt their head at them.

**Comment by ChrisAdderley** [comment]
Text has been flipped in a2e640e

**Comment by woeller** [comment]
> 
> 
> Text has been flipped in [a2e640e](https://github.com/PorktoberRevolution/ReStocked/commit/a2e640e00f741d46a118dc4cdb42c8d6c92e6ae2)

Works now as expected.

**Comment by ChrisAdderley** [comment]
Thanks for the verification!
