### ISSUE TITLE
Restock+ Corgi Emissive issue

### ISSUE THREAD

**Issue by Sgt-Shutesie** [PorktoberRevolution/ReStocked#226]
The emissive is weird, that's all.
![image](https://user-images.githubusercontent.com/17996283/51881066-bfdb9600-2347-11e9-9410-c40c66e0e5c4.png)

**Comment by ChrisAdderley** [comment]
Fixed by 5ac26fa

**Comment by TykoTek** [comment]
Closed per Shutesie

ShutesieToday at 9:04 PM
While you're closing stuff, can you close the corgi for me, it's fixed

**Comment by ChrisAdderley** [comment]
Closed
