### ISSUE TITLE
RT-1 Thrust off-center

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#227]
RT-1 thrust is off-center. KER is reporting torque and you can see in the image below that the engine cone isn't centered in the purple sphere. The cone is shifted to the right from this perspective

![image](https://user-images.githubusercontent.com/22890228/51881048-8ba7ab80-232e-11e9-86c0-5d2d4e7a0f29.png)

**Comment by ChrisAdderley** [comment]
Fixed by 5ac26fa

**Comment by TykoTek** [comment]
Confirmed
