### ISSUE TITLE
LV-1 Ant - 0.625m shroud is offset a bit

### ISSUE THREAD

**Issue by blowfishpro** [PorktoberRevolution/ReStocked#228]
![screenshot6](https://user-images.githubusercontent.com/10545461/51952221-83ae4100-23ec-11e9-8cbc-3c9d8f8ec009.png)

It clips into the part above and doesn't quite line up with the part below.  Probably just needs to be moved down a bit

**Comment by ChrisAdderley** [comment]
Seems good in 5ac26fa

**Comment by blowfishpro** [comment]
Actually seeing a bit of z-fighting at both ends now.

**Comment by ChrisAdderley** [comment]
Back to In Progress you go!

**Comment by ChrisAdderley** [comment]
7a397b9 should really fix this

**Comment by ChrisAdderley** [comment]
I actually see it at the top, odd. More changes a0426bf

**Comment by blowfishpro** [comment]
Yep, looks good now
