### ISSUE TITLE
Modify Twitch for 1.7 compatibility

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#231]
Guess what's losing it's angled nature in 1.7 and needs a useless variant!

**Comment by Kradgger** [comment]
I'm not sure but the new square mount looks like it might have the same area as the Cubic Octagonal Strut, maybe it'll be meant to fit at the end of it?

**Comment by ChrisAdderley** [comment]
Well, I'm not going to redo the current model to match the meh thing they did. The low effort solution is to rotate the entire pod ~15 degrees or whatever. The high effort solution is to actually do some work to model the internals of the engine and create a un-podded variant. The current model can then drop in as a "new" podded variant. We'll see what I'm motivated to do.

**Comment by Poodmund** [comment]
The high effort solution was undertaken and released in RS v1.4.0.
