### ISSUE TITLE
UV issue RC-001S

### ISSUE THREAD

**Issue by Sgt-Shutesie** [PorktoberRevolution/ReStocked#242]
UV is misaligned
![image](https://user-images.githubusercontent.com/17996283/52023225-49b36c80-24ca-11e9-9720-460c0dbaf944.png)

**Comment by ChrisAdderley** [comment]
7a397b9 has a fix

**Comment by woeller** [comment]
A texture seam is still visible.

**Comment by ChrisAdderley** [comment]
As discussed in discord, this is a shader artifact that we can't do anything about.

**Comment by ChrisAdderley** [comment]
As good as it's going to get in 5d5b915

**Comment by woeller** [comment]
Texture is looking good but now I found this:

![screenshot17](https://user-images.githubusercontent.com/35576383/52172678-04ff2e00-2775-11e9-955d-26ae9f05d982.png)

**Comment by Poodmund** [comment]
But the original issue is resolved and the one pointed out above is not relevant to it. Opened new issue at: https://github.com/PorktoberRevolution/ReStocked/issues/284
