### ISSUE TITLE
RC-14-A Plumes

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#245]
45 degree angle plumes are at incorrect angle and not centered on nozzles

![image](https://user-images.githubusercontent.com/22890228/52023933-cedf5700-24b3-11e9-8fb3-e89a38ba626c.png)

**Comment by ChrisAdderley** [comment]
This should have been fixed with the batch from last night, forgot to move this to verification.

**Comment by TykoTek** [comment]
Fixed
