### ISSUE TITLE
RV Series RCS attach nodes

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#246]
The attach nodes on the RV series thrusters are at different heights causing some clusters to sit higher or lower on their parent part. The ones that stick our further like the 5-way and 2-way give more clearance for the nozzles.

![image](https://user-images.githubusercontent.com/22890228/52024148-9724df00-24b4-11e9-9c26-d6e6782b85db.png)

**Comment by ChrisAdderley** [comment]
7a397b9 normalizes to the stock one

**Comment by TykoTek** [comment]
Confirmed
