### ISSUE TITLE
LV-T15 - compact variant has a see through section

### ISSUE THREAD

**Issue by blowfishpro** [PorktoberRevolution/ReStocked#251]
Seems to be missing geometry there?
![image](https://user-images.githubusercontent.com/10545461/52104108-ba778900-259d-11e9-9229-eba3be07645e.png)

**Comment by woeller** [comment]
Nope, now it's visible from outside

![screenshot18](https://user-images.githubusercontent.com/35576383/52172707-8ce53800-2775-11e9-8a22-144ed5cd56a5.png)

**Comment by Poodmund** [comment]
To add to the above, it seems Blowfish's issue was resolved:

![untitled-1](https://user-images.githubusercontent.com/10106634/52176218-8e2f5880-27a7-11e9-9638-5f1cb610e1fb.png)

... but a new one was created as pointed out by Woeller. The culled face on appears on this, one side of the motor:

![untitled-2](https://user-images.githubusercontent.com/10106634/52176220-95566680-27a7-11e9-96a2-f4ea8be6f6f0.png)

![untitled-3](https://user-images.githubusercontent.com/10106634/52176221-98515700-27a7-11e9-91ff-d05d8d4ea8d0.png)

Alongside this during a closer look, there are a couple of funky mesh issues with the gimballing mechanism:

![untitled-5](https://user-images.githubusercontent.com/10106634/52176226-a99a6380-27a7-11e9-86a4-2408c74ad085.png)

![untitled-4](https://user-images.githubusercontent.com/10106634/52176227-abfcbd80-27a7-11e9-9b1f-9818055d7232.png)

**Comment by ChrisAdderley** [comment]
Fixed the inverted face. Mitigated @Poodmund 's notes to the best I can as of 0d79074, but the gimbal links really are still screwy

**Comment by Poodmund** [comment]
Following https://github.com/PorktoberRevolution/ReStocked/commit/0d790746cbc65048e7b8cb70d0697aa305253736, I think this can now be closed. The links are good enough if they are causing headaches.
