### ISSUE TITLE
Vernor thruster gap between nozzle and body

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#253]
The underlying part is showing through the gap between the nozzle and body. 

![image](https://user-images.githubusercontent.com/22890228/52117199-fe7f8380-25c7-11e9-8b01-d92728379895.png)

**Comment by ChrisAdderley** [comment]
God damn it I hate this KSP game.

**Comment by ChrisAdderley** [comment]
21447b0 has cut off my beautiful inside mesh

**Comment by TykoTek** [comment]
Confirmed
