### ISSUE TITLE
Issue with LV-T45 Variants

### ISSUE THREAD

**Issue by woeller** [PorktoberRevolution/ReStocked#254]
After switching to Boattail, both other variants looses their  gimbal joints when switching to them

![1](https://user-images.githubusercontent.com/35576383/52144116-a7c48900-265d-11e9-95ba-fdc1fc3c8041.png)

**Comment by ChrisAdderley** [comment]
This was reported and confirmed fixed here: https://github.com/PorktoberRevolution/ReStocked/issues/248
Can you ensure you have a copy of master newer than the commit mentioned in that issue?

**Comment by woeller** [comment]
I've downloaed the latest master and tested it again. Can confirm that the issue is solved.

**Comment by ChrisAdderley** [comment]
Thanks!
