### ISSUE TITLE
Emissive texture on KR-2L Rhino

### ISSUE THREAD

**Issue by woeller** [PorktoberRevolution/ReStocked#255]
There is a visible emissive texture seam on the "Rhino"

![screenshot31](https://user-images.githubusercontent.com/35576383/52144658-40a7d400-265f-11e9-9b61-f2479f2fb871.png)

**Comment by ChrisAdderley** [comment]
Not actually an emissive texture issue but a main texture issue. Gone in 8fee855

**Comment by woeller** [comment]
Looks good
