### ISSUE TITLE
Emissive texture issue with LV-N

### ISSUE THREAD

**Issue by woeller** [PorktoberRevolution/ReStocked#256]
Imissive texture is shown while engine is off and throttle is up.

![screenshot33](https://user-images.githubusercontent.com/35576383/52145483-5ae2b180-2661-11e9-9de5-a59f60aa11d6.png)

**Comment by ChrisAdderley** [comment]
Fix applied in 5c7e966

**Comment by woeller** [comment]
Looks good

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/5c7e9669a04be192b7f91431d4f13db1e85df03d
