### ISSUE TITLE
Emissive speeds

### ISSUE THREAD

**Issue by woeller** [PorktoberRevolution/ReStocked#257]
Emissive response time is very fast

![2019-02-01 21-11-23 2](https://user-images.githubusercontent.com/35576383/52147251-67b5d400-2666-11e9-9dff-a409dca9fb24.gif)

**Comment by ChrisAdderley** [comment]
Can you give some examples of engines that work as you'd expect so i can track this down?

**Comment by ChrisAdderley** [comment]
Ah those are all using the legacy methodology. So mostly it's just a problem with the newer method, I will try to tune this accross the board (I'm going to assume that all engines using the newer method, eg Spark, Twitch, Reliant, Terrier, etc similarly problematic)

**Comment by ChrisAdderley** [comment]
21447b0 has added a new test item for the new method and its speed. It is only implemented on the **Terrier**, if this seems adequate (turns out this is hard to tune) i will push it to all the engines.

**Comment by woeller** [comment]
I tested the Terriers and what should I say? Much better! ;)

**Comment by ChrisAdderley** [comment]
As discussed on discord, there is a solution for this but it's extremely high effort. There's a fair chance it will not be implemented.

**Comment by ChrisAdderley** [comment]
I have normalized all the heat animation speeds to be the same as the prototypical terrier in 740242c
This affects the Mainsail, Skipper, Poodle, Twin Boar, Twitch, Spark, RAPIER, Boar, Torch, Mallet, Striker, Pug, Valiant and Corgi (ie, all the engines using the new methods)

**Comment by woeller** [comment]
Terrier: As Poodmund said, inside ramps up/down almost instantly. Outside is fine
Swivel: inside ramps up/down almost instantly. Outside is fine
Reliant: inside ramps up/down almost instantly. Outside is fine
Mainsail: inside ramps up/down almost instantly. Outside is fine
Skipper: inside ramps up/down almost instantly. Outside is fine
Poodle: inside ramps up/down almost instantly. Outside is fine
Twin Boar: inside is fine. Outside is fine
Twitch: inside ramps up/down almost instantly. Outside is fine
Spark: inside ramps up/down almost instantly. Outside is fine
RAPIER Airbreathing: inside is fine. Outside is fine
RAPIER closed cycle: inside/outside no emissive
Boar: inside/outside no emissive
Torch: inside/outside ramps up/down almost instantly
Mallet: inside/outside ramps up/down almost instantly
Striker: inside/outside ramps up/down almost instantly
Pug: inside/outside ramps up/down almost instantly
Valiant: inside/outside ramps up/down almost instantly
Corgi: inside/outside ramps up/down almost instantly

**Comment by woeller** [comment]
Some of the not mentioned engines:
Nerv: inside ramps up/down almost instantly. Outside is fine
RT-5: inside/outside ramps up/down almost instantly
RT-10: inside/outside ramps up/down almost instantly
BACC: inside/outside ramps up/down almost instantly
Rhino: inside ramps up/down almost instantly. Outside is fine
Vektor: inside ramps up/down almost instantly. Outside speed is fine but barely visible

**Comment by ChrisAdderley** [comment]
As mentioned all inside fast ramps are **_intentional_**

**Comment by woeller** [comment]
Sorry! I think this was only mentioned on discord. I've edited my comment.

**Comment by ChrisAdderley** [comment]
> RAPIER Airbreathing: inside is fine. Outside is fine
> RAPIER closed cycle: inside/outside no emissive
> Boar: inside/outside no emissive
These should be fixed now

> Torch: inside/ outside ramps up/down almost instantly
> Pug: inside/ outside ramps up/down almost instantly
> Valiant: inside/ outside ramps up/down almost instantly
> Corgi: inside/ outside ramps up/down almost instantly
These are wrong and I don't really get what's wrong, they are configured identically. Only difference  is that they are their own parts instead of patches. 

> Mallet: inside/ outside ramps up/down almost instantly
> Striker: inside/ outside ramps up/down almost instantly
> RT-5: inside/ outside ramps up/down almost instantly
> RT-10: inside/ outside ramps up/down almost instantly
> BACC: inside/ outside ramps up/down almost instantly
> S1 SRB: inside/ outside ramps up/down almost instantly
> Vektor: inside ramps up/down almost instantly. Outside speed is fine but barely visible

All intentional

**Comment by woeller** [comment]
> 

> 
> These should be fixed now
> 
RAPIER closed cycle: inside/outside is fine.

> These are wrong and I don't really get what's wrong, they are configured identically. Only difference is that they are their own parts instead of patches.
> 
Add the Boar to that list: inside/ outside ramps up/down almost instantly

**Comment by ChrisAdderley** [comment]
Completely new emissive texture model has been implemented over hours and hours of pain. There will be no further changes.

**Comment by woeller** [comment]
Well then you should close this.

**Comment by ChrisAdderley** [comment]
Ok that's good. Sorry I meant "no further changes" to the model/style of emissive effects, where now there are specific heat textures, and specialized blended transparent model components. Bugs will ofc still be fixed.
