### ISSUE TITLE
Advanced Nosecone  - Type A variants

### ISSUE THREAD

**Issue by woeller** [PorktoberRevolution/ReStocked#258]
Advanced Nosecone  - Type A Gray&Orange / Dark texture variants are having issues compared to type B
![2](https://user-images.githubusercontent.com/35576383/52149006-cc276200-266b-11e9-8088-fb1460711cc7.png)

**Comment by ChrisAdderley** [comment]
Now what on earth could be wrong here?

**Comment by woeller** [comment]
It seems that B/W is also applied, but in the config everything is looking good

**Comment by ChrisAdderley** [comment]
Yeah it's like there's a ghost image. I'll have to investigate further, never seen anything like this one before.

**Comment by ChrisAdderley** [comment]
Aw yeah 29d74de

**Comment by woeller** [comment]
fix confirmend in [29d74de](https://github.com/PorktoberRevolution/ReStocked/commit/29d74de2d9454238cd338d0b05bf2e6d8b832b96)
