### ISSUE TITLE
Off Center Thrust for Rhino

### ISSUE THREAD

**Issue by 51ngular1ty** [PorktoberRevolution/ReStocked#26]
The rhino engine thrust appears to be off center. 
![inkedscreenshot191_li](https://user-images.githubusercontent.com/2055883/43621472-46172c12-969d-11e8-96c1-1463516761de.jpg)

**Comment by ChrisAdderley** [comment]
Fixed in 1386bb3

**Comment by 51ngular1ty** [comment]
Confirmed.  Thank you for the beautiful work.
