### ISSUE TITLE
LV-T30 "Reliant" Liquid Fuel Engine - Compact variant shroud too short

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#260]
Shroud needs to extend a bit lower to avoid creating a gap with the next part down.

![image](https://user-images.githubusercontent.com/22890228/52165557-492bf900-26b7-11e9-9cc6-f5157ff2e83a.png)

**Comment by ChrisAdderley** [comment]
Looks good in 5c7e966

**Comment by TykoTek** [comment]
I'm seeing a bit of Z-fighting on the shroud bottom in compact engine variant only. Looks like the entire shroud drops down a little bit when in compact variant.

**Comment by Poodmund** [comment]
I can confirm the above, the 1.25m shroud seems perfect, however, the compact variant shroud seems to shift down ever so slightly which causes Z-fighting below. 

Video: https://youtu.be/2OuvbufjtZE

**Comment by ChrisAdderley** [comment]
Yes I did not change the compact shroud.

**Comment by ChrisAdderley** [comment]
Fixed in 0d79074

**Comment by TykoTek** [comment]
Confirmed
