### ISSUE TITLE
Reliant Turbopump exhaust pipe hitting boat tail fairing

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#261]
The turbopump exhaust pipe shouldn't be hitting the fairing for the boat tail

![image](https://user-images.githubusercontent.com/22890228/52165593-b475cb00-26b7-11e9-9077-e1a3bd5f3606.png)

**Comment by ChrisAdderley** [comment]
Looks good in 5c7e966. Damnit porky.

**Comment by TykoTek** [comment]
Confirmed Fixed
