### ISSUE TITLE
Swivel hole in mesh

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#262]
gap in the mesh around the bottom of the nozzle. In the picture below you can see the white windows showing through around the lip.

![image](https://user-images.githubusercontent.com/22890228/52165673-a1afc600-26b8-11e9-98d4-22d6d2345465.png)

**Comment by ChrisAdderley** [comment]
Looks good in 5c7e966

**Comment by TykoTek** [comment]
Fixed
