### ISSUE TITLE
Swivel top of shroud mesh fighting with mesh of part above

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#263]
The shroud mesh is fighting with the tank above

![image](https://user-images.githubusercontent.com/22890228/52165709-0b2fd480-26b9-11e9-95c7-326b8b76f1c6.png)

**Comment by ChrisAdderley** [comment]
Looks good in 5c7e966

**Comment by TykoTek** [comment]
Fixed
