### ISSUE TITLE
RE-M3 Mainsail bottom node too high

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#266]
The bottom node is too close to the bottom of the engine bell. This is causing shroud conflicts with other parts. You could shorten the shroud, but in this case the node is closer to the bell than on most other engines so lowering the node would make the part more consistent with others.

![image](https://user-images.githubusercontent.com/22890228/52166019-01a86b80-26bd-11e9-8184-766dd47a8fc0.png)

**Comment by ChrisAdderley** [comment]
Restock can't touch nodes, so the model has been modified in 8fee855

**Comment by TykoTek** [comment]
Fixed
