### ISSUE TITLE
KR-1x2 Twin Boar thrust torque or top node issue

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#267]
The part alone shows no torque by itself, but when I attach another tank on top I'm seeing 0.01kNm of torque (in KER). My guess is the top node isn't quite centered, but it's such a small amount it's hard to see.

**Comment by ChrisAdderley** [comment]
Restock doesn't touch nodes, but I discovered a small inconsistency in the gimbal position so I changed that in 8fee855

**Comment by TykoTek** [comment]
Issue present in Stock. Closing as unfixable without collider work
