### ISSUE TITLE
KR-1x2 Twin Boar hole in mesh

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#268]
There's a vertical gap in the flared housing around the engines allowing light through

![image](https://user-images.githubusercontent.com/22890228/52166211-36b5bd80-26bf-11e9-9651-8ae1243b9a04.png)

**Comment by ChrisAdderley** [comment]
Located and removed in 8fee855

**Comment by TykoTek** [comment]
Confirmed
