### ISSUE TITLE
KR-2L Rhino Top of part overlapping part above it

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#269]
What attached below a tank the two parts don't connect smoothly and you get a jagged color change where the black color of the engine suddenly emerges out past the white color of the tank above

![image](https://user-images.githubusercontent.com/22890228/52166299-5c8f9200-26c0-11e9-9c56-42e1e0549753.png)

**Comment by ChrisAdderley** [comment]
Cleaned up in 8fee855

**Comment by TykoTek** [comment]
Confirmed
