### ISSUE TITLE
SSME Plume is overextended.

### ISSUE THREAD

**Issue by 51ngular1ty** [PorktoberRevolution/ReStocked#27]
The plume is extended a fair distance from the nozzle.
![screenshot193](https://user-images.githubusercontent.com/2055883/43622115-4567d192-96a0-11e8-84a8-ae22c678b0d1.png)

**Comment by ChrisAdderley** [comment]
![screenshot51](https://user-images.githubusercontent.com/5642064/43670873-f7f99458-9745-11e8-9a1d-876a3c54d11b.png)
Can't repro this one!

**Comment by 51ngular1ty** [comment]
Performed clean install with your current build and no additional mods and it definitely works correctly.  Some other mod must have caused it.  Thanks and sorry.

**Comment by 51ngular1ty** [comment]
It appears that the issue was likely caused by Smokescreen/Realplume.

**Comment by ChrisAdderley** [comment]
Yes, the sane model structure that the new models use may not be compatible with how mods that depend on the exact layout of the old models, I suppose.
