### ISSUE TITLE
KR-2L Rhino Shroud issue. 

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#270]
Shroud for compact variant doesn't extend far enough up leaving a gap.

![image](https://user-images.githubusercontent.com/22890228/52166409-ae84e780-26c1-11e9-9c4b-d2857470f423.png)

**Comment by ChrisAdderley** [comment]
Cleaned up in 8fee855

**Comment by TykoTek** [comment]
Confirmed

**Comment by Poodmund** [comment]
Getting a slight gap between the bottom of the shroud on the Rhino on the normal and compact variants:

![untitled-1](https://user-images.githubusercontent.com/10106634/52522964-e244ac00-2c83-11e9-8126-5d242ea01e11.png)

Please close again if you feel its a non-issue.

**Comment by ChrisAdderley** [comment]
Checked the bottom in 8c5f04c

**Comment by TykoTek** [comment]
Improved @Poodmund, Please verify

**Comment by Poodmund** [comment]
Yep seems just fine in https://github.com/PorktoberRevolution/ReStocked/commit/8c5f04cb6f1a8dcaa0af827f4032652f92ee16f7. Closing as resolved.
