### ISSUE TITLE
Heat Shield (1.25m) - Node Positions (Top & Btm)

### ISSUE THREAD

**Issue by woeller** [PorktoberRevolution/ReStocked#271]
Heatshield is clipping through attached parts.
![screenshot0](https://user-images.githubusercontent.com/35576383/52168728-ba0df800-272d-11e9-87b5-796dd4030df5.png)

**Comment by Poodmund** [comment]
For reference, you're comparing this against a part which has not yet been revamped.

**Comment by woeller** [comment]
I've also compared this with Restock Tanks and its behavior remains the same

![screenshot1](https://user-images.githubusercontent.com/35576383/52168826-41a83680-272f-11e9-943d-c874ff37cb6d.png)

**Comment by ChrisAdderley** [comment]
The problem here is that squad put the heatshield note in a REALLY STUPID place. I will reasses this later but basically moving things one way or another screws different things up.

**Comment by Poodmund** [comment]
Whilst on the topic, the bottom, shroud node could be moved down a touch to avoid Z-fighting with the part attached below and the shroud. See animation showing current position and then with the attached part lowered down a small amount to avoid the Z-fighting:

![untitled-1](https://user-images.githubusercontent.com/10106634/52536532-bf81c880-2d53-11e9-98ff-296e3059ef16.gif)

**Comment by ChrisAdderley** [comment]
Problems look solved in 458e07d

**Comment by Poodmund** [comment]
I can confirm that https://github.com/PorktoberRevolution/ReStocked/commit/458e07d84d5cc004c55669d4aa7238ab2d093bd5 has resolved the issue so that the correct positioning is now experienced with the Mk1 Pod and other 1.25m parts.
