### ISSUE TITLE
Oscar-B Fuel Tank - Top/Bottom chamfer of tank is spaced unevenly when attached to other parts

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#273]
When the Oscar-B fuel tanks are stacked with other parts the top and bottom chamfer edges of the tanks are unevenly spaced whereas if the Oscar-B tank is stacked with itself, the chamfer spacing becomes even. See screenshots below:

![untitled-1](https://user-images.githubusercontent.com/10106634/52169945-576e2980-2738-11e9-84ee-302b9ea9b630.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/52169947-5ccb7400-2738-11e9-8b69-cbe6e7b59367.png)

Here you can see that at the connection between the top of the tank, there is not much/no chamfer but at the connection at the bottom of the tank there is a fair amount of chamfer; this is in comparison to the connection between the two Oscar-B tanks were the chamfer spacing at the connection is the same as the spacing between the panels on each tank horizontally.

This effect can be seen when, for example, stacking an LV-1 Ant engine between the Oscar-B tanks.

![untitled-1](https://user-images.githubusercontent.com/10106634/52169860-e2e6bb00-2736-11e9-8ed4-001796a69ea1.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/52169863-e67a4200-2736-11e9-8147-1caa869e2ce7.png)

The shroud has a very minor alignment issue with respect to the Oscar tank panel spacing.

**Comment by ChrisAdderley** [comment]
IMO, super minor, putting to deferred

**Comment by ChrisAdderley** [comment]
Moved into 0.1.0 project as part of the final push

**Comment by ChrisAdderley** [comment]
#482 fixed

**Comment by Poodmund** [comment]
Yep, much better. Resolved with https://github.com/PorktoberRevolution/ReStocked/pull/482.
