### ISSUE TITLE
LV-T15 Valiant - Model issue

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#276]
The gimbal actuator arms aren't lined up with the sockets near the mounting ring on 1.25m variant

![image](https://user-images.githubusercontent.com/22890228/52170430-e2cac900-26fe-11e9-80b9-2eb98b3cd8b0.png)

![image](https://user-images.githubusercontent.com/22890228/52170434-fd04a700-26fe-11e9-8b12-977731810913.png)

**Comment by ChrisAdderley** [comment]
Tuned in 0d79074

**Comment by TykoTek** [comment]
Fixed
