### ISSUE TITLE
LV-1R "Spider" Liquid Fuel Engine - Holes in mesh (ends of actuators and u/side of top pivot

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#277]
![untitled-1](https://user-images.githubusercontent.com/10106634/52170485-2ba47100-2743-11e9-833b-17d9fcde4cf9.png)

The ends of the gimbal actuators have missing faces allowing you to see through to the sky behind.

![untitled-2](https://user-images.githubusercontent.com/10106634/52170490-3a8b2380-2743-11e9-9097-271c8891ea57.png)

The underside of the top pivot point also has a missing face.

**Comment by woeller** [comment]
I can't reproduce the first issue, but confirm the second

![screenshot22](https://user-images.githubusercontent.com/35576383/52173145-41835780-277e-11e9-8a10-faa6a97cdd35.png)

**Comment by Poodmund** [comment]
In reference to the post above, the gimbal animation has to be at its furthest extents to rock the engine around the top pivot for the missing face to appear.

**Comment by ChrisAdderley** [comment]
Addressed 8880fff

**Comment by woeller** [comment]
No more holes in the mesh. But would not it be better if there was a kind of ball joint? Maybe it's not worth the work for such a small engine.

![screenshot34](https://user-images.githubusercontent.com/35576383/52433259-f1551e00-2b0c-11e9-91a7-597b550a9ccc.png)

**Comment by ChrisAdderley** [comment]
Imagine a teeny joint or something. Perils of using PJ's stuff is that it sucks and it's hard to pseudo-fix.

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/8880fff76c70e27349982311c55aa424e0d5f995
