### ISSUE TITLE
O-10 Puff - Gimbal Actuator Constraint Position Issue

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#279]
Gimbal actuator arm not lined up with its socket inside the fairing.

Right hand arm. Used green highlighting to make more visible

![image](https://user-images.githubusercontent.com/22890228/52170568-92a13600-2701-11e9-822e-7b404d1129a3.png)

**Comment by Poodmund** [comment]
![untitled-1](https://user-images.githubusercontent.com/10106634/52176966-73aeac80-27b2-11e9-929b-1712fbfe5a3e.png)

An additional screenshot displaying the issue.

**Comment by ChrisAdderley** [comment]
All good in 8880fff

**Comment by TykoTek** [comment]
Fixed
