### ISSUE TITLE
LV-1R "Spider" Liquid Fuel Engine - Texture Seams 

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#280]
![untitled-1](https://user-images.githubusercontent.com/10106634/52170701-1af5fa00-2747-11e9-9c6e-eeee74d34bdc.png)

See notes on image. Its a very small part so artist's discretion is advised as to whether this warrants any work or not.

**Comment by Poodmund** [comment]
![untitled-1](https://user-images.githubusercontent.com/10106634/52176407-6392cf00-27aa-11e9-8974-be8e3dcfbbf8.png)

The emissive texture seems to have a slightly noticeable seam towards the throat portion of the bell.

**Comment by ChrisAdderley** [comment]
Fixes applied in 8880fff (not perfect but enough)

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/8880fff76c70e27349982311c55aa424e0d5f995
