### ISSUE TITLE
RE-M3 Mainsail - hole in texture

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#281]
Missed this before....

There's a hole in this ring that allows you to see through the pipe beyond. Ring highlighted in picture. Demo of what you can see in the youtube video: https://youtu.be/lPAtNJ7Y8jU

![image](https://user-images.githubusercontent.com/22890228/52171919-562e0400-271a-11e9-8b87-480e6c2afe57.png)

**Comment by ChrisAdderley** [comment]
Hole is gone in 6c6dba1

**Comment by TykoTek** [comment]
Fixed
