### ISSUE TITLE
MK2 Landercan Mesh issue

### ISSUE THREAD

**Issue by woeller** [PorktoberRevolution/ReStocked#282]
Again the Landercan. 

![screenshot21](https://user-images.githubusercontent.com/35576383/52172988-2fec8080-277b-11e9-8ed3-84a5e20ff650.png)

**Comment by ChrisAdderley** [comment]
#311 should fix this one (and a few others I found while fixing it)

**Comment by ChrisAdderley** [comment]
yay!
