### ISSUE TITLE
24-77 "Twitch" Liquid Fuel Engine - Gimbal Constraint Issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#285]
One actuator on the Twitch gimbal mechanism doesn't seem to be constrained properly. See video: https://youtu.be/0afFI-Qatko

![untitled-1](https://user-images.githubusercontent.com/10106634/52176698-29c3c780-27ae-11e9-8ae8-d80dd38dded2.png)

The actuator housing point also seems to be weirdly dark black.

**Comment by ChrisAdderley** [comment]
Typo fixed in 8880fff

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/8880fff76c70e27349982311c55aa424e0d5f995
