### ISSUE TITLE
24-77 "Twitch" Liquid Fuel Engine - Mesh & Texture Seam

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#286]
It appears there is a small seam/crease/gap in the mesh at the top of the Twitch engine on the front-top side of the cowling:

![untitled-1](https://user-images.githubusercontent.com/10106634/52176838-5d9fec80-27b0-11e9-90f0-786b7e9ef7e8.png)

One the front side of the cowling and the front side of the nozzle there is some texture seam/alignment issues occuring:

![untitled-2](https://user-images.githubusercontent.com/10106634/52176843-71e3e980-27b0-11e9-886a-03b3f4989593.png)

**Comment by ChrisAdderley** [comment]
Good enough by 8880fff

**Comment by Poodmund** [comment]
![untitled-1](https://user-images.githubusercontent.com/10106634/52521285-b36f0b80-2c6c-11e9-95a3-6bbe822d9629.png)

There is still a slight mesh gap/seam down the front of the cowling but you have to be angled very specifically for the light the show it up.

Closing for now, @ChrisAdderley 	but please reopen the issue if it requires further resolution.
