### ISSUE TITLE
O-10 "Puff" MonoPropellant Fuel Engine - Small Mesh Seam/Hole

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#287]
There appears to be a small crease/seam/hole in the lower front region of the housing:

![untitled-1](https://user-images.githubusercontent.com/10106634/52177030-4282ac00-27b3-11e9-90da-5d2f537d5c18.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/52177031-46aec980-27b3-11e9-909f-1fcfe1a9de29.png)

It appears stronger when the camera is further away from the part as I guess the renderer tries to anti-alias the seam and so is more visible.

**Comment by ChrisAdderley** [comment]
Fixed e10b094

**Comment by Poodmund** [comment]
Almost invisible, absolutely fine. 😄 	

![untitled-1](https://user-images.githubusercontent.com/10106634/52532374-ede3b180-2d1b-11e9-9444-cc1fd1f3d932.png)
