### ISSUE TITLE
O-10 "Puff" MonoPropellant Fuel Engine - Emissive glow on actuator mounts

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#288]
As shown in the screenshot, the gimbal actuator mounting points glow hot when the emissive texture is ramped up.

![untitled-1](https://user-images.githubusercontent.com/10106634/52178104-3520ee00-27c2-11e9-9d8a-7907ef32312b.png)

**Comment by ChrisAdderley** [comment]
Done in 8880fff

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/8880fff76c70e27349982311c55aa424e0d5f995
