### ISSUE TITLE
48-7S "Spark" Liquid Fuel Engine - Texture seam and anomaly

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#289]
There is a visible seam in the diffuse texture on the engine bell adjacent to the gas generator exhaust pipe:

![untitled-1](https://user-images.githubusercontent.com/10106634/52178301-a2358300-27c4-11e9-8e5d-a9ffe48c8b9f.png)

There is a small blemish on one of the mounting struts, most visible on the 0.625m variant, that could be an error? It may have been/could be intended to be dirt or wear and tear. If so, then its a non-issue.

![untitled-2](https://user-images.githubusercontent.com/10106634/52178317-ce510400-27c4-11e9-8289-f10b9fa2a4cf.png)

**Comment by ChrisAdderley** [comment]
Fixed up in8880fff

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/8880fff76c70e27349982311c55aa424e0d5f995
