### ISSUE TITLE
LV-909 "Terrier" Liquid Fuel Engine - Emissive texture issues

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#292]
The boattail variant seems to be leaking light through its panel lines:

![untitled-2](https://user-images.githubusercontent.com/10106634/52179173-db72f080-27ce-11e9-9725-eb3f89fd084d.png)

The heatup-cooldown animation length between the inside of the bell and outside of the bell is very different. Here you can see a screenshot taken almost immediately after the engine was shutdown, the inside of the bell's emissive texture fades almost instantly whereas the outside takes a while to fade out:

![untitled-4](https://user-images.githubusercontent.com/10106634/52179156-96e75500-27ce-11e9-9dba-e7227dc4184c.png)

Lastly, on a more subjective note, the emissive textures that Porkjet did for this engine do not really match the standard of the ones done by Nertea for the other engines. Nertea's emissive textures show heat variation on the bells/heat banding whereas these ones look almost like a constant gradient has been applied. Finally, the combustion chamber/throat looks very saturated in colour:

![untitled-1](https://user-images.githubusercontent.com/10106634/52179187-0a896200-27cf-11e9-8c04-8fc4d4b6a7a6.png)

![untitled-1](https://user-images.githubusercontent.com/10106634/52179172-d746d300-27ce-11e9-860f-e828792626eb.png)

**Comment by ChrisAdderley** [comment]
Closing because it's pretty much the same issue as https://github.com/PorktoberRevolution/ReStocked/issues/257
