### ISSUE TITLE
LV-T30 "Reliant" Liquid Fuel Engine - Mesh hole in Boattail variant's gas generator exhaust

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#293]
The Boattail's blanking plate cuts through the gas generator exhaust pipe causing it to show through. 

![untitled-1](https://user-images.githubusercontent.com/10106634/52179463-db74ef80-27d2-11e9-8908-b116d3f420e0.png)

**Comment by ChrisAdderley** [comment]
Fixed in 0d79074

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/0d790746cbc65048e7b8cb70d0697aa305253736
