### ISSUE TITLE
LV-T30 "Reliant" Liquid Fuel Engine - Emissive texture issues

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#294]
The emissive texture animation heat-up/cool-down speeds are very different for the inside and outside of the bell. The outside of the bell takes a long time to heat-up compared to the inside. 

This is a screenshot after about a minute of running with the emissive at full opacity:

![untitled-1](https://user-images.githubusercontent.com/10106634/52179608-81752980-27d4-11e9-91a2-4d89c4b65ffc.png)

This is after about 1 second after cutting the engine. The inside of the bell fades out almost immediately.

![untitled-2](https://user-images.githubusercontent.com/10106634/52179593-60acd400-27d4-11e9-80c3-4cd2cd271822.png)

**Comment by ChrisAdderley** [comment]
https://github.com/PorktoberRevolution/ReStocked/issues/257 <- catchall for this issue
