### ISSUE TITLE
KR-10A "Corgi" - Bottom node too close to engine bells

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#297]
The bottom node is so close that a decoupler clips into the engine bells. 

![image](https://user-images.githubusercontent.com/22890228/52233794-da949a00-2874-11e9-8a0e-a321906183c2.png)

**Comment by ChrisAdderley** [comment]
Probably easier to compress the bells a bit..

**Comment by ChrisAdderley** [comment]
Shrank nozzles slightly in 6c6dba1

**Comment by TykoTek** [comment]
Fixed
