### ISSUE TITLE
CR-7 R.A.P.I.E.R - Thrust offcenter

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#298]
Only 1 nozzle is providing thrust.

![image](https://user-images.githubusercontent.com/22890228/52234722-2e07e780-2877-11e9-824d-d7d5df25a337.png)

**Comment by ChrisAdderley** [comment]
Worth investigating because they're all in the right place on the model. Maybe there's a hidden space or something.

**Comment by ChrisAdderley** [comment]
thrustTransform, not thurstTransform.

6c6dba1 fixes.

**Comment by TykoTek** [comment]
LOL...confirmed
