### ISSUE TITLE
CR-7 R.A.P.I.E.R. - Bottom Node

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#299]
Stacking a decoupler below CR-7 leaves a gap. Other parts appear to fit just fine, but would leave the nozzles clipping into the part below (even if not visible)

The gap also appears in Stock. In the RS model the nozzles extend past the length of the outer casing causing the clipping. The stock part the nozzles are flush with the outer casing length

May not be able to correct since the node position is set by stock part.

![image](https://user-images.githubusercontent.com/22890228/52235430-e1bda700-2878-11e9-8450-dd617b96a87b.png)

**Comment by ChrisAdderley** [comment]
I liked the nozzles poking out, was more like the real concepts, but I guess I'll have to get rid of that.

**Comment by ChrisAdderley** [comment]
Tuned in 6c6dba1

**Comment by TykoTek** [comment]
Improved, but now there is z-fighting at both top and bottom nodes.

https://youtu.be/WMIwJp1eICE

**Comment by ChrisAdderley** [comment]
ok that's gone now 763a495

**Comment by woeller** [comment]
No more z-fighting visible.
