### ISSUE TITLE
Probe cores

### ISSUE THREAD

**Issue by IronCretin** [PorktoberRevolution/ReStocked#3]
- Probodobodyne RoveMate
  - [ ] Model
  - [ ] Texture (White)
  - [ ] Texture (Grey)
  - [ ] Texture (Foil)
  - [ ] Integration
- Probodobodyne QBE
  - [x] Model
  - [ ] Texture (Grey)
  - [ ] Texture (Foil)
  - [x] Integration
- Probodobodyne HECS
  - [x] Model
  - [ ] Texture (Grey)
  - [ ] Texture (Foil)
  - [ ] Integration
- Probodobodyne OKTO
  - [x] Model
  - [ ] Texture (Grey)
  - [ ] Texture (Foil)
  - [ ] Integration
- Probodobodyne OKTO2
  - [x] Model
  - [ ] Texture (Grey)
  - [ ] Texture (Foil)
  - [ ] Integration
- Probodobodyne Stayputnik
  - [x] Model
  - [ ] Texture (Grey)
  - [ ] Texture (Foil)
  - [ ] Integration
- Probodobodyne HECS2
  - [x] Model
  - [ ] Texture (Grey)
  - [ ] Texture (Foil)
  - [ ] Integration

**Comment by ChrisAdderley** [comment]
Pretty sure I'm not making that.

**Comment by IronCretin** [comment]
I had you mixed up with Pak, I think. Sorry.

**Comment by ChrisAdderley** [comment]
Note: removed Mk2 Done Core from scope

**Comment by ChrisAdderley** [comment]
Closed as all moved to issues.
