### ISSUE TITLE
Mk1-3 Command Pod - model, top ring too tall

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#304]
The grey ring around the top port sticks up too high. As far as I can tell it's not part of the collider and is just "decorative" yet it's tall enough to stick up through several parts that would likely be attached on top.

Unless we have to keep it due to a compatibility issue with stock I'd suggest shortening the entire ring and getting rid of the 3 taller tabs entirely. They shouldn't be visible anyway when a craft is assembled and at it's current height it just limits building options.

![image](https://user-images.githubusercontent.com/22890228/52277360-6f48d780-2909-11e9-96b2-9fa2af321a28.png)

![image](https://user-images.githubusercontent.com/22890228/52277390-7e2f8a00-2909-11e9-8567-492a2053eea5.png)

**Comment by ChrisAdderley** [comment]
Ring thing height cut by 2/3 in #311

**Comment by TykoTek** [comment]
Confirmed
