### ISSUE TITLE
Mk-2 Lander Can - Texture Issues

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#305]
Two issues around the windows. There's what appears to be a dent in the red-circled area. The two corners circled in green have small white or very shiny points that look out of place. They're pretty small, might be easier to see in this video:  https://www.youtube.com/watch?v=SIx3CrQOEGQ

![image](https://user-images.githubusercontent.com/22890228/52278510-0dd63800-290c-11e9-8b3e-1aa193591f1b.png)

**Comment by TykoTek** [comment]
Update: the two bright spots in green are actually small holes in the mesh. Moving the camera around enables you to see the colors beyond the part. Didn't really notice til I moved the camera so the blue sky was behind and then it was obvious.

**Comment by ChrisAdderley** [comment]
#311 Fixed

**Comment by TykoTek** [comment]
Confirmed
