### ISSUE TITLE
Mk-2 Lander Can - Top Node not centered

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#306]
In the picture below you can see that the decoupler is shifted slightly right. Part of the Mk-2's ring is visible where indicated by the red arrow. When you follow the inside edge around there's more of the edge visible where indicated by the green arrow.

![image](https://user-images.githubusercontent.com/22890228/52279080-88538780-290d-11e9-97b7-2c0a9c27b733.png)

Also, the node may be a bit low as this part and others tend to clip into the top of the lander slightly

**Comment by ChrisAdderley** [comment]
#311 mitigates. Full solution not really possible... but this gets most of the way there

**Comment by TykoTek** [comment]
Looks a lot better. Calling this "fixed"
