### ISSUE TITLE
Vektor gimbeling issues

### ISSUE THREAD

**Issue by woeller** [PorktoberRevolution/ReStocked#309]
Nozzle clips through boattail while the gimbal animation is at its farthest extent (boattail variant)

![screenshot27](https://user-images.githubusercontent.com/35576383/52288302-3e4dbe80-296c-11e9-9956-3f0077509850.png)

The actuator mesh is too short while the gimbal animation is at its farthest extent (only 2 sides; 2.5/compact variant)

![screenshot28](https://user-images.githubusercontent.com/35576383/52288772-1743bc80-296d-11e9-9ae8-7240b42a86f0.png)
![screenshot29](https://user-images.githubusercontent.com/35576383/52288779-19a61680-296d-11e9-9720-c5fd3d102f44.png)

Gimbal actuator clipps through damper while the gimbal animation is at its farthest extent (all sides; 2.5/compact variant)

![screenshot30](https://user-images.githubusercontent.com/35576383/52288979-730e4580-296d-11e9-9482-ce89d376f9e0.png)

**Comment by woeller** [comment]
> 
> 
> Nozzle clips through boattail while the gimbal animation is at its farthest extent (boattail variant)
> 
> ![screenshot27](https://user-images.githubusercontent.com/35576383/52288302-3e4dbe80-296c-11e9-9956-3f0077509850.png)
> 
> The actuator mesh is too short while the gimbal animation is at its farthest extent (only 2 sides; 2.5/compact variant)
> 
> ![screenshot28](https://user-images.githubusercontent.com/35576383/52288772-1743bc80-296d-11e9-9ae8-7240b42a86f0.png)
> ![screenshot29](https://user-images.githubusercontent.com/35576383/52288779-19a61680-296d-11e9-9720-c5fd3d102f44.png)
> 
> Gimbal actuator clipps through damper while the gimbal animation is at its farthest extent (all sides; 2.5/compact variant)
> 
> ![screenshot30](https://user-images.githubusercontent.com/35576383/52288979-730e4580-296d-11e9-9482-ce89d376f9e0.png)

**Comment by ChrisAdderley** [comment]
Ok, gimbals lengthened and contracted, and boattail rework in 6c6dba1 . This is probably as good as it will get

**Comment by woeller** [comment]
Looks really good now
