### ISSUE TITLE
Mk1 command pod: I don't know if the hatch may open

### ISSUE THREAD

**Issue by GregroxMun** [PorktoberRevolution/ReStocked#313]
This is pretty minor, but I think the "Warning: Hatch May Open" panel should be added to the Mk1 pod. It was there in NovaSilisko's original model, it was there in the Porkjet revamp, and it was even kept in the stock revamp. Therefore I suggest it be added to the ReStock Mk1 pod.

**Comment by ChrisAdderley** [comment]
Maybe, but so minor that it's going to go in the deferred pile for now.

**Comment by ChrisAdderley** [comment]
Done in 1b6940843be848c5cd4031550da1cff6e1feb71d for next version
