### ISSUE TITLE
Jumbo-64 tank default color

### ISSUE THREAD

**Issue by GregroxMun** [PorktoberRevolution/ReStocked#315]
I'd like to suggest that you make the large Rockomax fuel tank default to the orange variant, as the description still refers to the orange color.

*The largest tank available from Rockomax, the Jumbo-64 holds a vast amount of fuel in a friendly orange insulated container. Contrary to popular belief, the Jumbo-64 is NOT orange flavored and should NOT be tasted.*

**Comment by ChrisAdderley** [comment]
Nah. We preserve the defaults as they currently stand.
