### ISSUE TITLE
LVT-45 - Holes in mesh

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#316]
Several holes in mesh -

1. Turbopump feed pipes have gaps
2. Can see through the pyramid shaped plate attached to the 4 support struts

![inkedscreenshot85_li](https://user-images.githubusercontent.com/22890228/52480144-b6300a80-2b5f-11e9-8ac2-d3af0a53126f.jpg)

**Comment by Poodmund** [comment]
![untitled-1](https://user-images.githubusercontent.com/10106634/52521583-1367b100-2c71-11e9-9e9d-782c4d6953d7.png)

To supplement, I could only see the culled faces of the pyramid mount on the Compact variant.

**Comment by ChrisAdderley** [comment]
Fixed  e10b094

**Comment by Poodmund** [comment]
Resolved as per https://github.com/PorktoberRevolution/ReStocked/commit/e10b094e2c202d9833bcea3560c1491d4f7c3e50
