### ISSUE TITLE
IX-6315 Dawn - Plume too far from engine

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#323]
The plume starts too far away from the engine.

![image](https://user-images.githubusercontent.com/22890228/52490328-5cd4d500-2b79-11e9-9143-ab2186f7eb70.png)

**Comment by Poodmund** [comment]
The thrust transform is also a bit away from the end of the engine which may be contributing to this:

![untitled-1](https://user-images.githubusercontent.com/10106634/52526090-9ad21600-2cab-11e9-9d1a-cc4f70fe9175.png)

**Comment by ChrisAdderley** [comment]
Squad put that there, not me. Plume moved in e10b094, might need a real replacement at some point though

**Comment by Poodmund** [comment]
Resolved as per https://github.com/PorktoberRevolution/ReStocked/commit/e10b094e2c202d9833bcea3560c1491d4f7c3e50
