### ISSUE TITLE
IX-6315 Dawn - Node placement

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#324]
The engine top node placement causes gap between it and an adjacent tank

![image](https://user-images.githubusercontent.com/22890228/52490540-d2d93c00-2b79-11e9-91ef-8f3700e8c8bd.png)

**Comment by Poodmund** [comment]
Can confirm:

![untitled-1](https://user-images.githubusercontent.com/10106634/52526148-627f0780-2cac-11e9-87d0-46805e812a38.png)

Tellingly, this is not an issue on the bottom node of the 1.25m Xenon tank, so it would suggest that the bottom node on that fuel tank is off... but that's an issue to be reported another day.

**Comment by ChrisAdderley** [comment]
Good in e10b094

**Comment by Poodmund** [comment]
Looks fine now in https://github.com/PorktoberRevolution/ReStocked/commit/e10b094e2c202d9833bcea3560c1491d4f7c3e50
