### ISSUE TITLE
KR-1 Boar - Gap in Gimbal piston model

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#325]
when at extreme gimbal there's a visible gap in the piston arm

![image](https://user-images.githubusercontent.com/22890228/52497083-ff954f80-2b89-11e9-8200-85a25619cb46.png)

**Comment by Poodmund** [comment]
Can confirm:

![untitled-1](https://user-images.githubusercontent.com/10106634/52526999-636a6600-2cb9-11e9-8e36-775e32e5ee53.png)

**Comment by Poodmund** [comment]
I just remembered I didn't mention this before, is it worth applying a smoothing group to the cylinder circled? The one one the opposite side actuator is similar.

![untitled-1](https://user-images.githubusercontent.com/10106634/52533506-9dc11b00-2d2c-11e9-9713-26ce2f79d6a9.png)

**Comment by ChrisAdderley** [comment]
All fixed with f950fea

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/f950feaabac4da21a1121b605846d191de46598e
