### ISSUE TITLE
LV-303 Pug - Emissive issue

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#326]
The boat tail variant's emissive extends onto the boat tail structure

![image](https://user-images.githubusercontent.com/22890228/52497356-babde880-2b8a-11e9-9107-c0ab4147dc82.png)

**Comment by blowfishpro** [comment]
Probably how Porkjet had it?  I guess it's debatable whether this is the desired effect or not

**Comment by blowfishpro** [comment]
I'm guessing that's how Porkjet made it?  Debatable I guess whether this is a desirable effect

**Comment by TykoTek** [comment]
I just checked and PJ's original Part Overhauls version didn't have an emissive.

**Comment by ChrisAdderley** [comment]
This is porkjet s work yeah. Perhaps the partoverhauls one didn't have it enabled. All the pork engines share the same texture sheet.

This does look particularly bad though

**Comment by ChrisAdderley** [comment]
Closed, see https://github.com/PorktoberRevolution/ReStocked/issues/349

**Comment by RandomAnnoyingGuy** [comment]
I like this
