### ISSUE TITLE
LV-303 Pug - Plume not wide enough at nozzle exit

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#327]
The plume looks like it should be wider to fill the nozzle diameter.

![image](https://user-images.githubusercontent.com/22890228/52497487-0e303680-2b8b-11e9-8624-e0a75a2aa188.png)

**Comment by ChrisAdderley** [comment]
Plume scaling changed in e10b094

**Comment by TykoTek** [comment]
I checked and it still looks too narrow. The gasses should look like they're ejecting at the full width of the nozzle - especially in a vacuum. You can see in the video below that it looks like you're getting flow separation which you'd expect at high pressures.

https://youtu.be/41vE8tJ4w_U

**Comment by ChrisAdderley** [comment]
Issue was actually related to squad's scaling shitshow, it should be fixed in f950fea

**Comment by TykoTek** [comment]
Great! Fixed.
