### ISSUE TITLE
LV-T15 Valiant - Emissive issue

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#328]
The emissives are showing up in the boat tail, tip of turbopump exhaust and in the flexible fuel feed joints.

![image](https://user-images.githubusercontent.com/22890228/52497824-f1e0c980-2b8b-11e9-9243-d958d8191aa5.png)

![image](https://user-images.githubusercontent.com/22890228/52497873-13da4c00-2b8c-11e9-87fb-c7e1fb1677df.png)

**Comment by ChrisAdderley** [comment]
Closed, see https://github.com/PorktoberRevolution/ReStocked/issues/349
