### ISSUE TITLE
Mk-1H Torch - Gimbal axis non-functional

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#329]
One axis of gimbaling is non functional. The engine will gimbal in the pitch axis, but not the yaw axis

![image](https://user-images.githubusercontent.com/22890228/52498490-cd85ec80-2b8d-11e9-8d63-037bf067570a.png)

**Comment by ChrisAdderley** [comment]
Gimbal transform pointed 90 degrees off axis. Surprised it worked at all. 03b5b38

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/03b5b383c4d3224db011f7a8dd6177708e853d5a
