### ISSUE TITLE
RT-1 Mallet / RT-2 Striker - Specs balances

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#330]
The thrust for these motors is currently as high as the Flea. I think we can drop that a bit to reflect the smaller nozzles - they're the same tech level, so I'd expect the thrust to somewhat scale with size.

Current: thrust / TWR    (VAC)
RT-10: 227 / 6.49
RT-5: 192 / 13.04
RT-2: 192 / 11.86      _maybe: 125 / 7.65_
RT-1: 192 / 18.63      _maybe: 115 / 11.18_

Open to other ideas. This is just a starting point.

**Comment by ChrisAdderley** [comment]
Changed in e10b094

**Comment by TykoTek** [comment]
Confirmed
