### ISSUE TITLE
RE-I5 "Skipper" Engine - 2.5m variant shroud texture issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#334]
The 2.5m variant shroud, right at the top of the shroud, has a texture issue where the panelling seems to be cut off (UV issue?), the Compact variant does not have this issue.

See screenshot:

![untitled-1](https://user-images.githubusercontent.com/10106634/52522040-0ac6a900-2c78-11e9-97a3-d5f91b853f3e.png)

You can see, like, the top 20% of the grey/orange panelling is cut off.

**Comment by ChrisAdderley** [comment]
Can't reliably repro, but had an idea and did a thing in 03b5b38, hope it helps

**Comment by Poodmund** [comment]
https://github.com/PorktoberRevolution/ReStocked/commit/03b5b383c4d3224db011f7a8dd6177708e853d5a seems to have fixed it. Resolved!
