### ISSUE TITLE
RE-M3 "Mainsail" Liquid Fuel Engine - Emissive texture issue near main gimbal point

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#335]
There seems to be a small amount of emissive bleed onto the main gimbal pivot point on all variants. See screenshot:

![untitled-1](https://user-images.githubusercontent.com/10106634/52522401-e9b48700-2c7c-11e9-9f77-b3c3a065d625.png)

**Comment by ChrisAdderley** [comment]
Done in . Plus more random bleeds fixed in 03b5b38.

**Comment by woeller** [comment]
Fix confirmend.

**Comment by Poodmund** [comment]
Can confirm, https://github.com/PorktoberRevolution/ReStocked/commit/03b5b383c4d3224db011f7a8dd6177708e853d5a resolves the issue.
