### ISSUE TITLE
LFB KR-1x2 "Twin-Boar" Liquid Fuel Engine - Mesh holes/anomalies

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#336]
There are 4 anomalies around the fuel tank area, one on each quarter:

![untitled-1](https://user-images.githubusercontent.com/10106634/52522576-0ea9f980-2c7f-11e9-8533-869cbc86bccc.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/52522577-110c5380-2c7f-11e9-8697-ff0167e5fe42.png)

There are also two areas (one each side) where there is a large hole in the mesh which, when looked at from certain angles, is visible.

![untitled-3](https://user-images.githubusercontent.com/10106634/52522590-37ca8a00-2c7f-11e9-9af2-20d7a3482915.png)

![untitled-4](https://user-images.githubusercontent.com/10106634/52522592-3b5e1100-2c7f-11e9-8079-ee89bfe29d07.png)

Here you can see the large area that is blank when I've clipped the camera through to the region in question:

![untitled-5](https://user-images.githubusercontent.com/10106634/52522595-529cfe80-2c7f-11e9-8604-5810055cb876.png)

**Comment by ChrisAdderley** [comment]
Got the hole fixed and moved the protruding meshes in 2dbf8b3

**Comment by woeller** [comment]
Fix confirmend.

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/2dbf8b3723eedff44dbb09035c0da0f624001349
