### ISSUE TITLE
RT-10 "Hammer" Solid Fuel Booster - Small gaps in mesh

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#337]
The ribs around the main cylinder seem to have small gaps where they join the main cylinder.

![untitled-1](https://user-images.githubusercontent.com/10106634/52523356-6f89ff80-2c88-11e9-88e7-1e1ebbdcf4aa.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/52523364-80d30c00-2c88-11e9-9d72-536793cc60c1.png)

**Comment by ChrisAdderley** [comment]
763a495 dragon01 level picky

**Comment by Poodmund** [comment]
Unlike dragon01, I am eternally grateful when you fix the issue, as per https://github.com/PorktoberRevolution/ReStocked/commit/763a4953288a018eb8a58f003517a9647cb28700 😝
