### ISSUE TITLE
RT-5 "Flea" Solid Fuel Booster - Small gaps in mesh

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#338]
The ribs around the main cylinder seem to have small gaps where they join the main cylinder.

![untitled-1](https://user-images.githubusercontent.com/10106634/52523484-ccd28080-2c89-11e9-9381-c124cf71577e.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/52523486-d2c86180-2c89-11e9-97e2-d77457a4a25a.png)

**Comment by ChrisAdderley** [comment]
763a495

**Comment by DMagic1** [comment]
They also appear around the base of the rim at the top.

![screenshot78](https://user-images.githubusercontent.com/5150421/52527086-db706600-2c90-11e9-97c2-4abb73f7b7bb.png)

**Comment by ChrisAdderley** [comment]
Top area fixed in 8c5f04c

**Comment by Poodmund** [comment]
All resolved as per https://github.com/PorktoberRevolution/ReStocked/commit/8c5f04cb6f1a8dcaa0af827f4032652f92ee16f7
