### ISSUE TITLE
BACC "Thumper" Solid Fuel Booster - Small gaps in mesh

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#339]
The ribs around the main cylinder seem to have small gaps where they join the main cylinder.

![untitled-1](https://user-images.githubusercontent.com/10106634/52523650-82ea9a00-2c8b-11e9-91d8-9f7006154390.png)

**Comment by ChrisAdderley** [comment]
763a495 have code

**Comment by Poodmund** [comment]
I see that https://github.com/PorktoberRevolution/ReStocked/commit/4158274aaa2dd0aec87d0c4f13ece0f6e7798491 uploaded a new Thumper .mu (https://github.com/PorktoberRevolution/ReStocked/commits/master/Distribution/Restock/GameData/ReStock/Assets/Engine/restock-engine-srb-thumper-1.mu) but using the latest build https://github.com/PorktoberRevolution/ReStocked/commit/2cdcba9d9cb5dc7c846f9fde66c7ae29685e87aa and by also downloading the latest .mu separately, I am still seeing the issue described above:

![untitled-1](https://user-images.githubusercontent.com/10106634/52532969-a3b2fe00-2d24-11e9-932d-af0c7f4f6276.png)

**Comment by ChrisAdderley** [comment]
Eh fixed it again f950fea

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/f950feaabac4da21a1121b605846d191de46598e
