### ISSUE TITLE
Engine sound levels

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#34]
The new engine sounds scale sound level to thrust in a linear fashion: 10% thrust = 10% volume and 100% thrust = 100% volume. This is different than stock sounds which are still at ...say 50% volume at low thrust.

I'd expect an engine to put out out a lot of noise even at lowest thrust levels. Is this curve adjustable?

**Comment by ChrisAdderley** [comment]
I wasn't aware I'd even changed this - copied keys from stock engines. I will look into it, it's almost certainly possible!

**Comment by ChrisAdderley** [comment]
Ok, it's quite easy to do this, there is a curve. 
```
fx-kickback-running
		{
			AUDIO
			{
				  channel = Ship
				  clip = sound_rocket_hard
				  volume = 0.0 0.0
				  volume = 1.0 1.0
				  pitch = 0.0 0.2
				  pitch = 1.0 1.0
				  loop = true
			}
```
I don't know precisely what the numbers should be like. Do you have any bandwidth to generate/test some curves and report on good numbers?

**Comment by TykoTek** [comment]
Just a followup... the audio effects being built by [ensou04 for RocketSoundEnhancement](https://github.com/ensou04/RocketSoundEnhancement) are Freakin'Awesome (TM) and would be a great compliment to your visual rebuild. 

It might be worth working with him to integrate his work, if he's willing to share, instead of building everything from scratch.

**Comment by Kradgger** [comment]
> Just a followup... the audio effects being built by [ensou04 for RocketSoundEnhancement](https://github.com/ensou04/RocketSoundEnhancement) offer a huge quality improvement over Stock and would be a great compliment to your visual rebuild.
> 
> It might be worth working with him to integrate his work, if he's willing to share, instead of building everything from scratch.

It works on top of RealPlume, and Nert always includes RealPlume configs, so I'm guessing count on it!

**Comment by TykoTek** [comment]
Ensou04 already said they'd consider a custom set of configs that wouldn't require RealPlume. This would avoid adding dependencies to ReStock

**Comment by ChrisAdderley** [comment]
> It works on top of RealPlume, and Nert always includes RealPlume configs, so I'm guessing count on it!

I don't actually, I always just make nice plumes. 

Re: this ticket, though it would be nice to have RSE support, I'd like to have dependency-less versions work out of the box so this should still be addressed.

**Comment by ChrisAdderley** [comment]
Ok for the purposes of this ticket, I have propagated the example curves from the Terrier and Vector above to all engines in e29c0cd. This should resolve the base issue, RSE support can be added at a later date.

**Comment by TykoTek** [comment]
Nice
