### ISSUE TITLE
S1 SRB-KD25k "Kickback" Solid Fuel Booster - Nozzle actuator issues

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#340]
THe actuators on the inside of the cowling are not constrained correctly to their hard points:

![untitled-1](https://user-images.githubusercontent.com/10106634/52523796-11135000-2c8d-11e9-8153-dc2f80988c08.png)

And some are missing the main piston housing(?):

![untitled-2](https://user-images.githubusercontent.com/10106634/52523800-153f6d80-2c8d-11e9-8b92-6aec2f6823a4.png)

A couple of the actuator hard points are clipping through to the outside of the SRB cowling:

![untitled-3](https://user-images.githubusercontent.com/10106634/52523808-2b4d2e00-2c8d-11e9-8628-212287826e75.png)

**Comment by ChrisAdderley** [comment]
763a495

**Comment by Poodmund** [comment]
Resolved as per https://github.com/PorktoberRevolution/ReStocked/commit/763a4953288a018eb8a58f003517a9647cb28700
