### ISSUE TITLE
S1 SRB-KD25k "Kickback" Solid Fuel Booster - Hole in mesh at nozzle gimbal point

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#341]
Hole in mesh between nozzle and bulkhead, see screenshot:

![untitled-1](https://user-images.githubusercontent.com/10106634/52523873-29d03580-2c8e-11e9-86d6-963ca7041ef0.png)

**Comment by ChrisAdderley** [comment]
Well its no longer a problem in 763a495

**Comment by Poodmund** [comment]
Resolved as per https://github.com/PorktoberRevolution/ReStocked/commit/763a4953288a018eb8a58f003517a9647cb28700
