### ISSUE TITLE
S1 SRB-KD25k "Kickback" Solid Fuel Booster - Small emissive issue on side of tank

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#342]
When the emissive ramps up, there is a small part on the side of the booster tank that is colouring red/orange at the seam, see screenshot:

![untitled-1](https://user-images.githubusercontent.com/10106634/52523884-7287ee80-2c8e-11e9-933c-b0ca608dff2d.png)

**Comment by ChrisAdderley** [comment]
And the black line is bad too 763a495

**Comment by Poodmund** [comment]
Resolved as per https://github.com/PorktoberRevolution/ReStocked/commit/763a4953288a018eb8a58f003517a9647cb28700
