### ISSUE TITLE
Clamp-O-Tron Sr. Docking Port - Many separate game objects in mesh

### ISSUE THREAD

**Issue by DMagic1** [PorktoberRevolution/ReStocked#344]
The 2.5m docking port has many duplicated game objects that share the same texture as the main mesh object. This results in a significant increase in the number of draw calls generated for each instance of the part.

![screenshot63](https://user-images.githubusercontent.com/5150421/52525518-f1722c80-2c78-11e9-8bcd-61fbe1c37246.png)
All objects under the "Cylinders" object should be able to be merged with the primary mesh object.

**Comment by ChrisAdderley** [comment]
Removed the rig in 2cdcba9

**Comment by DMagic1** [comment]
Looks good to me.
