### ISSUE TITLE
KR-10A 'Corgi' Liquid Fuel Engine Cluster - Mesh gaps in 3.75m mounting plate

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#347]
There are gaps in the mesh of the 3.75m Variant mounting plate on the top side at the inner and outer edges of the ring. See screenshot:

![untitled-1](https://user-images.githubusercontent.com/10106634/52526541-d5d74800-2cb1-11e9-8345-96eeefdff038.png)

The outer ring gap is just about observable when a tank is stack mounted on top.

**Comment by ChrisAdderley** [comment]
just welded it over, and over, and over in 8c5f04c

**Comment by woeller** [comment]
Fix confirmend.

**Comment by Poodmund** [comment]
Can confirm as resolved.
