### ISSUE TITLE
KR-10A 'Corgi' Liquid Fuel Engine Cluster - Emissive texture issue heating up parts of structural frame

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#348]
Some of the parts of the structural frame on the Corgi are being heated up when the emissive texture is ramped up. See screenshots:

![untitled-1](https://user-images.githubusercontent.com/10106634/52526632-6d896600-2cb3-11e9-9579-d30803cadf7b.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/52526635-6febc000-2cb3-11e9-9f03-a97a8139b63f.png)

**Comment by ChrisAdderley** [comment]
Yekh that was hard to find 8c5f04c

**Comment by woeller** [comment]
Fix confirmend

**Comment by Poodmund** [comment]
Can confirm as resolved.
