### ISSUE TITLE
KR-1 'Boar' Liquid Fuel Engine - Texture seam, pronounced when emissive is active

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#350]
When the emissive is ramped up there is a visible seam in the texture on the outside of the gas generator exhaust pipe:

![untitled-1](https://user-images.githubusercontent.com/10106634/52527042-3c606400-2cba-11e9-9041-6e6b0ef6c4e7.png)

**Comment by ChrisAdderley** [comment]
Adjusted for boar and twin boar in 2dbf8b3

**Comment by woeller** [comment]
Fix confirmend.

**Comment by Poodmund** [comment]
Yep, fine and dandy. Resolved.
