### ISSUE TITLE
KR-10A Corgi texture seam when emissive is active

### ISSUE THREAD

**Issue by woeller** [PorktoberRevolution/ReStocked#352]
More visible in Game, but the screenshots should clarify it.

![screenshot44](https://user-images.githubusercontent.com/35576383/52527764-44c29a00-2cce-11e9-8e18-7229166737d6.png)

![screenshot45](https://user-images.githubusercontent.com/35576383/52527768-48562100-2cce-11e9-9b92-26d8b2ef7bb9.png)

**Comment by Poodmund** [comment]
Whoops, this slipped past my radar. The bell isn't so visible to be honest but the throat seem is much more apparent.

![untitled-1](https://user-images.githubusercontent.com/10106634/52532272-0bb01700-2d1a-11e9-92c4-03837a05aeb6.png)

**Comment by ChrisAdderley** [comment]
Changed in latest push, not perfect but good enough.

**Comment by woeller** [comment]
Now there are new problems with the emissive. The links that hold the nozzle should not heat up. The nozzle itself is better now, but has had other problems added to it.

![screenshot50](https://user-images.githubusercontent.com/35576383/52576416-4d2aea00-2e20-11e9-92c4-b6d8d7c03556.png)

Yes it' way better but I don't know if I would feel comfortable with this, it is your Mod:

![screenshot51](https://user-images.githubusercontent.com/35576383/52577212-ea3a5280-2e21-11e9-8958-11fde9f4aad0.png)

**Comment by ChrisAdderley** [comment]
I don't know how that happened.

**Comment by ChrisAdderley** [comment]
Re-fixed in 6485b44

**Comment by woeller** [comment]
It seems you are satisfied with the nozzle throat. Then i can confirm the fix.

**Comment by Poodmund** [comment]
Tested https://github.com/PorktoberRevolution/ReStocked/commit/6485b4412ab7b46a5070bb69afa964c604794156 and issues with glowing frame as resolved.

This is the current, improved seam on the throat.

![untitled-1](https://user-images.githubusercontent.com/10106634/52588815-478bcf00-2e35-11e9-974f-6011ee82c557.png)

Please close if satisfactory.

**Comment by ChrisAdderley** [comment]
Screw this model
