### ISSUE TITLE
RE-M3 Mainsail visible texture seams when emissive is active

### ISSUE THREAD

**Issue by woeller** [PorktoberRevolution/ReStocked#353]
![screenshot46](https://user-images.githubusercontent.com/35576383/52527985-c74d5880-2cd2-11e9-987d-0fdd1a27b565.png)
![screenshot47](https://user-images.githubusercontent.com/35576383/52527996-ec41cb80-2cd2-11e9-9b68-f269015d4ed1.png)

To find the spots better, another screenshot with more lighting.
![screenshot49](https://user-images.githubusercontent.com/35576383/52527998-ee0b8f00-2cd2-11e9-8e2e-e33797777590.png)

**Comment by ChrisAdderley** [comment]
Changed in latest push, not perfect but good enough.

**Comment by woeller** [comment]
Fix confirmend.
