### ISSUE TITLE
RT-1 'Mallet' Solid Rocket Booster - Emissive stops halfway up nozzle

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#354]
The emissive has a hard stop line halfway up the nozzle. Not sure if intended or not so I thought I'd raise the issue anyway. Please close if a non-issue.

![untitled-1](https://user-images.githubusercontent.com/10106634/52533825-7751ae80-2d31-11e9-91af-f0039828afa3.png)

**Comment by ChrisAdderley** [comment]
Should be up with the material change higher up, fixed in f950fea

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/f950feaabac4da21a1121b605846d191de46598e
