### ISSUE TITLE
RT-2 'Striker' Solid Rocket Booster - Emissive stops halfway up nozzle

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#355]
Similar to https://github.com/PorktoberRevolution/ReStocked/issues/354. The emissive has a hard stop line halfway up the nozzle. Not sure if intended or not so I thought I'd raise the issue anyway. Please close if a non-issue.

![untitled-1](https://user-images.githubusercontent.com/10106634/52533857-327a4780-2d32-11e9-9414-182a71fb2a5d.png)

**Comment by ChrisAdderley** [comment]
As !354

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/f950feaabac4da21a1121b605846d191de46598e
