### ISSUE TITLE
AE-FF1.5 Airstream Protective Shell (1.875m) - Z-Fighting at bottom node connection

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#357]
When a part is connected to the bottom node of the 1.875m fairing base, there is some Z-Fighting occurring between the two parts. The bottom node may need to be lowered a bit?

See video: https://www.youtube.com/watch?v=k7hozE8lsIU

**Comment by ChrisAdderley** [comment]
Fixed  6485b44

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/6485b4412ab7b46a5070bb69afa964c604794156
