### ISSUE TITLE
AE-FF1.5 Airstream Protective Shell (1.875m) - Black/White variant mesh vertex issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#358]
There seems to be a mis-positioned vertex on the Black/White variant of the 1.875m fairing at the top ring, see animation showing the vertex spiking up and away from the top plane:

![untitled-1](https://user-images.githubusercontent.com/10106634/52534843-69565a80-2d3e-11e9-9476-89bcd420de75.gif)

**Comment by ChrisAdderley** [comment]
Fixed 6485b44

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/6485b4412ab7b46a5070bb69afa964c604794156
