### ISSUE TITLE
Heat Shield (0.625m) - Shroud texture seam

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#359]
It looks as though there may be some UV map issue with the shroud texture on the 0.625m Heat Shield. There is a seam that can be seen here:

![untitled-1](https://user-images.githubusercontent.com/10106634/52536224-a37c2800-2d4f-11e9-97ee-2c5b2d2df535.png)

For reference, here is the reverse side of the part shown above:

![untitled-2](https://user-images.githubusercontent.com/10106634/52536230-ae36bd00-2d4f-11e9-9e0e-2eb0d46a2216.png)

**Comment by ChrisAdderley** [comment]
Fixed 458e07d

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/458e07d84d5cc004c55669d4aa7238ab2d093bd5
