### ISSUE TITLE
Missing joints on Corgi

### ISSUE THREAD

**Issue by 51ngular1ty** [PorktoberRevolution/ReStocked#36]
![image](https://user-images.githubusercontent.com/2055883/45912411-63d79280-bde6-11e8-98b1-65dfc8c3f5d6.png)

Im not sure if joint is the right word but I did notice this.

**Comment by ChrisAdderley** [comment]
Weird! I'll put it on the list though.

(Just so you know, everything on that branch is really unstable).

**Comment by 51ngular1ty** [comment]
As best I can tell other than some localization issues and missing names everything seems to be working well on that branch.  That art bug is about the only thing I have been able to find so far. Anyway, I appreciate the hard work you are doing to pull this all together.

**Comment by ChrisAdderley** [comment]
Done with merge of #183

**Comment by Poodmund** [comment]
Confirmed resolved with https://github.com/PorktoberRevolution/ReStocked/pull/183

![untitled-2](https://user-images.githubusercontent.com/10106634/51629474-92ee4400-1f3f-11e9-8724-ab430d90c6ad.png)

**Comment by ChrisAdderley** [comment]
I will mark this as done as it's clear to me the fix worked from the other issue.
