### ISSUE TITLE
Heat Shield (3.75m) - Gaps in mesh on internal join between sheild and frame

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#360]
There are mesh gaps on the 3.75m fairings on the internal sides (affects all variants) where the ablative shield meets the internal frame. See screenshot:

![untitled-1](https://user-images.githubusercontent.com/10106634/52536451-a9273d00-2d52-11e9-8b41-cf2e9d6e326b.png)

Its also worth noting that the gaps 'seemed' different between variants. The 'Unpainted' variant, shown below, looked as if the internal frame and shield were offset from each other giving a large seam on one side but not the other:

![untitled-2](https://user-images.githubusercontent.com/10106634/52536460-d116a080-2d52-11e9-9737-58756f2c70d2.png)

**Comment by ChrisAdderley** [comment]
d555161 fixes

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/d555161af4bf96badd65dd1c5b5e808116683e19
