### ISSUE TITLE
Heat Shield (2.5m) - Top Node Position

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#361]
SQUAD screwing up the node positions on the heat shields again just the same as the 1.25m sheild (https://github.com/PorktoberRevolution/ReStocked/issues/271). 

![untitled-1](https://user-images.githubusercontent.com/10106634/52536619-decd2580-2d54-11e9-8f03-7c6eee7e62d9.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/52536621-e096e900-2d54-11e9-8534-eaf04af055a9.png)

**Comment by drewcassidy** [comment]
Would it be possible to add a second node flush with the top to allow for this without breaking use with the Mk 1-3 pod?

**Comment by Poodmund** [comment]
Fixed with the recent changes as per https://github.com/PorktoberRevolution/ReStocked/commit/458e07d84d5cc004c55669d4aa7238ab2d093bd5
