### ISSUE TITLE
AE-FF1.5 Airstream Protective Shell (1.875m) - Gap between base and fairing

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#362]
There's a gap between the top of the base and where the fairing starts. It appears in all three color variants

![image](https://user-images.githubusercontent.com/22890228/52542050-c3f8b200-2d50-11e9-89b3-49ba4efa6fa1.png)

**Comment by ChrisAdderley** [comment]
Fixed 6485b44

**Comment by TykoTek** [comment]
Confirmed
