### ISSUE TITLE
Heat Shield (3.75m) - Gap at bottom of shroud

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#363]
There's a gap between the bottom of the shroud and the next part attached below.

![image](https://user-images.githubusercontent.com/22890228/52543441-987cc400-2d5e-11e9-9e35-d51258020528.png)

**Comment by ChrisAdderley** [comment]
A fix was included in #390

**Comment by TykoTek** [comment]
Confirmed...
