### ISSUE TITLE
SC-9001 Science Junior - lip around top and bottom a bit bigger than 1.25m diameter

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#367]
The dark ring at the top and bottom stick out a bit past the 1.25m stack width

![image](https://user-images.githubusercontent.com/22890228/52599363-48106f80-2e0d-11e9-9fad-d0101490d9ff.png)

**Comment by drewcassidy** [comment]
fixed in d4b37f8
