### ISSUE TITLE
Mystery Goo Inline RS+ - Typo in localization

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#368]
"After an unfortunate accident where a technician attempted to **stock** delicate machinery on the classic Mystery Goo™ canister"

This should read **stack**, not stock

**Comment by drewcassidy** [comment]
should be fixed in https://github.com/PorktoberRevolution/ReStocked/commit/ed3d03c31d38ba0e74014a191676d858bb421957 along with another typo in the radial materials bay
