### ISSUE TITLE
US-locali[zs]ation spellings

### ISSUE THREAD

**Issue by drewcassidy** [PorktoberRevolution/ReStocked#369]
There are several canadian/british spellings of words in the localization files ("centre" and "realising"). Should these be changed to the US spellings? the file is `en_us` after all

**Comment by ChrisAdderley** [comment]
This is what happens when a canadian writes stuff ;)

**Comment by ChrisAdderley** [comment]
I found the one use of centre, but both realisings are copy-pastes from stock fairing descriptions

**Comment by ChrisAdderley** [comment]
e4dc754 changes the centre, let me know about any other things you want changes to wrong english
