### ISSUE TITLE
Docking Port Visuals

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#37]
The visual cues on the new docking ports (which are gorgeous) are each different, making it difficult to visually identify which direction is the top. Recommend having a consistent set of cues.

All three ports shown in the pic below are attached using their default alignment with the top of the pic corresponding to the top of the port.

- 2.5m port the 3 "flaps" are at the 2 o'clock, 6 and 10 positions, the hatch handles are up and down and shock absorbers connect at 12 o'clock, 4 and 8 positions
- 1.25m port the shock absorbers connect at 12 o'clock, 4 and 8 positions (hard to see at the picture angle) and the hatch handles are left and right
- 0.625m port the "flaps" are at 3 o'clock, 7 and 11 positions and the hatch handles are up and down

![screenshot8](https://user-images.githubusercontent.com/22890228/45918398-513b7880-be3b-11e8-9c0c-e328075493e2.png)

Recommendations: 

- 1.25m model - rotate only the hatch 90 degrees so handles are up down

- 2.5m model - rotate only the "flaps" 45 degrees clockwise so that one of the "flaps" is at 3 o'clock but handles and shocks stay the same

- 1.25m shielded port (not shown) rotate the hatch only 90 degrees so handles are up down

Explanation: I know you'll never dock a 2.5 to a 1.25m or a 0.625, but if they're consistent builders and pilots will have a familiar set of reference points - flaps, shocks and handles - across all the docking ports. The reason I'm orienting the flaps with one at 3 o'clock is that when two of these ports mate, both with up being up, the flaps will be in the correct positions to interleave with those on the other port. If one of the flaps is up or down, then when the two ports mate the flaps would hit each other instead of interleaving.

NOTE: These are low priority visual only tweaks and nothing's actually broken, but I know you strive for consistency so you may want to tackle at some point.

**Comment by ChrisAdderley** [comment]
Item 1 and 3 are easy and ok, but I'm confused about 2. If the flaps are rotated, the shocks necessarily have to also be rotated for this model.

**Comment by TykoTek** [comment]
Got it, I guess either the shocks or the flaps won't be quite symmetrical...if that's the case it's probably better to have to flaps oriented so they'll interleave with the other port when docked. This means rotating the flaps/shocks 45 degrees clockwise and keeping the rest of the model as is.

**Comment by ChrisAdderley** [comment]
Ok, if I understood all the changes right they should be fixed with dc9c230

**Comment by TykoTek** [comment]
They all look correct. Great job
