### ISSUE TITLE
RV-105-X RCS (RS+) - localization, part name

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#371]
Should this be the 105X or 105-X**L**  ?   I think 105-X   would be most consistent. "XL" usually means Extra-Large

![image](https://user-images.githubusercontent.com/22890228/52650810-cd446480-2e9f-11e9-98c5-46f5dea529ab.png)

**Comment by ChrisAdderley** [comment]
X is the correct one

**Comment by ChrisAdderley** [comment]
e4dc754 fixed

**Comment by TykoTek** [comment]
is it 5-X or just 5X??? The new part name is 5X, but the localization says 5-X

**Comment by ChrisAdderley** [comment]
Didn't notice that bit. Changed.
