### ISSUE TITLE
RV-105-X 5-Way RCS (RS+) - texture issue

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#372]
The black "Hole" behind the middle thruster isn't centered. This is only a visual issue. The thruster is correctly centered in the part.

![image](https://user-images.githubusercontent.com/22890228/52653466-e13e9500-2ea4-11e9-8db0-2d3741fa57d5.png)

**Comment by ChrisAdderley** [comment]
Fixed e4dc754
