### ISSUE TITLE
HG-20 High Gain Antenna - Model issue

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#375]
The extendable copper antenna components are sticking out further in the top to dishes. 

![image](https://user-images.githubusercontent.com/22890228/52671715-a9e5dd80-2ed0-11e9-983e-64fa1c600d3a.png)

**Comment by drewcassidy** [comment]
oh dear. no the copper parts are even, the problem is the dishes are crooked. working on it

**Comment by drewcassidy** [comment]
nope it was the copper. fixed with 5543da7
