### ISSUE TITLE
RA-2 Relay Antenna - Holes in mesh

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#376]
Holes in mesh where supports meet the dish. Around other legs too. Just couldn't capture all in the same pic. Holes in both 0.625 and Truss variants

![image](https://user-images.githubusercontent.com/22890228/52672871-e961f900-2ed3-11e9-93c3-c8c1bed71abd.png)

A gap in mesh that runs up the side of the dish

![image](https://user-images.githubusercontent.com/22890228/52672934-1f9f7880-2ed4-11e9-9f6e-664430fcfe61.png)

**Comment by drewcassidy** [comment]
something stupid I did thinking I was clever. fixed with b2bcb6f

**Comment by TykoTek** [comment]
Confirmed
