### ISSUE TITLE
RA-15 Relay Antenna - Holes in mesh

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#377]
There appear to be gaps between the triangular panes that make up the dish. In the video below you can see the lines radiating out from the bottom center of the dish.

https://youtu.be/vaHCnCSbhwA

![image](https://user-images.githubusercontent.com/22890228/52674294-03053f80-2ed8-11e9-9327-0bc3a33f04b7.png)

**Comment by drewcassidy** [comment]
Not sure what caused this, but for what its worth I re-exported the model with 975f9a3 and can't reproduce the issue 
<img width="967" alt="screen shot 2019-02-12 at 3 35 42 pm" src="https://user-images.githubusercontent.com/3837797/52675609-3649cd80-2edc-11e9-8b53-8f6c36634f57.png">

**Comment by TykoTek** [comment]
I  can barely see it, but only from one angle now that I know to look for it. It's much better.

@drewcassidy  I'll leave it up to you if you want to pursue further or close
