### ISSUE TITLE
RA-100 Relay Antenna - Bottom node Z-Fighting.

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#378]
parts attached to bottom node are Z-Fighting. Definitely happening on 1.25 mount. Can't tell on compact mount

![image](https://user-images.githubusercontent.com/22890228/52674555-cbe35e00-2ed8-11e9-8ad1-2141d795aa1b.png)

**Comment by drewcassidy** [comment]
should be solved in f4af383

**Comment by TykoTek** [comment]
Fixed
