### ISSUE TITLE
2.5m Docking Port node off-center

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#38]
The top node is slightly off such that when two 2.5m docking ports mate they don't line up. You can see it in the picture below

![screenshot15](https://user-images.githubusercontent.com/22890228/45919015-2a357480-be44-11e8-8c79-4efd989276bf.png)

**Comment by ChrisAdderley** [comment]
Will investigate

**Comment by ChrisAdderley** [comment]
Fixed with dc9c230

**Comment by TykoTek** [comment]
Fix confirmed!
