### ISSUE TITLE
SKLE-2-3 gaps in mesh

### ISSUE THREAD

**Issue by woeller** [PorktoberRevolution/ReStocked#382]
Well recognizable on the screenshot

![screenshot56](https://user-images.githubusercontent.com/35576383/52710901-d2cda780-2f90-11e9-8250-3b5443bf1524.png)

**Comment by ChrisAdderley** [comment]
A fix was included in  #390

**Comment by woeller** [comment]
Not completely solved:

![screenshot87](https://user-images.githubusercontent.com/35576383/52920548-d903b100-330d-11e9-8ecb-aeb06ddfaf4e.png)

**Comment by ChrisAdderley** [comment]
Now it is 0fea175

**Comment by TykoTek** [comment]
Confirmed. Closing
