### ISSUE TITLE
SKLE-2-3 Part width

### ISSUE THREAD

**Issue by woeller** [PorktoberRevolution/ReStocked#383]
The width at the bottom of the part is too large.
![screenshot60](https://user-images.githubusercontent.com/35576383/52712002-9f404c80-2f93-11e9-81d1-b576fcc6bd22.png)

**Comment by TykoTek** [comment]
Confirmed against our test piece. It's a bit too wide.

![image](https://user-images.githubusercontent.com/22890228/52722918-6a1b0680-2f61-11e9-9ecc-2cb74ef41452.png)

**Comment by ChrisAdderley** [comment]
A fix was included in #390, should now be slightly smaller, which was the intention

**Comment by woeller** [comment]
So the adapter should be narrower than a fuel tank now?
If you don't want to change the node position that seems to have changed minimally after the mesh fix, please close it.
![screenshot88](https://user-images.githubusercontent.com/35576383/52920668-8c20da00-330f-11e9-876f-87810b66f45e.png)

**Comment by ChrisAdderley** [comment]
0fea175 moved
