### ISSUE TITLE
S3-7200 LFO Tank part  width

### ISSUE THREAD

**Issue by woeller** [PorktoberRevolution/ReStocked#384]
The width at the top of the part is too large compared to other tanks

Bottom part width is ok.
![screenshot57](https://user-images.githubusercontent.com/35576383/52712283-66ed3e00-2f94-11e9-9174-be5a78c21ffc.png)

Top part width is too wide.
![screenshot58](https://user-images.githubusercontent.com/35576383/52712500-15917e80-2f95-11e9-8365-0b40227f774c.png)

**Comment by TykoTek** [comment]
Top:
![image](https://user-images.githubusercontent.com/22890228/52723091-ba926400-2f61-11e9-8dc7-a1987892e956.png)

Bottom:
![image](https://user-images.githubusercontent.com/22890228/52723153-d72e9c00-2f61-11e9-9c17-3ad0f6713bbf.png)

**Comment by ChrisAdderley** [comment]
A fix was included in  #390

**Comment by woeller** [comment]
Fix confirmend.
