### ISSUE TITLE
Clamp-O-Tron Docking Port - nodes model issues

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#386]
Both the top and bottom nodes are a bit off-center. Note in the pictures below that the part is shifted slightly in the "up" direction. In the top pic I've rotated the top docking port 180 degrees to accentuate the issue. 

In the bottom pic you can still see that the part is shifted slightly to the right or "up".

Other things to check
- it looks like the part is slightly smaller than 1.25m diameter. Note that in the bottom pic on the up side the port it flush with the pink reference part while on the left it's not.
- there's a gap between the port and the pink reference part. Node needs to be lowered slightly

![image](https://user-images.githubusercontent.com/22890228/52866315-3d96f400-30f3-11e9-83d7-4ffdc984463f.png)

![image](https://user-images.githubusercontent.com/22890228/52866517-b007d400-30f3-11e9-830a-76041c6ed7d6.png)

**Comment by DMagic1** [comment]
This is a slightly different, but related issue with some of the docking ports.

Most of the stock docking ports have their docking transform nodes aligned with the top of their colliders:

![stock 1 25m docking](https://user-images.githubusercontent.com/5150421/53180929-91f31580-35c4-11e9-84ae-d33805ba27bb.PNG)

In Restock the docking transform nodes are set above the collider:

![restock 1 25m docking](https://user-images.githubusercontent.com/5150421/53180969-ab945d00-35c4-11e9-8855-6df0937ca795.PNG)

This can result in gaps between two ports after docking (note that this is different than issues with docking node attachment position in the editor, which is based on attach node position).

![screenshot88](https://user-images.githubusercontent.com/5150421/53181024-bfd85a00-35c4-11e9-81b5-00ff2841d591.png)

This affects 1.25m, 0.625m, and shielded 1.25m ReStock docking ports, though there is not a noticeable gap for the 0.625m port. The stock 2.5m and inline docking ports have their docking transform set slightly above the collider, at about the same position as the ReStock ports.

Also, the 1.25m and 0.625m docking ports appear to have the stock model meshes included in the .mu file, the Mesh Renderer is disabled for these meshes, but they are still present in the file.

**Comment by ChrisAdderley** [comment]
Fixed more or less both problems in c0ba981

**Comment by TykoTek** [comment]
There's a small amount of z-fighting occurring now...video attached

https://youtu.be/nOxtjGRZlCY

**Comment by TykoTek** [comment]
we have a gap now...the adjustment you made opened up the space too much.

**Comment by TykoTek** [comment]
hit close accidentally. We have a slight gap now when two ports are attached together in VAB

**Comment by ChrisAdderley** [comment]
Arrrgh d7cfc57

**Comment by TykoTek** [comment]
Success!!!
