### ISSUE TITLE
LV-T15 - compact variant should have darkening/AO below spherical tank

### ISSUE THREAD

**Issue by blowfishpro** [PorktoberRevolution/ReStocked#387]
The 1.25m variant has this, it stands out a lot in the compact variant though.  Could probably be done with vertex colors even
![image](https://user-images.githubusercontent.com/10545461/52908286-b1d2b400-3227-11e9-8c8d-7f895ca9f09a.png)

**Comment by ChrisAdderley** [comment]
Eh.... as with all nonmajor fixes to these engines, it's low priority

**Comment by ChrisAdderley** [comment]
#482 adjusts to be better

**Comment by blowfishpro** [comment]
![image](https://user-images.githubusercontent.com/10545461/53679393-19095300-3c81-11e9-8571-7e7b32eb21f3.png)

Seems to be some wierdness in that area now
* Phantom AO on the struts (and some other AO weirdness)
* Struts have sharp edges now?
* Sharp shadowing boundaries in the area I was mentioning initially (might be just more AO weirdness)

**Comment by ChrisAdderley** [comment]
Relevant fixes 61e2f11

**Comment by blowfishpro** [comment]
I still see some mismatching on the AO, it's a lot closer now and if you feel this is as good as it's going to get I can be ok with that

**Comment by ChrisAdderley** [comment]
Yeah... it's not going to be that good at this point.
