### ISSUE TITLE
Mystery Goo™ Containment Unit - Cannister clips into attached part

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#388]
The Goo Cannister clips into the attached part when mounted in its default position (not offset or moved). The stock version does not seem to do this as, possibly, the cannister diameter may be smaller or that the stock mounting 'plates' project down into the attached part whereas the ReStock version's black rim is the larger diameter?

 ![untitled-1](https://user-images.githubusercontent.com/10106634/52918783-e6f80880-32f2-11e9-80f1-5394bf01d025.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/52918784-ea8b8f80-32f2-11e9-8a4e-7b3832bfc5b4.png)

**Comment by drewcassidy** [comment]
I'm not sure how feasible it is to fix this. I could move the whole body forwards but then it won't be aligned with the capsule collider, or I guess I could scale the rim down. I don't know if either option is really necessary.

**Comment by drewcassidy** [comment]
Fixed with ce303d7d8

**Comment by drewcassidy** [comment]
Sorry testing commenting from this github third party app please ignore
