### ISSUE TITLE
SC-9001R Radial Science Jr. - Possibly change main mesh collider to primitive box collider

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#389]
As it says on the tin, could the central, main mesh collider be changed to a simple box collider?

![untitled-1](https://user-images.githubusercontent.com/10106634/52919043-f6c51c00-32f5-11e9-8c7c-579f768f68bc.png)

**Comment by drewcassidy** [comment]
I could, but I like being able to attach things to the diagonals on the front. I don't think the very slight performance gain is worth that
