### ISSUE TITLE
1.25m Docking Port Rotation

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#39]
When two 1.25m docking ports mate their alignment is off 180 degrees from the expected alignment. 

If you build a station in the VAB including 1.25m docking ports between sections, when you get into space and try to dock them Docking Port Alignment Indicator shows that the two ports are at 180 degrees to each other - meaning one is upside down. If you rotate to show 0 degrees the two modules of your station will be rotated with respect to your planned build.

The other docking ports and stock docking ports all line up at 0 degrees. The new 1.25m port is different. In the pic below you can see that DPAI shows the two craft at 180 degrees, but the reference antennas I added are both pointing upwards. I've run this same test with the other 2 new ports and all three stock ports, Only the 1.25m port is showing this issue.

![screenshot12](https://user-images.githubusercontent.com/22890228/45919245-12132480-be47-11e8-989e-fdb9a86e057a.png)

NOTE TO NERTEA: This may be a result of the earlier change you'd made to rotate the 1.25m docking port so the shocks aligned. I'm thinking that when you did that 90 degree model rotation something got changed with respect to what the game thinks of as the "top" causing it to be off 180 degrees

**Comment by ChrisAdderley** [comment]
So I wasn't really aware that this orientation actually mattered to anyone. I've never bothered about the actual rotational alignment of the docking node, besides ensuring it points the right way.

I mean, these things attach at any angle. I guess the only way they show it is if you're pedantic about exact orientations or are using something like the aligner. 

Just to be clear, essentially you're saying that the perpendicular up axis of the docking port is not where you would expect it to be. Observing the following image, you'd prefer that the blue axis be rotated 180 degrees around the green axis. Correct?

<img width="334" alt="screen shot 2018-09-22 at 11 56 49 am" src="https://user-images.githubusercontent.com/5642064/45920796-99b85d80-be5e-11e8-931e-997790f504cb.png">

**Comment by TykoTek** [comment]
Let's use the Red arrow in your picture above for reference and call that "Up". I'm calling that Up because when you build a craft by placing a crewed pod and then snap a docking port on top - without rotating either one - the Red arrow will be pointing up with reference to the pilot's seating. 

When using docking mods they also read out where Up or 0 degrees is on the targeted docking port. This is really useful in making sure multi-part stations are oriented as planned when you launch the parts separately and dock them together in space.

On the other 2 New ports and the 3 Stock ports, Up is aligned toward Red. On the 1.25m docking port it snaps during building with Red pointing relative to the capsule, but when you're docking it thinks that Up is set opposite the Red arrow. If you're using a docking mod and you orient to what the mod is reading out as Up / 0 degrees you're, in fact, docking the parts rotated 180 degrees from the plan. You can see that from the antennas in my original pictures. 

I'm not sure what the fix is since I'm not skilled at building and importing parts. I'm guessing that at some point during the import process there's a Up assigned to the part and somehow that got oriented incorrectly for this part. The other 5 ports all work the way they're supposed to, so there's something different about this part.

**Comment by TykoTek** [comment]
On a hunch I checked the SSPXR version of this same port. That one shows 270 degrees versus the 180 we're seeing on the ReStocked version. Previously you'd rotated the ReStocked version 90 degrees to visually align the shocks and that made the ReStocked version orient 0 degrees differently from the SSPXR version. There's probably a clue in there as to what's causing this.

Restocked version:
![screenshot12](https://user-images.githubusercontent.com/22890228/45958390-32202080-bfcc-11e8-85a6-12c0dca9fa3f.png)


SSPRX version:
![screenshot22](https://user-images.githubusercontent.com/22890228/45958287-eb322b00-bfcb-11e8-82c4-cfc4e10838af.png)

**Comment by ChrisAdderley** [comment]
Alright, if I understood aright this should be fixed with dc9c230, please let me know if I was successful

**Comment by TykoTek** [comment]
This worked great! The 1.25m docking port is correctly oriented now.

I missed this before, when you dock two 1.25m port together there's a clear air gap between the two docking ports. They should be closer together.

![screenshot23](https://user-images.githubusercontent.com/22890228/46056690-b24aa100-c106-11e8-8def-92c04812056b.png)

**Comment by ChrisAdderley** [comment]
Fixed dc9c230

**Comment by TykoTek** [comment]
Gap fix confirmed!
