### ISSUE TITLE
Place-Anywhere 7 Linear RCS Port - Texture seam issue at Panel Line joint

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#391]
The panel line seam one on half of the RCS port is a lot thicker than the one on the opposite side; the thinner panel line seam looks to be the correct, inteded appearance.

![untitled-1](https://user-images.githubusercontent.com/10106634/52920576-dac97680-3305-11e9-939b-c4179a6e41b3.png)

**Comment by ChrisAdderley** [comment]
Tuned 2494c9d

**Comment by Poodmund** [comment]
Better in https://github.com/PorktoberRevolution/ReStocked/commit/2494c9dd7a264dd90a70c079702c2792a26ef637. Good enough to close.
