### ISSUE TITLE
RV-103 RCS Thruster Block - Texture Alignment Issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#392]
One of the black circle surrounds on the 103 RCS thruster is misaligned to the nozzle structure, see screenshot:

![untitled-1](https://user-images.githubusercontent.com/10106634/52920762-40b6fd80-3308-11e9-8640-5f48df1bf621.png)

**Comment by ChrisAdderley** [comment]
Addressed 2494c9d

**Comment by Poodmund** [comment]
Resolved the area in question; the front facing port shifted slightly but its good enough.

![untitled-1](https://user-images.githubusercontent.com/10106634/53041665-767cf300-347c-11e9-9905-e198f07c82a8.png)

Closed.
