### ISSUE TITLE
FL-T400 Fuel Tank - Bottom Node

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#394]
The tank's bottom node is a bit too low enabling the lip of the tank to show.

![image](https://user-images.githubusercontent.com/22890228/52985978-0bafb700-33ab-11e9-8dca-9747b492c463.png)

**Comment by ChrisAdderley** [comment]
Addressed a3b8ca3

**Comment by TykoTek** [comment]
Confirmed
