### ISSUE TITLE
X200-8 Fuel Tank - Bottom node too low

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#395]
There's a gap between bottom of part and top of adjacent part. It doesn't extend all the way across, but is visible at the edges

![image](https://user-images.githubusercontent.com/22890228/52987022-71517280-33ae-11e9-8470-a12e48b07364.png)

**Comment by ChrisAdderley** [comment]
Got it in 7cf278f

**Comment by TykoTek** [comment]
Confirmed
