### ISSUE TITLE
X200-32 Fuel Tank - Bottom Node

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#396]
Bottom node too low leaving a visible gap with part attached below it.

![image](https://user-images.githubusercontent.com/22890228/52987236-326fec80-33af-11e9-9b7c-1583bd76d707.png)

**Comment by ChrisAdderley** [comment]
Fixed a3b8ca3

**Comment by TykoTek** [comment]
confirmed
