### ISSUE TITLE
S3-3600 Fuel Tank - texture color issue

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#397]
The texture has a greenish tinge and a "butterfly" or "space invader" shape in the middle of a grey field

![image](https://user-images.githubusercontent.com/22890228/52987521-42d49700-33b0-11e9-906f-298aff84841c.png)

**Comment by ChrisAdderley** [comment]
Going to do a catchall issue in #402, please add to it if you find more
