### ISSUE TITLE
Rocket fuel tanks

### ISSUE THREAD

**Issue by IronCretin** [PorktoberRevolution/ReStocked#4]
- .625m
  - ROUND-8 Toroidal Fuel Tank
    - [ ] Model
    - [ ] Texture
    - [ ] Integration
  - Baguette Fuel Tank
    - [ ] Model
    - [ ] Texture
    - [ ] Integration
  - Dumpling Fuel Tank
    - [ ] Model
    - [ ] Texture
    - [ ] Integration
  - Oscar-B Fuel Tank
    - [x] Model
    - [x] Texture
    - [x] Integration
- 1.25m
  - FL-T100 Fuel Tank
    - [X] Model
    - [X] Texture
    - [x] Integration
  - FL-T200 Fuel Tank
    - [X] Model
    - [X] Texture
    - [x] Integration
  - FL-T400 Fuel Tank
    - [X] Model
    - [X] Texture
    - [x] Integration
  - FL-T800 Fuel Tank
    - [X] Model
    - [X] Texture
    - [x] Ingame
- 2.5m
  - Rockomax X200-8 Fuel Tank
    - [X] Model
    - [x] Texture (White)
    - [x] Texture (Grey)
    - [x] Texture (Orange)
    - [x] Ingame
  - Rockomax X200-16 Fuel Tank
    - [X] Model
    - [x] Texture (White)
    - [x] Texture (Grey)
    - [x] Texture (Orange)
    - [x] Ingame
  - Rockomax X200-32 Fuel Tank
    - [X] Model
    - [x] Texture (White)
    - [x] Texture (Grey)
    - [x] Texture (Orange)
    - [x] Ingame
  - Rockomax Jumbo-64 Fuel Tank
    - [X] Model
    - [x] Texture (White)
    - [x] Texture (Grey)
    - [x] Texture (Orange)
    - [x] Ingame
- 3.75m
  - Kerbodyne S3-3600 Tank
    - [X] Model
    - [X] Texture
    - [X] Ingame
  - Kerbodyne S3-7200 Tank	
    - [X] Model
    - [X] Texture
    - [X] Ingame
  - Kerbodyne S3-14400 Tank	
    - [X] Model
    - [X] Texture
    - [X] Ingame

**Comment by ChrisAdderley** [comment]
Closed and moved to individual tickets
