### ISSUE TITLE
Corgi - various model issues

### ISSUE THREAD

**Issue by blowfishpro** [PorktoberRevolution/ReStocked#40]
![screenshot17](https://user-images.githubusercontent.com/10545461/45933145-05bcc380-bf3c-11e8-9c61-b1532af46352.png)

1) Visible texture seam
2) AO that doesn't seem to be coming from anywhere
3) Doesn't seem to be any AO where these attach
4) Uses sharp shading but should be smooth
5) These are completely black and probably shouldn't be

**Comment by ChrisAdderley** [comment]
Hopefully all/completely fixed with merge of #183
