### ISSUE TITLE
RC-L01 Probe Core - Hole in mesh

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#400]
There's a gap around the edge where the green circular PCB meets the outer case of the core.

![image](https://user-images.githubusercontent.com/22890228/52994207-af10c400-33cb-11e9-9aa0-e0cc90f146e5.png)

**Comment by Poodmund** [comment]
Additional screenshot:

![untitled-1](https://user-images.githubusercontent.com/10106634/53203999-846c7880-3622-11e9-8395-8a70e47418de.png)

**Comment by ChrisAdderley** [comment]
Got it in 7cf278f

**Comment by Poodmund** [comment]
The above described issue was resolved in https://github.com/PorktoberRevolution/ReStocked/commit/7cf278fb342c0c31d4dbdea29a6bd473e252c2b9 but upon further inspection, there are a couple of gaps on the underside where the inner ring meets the underside face plate:

![untitled-1](https://user-images.githubusercontent.com/10106634/53284857-b92b1d80-3751-11e9-99ec-db43bc5942c7.png)
