### ISSUE TITLE
Parts with DDS compression issues

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#402]
Issue to collect all the parts that have strongly obvious purple/green compression artifacts

- [ ] ADTP-2-3 Fuel Tank adapter
- [ ] S3-3600 Fuel Tank

**Comment by TykoTek** [comment]
PB-X50R, PB-X150 and PB-X750 Xenon Containers

![image](https://user-images.githubusercontent.com/22890228/53217458-e326f780-360c-11e9-927c-d41e6e17d098.png)

**Comment by ChrisAdderley** [comment]
Everything was recently recompressed with a higher quality compressor - this is probably as good as it is going to get.

**Comment by TykoTek** [comment]
Confirmed. Looks a lot better
