### ISSUE TITLE
Communotron DTS-J1 - Balance; mass could be increased to be higher than radial DTS-M1

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#405]
The DTS-J1's description is:

> A fixed mount version of the popular DTS-M1 antenna. this version is a more traditional dish, giving it better efficiency at the expense of higher mass.

For balance, it kinda makes sense that the part should be heavier as it is cheaper and bulkier but the mass is 0.04T compared to the DTS-M1's 0.05T.

Looking at the other antenna parts, it seems the DTS-M1 is way too heavy... however, to keep the DTS-J1 part consistent with the DTS-M1, I would spec it at something like 0.055T just so it falls in line with thinking and its description...?

**Comment by drewcassidy** [comment]
Ah, I had made the mass higher when I added it, then reduced it when I added the next antenna. .055 tons sounds good

**Comment by Poodmund** [comment]
Resolved
