### ISSUE TITLE
Communotron HG-89 - Balance; price may need hiking above the HG-55?

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#408]
It performs the same as its larger, radial mounted counterpart, the HG55, but is lighter and in a small form factor. 

Maybe it should be priced at a higher cost than the HG-55? I suggest maybe 1,400 credits, compared to the HG-55's 1,200.

**Comment by drewcassidy** [comment]
Why would it be higher cost if it lacks the deployment arm?

**Comment by Poodmund** [comment]
Miniaturised form factor? Things tend to be more expensive the smaller/lighter they become. That's my only 'IRL reasoning' but really it's more that you would probably never use the HG-55 over it's smaller, lighter, cheaper counterpart if both can be radially attached so I'm just coming at it from a gameplay balance stand point mostly.

**Comment by drewcassidy** [comment]
The antenna assembly is identical, the only difference is the arm. Sure, adding a radially mounted HG-61 is cheaper and lighter than an HG-55, but it doesnt look as cool (and sticks out when retracted), especially if you want it to point forwards. And if you build your own arm out of girders, which is entirely an option, it ends up more expensive.
