### ISSUE TITLE
Gap between Rockomax 2.5m adapter and the 2.5m Service Bay

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#41]
There's a visual gap when you stack the 2.5 conical adapter on top of the new 2.5m service bay. When I tried with other parts neither of these two parts alone seems to be responsible for the full gap, so I think it's additive - the conical adapter's node is a bit to low and the service bay's top node is a bit too high so combining the two results in a visible gap.

You can see it in this picture:

![](https://i.imgur.com/AsFexVb.png)

**Comment by ChrisAdderley** [comment]
Mostly the adapter's fault, it'll be fixed in the branch soon!

**Comment by TykoTek** [comment]
Fix confirmed in 34c032d

**Comment by TykoTek** [comment]
Confirmed...I'll close this one :)
