### ISSUE TITLE
Mk1 Command Pod - 1.25m base of part is slightly undersized

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#411]
The 1.25m base of the Mk1 Pod is slightly under the 1.25m diameter size as can be seen here up against a 1.25m diameter testing part.

![untitled-1](https://user-images.githubusercontent.com/10106634/53184408-deeee000-35f4-11e9-9233-302a9998155d.png)

If this is intentional to satisfy the heatshield woes that stock has lumbered us with, then please close this issue.

**Comment by ChrisAdderley** [comment]
As with the other - heatshield related
