### ISSUE TITLE
Mk1-3 Command Pod - 2.5m base of part is slightly undersized

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#412]
The 2.5m base of the Mk1-3 Pod is slightly under the 2.5m diameter size as can be seen here up against a 2.5m diameter testing part.

![untitled-1](https://user-images.githubusercontent.com/10106634/53184757-8409b880-35f5-11e9-98c5-e1a80e0cfa4c.png)

If this is intentional to satisfy the heatshield woes that stock has lumbered us with, then please close this issue.

**Comment by ChrisAdderley** [comment]
Yes this is heatshield related
