### ISSUE TITLE
Mk1-3 Command Pod - Texture seam in Normal on rear of pod

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#413]
There is an odd change in width of a panel line on the rear side of the pod as can be seen in the screenshot below:

![untitled-1](https://user-images.githubusercontent.com/10106634/53185272-933d3600-35f6-11e9-96de-59c87017eb72.png)

**Comment by ChrisAdderley** [comment]
a3b8ca3

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/a3b8ca386fe5eb7c0405e43c793632f389e3c0fd
