### ISSUE TITLE
Mk2 Lander Can - Bottom node may be too high/clipping with attached part

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#414]
I think the bottom node is aligned to the edge of the collider but the model extends further down slightly than the collider as seen here:

![untitled-2](https://user-images.githubusercontent.com/10106634/53186829-b1f0fc00-35f9-11e9-8d01-add05462e1bf.png)

This causes parts attached below to clip inside the bottom of the Mk2 Lander as can be seen here:

![untitled-1](https://user-images.githubusercontent.com/10106634/53186849-c1704500-35f9-11e9-86e2-5d3e4e980a07.png)

**Comment by ChrisAdderley** [comment]
a3b8ca3

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/a3b8ca386fe5eb7c0405e43c793632f389e3c0fd
