### ISSUE TITLE
Mk2 Lander Can - Model possibly off-centre in the .mu

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#415]
I noticed that parts stacked above and below the Mk2 Lander were slightly off-centre, see screenshots below (you can see the difference in thickness of overhang):

![untitled-1](https://user-images.githubusercontent.com/10106634/53188054-70ae1b80-35fc-11e9-939d-6d95d7bc7fe9.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/53188056-73107580-35fc-11e9-9eb2-d6c5b664e7ab.png)

Looking in the VAB, at parts that are symmetrically positioned around the top node, you can see that there is a slight difference in how parts are being positioned around the top node. In the screenshots below, you can see on one side, the strut is touching the black rim but on the other side it is slightly away from it:

![untitled-3](https://user-images.githubusercontent.com/10106634/53188117-9c310600-35fc-11e9-8a13-7f0c1ca0f427.png)

![untitled-4](https://user-images.githubusercontent.com/10106634/53188123-9e936000-35fc-11e9-9eb0-40808e46d157.png)

Importing the .mu into Blender, it seems the Top and Bottom nodes are located on the 0, 0 X, Y planes but I think the whole model mesh is slightly shifted over to one side. By looking at the difference in the vertices on opposite sides it would appear to me that it is off-centre by 0.00551m in the Y-axis, this is the same at the vertices on the bottom of the mesh also.

![untitled-6](https://user-images.githubusercontent.com/10106634/53188227-d26e8580-35fc-11e9-99be-49845ead2b58.png)

![untitled-5](https://user-images.githubusercontent.com/10106634/53188235-d4d0df80-35fc-11e9-8cc6-0bafc2f64831.png)

**Comment by ChrisAdderley** [comment]
Anything that is going to be done has been done in a3b8ca3

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/a3b8ca386fe5eb7c0405e43c793632f389e3c0fd
