### ISSUE TITLE
Mk2 Lander Can - Holes in model mesh

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#416]
With changes made to the Mk2 Lander Can some gaps/holes have crept in.

On the underside at each of the four corners there is a small hole:

![untitled-1](https://user-images.githubusercontent.com/10106634/53189477-8244f280-35ff-11e9-8b36-b2e2b8ca25c2.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/53189483-853fe300-35ff-11e9-98a3-4aafe6595ace.png)

Around the bay doors there are areas where the gaps can be seen through the model:

![untitled-3](https://user-images.githubusercontent.com/10106634/53189514-9983e000-35ff-11e9-8851-c8ba5be71d8f.png)

![untitled-4](https://user-images.githubusercontent.com/10106634/53189520-9c7ed080-35ff-11e9-818f-4a3bc6f93843.png)

![untitled-5](https://user-images.githubusercontent.com/10106634/53189525-9ee12a80-35ff-11e9-870f-0b7c3df8777b.png)

![untitled-6](https://user-images.githubusercontent.com/10106634/53189533-a30d4800-35ff-11e9-81a7-9912ba235b64.png)

On the top, on the front side, there are two small gaps:

![untitled-7](https://user-images.githubusercontent.com/10106634/53189557-b3252780-35ff-11e9-92c6-57ce8f3cdeff.png)

I *think* the Rover variant does not suffer any issues.

**Comment by ChrisAdderley** [comment]
Addressed to the extent I care in a3b8ca3

**Comment by Poodmund** [comment]
Resolved past the extent of my satisfaction with https://github.com/PorktoberRevolution/ReStocked/commit/a3b8ca386fe5eb7c0405e43c793632f389e3c0fd
