### ISSUE TITLE
Mk2 Lander Can - Little texture weirdness on ring around hatch

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#417]
A small part of the texture seems to be acting a little strangely.

![untitled-1](https://user-images.githubusercontent.com/10106634/53193388-be308580-3608-11e9-903c-ab15758e4048.png)

**Comment by ChrisAdderley** [comment]
REmoved a3b8ca3

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/a3b8ca386fe5eb7c0405e43c793632f389e3c0fd
