### ISSUE TITLE
Probodobodyne QBE - Vertice blemish in model

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#418]
There is a little funky area on the top and bottom of the QBE in each of the 4 corners around the grills.

![untitled-1](https://user-images.githubusercontent.com/10106634/53194284-e4572500-360a-11e9-96fb-bb73650198d7.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/53194290-e8834280-360a-11e9-9978-89da1236b36b.png)

**Comment by ChrisAdderley** [comment]
Fixed in 7cf278f

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/7cf278fb342c0c31d4dbdea29a6bd473e252c2b9
