### ISSUE TITLE
Probodobodyne QBE - Bare variant is offset -0.005m in the Z-axis in the .mu

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#419]
The bare variant of the QBE seems to be positioned different in the .mu compared to the two foil variants which causes the foil variants to clip upwards into the parts they are attached to at the top and move away from their parent part underneath.

![untitled-1](https://user-images.githubusercontent.com/10106634/53195127-e7531500-360c-11e9-926a-1c81736c4a4e.gif)

![untitled-1](https://user-images.githubusercontent.com/10106634/53195138-ecb05f80-360c-11e9-8689-56c3a0068492.png)

**Comment by ChrisAdderley** [comment]
Fixed in 7cf278f

**Comment by Poodmund** [comment]
https://github.com/PorktoberRevolution/ReStocked/commit/7cf278fb342c0c31d4dbdea29a6bd473e252c2b9 seems to have aligned the Basic and Foil variants but the models for all variants are now sitting higher than the collider/nodes would suggest and as a result the part is clipping at the top to the connected parts.

![untitled-1](https://user-images.githubusercontent.com/10106634/53285107-c39ae680-3754-11e9-8e21-a818abea135e.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/53285108-c5fd4080-3754-11e9-9fce-5e78bbbb3ac4.png)

Looking at both the bare and foil variant models in Blender, the collider is positioned correctly around the origin but both the variant models are sitting a little high. Selecting the top and bottom faces on the models and then snapping the cursor to the centre of the selections suggests they are positioned a little higher above the Z-axis origin, which would tie in to the screenshots above.

![untitled-3](https://user-images.githubusercontent.com/10106634/53285129-01980a80-3755-11e9-8486-b7c741fd0bc1.png)

![untitled-4](https://user-images.githubusercontent.com/10106634/53285133-06f55500-3755-11e9-8b23-d1def18a4585.png)

**Comment by Poodmund** [comment]
Out of curiosity, I just zeroed out the models vertically and exported them using Taniwha's exporter through Blender (I'm not sure what may be lost from the .mu by doing this) and it resolves the offset.

![untitled-1](https://user-images.githubusercontent.com/10106634/53286032-3f4e6080-3760-11e9-951a-786333c40489.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/53286034-41b0ba80-3760-11e9-84e4-9585744745ee.png)

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/a458270d1adbfe4ef0bc5d33f3bebfec33389e03 ... I think
