### ISSUE TITLE
Probodobodyne HECS - Model isn't centred vertically in relation to collider (affecting part connections)

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#420]
The model for the HECS is not centred vertically in relation to the collider which is causing the bottom and top nodes to be positioned, apparently, too low on the model. It seems as though the nodes are located on the surface of the collider mesh but the HECS model, at the bottom, is aligned so that the main Probe body sits slightly higher than the part below and at the top, the model sits slightly higher into the part above. See screenshots:

![untitled-1](https://user-images.githubusercontent.com/10106634/53195924-a2c87900-360e-11e9-9f2e-6165c482126c.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/53195935-a52ad300-360e-11e9-8175-4527be39b471.png)

![untitled-3](https://user-images.githubusercontent.com/10106634/53195942-a78d2d00-360e-11e9-83e4-d98cf7214510.png)

![untitled-4](https://user-images.githubusercontent.com/10106634/53195946-a9ef8700-360e-11e9-9d97-45dea74d9bcd.png)

**Comment by ChrisAdderley** [comment]
Centred in 7cf278f

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/7cf278fb342c0c31d4dbdea29a6bd473e252c2b9
