### ISSUE TITLE
Probodobodyne HECS - Vertice blemish in model

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#421]
There is a little funky area on two of the corners of the two grills in the mesh. See screenshots:

![untitled-1](https://user-images.githubusercontent.com/10106634/53197583-6860db00-3612-11e9-8fd5-211a44645727.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/53197590-6b5bcb80-3612-11e9-8e8d-e16573c2d617.png)

**Comment by ChrisAdderley** [comment]
Fixed in 7cf278f

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/7cf278fb342c0c31d4dbdea29a6bd473e252c2b9
