### ISSUE TITLE
Probodobodyne OKTO - Bare variant is offset +0.001m in the Z-axis in the .mu

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#422]
The bare variant of the OKTO seems to be positioned different in the .mu compared to the two foil variants much like the similar issue with the QBE.

![untitled-1](https://user-images.githubusercontent.com/10106634/53198961-b62b1280-3615-11e9-9aa4-9bf769beebe3.png)

![untitled-1](https://user-images.githubusercontent.com/10106634/53198968-ba573000-3615-11e9-9815-fa0bebc5486c.gif)

**Comment by ChrisAdderley** [comment]
Fixed in 7cf278f

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/7cf278fb342c0c31d4dbdea29a6bd473e252c2b9
