### ISSUE TITLE
Probodobodyne OKTO - Vertice blemish in model

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#423]
There is a little funky area on two of the corners of the two grills in the mesh. See screenshots:

![untitled-1](https://user-images.githubusercontent.com/10106634/53199281-93e5c480-3616-11e9-807c-2a44e34e824c.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/53199286-96481e80-3616-11e9-9a54-dff53a394355.png)

**Comment by ChrisAdderley** [comment]
Fixed in 7cf278f

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/7cf278fb342c0c31d4dbdea29a6bd473e252c2b9
