### ISSUE TITLE
Probodobodyne OKTO2 - Hole in meshes of Foil variants.

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#424]
For the foil variants of the OKTO2, there is a hole in the mesh between the main body and the bottom foil section. This gap/hole does not appear in the bare variant:

![untitled-1](https://user-images.githubusercontent.com/10106634/53200012-6c8ff700-3618-11e9-9548-54a73cdbdf8e.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/53200045-85001180-3618-11e9-9893-4e2867d62975.png)

**Comment by ChrisAdderley** [comment]
Fixed in 7cf278f

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/7cf278fb342c0c31d4dbdea29a6bd473e252c2b9
