### ISSUE TITLE
Probodobodyne OKTO2 - Model isn't centred vertically in relation to collider (affecting part connections)

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#425]
Much like a similar issue for the HECS https://github.com/PorktoberRevolution/ReStocked/issues/420 the model for the OKTO is not centred vertically in relation to the collider/nodes which is causing the bottom and top nodes to be positioned, apparently, too low on the model. Thus, at the bottom its aligned so that the main Probe body sits slightly higher than the part below and at the top, the model sits slightly higher into the part above. See screenshots:

![untitled-1](https://user-images.githubusercontent.com/10106634/53200884-98ac7780-361a-11e9-8e8a-1e411cbb3df7.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/53200889-9b0ed180-361a-11e9-9faa-826d4e9ef8ec.png)

![untitled-3](https://user-images.githubusercontent.com/10106634/53200893-9e09c200-361a-11e9-8eab-d0bce63e2e36.png)

![untitled-4](https://user-images.githubusercontent.com/10106634/53200897-a06c1c00-361a-11e9-97db-28e080c180ea.png)

![untitled-5](https://user-images.githubusercontent.com/10106634/53200902-a2ce7600-361a-11e9-9f2b-1f2413261e44.png)

**Comment by ChrisAdderley** [comment]
Looks centered now

**Comment by Poodmund** [comment]
Fixed with https://github.com/PorktoberRevolution/ReStocked/commit/7cf278fb342c0c31d4dbdea29a6bd473e252c2b9 ... I think
