### ISSUE TITLE
Probodobodyne HECS2 - Endcap greeble centre hole... not actually centred

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#426]
The hole in the middle of the endcaps of the HECS2 is not actually in the middle of the endcap which makes it awkward when node attaching small parts like the Ant Engine or similar (which have to be centred to avoid inducing torque). 

![untitled-1](https://user-images.githubusercontent.com/10106634/53202562-c3003400-361e-11e9-9f56-bca1a54cdc82.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/53202567-c4c9f780-361e-11e9-8971-881ec460440b.png)

![untitled-3](https://user-images.githubusercontent.com/10106634/53202570-c7c4e800-361e-11e9-9608-28da1e205d5d.png)

![untitled-4](https://user-images.githubusercontent.com/10106634/53202573-c98eab80-361e-11e9-8f03-38a98da330d6.png)

Putting this as a deferred issue as its not critical and is a 'would-be-nice-if' kind of thing.

**Comment by ChrisAdderley** [comment]
I'll see what I can do here as part of 0.1.0.

**Comment by ChrisAdderley** [comment]
Ok, feasbility of this is zero. would require a complete rebuild of the endcap. Not happening

**Comment by Poodmund** [comment]
A real shame but I kind of guessed this would be the case.
