### ISSUE TITLE
RC-001S Remote Guidance Unit - Supporting framework has odd geometry on underside

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#427]
The metal framework tubes that go down the inside of the probe turn 90 degrees at the bottom but terminate abruptly leaving a flat face that looks a little odd like it is a model mesh error. See screenshot:

![untitled-1](https://user-images.githubusercontent.com/10106634/53203698-c6e18580-3621-11e9-9519-fbd3b415808f.png)

It happens on all four sides where the tubes are, visible on two sides here because of the lighting:

![untitled-2](https://user-images.githubusercontent.com/10106634/53203718-d6f96500-3621-11e9-9d14-420fea113d3e.png)

Even if a small handle of quads were introduced to blend in into the underside panel I think it may look a little less like a model error.

**Comment by ChrisAdderley** [comment]
Got it in 7cf278f

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/7cf278fb342c0c31d4dbdea29a6bd473e252c2b9
