### ISSUE TITLE
FL-R25 RCS tank - Top node too high

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#429]
Top node is too high

![image](https://user-images.githubusercontent.com/22890228/53216722-609d3880-360a-11e9-948b-d5083d4948e2.png)

**Comment by ChrisAdderley** [comment]
Okay good 7cf278f

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/7cf278fb342c0c31d4dbdea29a6bd473e252c2b9
