### ISSUE TITLE
Stratus-V Roundified - Attach point to parent part

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#430]
The attachment point causes the tank to sit too close to its parent part

![image](https://user-images.githubusercontent.com/22890228/53217004-56c80500-360b-11e9-9c99-1d5e4f8d2d2c.png)

**Comment by ChrisAdderley** [comment]
Working as stock
![screenshot124](https://user-images.githubusercontent.com/5642064/53292772-db866080-377c-11e9-93ed-5e4f9bd58b74.png)
