### ISSUE TITLE
Stratus-V Cylindrified - Attach point to parent part 

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#431]
Part sits to close to parent part so tank clips inside.

![image](https://user-images.githubusercontent.com/22890228/53217156-de157880-360b-11e9-811b-cdacf5d50831.png)

**Comment by ChrisAdderley** [comment]
![screenshot124](https://user-images.githubusercontent.com/5642064/53292768-bc87ce80-377c-11e9-9d93-af24389e1049.png)
Working as stock.
