### ISSUE TITLE
Stratus-V Cylindrified - Line in texture

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#432]
There's a grey line showing up on the left side of the tank right next to where the band goes around it. It doesn't appear on the other end.

![image](https://user-images.githubusercontent.com/22890228/53217212-13ba6180-360c-11e9-98c2-295a60ec3483.png)

**Comment by ChrisAdderley** [comment]
Fixed in 7cf278f

**Comment by TykoTek** [comment]
not fixed. I'm still seeing it in master 822c07c

**Comment by ChrisAdderley** [comment]
You need to refresh your textures, all the parts went back to tgas.
