### ISSUE TITLE
Rockomax Brand Adaptor - internal model structure not aligned

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#433]
In the internal crossbar structure one of the struts is not aligned properly. The bottom horizontal member doesn't actually meet the verticals at the correct crossing points

![image](https://user-images.githubusercontent.com/22890228/53224169-abc64400-3628-11e9-87dd-4d51052bbbc4.png)

**Comment by ChrisAdderley** [comment]
Fixed e93b8ec

**Comment by TykoTek** [comment]
The struts still aren't aligned. You can see in the video below that the struts are moving around as I rotate the part.

https://youtu.be/xfC5vE-Igro

**Comment by ChrisAdderley** [comment]
I think that looks perfectly acceptable... if I had to ensure that every part was perfectly identical when rotated I would never finish anything.
