### ISSUE TITLE
Rockomax Brand Adaptor - Holes in mesh

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#434]
Hole in mesh between the smaller end cap and the cone body

![image](https://user-images.githubusercontent.com/22890228/53224298-15dee900-3629-11e9-93ba-82270a8a8978.png)

**Comment by ChrisAdderley** [comment]
Fixed e93b8ec

**Comment by TykoTek** [comment]
Confirmed
