### ISSUE TITLE
BZ-52 Radial Attachment Point - Node to low

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#435]
The node is too low and causing z-fighting with attached parts

![image](https://user-images.githubusercontent.com/22890228/53225443-e205c280-362c-11e9-981a-8792bbc4da08.png)

**Comment by Poodmund** [comment]
To further this, the part connects radially/surface mounted to its part part ok.

![untitled-1](https://user-images.githubusercontent.com/10106634/53256848-c51acf00-36c0-11e9-91dc-4e737b0763b7.png)

And when connecting a child part like Tyko has above I also get the Z-Fighting:

![untitled-2](https://user-images.githubusercontent.com/10106634/53256878-d368eb00-36c0-11e9-9a82-ade0f8607397.png)

Comparing this to stock, it seems that the stock Attachment Point part is a slightly smaller diameter that 1.25m on the top, outer ring to avoid this issue. See the screenshot below where you can see the stock version has a slightly smaller diameter causing a slight lip to be seen on the pink 1.25m part:

![untitled-3](https://user-images.githubusercontent.com/10106634/53256951-f98e8b00-36c0-11e9-9baa-4b922a52d6ab.png)

**Comment by ChrisAdderley** [comment]
Fixed e93b8ec

**Comment by TykoTek** [comment]
Confirmed
