### ISSUE TITLE
Rockomax HubMax Multi-Point - nodes causing z-fighting

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#436]
The nodes are too close to the center causing z-fighting with attached parts. Affects all 6 directions

![image](https://user-images.githubusercontent.com/22890228/53225630-8be54f00-362d-11e9-92c2-1b6c849ff6e4.png)

**Comment by ChrisAdderley** [comment]
Fixed e93b8ec

**Comment by TykoTek** [comment]
Confirmed
