### ISSUE TITLE
Not-Rockomax micronode - z-fighting

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#437]
when the nodes are attached to each other there's slight z-fighting at all the joints. Hard to see in the pic, but it's present and you can see the shifting when moving the camera

![image](https://user-images.githubusercontent.com/22890228/53226254-60fbfa80-362f-11e9-8a30-741017599fa7.png)

**Comment by Poodmund** [comment]
I've just tested the stock behaviour and it doesn't seem to be happening in stock.

Here is a video showing the Z-Fighting: https://www.youtube.com/watch?v=l4FmjmvzOB4

**Comment by ChrisAdderley** [comment]
I hope you prefer tiny gaps because that's what you get now in e93b8ec

**Comment by TykoTek** [comment]
Looks good...closing
