### ISSUE TITLE
FL-T800 Fuel Tank - White variant texture issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#439]
The is a anomalous region on the White variant's texture as shown in the screenshot below:

![untitled-1](https://user-images.githubusercontent.com/10106634/53242795-be2e9500-369d-11e9-8331-6d86cf66f779.png)

**Comment by ChrisAdderley** [comment]
Okay good 7cf278f

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/7cf278fb342c0c31d4dbdea29a6bd473e252c2b9
