### ISSUE TITLE
Mystery Goo container larger than stock

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#44]
Bug: In order for Mystery Goo container to match Stock dimensions it needs to be scaled down to 60% its current size.

Art Request: It would be really cool if the Goo inside the container glowed when open too. Not a bug, but maybe a little bonus to really make this part a lot more interesting than the stock version :) 

Something like this, only Goo purple. Might have to make the glass goo tube a bit smaller so the glow has space to bounce off the inside of the case:
![image](https://user-images.githubusercontent.com/22890228/46212812-c69bc300-c2eb-11e8-8df6-56647a85d619.png)

**Comment by drewcassidy** [comment]
ah, thank you. I though I had accounted for that in the model. It no longer lines up as well with the inline variant, but I guess the inline one can just hold more goo.

**Comment by drewcassidy** [comment]
I could add the glow, but it would require adding an emissive map to the base texture, which I was trying to avoid. I guess I could make it a smaller texture size... I'll consider it.

**Comment by TykoTek** [comment]
Another way to handle the inline version is to make it half the height. This brings the approx goo volume close to the surface attach version so you can keep the weight the same. You end up with an oval goo container instead of a circular one, but it actually works and wouldn't require additional modeling work.

![screenshot37](https://user-images.githubusercontent.com/22890228/46260526-fa1d4f80-c49b-11e8-99d4-cd56d67d817a.png)
