### ISSUE TITLE
FLT-100/200/400/800 Fuel Tank - Orange/Grey Variants texture issue on endcaps

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#440]
On the top and bottom endcaps of all the orange/grey variants on the 1.25m FLT Fuel Tank range, there is a small texture bleed. See screenshots below showing a dark spot on two of the opposite corners where the UVs mirror:

![untitled-1](https://user-images.githubusercontent.com/10106634/53242946-36955600-369e-11e9-851e-cd74f682f26c.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/53242949-39904680-369e-11e9-809e-84f7b8c36661.png)

**Comment by ChrisAdderley** [comment]
Okay good 7cf278f

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/7cf278fb342c0c31d4dbdea29a6bd473e252c2b9
