### ISSUE TITLE
Kerbodyne S3-3600 Tank - Z-Fighting at bottom node

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#441]
There appears to be Z-Fighting with parts attached to the bottom node. The top of the part is fine so it may be that the bottom node is too low or the model extends past the node too far, see video: https://youtu.be/De8zk-e0YpI

**Comment by ChrisAdderley** [comment]
Fixed a3b8ca3

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/a3b8ca386fe5eb7c0405e43c793632f389e3c0fd
