### ISSUE TITLE
FL-R1 RCS Fuel Tank - Z-Fighting at top and bottom

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#442]
There appears to be Z-Fighting with parts attached to the top and bottom node, see video: https://youtu.be/5J5yOkoVPSc

**Comment by ChrisAdderley** [comment]
Okay good 7cf278f

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/7cf278fb342c0c31d4dbdea29a6bd473e252c2b9
