### ISSUE TITLE
FL-R25 RCS Fuel Tank - Top pipework mesh fidelity issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#443]
The top, yellow pipework seems of a lesser fidelity than that featured on the FL-R10 and FL-R1 tanks. See the screenshot below, it may need a smoothing group re-applied or something?

![untitled-1](https://user-images.githubusercontent.com/10106634/53250316-14a5ce80-36b2-11e9-8ba3-6f993d891368.png)

The other tanks (smaller & larger) for comparison:

![untitled-1](https://user-images.githubusercontent.com/10106634/53250513-723a1b00-36b2-11e9-9129-8778566cae3a.png)

**Comment by ChrisAdderley** [comment]
Okay good 7cf278f

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/7cf278fb342c0c31d4dbdea29a6bd473e252c2b9
