### ISSUE TITLE
PB-X150 Xenon Container - Z-Fighting when stacked top to bottom

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#444]
When you stack the PB-X150 containers between a top node and a bottom node, there is Z-Fighting at the connection. If you stack them top node to top node, or bottom node to bottom node this Z-Fighting does not occur.

See video in which this can be seen: https://youtu.be/6RIxNRIh7W8

**Comment by ChrisAdderley** [comment]
Fixed in 7cf278f

**Comment by Poodmund** [comment]
I'm not sure if this issue was resolved in the https://github.com/PorktoberRevolution/ReStocked/commit/7cf278fb342c0c31d4dbdea29a6bd473e252c2b9 change. When I stack the fuel tank post-https://github.com/PorktoberRevolution/ReStocked/commit/7cf278fb342c0c31d4dbdea29a6bd473e252c2b9 I am experiencing the following:

![untitled-1](https://user-images.githubusercontent.com/10106634/53364180-27303a00-3936-11e9-855b-f567346ff6db.png)

@TykoTek 	are you able to confirm that you're seeing the same?

**Comment by ChrisAdderley** [comment]
Should be cleaned up now with #482 merged

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/pull/482.
