### ISSUE TITLE
Cubic Octagonal Strut - Vertice blemish in model

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#446]
There are a couple of spiky bits on two of the uprights on the Cubic Octag as can be seen in the screenshots below:

![untitled-1](https://user-images.githubusercontent.com/10106634/53258063-9c480900-36c3-11e9-8ff1-e3feb92b5ea0.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/53258065-9e11cc80-36c3-11e9-85dc-3f4d510ae1f2.png)

**Comment by ChrisAdderley** [comment]
Fixed e93b8ec

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/e93b8ecec59929d3447aac510777d827b59b859c
