### ISSUE TITLE
The Not-Rockomax Micronode - Hole in model mesh

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#448]
The square 'face plates' on each face of the cube are sitting slightly off the main cube as can be seen in the screenshot below:

![untitled-1](https://user-images.githubusercontent.com/10106634/53259162-5771a180-36c6-11e9-8f28-91055e25fb77.png)

**Comment by ChrisAdderley** [comment]
Fixed e93b8ec

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/e93b8ecec59929d3447aac510777d827b59b859c
