### ISSUE TITLE
Mobile Processing Lab MPL-LG-2 - Hole in mesh

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#449]
The are holes in the mesh at the top and bottom of each window recess on either side of the part, see screenshots below:

![untitled-1](https://user-images.githubusercontent.com/10106634/53259705-a2d87f80-36c7-11e9-95af-46a539d0ec22.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/53259716-aa982400-36c7-11e9-9339-f6470114573e.png)

**Comment by ChrisAdderley** [comment]
WOO. 

Fixed e93b8ec

**Comment by Poodmund** [comment]
I appreciate your (faux-)enthusiasm. 😄 	Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/e93b8ecec59929d3447aac510777d827b59b859c
