### ISSUE TITLE
Material Bay art request

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#45]
The new Material Bay rocks, love all the detail! This isn't a bug, but since you've put so much work into the interior some lighting would really make this thing pop. Some suggestions:

- the two crystals could glow
- "squid tank" could have a little aquarium glow
- plant bay should have a small grow light on the roof
- in the asteroid sample the green veins could glow - this would match the actual glowing asteroids in the game.

**Comment by drewcassidy** [comment]
this are all things I added to the current artwork. is the emissive map not working? do you have the ambient lighting set too high?

**Comment by TykoTek** [comment]
Took another look in the middle of the night with default ambient lighting. I can see a bit of a glow, but it's hard to discern. Take a look at the glow coming off various parts compared to just ambient lighting off the cables on the floor and there isn't much difference. I thought I was just seeing reflected light. 

![screenshot35](https://user-images.githubusercontent.com/22890228/46247733-77759100-c3c4-11e8-8259-5bdc7d867cca.png)

I'd recommend you pump it up a bit...you put a lot of work into making it look so cool and it's probably better to err towards a bit too bright rather than be too subtle and have people miss it. This is KSP - moar glow!  :)
