### ISSUE TITLE
Stratus-V Minified Monopropellant Tank - Attachment positioning

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#450]
The tank clips into the parent part slightly, it would be preferable to have the ribbing ring not clip into the parent part as it is the tanks own structure... maybe scaling the whole part down very slightly may suffice?

Here is a screenshot showing the MH similar tank on the right, the current position-attached RS+ tank part in the middle, and the RS+ tank on the left where I've offset the part slightly out from the parent part until it is no longer clipping.

![untitled-1](https://user-images.githubusercontent.com/10106634/53260260-f8f9f280-36c8-11e9-9481-c95ad82d1ca9.png)

**Comment by ChrisAdderley** [comment]
Fixed e93b8ec

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/e93b8ecec59929d3447aac510777d827b59b859c
