### ISSUE TITLE
Probodobodyne HECS2 - Holes in model mesh

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#451]
On behalf of Drew, there is a small gap between the main hexagonal body and the lower end cap portion. This only occurs on the gold and silver foil variants.

![untitled-1](https://user-images.githubusercontent.com/10106634/53263330-f7ccc380-36d0-11e9-9b40-858ed27153e0.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/53263332-fa2f1d80-36d0-11e9-8696-10bce90e82d5.png)

![untitled-3](https://user-images.githubusercontent.com/10106634/53263335-fbf8e100-36d0-11e9-881f-7ce05c1fd3b7.png)

Bit hard to see from a screenshot so I tried to show how it spans around the width of the part.

**Comment by ChrisAdderley** [comment]
Fixed in bd3498e

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/bd3498e34b5265b9a3713048542fda5952f1d732
