### ISSUE TITLE
TS-18 Stack Separator - Model Position and Model Orientation Issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#452]
The model on the 1.875m Stack Separator seems to be incorrectly positioned (the collider is positioned fine) and it also seems to be rotated through 45 degrees from the intended orientation. See screenshot below:

![untitled-1](https://user-images.githubusercontent.com/10106634/53272482-5d2cae80-36e9-11e9-9280-885da7ffc547.png)

I loaded the .mu into Blend and the Colliders are positioned evenly around the origin in the Z-axis but the Model appears to be shifted upwards by 0.026843m.

**Comment by Poodmund** [comment]
Wider, more encompassing issue discussed here: https://github.com/PorktoberRevolution/ReStocked/issues/454 but model rotation/orientation of this part is still relevant to require its own issue.

**Comment by ChrisAdderley** [comment]
Fixed in e93b8ec

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/e93b8ecec59929d3447aac510777d827b59b859c
