### ISSUE TITLE
All Decouplers and Stack Separators - Vertical Positioning of Model Meshes

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#454]
I've noticed that all the Decouplers and Stack Separators are experiencing a little Z-Fighting, some at their bottom nodes and some at their top nodes.

Looking into the .mu files, all the colliders are centred evenly around their 0 origin on the Z-axis but the models seem to all be very slightly shifted up or down on their Z-axis; some by very small amounts and some by larger amounts. I expect this is the cause of the vary levels of Z-fighting on the parts and some of the gaps that can be seen between the couplers and their attached parts.

I think it could be worth going through all the model meshes (not colliders or nodes) and centring them vertically and re-exporting them to see if it resolved the issues with all the couplers.

As an addendum, looking at the stock models it would seem as though SQUAD have all their model meshes centred vertically as per the colliders.

**Comment by ChrisAdderley** [comment]
I could not reproduce any of these problems. 2-3 test parts were attached on each node in the VAB and no-z-fighting was observed except in the one reported in a separate issue https://github.com/PorktoberRevolution/ReStocked/issues/452

**Comment by Poodmund** [comment]
It was only VERY slight gaps between them so you could see the light reflections change from light to dark and vice-versa on connected parts. If its all good on your end then I'll close this.
