### ISSUE TITLE
Z-4K Rechargable Battery Bank - 2.5 meter inline battery texture problems

### ISSUE THREAD

**Issue by GregroxMun** [PorktoberRevolution/ReStocked#455]
![https://i.imgur.com/pL7eVwE.png](https://i.imgur.com/pL7eVwE.png)

The texture is partly white and seems to have parts of the original model sticking out.

**Comment by ChrisAdderley** [comment]
Fixed 502f516

**Comment by TykoTek** [comment]
Confirmed.
