### ISSUE TITLE
TS-12 Stack Separator - Black / blank texture locations

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#456]
The inner ring has two spots where the grey texture is just black. One is pictured below and the other is identical, but on the opposite side. At first I thought these were odd shadows, but they black areas are present regardless of which way I turn the part

![image](https://user-images.githubusercontent.com/22890228/53311605-59726680-3866-11e9-805b-39ac5f446a4c.png)

![image](https://user-images.githubusercontent.com/22890228/53311631-6e4efa00-3866-11e9-93d4-2d64c6f62021.png)

**Comment by ChrisAdderley** [comment]
Fixed 89341c5

**Comment by TykoTek** [comment]
Confirmed
