### ISSUE TITLE
Z-200 Battery - bottom node leaving gap with part attached below

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#458]
There's a gap showing between the bottom of the battery and the reference part. The node needs to be moved slightly

![image](https://user-images.githubusercontent.com/22890228/53312168-d7d00800-3868-11e9-9422-3f915be22bf3.png)

**Comment by ChrisAdderley** [comment]
Fixed 502f516

**Comment by TykoTek** [comment]
Confirmed
