### ISSUE TITLE
Z-1k Battery - wear marks around panel too bright

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#459]
The wear marks around the control panel are a lot brighter than similar marks on the other batteries. They stand out. Especially the lines on the left side.

![image](https://user-images.githubusercontent.com/22890228/53312310-647ac600-3869-11e9-9f7b-b1bb9e98f7ac.png)

**Comment by ChrisAdderley** [comment]
Fixed 502f516

**Comment by TykoTek** [comment]
Confirmed
