### ISSUE TITLE
TS-18 Stack Separator - Balance issues

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#460]
**Change mass to 0.12**   - normally Separators are about 20% heavier than their decoupler counterparts. the 1.875m decoupler is 0.09, so the separator should be .11 or .12. The MH version is 0.12.

**Change ejection force to 125** to match MH version. This also puts it halfway between the 1.25m and 2.5m versions

**Comment by ChrisAdderley** [comment]
Fixed 89341c5

**Comment by TykoTek** [comment]
Confirmed
