### ISSUE TITLE
STS-1 'Anvil' Solid Rocket Booster - Hole in mesh

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#465]
Under the SRB up where the nozzle meets the underside there's a light colored rectangle. Can tell if it's a hole or a texture error.

![image](https://user-images.githubusercontent.com/22890228/53313694-7e1f0c00-386f-11e9-9af9-a7fcd1bc9305.png)

**Comment by ChrisAdderley** [comment]
Texture issue fixed in 502f516

**Comment by TykoTek** [comment]
Confirmed
