### ISSUE TITLE
Z-4K Rechargable Battery Bank - Green patch in texture

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#469]
Couldn't see this before with the overlapping stock texture...

There's a green patch that looks like the light color

![image](https://user-images.githubusercontent.com/22890228/53315411-e07c0a80-3877-11e9-929e-46ec084c1357.png)

**Comment by ChrisAdderley** [comment]
Fixed in 502f516

**Comment by TykoTek** [comment]
Confirmed
