### ISSUE TITLE
Clamp-o-tron Shielded Docking Port - pressure hatch missing

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#470]
The hatch isn't showing on the shielded port

![image](https://user-images.githubusercontent.com/22890228/53317481-a400dc80-3880-11e9-8c49-4dea98c4a249.png)

**Comment by ChrisAdderley** [comment]
Fixed d7cfc57

**Comment by TykoTek** [comment]
Confirmed
