### ISSUE TITLE
TT-70 Radial Decoupler - Attachment sits to deep in parent part

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#471]
The lower part of the decoupler base is completely clipped inside the parent part

![image](https://user-images.githubusercontent.com/22890228/53317838-145c2d80-3882-11e9-9188-3ae9055f6c7f.png)

**Comment by ChrisAdderley** [comment]
#482 fixed

**Comment by Poodmund** [comment]
Clipping issue resolved with https://github.com/PorktoberRevolution/ReStocked/pull/482
