### ISSUE TITLE
TT-38K Radial Decoupler - Texture blemish on bottom of part

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#472]
There is an anomaly on the bottom of the decoupler part, see screenshot below:

![untitled-1](https://user-images.githubusercontent.com/10106634/53367396-fce27a80-393d-11e9-88a6-b0be211faeef.png)

**Comment by ChrisAdderley** [comment]
Should be cleaned up now with #482 merged

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/pull/482
