### ISSUE TITLE
Duplicate and unused textures

### ISSUE THREAD

**Issue by drewcassidy** [PorktoberRevolution/ReStocked#479]
Some files that are either redundant or unused
* Assets/Command/restock-cupola-lab-1.png (redundant with dds)
* Assets/Command/restock-endcap-crewed-1-b.dds
* Assets/Command/restock-probe-stayputnik-1-b.dds

**Comment by ChrisAdderley** [comment]
Should be cleaned up now with #482 merged

**Comment by drewcassidy** [comment]
Looks good. Not sure where that png even came from because I can’t even find it again in older commits
