### ISSUE TITLE
1.25m tank textures aren't mapping to part correctly

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#48]
Something was changed with the most recent release and the textures are off now.

![screenshot0](https://user-images.githubusercontent.com/22890228/48270352-b8fb5200-e3ee-11e8-988f-9a8895630c2a.png)

**Comment by ChrisAdderley** [comment]
Uh, KSP 1.5 screwed this all up, I haven't fixed it yet. It's trying to switch the textures to the orange/whatever variants that were added.

**Comment by ChrisAdderley** [comment]
Fixed in 01823a5

**Comment by TykoTek** [comment]
Did you intend to remove the other variants? I'm only seeing the ReStocked option now, the other Stock variants aren't selectable

**Comment by ChrisAdderley** [comment]
Yes I did.
