### ISSUE TITLE
Mk1 Pod white variant is slightly too white.

### ISSUE THREAD

**Issue by GregroxMun** [PorktoberRevolution/ReStocked#486]
![https://i.imgur.com/Ig4mjKM.png](https://i.imgur.com/Ig4mjKM.png)

The white variant of the Mk1 pod is noticeably but not critically brighter compared to other 1.25m rocket parts. Since it seems to me that a major part of this mod involves standardizing the color pallets, I thought it would be worth bringing up.

**Comment by Poodmund** [comment]
![untitled-1](https://user-images.githubusercontent.com/10106634/53700425-268e1c80-3dea-11e9-8a1c-8ba884d51877.png)

Its due to the fact that the Mk1 panels are receiving much more light due to them being angled rather than vertical. When you align all the parts they look the same colour.
