### ISSUE TITLE
TT-14 Radial Decoupler - Attach node is not centered

### ISSUE THREAD

**Issue by drewcassidy** [PorktoberRevolution/ReStocked#488]
the attach node or mesh for the TT-14 is offset slightly, very apparent when attaching to a .625m stack <img width="561" alt="screen shot 2019-03-03 at 4 32 27 pm" src="https://user-images.githubusercontent.com/3837797/53704516-094d5400-3dd2-11e9-8ad2-d8a8d216f4ac.png">

**Comment by Poodmund** [comment]
Has this been resolved in https://github.com/PorktoberRevolution/ReStocked/commit/3235a0680e078db1adb496f790256dfaaf32a7fe as I no longer have this issue. 

![untitled-1](https://user-images.githubusercontent.com/10106634/53764732-fddb5500-3ec5-11e9-9a27-855b15b8a92f.png)

It seems to be centred now.

**Comment by ChrisAdderley** [comment]
Yes I did fix it, forgot to note it here.

**Comment by Poodmund** [comment]
Ok I'll close the issue then on Drew's behalf.
