### ISSUE TITLE
Mk-16 parachute - Node off-center

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#496]
The node is off-center. It's so small we missed it before, but you can see it in the picture below with another chute rotated 180 degrees and flipped upside down. Note the the top chute is shifted left compared to the bottom one.

![image](https://user-images.githubusercontent.com/22890228/53818346-c51a9a80-3f1c-11e9-8576-477e7b41579b.png)

**Comment by ChrisAdderley** [comment]
Should be good now

**Comment by drewcassidy** [comment]
I just checked in game and can confirm
