### ISSUE TITLE
Re-rig Gigantor panels

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#499]
Re-rig the Gigantor so the 26 individual panels become one single object for improved performance

**Comment by drewcassidy** [comment]
The part also appears to be using mesh colliders instead of box colliders. not a huge issue but might be worth fixing when you get around to this

**Comment by ChrisAdderley** [comment]
Fixed in `mh-engines-1` branch

**Comment by ChrisAdderley** [comment]
Ready to test in `develop`
