### ISSUE TITLE
Mk-16 Parachute - Node placement

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#502]
The parachute is sitting a bit too high causing a gap between the edge of the widest point in the chute and the top of the mk1 pod

![image](https://user-images.githubusercontent.com/22890228/53900052-82c28d80-3ff0-11e9-9aa3-b598733c6b60.png)

![image](https://user-images.githubusercontent.com/22890228/53900064-8c4bf580-3ff0-11e9-8e6e-8c110275c08e.png)

**Comment by ChrisAdderley** [comment]
ce0ff5b moves it down the required tiny bit

**Comment by TykoTek** [comment]
Confirmed. small change but it made a difference
