### ISSUE TITLE
Mk16-XL Parachute - not 1.25m diameter

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#503]
The chute is a bit narrower than 1.25m at base

![image](https://user-images.githubusercontent.com/22890228/53900181-cc12dd00-3ff0-11e9-9f7e-6bc39963f6a3.png)

![image](https://user-images.githubusercontent.com/22890228/53900197-d6cd7200-3ff0-11e9-8565-ef0366db2973.png)

**Comment by ChrisAdderley** [comment]
ce0ff5b should fix this

**Comment by TykoTek** [comment]
Confirmed
