### ISSUE TITLE
1.875m Monopropellant Tank

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#512]
Missing part from 1.875m lineup!

- [x] Model
- [x] Unwrap
- [x] Texture
- [x] Integration
- [x] Basic QC (nodes/holes/smoothing/seams)

**Comment by drewcassidy** [comment]
By the way there is a [1.875m mono tank](https://wiki.kerbalspaceprogram.com/wiki/FL-R5_RCS_Fuel_Tank) in MH (though you probably shouldn’t look directly at it)

**Comment by ChrisAdderley** [comment]
Yes I should tag this MH also.
