### ISSUE TITLE
Jettisoned interstage fairings from upgraded ships hang around

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#521]
See https://forum.kerbalspaceprogram.com/index.php?/topic/182679-161-restock-revamping-ksps-art/&do=findComment&comment=3553076

**Comment by ChrisAdderley** [comment]
Potentially fixed by e357a9c but needs confirmation. 
Test was done by:
- stock save, teleport pod with engine (lv909) +decoupler on it to space
- stage decoupler, shroud disappears
- enable restock
- load orbiting vessel, shroud is still gone.

**Comment by MuchozolF** [comment]
In 0.1.1 the [Ant engines display this issue](https://imgur.com/1yACNOw) To my knowledge, they were just fine in 0.1.0.

**Comment by ChrisAdderley** [comment]
I didn't change anything re: the ant between the two versions.
