### ISSUE TITLE
Mk25 Drogue Chute - not 1.25m diameter

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#524]
The Mk25 was the same size as the Mk16-XL. It also needs to be increased slightly in diameter.

![image](https://user-images.githubusercontent.com/22890228/53926692-47987c80-4039-11e9-936f-a79940debfb8.png)

I should have realized they're based on the same model and would need the same treatment  :/

**Comment by ChrisAdderley** [comment]
84cb53c fix

**Comment by TykoTek** [comment]
Confirmed
