### ISSUE TITLE
:First directive & Other Mods

### ISSUE THREAD

**Issue by HSJasperism** [PorktoberRevolution/ReStocked#526]
After experimenting, it seems that adding :FIRST to ReStock part changes will prevent mods that clone stock parts from breaking, as they should now copy the parts with references to ReStock assets.

Do you think it's an acceptable change, or will it cause more problems in the long run?

**Comment by drewcassidy** [comment]
Alternatively, those mods could add :AFTER[Restock]

**Comment by HSJasperism** [comment]
From the MM handbook 

> "Patches for modname values in NEEDS, BEFORE, AFTER that don't exist are removed."

I've been messing with BetterSRBs. From originally:

```
+PART[solidBooster1-1]
{
 @name = BetterSRB_1p875x12
 ...
}
```

it would become

```
+PART[solidBooster1-1]:NEEDS[!ReStock]
{
 @name = BetterSRB_1p875x12
}

+PART[solidBooster1-1]:AFTER[ReStock]
{
 @name = BetterSRB_1p875x12
}

@PART[BetterSRB_1p875x12]
{
 ...
}
```

for every copied part each for all other existing mods

**Comment by HSJasperism** [comment]
Alternatively,

```
+PART[solidBooster1-1]
{
 @name = BetterSRB_1p875x12
 ...
}

@PART:NEEDS[ReStock]
{
 !mesh
 !model {}
 model
 {
  "insert references to ReStock assets here"
 }
}
```
The above will likely be the case for MissingHistory's rescaled parts, while OhioBob/BetterSRBs will have to decide if they will still use their retexture on whitelisted Squad models or just use ReStock assets.

**Comment by ChrisAdderley** [comment]
I'm concerned that this is further modifying the targeting behaviour so would rather these be handled with `NEEDS` patches to make things more predictable for other mods.
