### ISSUE TITLE
Communotron HG-20 - TechRequired issue

### ISSUE THREAD

**Issue by theJesuit** [PorktoberRevolution/ReStocked#527]
restock-relay-radial-2 under the Communication folder has a TechRequired = Electrical.

This will result in it not being available in career and science mode games.  I'd do a PR, but i'm not sure which node you'd like it in.

Peace.

**Comment by drewcassidy** [comment]
Ah, that was supposed to be `electrics`

**Comment by drewcassidy** [comment]
Please try the latest Master (sorry I’m not in a position to do any testing right now)

**Comment by theJesuit** [comment]
I can't test either until the weekend - I'm on a hospital wifi network and it is s  l  o  w.  But looking at the commit, it looks good!

**Comment by TykoTek** [comment]
Confirmed it shows in Electrics
