### ISSUE TITLE
Replace solid collider for Kerbodyne SKLE-2-3 with a hollow one

### ISSUE THREAD

**Issue by theJesuit** [PorktoberRevolution/ReStocked#528]
What I mean is that the 
restock-adapter-skeletal-25-375-1 from ReStockPlus 
and the 
rockomax brand adaptors (largeAdapter and largeAdapter2) patched in ReStock

aren't hollow to fall through.  The flat rockomax version is hollow as such, but still won't allow you to stand on the inside plating.  With these parts the kerbals walk across air like "magic". 

The excellent restock-adapter-hollow-25-375-1 does work as What You See Is What You Get and kerbals will fall through the middle of this one.

I guess this is only an OCD issue really.  If I can fall through one, why not the others?

Peace.

**Comment by ChrisAdderley** [comment]
So there's no scope for changing stock colliders, but the restock+ one could use improvement.

**Comment by ChrisAdderley** [comment]
Added hollow collider in a229b0a

**Comment by theJesuit** [comment]
Awesome thank you!

Could we please have it for the insides of the largeAdapter and largeAdapter2, or are you bound by the initial model?

**Comment by theJesuit** [comment]
That is fantastic!  Thank you so much.

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/a229b0ac91a0ef2e6c88bdc9df0390317461e2ca
