### ISSUE TITLE
Z-10K Rechargeable Battery Bank - Hole in mesh along bottom rim

### ISSUE THREAD

**Issue by DMagic1** [PorktoberRevolution/ReStocked#531]
The 3.75m battery from Restock + has a gap in the mesh along both sides of the outer bottom rim:

![screenshot95](https://user-images.githubusercontent.com/5150421/53971251-875b7480-40ca-11e9-890e-25c0989ecbd6.png)

**Comment by ChrisAdderley** [comment]
74f5a85 has a fix

**Comment by DMagic1** [comment]
No more holes now.
