### ISSUE TITLE
SurfaceLights Compatability 

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#532]
SL breaks our light replacements! We are not 100% sure why but it has something to do with https://github.com/ihsoft/SurfaceLights/blob/master/Source/ModuleStockLightColoredLens.cs#L31

**Comment by ChrisAdderley** [comment]
The root cause here is that SL deletes the animations on the stock part and rebuilds them. (see https://github.com/ihsoft/SurfaceLights/blob/master/Source/ModuleStockLightColoredLens.cs#L31) 

This is not compatible with the different hierarchy the Restock models have.

**Comment by ChrisAdderley** [comment]
This should be in the next version of SL. Keeping in verif until this occurs.

**Comment by ihsoft** [comment]
FYI. The SL fix has been released.

**Comment by ChrisAdderley** [comment]
Excellent. I'll close this one then.

**Comment by VasylMarchuk** [comment]
Hi @ChrisAdderley !

This issue has resurfaced with the release of Restock 1.0 :(

Deleting `MM-StockLights.cfg` helps to get the lights working again, but all the custom colors get reset and all the lights appear white (on already launched vessels).
