### ISSUE TITLE
STS-1 'Anvil' Solid Rocket Booster - Bottom attach node too high

### ISSUE THREAD

**Issue by DMagic1** [PorktoberRevolution/ReStocked#534]
The bottom stack attach node for the Restock 1.875m SRB is placed about 1/3 of the way inside the part.

![screenshot100](https://user-images.githubusercontent.com/5150421/53975673-6ba89c00-40d3-11e9-98dd-6269a1c7cf81.png)

**Comment by ChrisAdderley** [comment]
Fix in a229b0a

**Comment by DMagic1** [comment]
Looks fixed to me.
