### ISSUE TITLE
Heat Shield (0.625m) appears asymmetric

### ISSUE THREAD

**Issue by MuchozolF** [PorktoberRevolution/ReStocked#536]
Screenshots say it all, I-beam for orientation reference 

![22-06-56](https://user-images.githubusercontent.com/48312586/53989514-6c1e5280-4126-11e9-9ec4-cac23cb45698.jpg)
![22-07-06](https://user-images.githubusercontent.com/48312586/53989520-704a7000-4126-11e9-87d7-c2c2340c377e.jpg)

**Comment by ChrisAdderley** [comment]
Fixed in 7085705

**Comment by Poodmund** [comment]
Can confirm, resolved in https://github.com/PorktoberRevolution/ReStocked/commit/708570522ef6fbfa4013bd9c36b22414e651be4d
