### ISSUE TITLE
KR-2L+ Rhino - Plume trail 

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#538]
There's an odd exhaust portion of the plume that looks wrong in space. First there's a particle trail which most other engines I've checked don't have. Also the trail particles look to be stopping once they leave the engine causing the ship to fall through it when firing retrograde.

This video captures the behavior:  https://youtu.be/T0IP6TYEEDA

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/6ff7420da088aee8c8a131de6b4264b8cd76d78b
