### ISSUE TITLE
Spark engine shroud stuck in new vessels

### ISSUE THREAD

**Issue by MuchozolF** [PorktoberRevolution/ReStocked#539]
![18-13-50](https://user-images.githubusercontent.com/48312586/54044107-6c722880-41ce-11e9-8200-495f96a90a70.jpg)
![18-14-12](https://user-images.githubusercontent.com/48312586/54044108-6c722880-41ce-11e9-8a80-9d839d596d09.jpg)
![18-14-24](https://user-images.githubusercontent.com/48312586/54044109-6d0abf00-41ce-11e9-8bff-520368b306f3.jpg)

before staging the decouplers
![18-15-16](https://user-images.githubusercontent.com/48312586/54044110-6d0abf00-41ce-11e9-8148-b292b96df96e.jpg)

after staging
![18-15-26](https://user-images.githubusercontent.com/48312586/54044111-6d0abf00-41ce-11e9-8a37-e71988b60400.jpg)

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/6ff7420da088aee8c8a131de6b4264b8cd76d78b as far as I know.

![Untitled-1](https://user-images.githubusercontent.com/10106634/54071211-80b33580-4261-11e9-89aa-41abf64ec67f.png)

Showing 3 variants in default state on left and 3 variants with decouplers attached to them on right side.

![Untitled-2](https://user-images.githubusercontent.com/10106634/54071219-988ab980-4261-11e9-8358-8544eba83e89.png)

Post decouple staging (I won the hoopla contest on the boattail variant 😄 	).

Please close if no further work is required.
