### ISSUE TITLE
Small Inline Reaction Wheel - incompatibility with Indicator Lights

### ISSUE THREAD

**Issue by drewcassidy** [PorktoberRevolution/ReStocked#540]
From the [forums](https://forum.kerbalspaceprogram.com/index.php?/topic/182679-161-restock-revamping-ksps-art/&do=findComment&comment=3553552):

> The 0.625m inline Reaction Wheel has an issue with the lights from IndicatorLights being positioned floating in space and extra-large. This appears to be because the stock 0.625 Reaction Wheel has a Rescale Factor of 0.5 built in, while the ReStock part does not... so the Indicator Lights people doubled the scale and position coordinates for the lights. It's easily corrected by undoing this doubling in their config file. A patch could do the same... just not sure if that would be more appropriate to put here or there.

**Comment by drewcassidy** [comment]
The small radial gyroscope could also get an indicator light patch

**Comment by ChrisAdderley** [comment]
Snark will be fixing this in IL itself.

**Comment by drewcassidy** [comment]
Alright, going to put this in Verification then until its fixed in IL

**Comment by ChrisAdderley** [comment]
I believe this is now fixed.
