### ISSUE TITLE
Incorrect SC-9001 dimensions in Engineer's Report

### ISSUE THREAD

**Issue by izeau** [PorktoberRevolution/ReStocked#542]
Hi! Wonderful project!

I have an issue regarding the SC-9001 Science Jr. part. It seems that its dimensions (as reported by Engineer's Report) are a bit bugged (see screenshots below). Strangely enough, the reported dimensions are also varying depending on where the root part (here the Mk1 Command Pod) is placed in the VAB.

*Edit: the SC-9001 height seems not to be random at all but rather the distance between the top of it and the VAB ground.*

It's a bit of an inconvenience early in career mode where height does matter.

* Restock version: 0.1.1
* KSP version: 1.6.1.2401 (64-bit, Windows)

*(complete mod list below)*

My apologies if the bug has been reported before, didn't see it in the issue list.
Cheers!

---

![image](https://user-images.githubusercontent.com/838867/54071391-5155f600-426c-11e9-831e-7036925d9b24.png)
*Without the SC-9001: 1.1m*

---

![image](https://user-images.githubusercontent.com/838867/54071403-6df22e00-426c-11e9-814b-b0fbee57113e.png)
*With the SC-9001: distance between the top of the rocket and the VAB ground*

---

![image](https://user-images.githubusercontent.com/838867/54071466-0092cd00-426d-11e9-953b-031887ac552d.png)
*Installed mods list*

**Comment by drewcassidy** [comment]
Odd, I wonder if it’s caused by the objects with zero scale I added for dmagic support
