### ISSUE TITLE
HG-20 doesn't retract properly, in editor, when using symmetry

### ISSUE THREAD

**Issue by MuchozolF** [PorktoberRevolution/ReStocked#544]
[terrible quality video from my phone](https://drive.google.com/file/d/1CnqaEhX3YARx9CJtw52Mczvb3Fvm7kbh/view)

It's not even annoying and doesn't occur in flight.

**Comment by drewcassidy** [comment]
I’ve noticed this before and am 99% sure it’s a stock bug, closing
