### ISSUE TITLE
Anvil SRB balancing 

### ISSUE THREAD

**Issue by riocrokite** [PorktoberRevolution/ReStocked#547]
Anvil SRB seems to be underpowered and inferior to stacked kickbacks
price wise 1 x anvil = 4 x kickback + quadcoupler

comparisons between Ares-1 type rocket:

1 x anvil                  = 1414 dV, 2.12 SL TWR, 940m/s / 20k m upon separation
4 x kickback +quad = 1800 dV, 1.89 SL TWR, 1280m/s / 31k m upon separation

increasing fuel from 4500 to 5500 and SL isp +10 decreases this difference but cost wise anvil is still inferior to quad kickbacks:

1 x anvil 5500 fuel,+10 SL ISP = 1708 dV, 2 SL TWR, 1135 m/s / 28k m upon separation

-------------------------------------------------------

it seems that anvil has too little fuel for its size:

kickback = 2600 units (13m height for fuel, 1.25m diameter)
anvil = 4500 units but is 23% higher (16m) and 2.25 x bigger cross-section area from 50% bigger diameter so theoretically anvil should hold 2600 x 1.23 x 2.25 = 7195 units of solid fuel

one way to fix that would be to increase fuel in anvil to 7000 units, vac thrust to 2000 kN, mass to 4-5t, increasing cost to 14-15k from 11k so it won't outclass LRB price-wise
with those stats it will be superior to 4 x kickback (about 80-100 dV more + less parts) offset by a higher price

reference images for compared vehicles:

![image](https://user-images.githubusercontent.com/9766897/54118546-90fb1a00-43f3-11e9-9400-739fd5769b40.png)

![image](https://user-images.githubusercontent.com/9766897/54118556-9bb5af00-43f3-11e9-84f2-9df39b6cafa8.png)

**Comment by Poodmund** [comment]
Comparing some of the SRB volumes and the solid fuel capacities of boosters from Stock, KW Rocketry, BDB and SpaceY, the Anvil comes in around 7155 units of Solid Fuel for its volume, therefore I feel a suggestion could be to bump its Solid Fuel capacity to 7200 as that's a nice regular number common in KSP.

I also feel as though, seeing as these are going to be used a lot with Shuttles, a slightly better performing side booster may be a good bonus.

**Comment by TykoTek** [comment]
7200 works for capacity. Thx for the suggestion. WRT performance. If we were really modeling an STS booster it would be about 6000kN 

- SLS core (standing in for Mammoth) is ~7500kN
- STS booster is 12000kN. 

So the Anvil would be ~1.5x Mammoth = 6000kN.

If we went with the "standard" KSP conversion of 1/4 power for boosters then we're looking at 3000kN

3000-6000kN would make it a real beast of a booster. I don't build shuttles though. @Poodmund do you build shuttles and have a recommendatinon?

**Comment by drewcassidy** [comment]
Keep in mind the SLS parts are not scaled “correctly”, since the booster should really be more like 2.2m diameter in KSP. I would look at the TWR compared to other solid boosters

**Comment by Poodmund** [comment]
Looking at the same sample group plotting fuel capacity against thrust (with a fuel cap of 7200) it would suggest a thrust of around 2500kN for the Anvil. 

The Kickback is a bit of an outlier in that it has a lot of fuel for its thrust. If you were balancing it against Kickbacks it'd suggest a thrust of around 1850kN but then that would still favour using 4 Kickbacks over 1 Anvil.

I don't build Shuttles unfortunately... however, 2500kN is still a heck of a lot of thrust.

**Comment by TykoTek** [comment]
Here's my proposed balance. Please try it out and let me know. Increasing the fuel to 7500 got it's burn time over 1 minute and got the TWR where it felt right. I'm still not sure about the dry mass, but it's now 1.5x the mass of a Kickback.

// ReStock+ 
// Test Balance
// By Tyko
@PART[restock-srb-anvil-1]:FINAL
{
  @mass = 6.75
  
  @MODULE[ModuleEnginesFX]
  {
    @maxThrust = 2000
  }
  
  @RESOURCE[SolidFuel]
  {
    @amount = 7500
    @maxAmount = 7500
  }
}

**Comment by riocrokite** [comment]
looking good, after some comparison (mostly with 1.5 tank + mainsail that gives comparable results) I would increase cost of Anvil to around 18k. With 7500 fuel and higher dry mass (6.75) as well as cost it might be good to give anvil a bit more oomph around 2300kN (player still can lower that for a longer burn). In effect it's more useful as a SRB for sustainer style rockets (with skipper or Rhino - H2a/Ariane/Titan style rockets) that in stock have terrible SL isp and need stronger SRBs.

**Comment by Poodmund** [comment]
I think Rio and I have both agreed that, volume wise, the Anvil should be at 7200... but also the Kickback seems over fuelled when compared to the majority of other SRBs for its size so I am not opposed to saying that the Anvil could be bumped slightly to 7500 to make it fall in line with the stock Kickback balancing.

I do agree with Rio that the thrust should be a little higher than 2000kN though. I suggested 2500kN, inline with other SRBs for its size and Rio is suggesting around 2250kN. Maybe 2300kN could be enough?

I wish suggest downloading a bunch of stock Shuttle type craft of KerbalX and replacing the side SRBs (assuming they are using multiple clipped Kickbacks) with Anvils and seeing how the dV, TWR and Mass compare. That should give a good indication of if we are in the right ball park with 7500 and 2200-2300kN. 

This evening I can post the small sample data I collected showing trends with regards to fuel capacity, part volume and thrust for reference.

**Comment by riocrokite** [comment]
I'm absolutely fine with everything that has >=7000 solid fuel and >=2000 vac thrust. Already tested solids with stock shuttle, Ares-1 type rockets and big / small sustainer-type rockets and it works fine. Setting thrust and solid fuel on the higher side (2300/7500) might help to keep it competitive against twin-boar LRBs in late game but again, I'm fine with less fuel and thrust as mentioned in the first sentence. Suggested price = 13k for less fuel/thrust variant, 15k for more fuel/thrust variant so it's competitive with twin-boar + half-height 2.5m tank that costs 20k.

**Comment by TykoTek** [comment]
Okay...before we keep inflating numbers...I'm going back to what we are pretty confident about. It should hold about 7200 fuel based on its volume.

**Mass = 10.125**   This is the same wet/dry mass ratio as other boosters
**Fuel = 7200**       We figured this out already
**Thrust = 2000 kN**    Gives a TWR of 3.18. A little higher than the anemic Kickback, but close and offers 1 min 2.8 seconds of burn time

**Comment by TykoTek** [comment]
`// ReStock+ 
// Test Balance
// By Tyko
@PART[restock-srb-anvil-1]:FINAL
{
  @mass = 10.125
  
  @MODULE[ModuleEnginesFX]
  {
    @maxThrust = 2000
  }
  
  @RESOURCE[SolidFuel]
  {
    @amount = 7200
    @maxAmount = 7200
  }
}
`

**Comment by riocrokite** [comment]
looks good, in this scenario a current price of 11k funds for Anvil seems to be balanced (cheaper than 4 sidekicks with a bit inferior stats except a bit better TWR)

**Comment by TykoTek** [comment]
Recommended stats:

cost = 10500
mass = 10 tons
maxThrust = 2200
Solid Fuel = 7200

**Comment by TykoTek** [comment]
I ran a bunch of tests last night with various 2.5 and 3.75m cores. I didn’t run into any problems with initial TWR @ 2200kN. The problem was always giving the sustainer core enough time to burn fuel to get its TWR up to a decent level. With higher thrust it gave insane initial TWR but then burned out too quickly.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Poodmund** [comment]
![Untitled-1](https://user-images.githubusercontent.com/10106634/54224942-7c517b80-44f2-11e9-88d2-f96a9fd835c2.png)

![Untitled-2](https://user-images.githubusercontent.com/10106634/54224946-7eb3d580-44f2-11e9-870e-99cd5c65bb24.png)

There are the balancing plots for reference. I would be happy with 7200 units of fuel and 2200kN of thrust. Seems in the right ball park to me.

**Comment by TykoTek** [comment]
Wow, actual data! If I'm reading your second graph right a thrust of 2500kN would put it right on the median line?

I'm fine with that really...better to have too much and let people dial it back than have it too low

**Comment by Poodmund** [comment]
As has been noted elsewhere, the SpaceY boosters tend to skew the trendline upwards in thrust but the Kickback falls in line with the KW boosters (all below the trendline), hence why the 2200kN-2300kN figures were suggested as good targets.

... but yes, you're reading it correctly, I'm just not sure that 2500kN is the most apporiate value as some of the data set may be skewing results. :D

**Comment by TykoTek** [comment]
Okay. We’ve rehashed this a lot. I’ll change the recommended stats above to 2250kN and we can call this done 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TykoTek** [comment]
@ChrisAdderley  we have a consensus 

cost = 10500
mass = 10 tons
maxThrust = 2250
Solid Fuel = 7200. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ChrisAdderley** [comment]
Changed in 57e9252

**Comment by TykoTek** [comment]
Confirmed
