### ISSUE TITLE
Check flame-out effects

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#549]
Flameout effect for Reliant, Swivel and SRBs were reported to be emitting at a 90 degree angle.

Need to confirm

**Comment by Joker58th** [comment]
I an confirm the issue with stock 1.6.1 and only Restock/Restock+ installed.  No realplume.

https://youtu.be/aiP2m_IZjYA

**Comment by ChrisAdderley** [comment]
All flameout effects should be disabled because they suck and make me cry.

**Comment by TykoTek** [comment]
Tested all the Porkjet engines + Spark. Can confirm the following engines with flame out issues

Valiant, Reliant, Swivel

Spark (startup and flame out effects are HUGE)

The 303 and 909 are fine.

**Comment by TykoTek** [comment]
Quickest way to test is to stack on top of a decoupler and enable/disable crossfeed to kill fuel flow

**Comment by ChrisAdderley** [comment]
Fixed in fd99e73 (removed FX)

**Comment by TykoTek** [comment]
Confirmed
