### ISSUE TITLE
Reliant engine boattail model is solid inside

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#55]
The Reliant engine's boat tail model is solid inside while the Swivel's is hollow allowing you to see the plumbing within. Not sure if this is intended.

Reliant is on the left

![screenshot1](https://user-images.githubusercontent.com/22890228/49263053-d758da00-f3fd-11e8-93f1-3d95516f1578.png)

**Comment by ChrisAdderley** [comment]
Intended, but probably not ideal. Porkjet made the boattail solid because the Reliant doesn't gimbal so needs no room.
