### ISSUE TITLE
Antennas Missing Communication Information

### ISSUE THREAD

**Issue by xdreaper15** [PorktoberRevolution/ReStocked#552]
The various communication relays/antennas that are included, do not contain useful part information when viewing in the VAB. i.e. Range, Strength, Power Draw, etc.

**Comment by drewcassidy** [comment]
Has this ever been a thing?

**Comment by CGADragon** [comment]
FYSA I also see this but suspect it is due to RemoteTech installation not recognizing the antenna since RT replaces the stock antenna info displayed.
