### ISSUE TITLE
HG-5 and HG-20 antennas incompatible with Procedural Fairings

### ISSUE THREAD

**Issue by Angel-0a** [PorktoberRevolution/ReStocked#554]
Procedural Fairings mod "sees" both axial and radial models simultaneously and creates huge fairing to accommodate both of them. Both models are also visible in the R&D tech tree. Other deployable antennas don't seem to have this problem.

**Comment by drewcassidy** [comment]
Not much I can do about this, sounds like a bug in PF

**Comment by blowfishpro** [comment]
Yeah, PF should ignore stuff that’s disabled in the hierarchy when calculating payload size

**Comment by drewcassidy** [comment]
Closing since it’s not our bug. I suggest reporting this in the PF repo though
