### ISSUE TITLE
Clamp-o-Tron Sr - Docking node not centered

### ISSUE THREAD

**Issue by drewcassidy** [PorktoberRevolution/ReStocked#555]
The docking node on the clamp-o-Tron Sr. appears to be not centered.  [See here](https://www.reddit.com/r/KerbalSpaceProgram/comments/b0ec6z/comment/eijwqr8)

**Comment by ChrisAdderley** [comment]
Fixed in fd99e73

**Comment by DMagic1** [comment]
This still looks off in the latest version, though I think less than before.

![screenshot116](https://user-images.githubusercontent.com/5150421/54444116-763ce400-4718-11e9-993b-3975a5697878.png)

![screenshot117](https://user-images.githubusercontent.com/5150421/54444061-5e656000-4718-11e9-9be9-b1d8a09d3bc4.png)

**Comment by ChrisAdderley** [comment]
Ok we should be good now (c386632)
