### ISSUE TITLE
Mk1 Lander Can flag is stretched

### ISSUE THREAD

**Issue by damonvv** [PorktoberRevolution/ReStocked#558]
I noticed on the MK-1 Lander Can that the flag is slightly stretched. Not sure about other parts. But good to look into.

**Comment by ChrisAdderley** [comment]
Seems like this happens in stock too, but we can fix it.

**Comment by ChrisAdderley** [comment]
8443922 has a fix

**Comment by TykoTek** [comment]
Confirmed
