### ISSUE TITLE
KIS Volume calculation affected by ReStock

### ISSUE THREAD

**Issue by xot1643** [PorktoberRevolution/ReStocked#567]
Hello guys.
I noticed a side effet of ReStock: the volume of parts calculated by Kerbal Inventory System are affected.
([**KIS**](https://forum.kerbalspaceprogram.com/index.php?/topic/101928-112-kerbal-inventory-system-kis-1212/) is a mod that adds inventory to Kerbals and storage containers to the game and allows parts building in the game when in EVA)
Almost every time the ReStock volume is bigger than the Stock volume and sometimes the difference is huge. Sometimes it could be less.
From what I understood KIS determines the smallest box in which a part could fit to determine its volume. I believe the changes you made on the parts changes something somewhere.
Here is a [short Gsheet](https://docs.google.com/spreadsheets/d/1rtdGw9g7VTSMq6z2mcwcGcJTmE9j1K22OcGRy0RJ4ow/edit?usp=sharing) in which I listed a few parts and the differences between stock and restock behaviour.
I know almost nothing about the internal mechanics of the game but tell me if I can give a hand in any way.

**Comment by drewcassidy** [comment]
Will need to get @ihsoft to weigh in but at first glance this looks similar to #537 where other mods don’t correctly handle skinned meshes

**Comment by xot1643** [comment]
@ihsoft I understand that parts could have a different volume from Stock to ReStock. But if you consider the XL solar panel the volume changes from 440L to 6891L which I believe is not minor. It is actually with this part that I noticed a change.
Maybe the issue concerns actually a few parts and not methodology in any way.

**Comment by drewcassidy** [comment]
the stock RadialDrill is using a skinned mesh, btw

**Comment by ihsoft** [comment]
@drewcassidy Yes, but specifically `RadialDrill` has another problem: its model is made for the _deployed_ state. When the part starts, the model state is updated, but `KIS` deals with prefabs. So the only way to have a reasonable volume for such parts is volume overriding.

And speaking about the `Restock` parts, it seems the correct handling of skinned meshes solved the problem. I'll release it in the next version.

**Comment by drewcassidy** [comment]
Ah, understood. I’ll leave this issue open until that is released just so we don’t get duplicate reports in the meantime

Also I realized my Communotron 88-88 is modeled deployed... I’ll have to either adjust the animation or manually patch it’s volume to fix that

**Comment by drewcassidy** [comment]
Ah, but why does the Vernor get a wildly different volume? it doesnt use a skinned mesh from what I can tell

**Comment by ihsoft** [comment]
With the skinned mesh handling fixed, "vernor" returned back to the normal scale. However, I can't say if it does use skinned meshes or doesn't.

**Comment by drewcassidy** [comment]
This appears to be fixed by the latest version of KIS, @xot1643 can you confirm?

**Comment by xot1643** [comment]
Sorry for this very late feedback but yes, volume of the Solar XL panel is now back to normal :)
