### ISSUE TITLE
Linear RCS port collider is wrong scale

### ISSUE THREAD

**Issue by Avera9eJoe** [PorktoberRevolution/ReStocked#569]
The collider for the Linear RCS port is larger in ReStock, causing issues with stock hinges.

Stock image: https://i.imgur.com/CSnpvmR.png
ReStock image: https://i.imgur.com/qY8nQWf.png

**Comment by Poodmund** [comment]
I can confirm the issue above. The stock part collider has a radius of 0.08 on the node collider transform whereas the ReStock part has a radius of 0.005 which is scaled up 20x higher up in the hierarchy, resulting in a radius of 0.1.

See screenshot below, ReStock on left, Stock on right:

![Untitled-1](https://user-images.githubusercontent.com/10106634/55258250-3a4a6880-525a-11e9-984d-1bb2e3f0494b.png)

I think the two colliders are not positioned similarly around the origin too which would causes further issues to the OP's vessel potentially.

**Comment by ChrisAdderley** [comment]
Should be fixed in 8443922

**Comment by Poodmund** [comment]
Fixed in https://github.com/PorktoberRevolution/ReStocked/commit/844392282db91564703c977901b24befc203cecf
