### ISSUE TITLE
Spark double variant selectors

### ISSUE THREAD

**Issue by Vladimir-csp** [PorktoberRevolution/ReStocked#57]
Spark has two variant selectors (although I see only one ModulePartVariants instance for it in config)

**Comment by ChrisAdderley** [comment]
I'm not seeing this in my install, will investigate though.

**Comment by TykoTek** [comment]
I'm seeing it too in the latest build. Here's a screen shot:

![screenshot2](https://user-images.githubusercontent.com/22890228/49343055-1793a480-f618-11e8-80c4-0ddf56847251.png)

**Comment by ChrisAdderley** [comment]
Ah, I was working in a branch that I thought was up to date with master, but was not.
Fixed in a55d5f8

**Comment by TykoTek** [comment]
Yep looks correct now
