### ISSUE TITLE
Boar engine is (too?) expensive

### ISSUE THREAD

**Issue by LouisB3** [PorktoberRevolution/ReStocked#571]
The Boar engine seems to cost too much compared to similar engines such as the Twin-Boar or Mainsail.

- Boar: 1000 thrust, 12000 cost (12 cost/thrust)
- Twin-Boar: 2000 cost, 11250 cost (5.625 cost/thrust) [excludes cost of fuel tank, Jumbo-64 equivalent]
- Mainsail: 1500 thrust, 13000 cost (8.67 cost/thrust)

A more balanced cost would likely be in the range of 6000 to 9000 funds.

**Comment by ChrisAdderley** [comment]
Reduced to 7k in 81626fc05e24998e4ef4d1c55f8518cfbdb25592
