### ISSUE TITLE
Heat Shields with FAR

### ISSUE THREAD

**Issue by svm420** [PorktoberRevolution/ReStocked#572]
The current master release and latest FAR has some issue with the meshs(?) when using FAR. I know it isn't designed for FAR, but I want to at least report it. Feel free to say you don't care. 

[Images](https://imgur.com/a/9DfkHi7)

The 0.625 heat shield appears flat and extended beyond the actual part bounds
The 1.25m shield has the shroud mesh always on.
The 2.5m shield mesh extends down beyond the bounds of the part around the outer edge of the part. 
Let me know if you need anything from me.

**Comment by ChrisAdderley** [comment]
Based on these images, FAR is voxelizing the colliders vs the meshes - those look like the stock ones. You could indicate that to the FAR dev, I spend a while in the FAR repo trying to see if they were overridden somewhere and can't find anything, so I have no idea what I might do to fix this.

**Comment by PhineasFreak** [comment]
You can command FAR to use the mesh instead of the collider by:

```
@PART[MyPart1|MyPart2|MyPartN]:AFTER[FerramAerospaceResearch]
{
    @MODULE[GeometryPartModule]
    {
        %forceUseMeshes = True
    }
}
```

But i find it weird that RS would need such patches since you are replicating the part colliders. **[FAR itself does ship a patch for specific parts](https://github.com/ferram4/Ferram-Aerospace-Research/blob/master/GameData/FerramAerospaceResearch/FARVoxelGeometryOverrides.cfg)** but the stock heat shields are not among them.

**Comment by dkavolis** [comment]
Actually, you will probably want to force colliders (meshes are used by default pretty much always). In the screenshot, voxels are based on the mesh and the wireframe shows collider which is much closer to the actual heat shield shape than the mesh itself, though still a cylinder.

![screenshot35](https://user-images.githubusercontent.com/12998363/55470885-72f29500-5600-11e9-8826-90f5010c0494.png)

The 3.75m heat shield has a bug in its mesh
![screenshot36](https://user-images.githubusercontent.com/12998363/55471380-85210300-5601-11e9-95aa-0b09282e474b.png)

The problem with heat shield meshes are that they all have fairing meshes baked in even if the fairing is not used/visible. It's not really a FAR issue.

**Comment by ChrisAdderley** [comment]
I think you're going to need to be clearer about how you define a _bug in the mesh_ for FAR's purposes. 

Looking at the list of mesh items that have the `fail` tag next to them, it's not clear to me what is going on - in fact it looks like all of the actual visible model mesh objects (HeatShield125Brown, HeatShield125Internals, fairing) have failed. 

What causes a mesh to fail voxelization, specifically? These parts aren't doing anything special.

**Comment by dkavolis** [comment]
You can see in the 2nd screenshot that there are 2 planes in the mesh which I suppose should not be there. FAR will generate tons of drag with it in its current state.

Mesh isn't voxelized if the transform doesn't have `MeshFilter` or `SkinnedMeshRenderer` component attached or the part prefab contains model transform from the associated `gameObject` in TransparentFX layer.

https://github.com/dkavolis/Ferram-Aerospace-Research/blob/d902b9d8cf6b659554f810d7e42a2a8c85d8fc8d/FerramAerospaceResearch/FARPartGeometry/GeometryPartModule.cs#L669-L673

**Comment by ChrisAdderley** [comment]
I'm fairly certain there aren't any giant planes in that model. I will check it out.

That doesn't clarify much regarding the 3rd screenshot and the failing objects, though. I am completely sure that those objects that are failing have MeshFilters and not on that layer.

**Comment by dkavolis** [comment]
Oh sorry, the `success` and `fail` should be inverted.

**Comment by ChrisAdderley** [comment]
Ok that's helpful. I will look into the issue in the 3.75m case to see if there are any anomalies, but getting back to the original issues in the first post, what can be done here? It looks certainly like the voxelization is not operating successfully on the parts that are described.

**Comment by dkavolis** [comment]
The voxelization works fine, in the case of `HeatShield2` `fairing.001` and `COLLIDER 1` are unnecessary. I'm trying to add a config key for ignoring specific model transforms right now.

**Comment by ChrisAdderley** [comment]
Hang on I think I might see what's going on here. It's possible that these items have mesh filters but no mesh renderers. Therefore we don't see them in the game or in Unity but I guess FAR sees them. Is there a particular reason why keying off the filters vs the renderers was done?

**Comment by dkavolis** [comment]
The `MeshFilter` components contain the meshes, tried discarding transforms without `MeshRenderer` attached. While it worked for heat shields, it broke some other parts, at least the Mammoth engine (nozzles were no longer voxelized). I can add config value for ignoring transforms without `MeshRenderer` component or ignore specific transforms. Something like
```
@PART[HeatShield2]:AFTER[FerramAerospaceResearch]
{
	@MODULE[GeometryPartModule]
	{
		%ignoreNoRenderer = true // ignore all transforms without MeshRenderer component
		ignoreTransform = fairing.001 // ignore specific transform
		ignoreTransform = COLLIDER 1
	}
}
```

**Comment by dkavolis** [comment]
I've added new nodes to `GeometryPartModule` and included heat shield fixes in FAR since stock heat shields were affected as well. With the new config nodes, engines should be checked and fixed since a lot of them have invisible cones that get voxelized.
See dkavolis/Ferram-Aerospace-Research#37. I will do a release next week when KSP 1.7 ships.

**Comment by dkavolis** [comment]
FYI, this can be closed now, the latest FAR release contains the changes.

**Comment by ChrisAdderley** [comment]
Noted, thank you!
