### ISSUE TITLE
Twin-Boar flag is on wrong side

### ISSUE THREAD

**Issue by LouisB3** [PorktoberRevolution/ReStocked#573]
The stock Twin-Boar has a flag on the "west" side, so that it faces out when placed radially. 

The Restock Twin-Boar has a flag on the "east" side, so that it faces in when placed radially.

**Comment by ChrisAdderley** [comment]
This is so minor it's going in the deferred bin.

**Comment by ChrisAdderley** [comment]
Fixed in `mh-engines-1` branch
