### ISSUE TITLE
Career Mode Bug: "Part model requires entry purchase in R&D" problems with FL-T series.

### ISSUE THREAD

**Issue by paperbw** [PorktoberRevolution/ReStocked#574]
Career Mode

Both the FL-T800 and FL-T100 are blacked out and can't be used to build. It says "Part model requires entry purchase in R&D. When I mouse over the parts it does not give me the button to pay said fee. If I go to R&D complex and pay there, nothing changes. 

However, the FL-T400 and FL-T200 are unlocked, but when moused over, they give the option to pay the entry purchase fee. Paying their fee's change nothing.

Edit: 
Problem does not persist if ReStock is removed from GameData

**Comment by drewcassidy** [comment]
Have you tried deleting the squad folder and reinstalling the game?

**Comment by paperbw** [comment]
That worked. Thank you very much!
