### ISSUE TITLE
Inline Goo Container not recognized for contract completion

### ISSUE THREAD

**Issue by GakkSimian** [PorktoberRevolution/ReStocked#576]
Reached the designated Minmus orbit (target orbit disappeared, and 'maintain orbit' checked) and all but mystery goo was checked off.  Had the inline container on board and was able to 'observe'.

Love the mod.  Thanks for your work.

**Comment by drewcassidy** [comment]
This is currently fixed in the master ready for a 0.1.4 release but hasn’t been released yet. In the meantime you can manually mark the contract completed in the debug menu
