### ISSUE TITLE
Engine Plumes For Making History

### ISSUE THREAD

**Issue by lmtz2000** [PorktoberRevolution/ReStocked#578]
I noticed new, more realistic engine plumes when I installed ReStocked, however, I also realized that the Making History Expansion engines did not get the plume remodel.  I am having issues with realplume engine plumes being too far away from the engine bell (for the mailsail, reliant and skipper engines) if I have both installed, but I wonder if the plumes will be remodeled for those engines?
Thanks

**Comment by drewcassidy** [comment]
I don't believe any of the MH engines are in scope for Restock, sorry. If you're having issues with Realplume there's a version fixed for Restock in [this Pull Request](https://github.com/KSP-RO/RealPlume-StockConfigs/pull/81).
