### ISSUE TITLE
T800 Attachment nodes inside tank

### ISSUE THREAD

**Issue by seconddawn** [PorktoberRevolution/ReStocked#580]
When using the T800 fuel tank the attachment node is about 10% inside the tank itself clipping whatever you attach it to inside the tank.

Unattached no nodes showing:
![image](https://user-images.githubusercontent.com/49457015/55832740-0dece280-5acb-11e9-9c0c-9eea89a55d8f.png)

Attached:
![image](https://user-images.githubusercontent.com/49457015/55832630-cf572800-5aca-11e9-803e-8c01c9df16a3.png)

((edit:  Meant to mention this before.  I LOVE this mod))

**Comment by drewcassidy** [comment]
In your squad folder, delete the `Parts/FuelTank/fuelTankT*` files. Steam doesn’t properly delete old files when you update the game and those get left behind leaving duplicate part configs which confuse the game.

**Comment by seconddawn** [comment]
thanks.  that fixed it.  Interesting that it didn't ear it's ugly head unless restock was installed.  Oh well.

**Comment by ChrisAdderley** [comment]
It is a fairly annoying problem!
