### ISSUE TITLE
Balance updates

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#582]
Need to check some stuff out:
- [x] RS+ RCS parts - update mass and cost for 1.7
- [ ] Examine Pug/Valiant balance , see [here](https://forum.kerbalspaceprogram.com/index.php?/topic/182679-161-restock-revamping-ksps-art-march-15-bugfixes/&do=findComment&comment=3579739)

**Comment by ChrisAdderley** [comment]
251aeb6 has the RCS part updates

**Comment by LouisB3** [comment]
Here are some notes and initial suggested values for the Pug/Valiant. 

Valiant: This is a starter engine and doesn't necessarily need to be "good" compared to other liquid engines. If a Valiant/Pug stack can push a Mk1 capsule into a sub-orbital flight, then it's probably good enough. Later on, it would be nice if this could fill a niche between the Torch and the 1.25m lifting engines.

Pug: This is a vacuum engine that should fall between the Terrier and Spark in that role. Unlike the Valiant, it might have a mid- to late-game role in pushing around satellites etc.

Source | Engine | Thrust (Vac) | ISP Vac | ISP ASL | Mass | Vac TWR | ASL TWR | Cost | Cost/kN Thrust
-- | -- | --: | --: | --: | --: | --: | --: | --: | --:
Stock | Swivel | 215 | 320 | 250 | 1.50 | 14.61 | 11.41 | 1200 | 5.58
Restock+ | Torch | 55 | 295 | 260 | 0.30 | 18.69 | 16.47 | 280 | 5.09
Restock+ | Valiant | 100 | 270 | 240 | 0.75 | 13.59 | 12.08 | 500 | 5.00
Proposed | Valiant | 120 | 285 | 250 | 0.75 | 16.31 | 14.31 | 500 | 4.17
Stock | Terrier | 60 | 345 | 85 | 0.50 | 12.23 | 3.01 | 390 | 6.50
Stock 1.7 | Spark | 20 | 320 | 265 | 0.13 | 15.68 | 12.99 | 240 | 12.00
Restock+ | Pug | 25 | 320 | 150 | 0.20 | 12.74 | 5.97 | 300 | 12.00
Proposed | Pug | 28 | 330 | 120 | 0.20 | 14.27 | 5.19 | 300 | 10.71

**Comment by neistridlar** [comment]
> Valiant: This is a starter engine and doesn't necessarily need to be "good" compared to other liquid engines. 
The Valiant is unlocked at the same node as the torch and the swivel, so it would make sense that they all have their own niches. Other possible solutions: move Torch to a later node or increase the price, closer to Spark, which would leave the Valiant more "Room to breathe", balance wise. It would still be overshadowed by the Swivel for even moderately sized rockets though.

**Comment by LouisB3** [comment]
Agreed. Moving Torch to a later node (near other 0.625m parts) might be easiest and most consistent with stock’s “manned first” balance. 

Valiant is likely to be overshadowed by Swivel no matter what. This was true in PartOverhauls too, even though that pushed the Swivel later one tech node.

**Comment by TykoTek** [comment]
Here's my recommendation:
**Valiant:** no change

**Pug:** no change

**Torch:**
TechRequired = propulsionSystems
mass = 0.29
atmosphereCurve
		{
			key = 0 295
			key = 1 275
			key = 7 0.001
		}

**Comment by Poodmund** [comment]
I not adverse to the above really as the Torch is mainly intended as a lifter. I do think the Pug could have its Isp values changed as per Louis' suggestions to make it a very low thrust, high efficiency Vac engine. It kinda gets overshadowed by the Terrier at the moment even with its extra mass.

**Comment by ChrisAdderley** [comment]
Changes made in dcac5f5

**Comment by TykoTek** [comment]
Confirmed!

Do you want this closed or are there other balance issues you want to address here?

**Comment by ChrisAdderley** [comment]
Nope, I'll close it off.
