### ISSUE TITLE
RCS 105 not using Restock Models

### ISSUE THREAD

**Issue by TheRedTom** [PorktoberRevolution/ReStocked#584]
1.7 issue.
Clean install with only Restock, Restock + and KER.
Probably due to Squad part update in 1.7.
![Screenshot 2019-04-18 at 09 24 04](https://user-images.githubusercontent.com/33154608/56347317-ec22e800-61bb-11e9-9b15-1b40948dcea4.png)

**Comment by TheRedTom** [comment]
It looks so gross, kill it with fire

**Comment by DeltaDizzy** [comment]
Yes, it most likely has a new internal name so restock neither unloads its assets nor replaces them with the proper ones.

**Comment by theonegalen** [comment]
Yep, RCSblock_v2

**Comment by drewcassidy** [comment]
We should probably include patches for both the old and new parts, since the old ones will still be on a lot of vessels

**Comment by GregroxMun** [comment]
This is also true of Spider, Ant, and Twitch in 1.7.

**Comment by ChrisAdderley** [comment]
I'm going to close this as it is captured in #505
