### ISSUE TITLE
24-77 Twitch Attach Point too far from parent part

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#589]
When you attach to another part there's a gap between the base of the part and the parent.

![image](https://user-images.githubusercontent.com/22890228/57187649-20c6bd00-6ea7-11e9-8f1c-949742671af2.png)

**Comment by ChrisAdderley** [comment]
This should be fixed in the latest push

**Comment by Poodmund** [comment]
Yeah, I'm seeing this resolved in the latest commit. I'll let Tyko also confirm it.

**Comment by ChrisAdderley** [comment]
Marking as fixed.
