### ISSUE TITLE
Rockomax Jumbo-64 Variants are in different order than other Rockomax tanks

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#59]
The other three tanks present variants as Orange | Black and White | Metal

The Jumbo-64 lists them as Black and White | Orange | Metal

Not a game-breaker, but might as well be consistent.

![screenshot3](https://user-images.githubusercontent.com/22890228/49343120-d18b1080-f618-11e8-93a2-974cfd3fc3c2.png)

**Comment by ChrisAdderley** [comment]
Fixed in a55d5f8

**Comment by TykoTek** [comment]
Tested and confirmed
