### ISSUE TITLE
RV-105 RCS block - Attach Point too far from parent part

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#592]
The RCS block's attach point is too far out causing the part to sit to far away from the parent.

In the pic below the RV-105 is in the center. Two other RCS blocks are above and below for comparison

![image](https://user-images.githubusercontent.com/22890228/57187742-88313c80-6ea8-11e9-9564-bb6020d59982.png)

**Comment by ChrisAdderley** [comment]
This should be fixed in the latest push

**Comment by Poodmund** [comment]
Seems resolved for me in the latest commit, I'll let Tyko confirm also.

**Comment by ChrisAdderley** [comment]
Marking as fixed.
