### ISSUE TITLE
FL-T100 & FL-T200 duplicated in Technology Tree

### ISSUE THREAD

**Issue by Foqueasy** [PorktoberRevolution/ReStocked#593]
Hello - I looked through the issue list and did not see this mentioned. Once I have Restock installed, I have the FL-T100 and FL-T200 fuel tanks in the technology tree listed twice.

**Comment by Foqueasy** [comment]
Attached log for list of mods and errors - as a test I tried to add the stock tanks in the blacklist file but got the following error;
Line 426: [ERR 00:49:30.801] [Restock] No files found matching url Squad/Parts/FuelTank/fuelTankT100

[KSP.log](https://github.com/PorktoberRevolution/ReStocked/files/3162217/KSP.log)

**Comment by drewcassidy** [comment]
the `fuelTankT*00` directories are actually left over from an older KSP version that don't get removed correctly when updating through Steam, and can be safely deleted. see #581. Next version will put up a warning message to delete those directories

**Comment by ChrisAdderley** [comment]
I've added this particular symptom of the issue to the Common Issues ticket.
