### ISSUE TITLE
RestockPlus generating invalid metadata

### ISSUE THREAD

**Issue by HebaruSan** [PorktoberRevolution/ReStocked#595]
The latest release has a minimum version greater than the maximum version, which I think will mean it can never be installed:

https://github.com/KSP-CKAN/CKAN-meta/commit/b4bed212b7292dbde4a6e6b90e181d88c7961ea7

```json
    "ksp_version_min": "1.7.0",
    "ksp_version_max": "1.6.99",
```

**Comment by drewcassidy** [comment]
fixed in 1a004493a

**Comment by Poodmund** [comment]
The RS+ distribution package needs to be repackaged and uploaded as I think CKAN looks directly at the version file in the .zip(???).

**Comment by HebaruSan** [comment]
Or you could update this copy as well:

https://raw.githubusercontent.com/PorktoberRevolution/ReStocked/prod/Distribution/RestockPlus/GameData/ReStockPlus/Versioning/ReStockPlus.version

**Comment by Poodmund** [comment]
Fixed in the latest build of RS+ deployed to the 1.4.0 release. Thanks for the heads-up, HebaruSan.
