### ISSUE TITLE
Bug with model of RA-100 relay antenna

### ISSUE THREAD

**Issue by Iasus** [PorktoberRevolution/ReStocked#608]
There's a white blob floating above the model of the RA-100 relay antenna, disconnected from the rest of the model.

![screenshot73](https://user-images.githubusercontent.com/5116159/58370476-e6c56580-7efe-11e9-934c-8999a005c1e3.png)

**Comment by ChrisAdderley** [comment]
![screenshot36](https://user-images.githubusercontent.com/5642064/58372542-c502b900-7ed3-11e9-85f7-f28c58e6447b.png)
I don't see this in a basic install, do you have IndicatorLights installed?

**Comment by Iasus** [comment]
Yes, I have IndicatorLights and IndicatorLights Community Extensions installed.

I removed both and the issue disappeared:

![screenshot74](https://user-images.githubusercontent.com/5116159/58372751-3d8c6880-7f1a-11e9-88df-a69746e6a108.png)

**Comment by ChrisAdderley** [comment]
Yeah, that blob is the indicator light for the antenna. Since the stock model is different, it would need to be in a somewhat different position.
We kinda have it on the list to address with Snark eventually but it will take time and it's low priority.

**Comment by Iasus** [comment]
Thanks for chasing it, man.  You're doing great work, I love Restock.
