### ISSUE TITLE
IndicatorLights issues

### ISSUE THREAD

**Issue by Gordon-Dry** [PorktoberRevolution/ReStocked#610]
See
https://forum.kerbalspaceprogram.com/index.php?/topic/137806-171-indicatorlights-v15-small-convenient-informative/&do=findComment&comment=3610389

The most relevant excerpt:
> I edit every Restock .cfg to add the :FIRST directive to each part. I think this should have been done by the Restock team. This will take care of the IL patch ordering issue, but ...

**Comment by drewcassidy** [comment]
This has already been discussed and has to be fixed in indicatorlights
