### ISSUE TITLE
1875 Reaction Wheel - localization text 

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#622]
The descriptive text for the 1875 reaction wheel isn't showing properly

![image](https://user-images.githubusercontent.com/22890228/59149082-00b67c00-89c6-11e9-8885-e171008c99be.png)

**Comment by ChrisAdderley** [comment]
Fixed in bf07033

**Comment by drewcassidy** [comment]
Confirmed
