### ISSUE TITLE
Kelus & Kelus LV Mobility Enhancer - Root Part visible in open ladder bay

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#623]
In many placements you can still see the root part within the open ladder bay.

![image](https://user-images.githubusercontent.com/22890228/59149113-5d199b80-89c6-11e9-888c-9adb41764c62.png)

**Comment by ChrisAdderley** [comment]
This is going to be investigated in #628 so I'm going to close it.
