### ISSUE TITLE
FL-X220 1875 Tank - seam in texture

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#624]
There's a seam visible on both sides of the tank

![image](https://user-images.githubusercontent.com/22890228/59149148-ed57e080-89c6-11e9-965e-0d14552f2d97.png)

**Comment by ChrisAdderley** [comment]
Fixed in `mh-engines-1` branch

**Comment by ChrisAdderley** [comment]
Ready to test in `develop`

**Comment by TykoTek** [comment]
Confirmed
