### ISSUE TITLE
FL-R4 - Texture pattern issue

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#625]
In the repeating checkerboard pattern one of the squares is too thin. This occurs 4 times around the edge

![image](https://user-images.githubusercontent.com/22890228/59149266-45dbad80-89c8-11e9-8e44-da0a56b4032b.png)

**Comment by ChrisAdderley** [comment]
Fixed in `mh-engines-1` branch

**Comment by ChrisAdderley** [comment]
Ready to test in `develop`

**Comment by TykoTek** [comment]
Fixed
