### ISSUE TITLE
Oscar-A Liquid Tank - Texture Issues

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#626]
3 items - 
1) There's a strange seam line running the circumference of the tank right around the centerline that's only visible from certain angles.

![image](https://user-images.githubusercontent.com/22890228/59149328-019cdd00-89c9-11e9-98b0-f79614dc0749.png)

2) There's a shadowy X shape showing up

![image](https://user-images.githubusercontent.com/22890228/59149337-26915000-89c9-11e9-9474-cbd580e397b8.png)

3) The entire tank texture seems rotated 45 degrees and the panel lines don't line up with those on the Oscar- B

![image](https://user-images.githubusercontent.com/22890228/59149366-49236900-89c9-11e9-82db-ad5e7b803db1.png)

**Comment by Poodmund** [comment]
2 and 3 have been resolved but there still seems to be a weird join in the mesh around the centre loop cut on the main cylinder.

![Untitled-1](https://user-images.githubusercontent.com/10106634/67591802-24504800-f756-11e9-8570-a09b61ba4681.png)

**Comment by ChrisAdderley** [comment]
Fixed in the expedient way, by redoing it completely, in 31de344ede64b44cef24426a4962b2ad62b85910.

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/31de344ede64b44cef24426a4962b2ad62b85910
