### ISSUE TITLE
RC-M001 - Attach nodes not centered

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#627]
The nodes are off a bit leaving the part un-centered in a stack

![image](https://user-images.githubusercontent.com/22890228/59149463-2f365600-89ca-11e9-9e5a-f188f24453d3.png)

**Comment by ChrisAdderley** [comment]
Fixed in `mh-engines-1` branch

**Comment by ChrisAdderley** [comment]
Ready to test in `develop`

**Comment by TykoTek** [comment]
Fixed
