### ISSUE TITLE
Investigate occlusion tweaks on various parts

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#628]
Investigate the follwing shortlist of parts to see if the new occlusion technique is suitable for use in them:

- [x] Pegasus I Mobility Enhancer
- [x] Kelus Mobility Enhancer
- [x] Kelus-LV Bay Mobility Enhancer
- [x] RV-102 RCS Thruster Block
- [x] RV-103 RCS Thruster Block
- [x] RV-105 RCS Thruster Block
- [x] RV-105-A RCS Thruster Block
- [x] RV-105-XL RCS Thruster Block
- [x] RC-12 RCS Thruster Block
- [x] RC-13 RCS Thruster Block
- [x] RC-14 RCS Thruster Block
- [x] RC-14-A RCS Thruster Block
- [x] RC-15 RCS Thruster Block
- [x] RC-12 RCS Thruster Block
- [x] RC-1 RCS Linear RCS Port
- [x] Place-Anywhere 7 Linear RCS Port
- [x] Vernor Engine
- [x] Mk2-R Radial-Mount Parachute
- [x] Mk12-R Radial-Mount Drogue Chute
- [x] Separatron I
- [x] OX-4L 1x6 Photovoltaic Panels
- [x] OX-4W 1x6 Photovoltaic Panels

**Comment by drewcassidy** [comment]
<img width="428" alt="Screen Shot 2019-06-10 at 3 04 37 PM" src="https://user-images.githubusercontent.com/3837797/59230051-14faa480-8b91-11e9-846d-539cb5d8e830.png">
The puff could be another good candidate

**Comment by ChrisAdderley** [comment]
All good now for this batch.
