### ISSUE TITLE
Pegasus II and III: Colliders are too small

### ISSUE THREAD

**Issue by drewcassidy** [PorktoberRevolution/ReStocked#629]
The colliders not he Pegasus II and III appear to be the same size as the stock part, making them hard to select in the VAB

**Comment by ChrisAdderley** [comment]
They're certainly bigger, but they're only doubled/quadrupled. This may not be enough because the original middle collider is basically a tiny bit.

**Comment by ChrisAdderley** [comment]
Ready to test

**Comment by drewcassidy** [comment]
Looks better. closing
