### ISSUE TITLE
Depth mask errors on linear RCS 

### ISSUE THREAD

**Issue by drewcassidy** [PorktoberRevolution/ReStocked#631]
<img width="672" alt="Screen Shot 2019-06-13 at 3 23 31 PM" src="https://user-images.githubusercontent.com/3837797/59471183-3658cc00-8def-11e9-947e-0552ec45e1a1.png">
<img width="587" alt="Screen Shot 2019-06-13 at 3 21 44 PM" src="https://user-images.githubusercontent.com/3837797/59471307-8df73780-8def-11e9-890c-23521f09e596.png">

<img width="274" alt="Screen Shot 2019-06-13 at 3 24 06 PM" src="https://user-images.githubusercontent.com/3837797/59471208-4b355f80-8def-11e9-84a8-a41336974cc1.png">

The mask on the linear RCS is shaped as a conic frustum, when it should really be shaped as two circles. 
how it should be shaped: 
<img width="830" alt="Screen Shot 2019-06-13 at 3 25 18 PM" src="https://user-images.githubusercontent.com/3837797/59471263-7750e080-8def-11e9-8ab1-2ec8e319b44a.png">

There is also the issue shared with all RCS using the masks right now where the particle effects are inside the masked area. its not very obvious but if its possible I think the particle emitters should be moved further out

**Comment by ChrisAdderley** [comment]
Fixed in `mh-engines-1` branch

**Comment by ChrisAdderley** [comment]
Ready to test in `develop`

**Comment by drewcassidy** [comment]
<img width="364" alt="Screen Shot 2019-06-29 at 2 38 37 PM" src="https://user-images.githubusercontent.com/3837797/60389710-9dc37c80-9a7b-11e9-9092-9df0848b49c3.png">
still slightly offset on the bare variant, otherwise fixed

**Comment by ChrisAdderley** [comment]
Should be fixed completely as of feefaed1f44f48d0dd14f44c675d6229ab927e88
