### ISSUE TITLE
Gigantor XL Solar Array - Multiple collider issues

### ISSUE THREAD

**Issue by drewcassidy** [PorktoberRevolution/ReStocked#633]
• The colliders on the Gigantor are oversized when retracted
• ~~They are mesh colliders instead of box colliders (might not be a problem)~~
• The collider for the panels themselves doesn't animate at the same speed as the end collider, forming a gap as it animates
<img width="974" alt="Screen Shot 2019-06-15 at 2 15 09 PM" src="https://user-images.githubusercontent.com/3837797/59556488-fe30c500-8f77-11e9-9e5f-56e6364656c3.png">

**Comment by ChrisAdderley** [comment]
Fixed in `mh-engines-1` branch

**Comment by ChrisAdderley** [comment]
Ready to test in `develop`
