### ISSUE TITLE
RV-105 RCS Thruster Block - missing mask mesh

### ISSUE THREAD

**Issue by drewcassidy** [PorktoberRevolution/ReStocked#634]
the RV-105 RCS thruster block is missing the referenced `4mask` object throwing errors. if we're going to keep the masks on the RCS thrusters this will have to be fixed

**Comment by ChrisAdderley** [comment]
Fixed in `mh-engines-1` branch

**Comment by ChrisAdderley** [comment]
Ready to test in `develop`
