### ISSUE TITLE
FL-151L Fuel tank adapter, Incorrect variants.

### ISSUE THREAD

**Issue by omega489** [PorktoberRevolution/ReStocked#641]
### Branch: 
Develop, Making History 

### Issue: 
FL-151L Fuel tank adapter (Adapter - 1.875 to 1.25m Long) from the making history parts has a variants issue. Multiple variants z-fight in all variants of the part.

### Cause: 
In cfg file "restock-mh-fueltanks-1875.cfg" there are some incorrect mesh names and one instance of two meshes enabled by mistake. Lines 403-450.

> MODULE
>   {
>     name = ModulePartVariants
>     useMultipleDragCubes = false
>     baseVariant = White
>     VARIANT
>     {
>       name = White
>       displayName = #autoLOC_8007122
>       themeName = BlackAndWhite
>       primaryColor = #ffffff
>       secondaryColor = #000000
>       GAMEOBJECTS
>       {
>       	1875-125Long = true
>       	1875-125**GreyLong** = false
>       	1875-125**OrangeLong** = **true**
>       }
>     }
>     VARIANT
>     {
>       name = Grey
>       displayName = #autoLOC_8007119
>       themeName = White
>       primaryColor = #ffffff
>       secondaryColor = #ffffff
>       GAMEOBJECTS
>       {
>       	1875-125Long = false
>       	1875-125**GreyLong** = true
>       	1875-125**OrangeLong** = false
>       }
>     }
>     VARIANT
>     {
>       name = Dark Grey
>       displayName = #autoLOC_8007121
>       themeName = GrayAndOrange
>       primaryColor = #4c4f47
>       secondaryColor = #f49841
>       GAMEOBJECTS
>       {
>       	1875-125Long = false
>       	1875-125**GreyLong** = false
>       	1875-125**OrangeLong** = true
>       }
>     }
>   }

### Fix:

Changes the mesh names from "GreyLong" to "LongGrey" etc. for all offending meshes.

> MODULE
>   {
>     name = ModulePartVariants
>     useMultipleDragCubes = false
>     baseVariant = White
>     VARIANT
>     {
>       name = White
>       displayName = #autoLOC_8007122
>       themeName = BlackAndWhite
>       primaryColor = #ffffff
>       secondaryColor = #000000
>       GAMEOBJECTS
>       {
>       	1875-125Long = true
>       	1875-125LongGrey = false
>       	1875-125LongOrange = false
>       }
>     }
>     VARIANT
>     {
>       name = Grey
>       displayName = #autoLOC_8007119
>       themeName = White
>       primaryColor = #ffffff
>       secondaryColor = #ffffff
>       GAMEOBJECTS
>       {
>       	1875-125Long = false
>       	1875-125LongGrey = true
>       	1875-125LongOrange = false
>       }
>     }
>     VARIANT
>     {
>       name = Dark Grey
>       displayName = #autoLOC_8007121
>       themeName = GrayAndOrange
>       primaryColor = #4c4f47
>       secondaryColor = #f49841
>       GAMEOBJECTS
>       {
>       	1875-125Long = false
>       	1875-125LongGrey = false
>       	1875-125LongOrange = true
>       }
>     }
>   }

**Comment by ChrisAdderley** [comment]
Fixed in `develop`, good find, unfortunately I don't have MH so have trouble testing the patched versions.

**Comment by ChrisAdderley** [comment]
Let me know if this is confirmed resolved.

**Comment by omega489** [comment]
I can confirm it is resolved.
