### ISSUE TITLE
RE-I2 "Skiff" engine shroud and plume issues.

### ISSUE THREAD

**Issue by omega489** [PorktoberRevolution/ReStocked#643]
### Branch:
Develop, Making History

### Issue 1:
RE-I2 "Skiff" engine has a shroud enabled with the "shrouded" and "1.875" variants that interferes with the stock auto-shroud. This results in some z-fighting and a shroud appearing over the existing shroud.
[Gif included for issue behavior](https://gfycat.com/icyscrawnyiberianemeraldlizard)

### Issue 2:
RE-I2 "Skiff" engine plume is always showing in the flight scene. Even when the engine has not been activated.

[Gif included](https://gfycat.com/tightmisguidedcamel)

**Comment by omega489** [comment]
Issue 1 has been fixed in the latest commit. Issue 2 persists.

**Comment by ChrisAdderley** [comment]
Should be resolved in f1354e7461266481798b022b6b495d674b6a24c0

**Comment by omega489** [comment]
Confirmed to be fixed in the latest dev branch.
