### ISSUE TITLE
RK-7 "Kodiak" engine, shroud boattail issues

### ISSUE THREAD

**Issue by omega489** [PorktoberRevolution/ReStocked#644]
### Branch:
Develop, Making History

### Issue:
RK-7 "Kodiak" engine has a double ring of permanently enabled shrouds around the engine bells irrespective of the variant. Results in some z-fighting.

[Gif of issue behavior ](https://gfycat.com/highminorbeauceron)

**Comment by ChrisAdderley** [comment]
Try the latest commit. Hard to see what might be wrong (the RS+ versions of these engines work fine) but maybe force deleting all the old models will work.

**Comment by omega489** [comment]
Tried the latest commit, Can confirm that the shrouds and boattails are working correctly. :)
