### ISSUE TITLE
MH 1.875 heat shield shroud issues.

### ISSUE THREAD

**Issue by omega489** [PorktoberRevolution/ReStocked#645]
### Branch: 
Develop, Making History 

### Issue: 
Heat Shield (1.875m) has a permanently enabled shroud.

### Cause: 
Likely missing ModuleJettison in "restock-mh-heat-shields.cfg"

### Fix:
Fixed on my end by including:
	

> MODULE
> 	{
> 		name = ModuleJettison
> 		jettisonName = HeatShield1875Fairing
> 		bottomNodeName = bottom
> 		isFairing = True
> 		jettisonedObjectMass = 0.5
> 		jettisonForce = 15
> 		jettisonDi rection = 0 0 1
> 		stagingEnabled = False
> 		checkBottomNode = True
> 	}	

Values are taken from the vanilla MH 1.875 heatshield.

**Comment by ChrisAdderley** [comment]
Actually needs model changes to not break existing shields.

**Comment by ChrisAdderley** [comment]
Merged to `develop`
