### ISSUE TITLE
RE-J10 "Wolfhound" Plume Issue

### ISSUE THREAD

**Issue by omega489** [PorktoberRevolution/ReStocked#646]
### Branch: 
Develop, Making History 

### Issue: 
RE-J10 "Wolfhound" plume is permanently enabled in the flight scene (i.e. the plume is active before the engine is activated and ignores throttle control). This issue is similar to the issue seen in the "skiff" engine.

**Comment by ChrisAdderley** [comment]
feefaed1f44f48d0dd14f44c675d6229ab927e88 has a fix.

**Comment by ChrisAdderley** [comment]
Merged to `develop`
