### ISSUE TITLE
3.75m Battery - No surface attach

### ISSUE THREAD

**Issue by AmpCat** [PorktoberRevolution/ReStocked#648]
The 3.75 battery can't be surface mounted to, unlike all of the other battery sizes.

**Comment by ChrisAdderley** [comment]
Fixed in 957cad1 (`develop`).

**Comment by Poodmund** [comment]
Disabled srfAttach and enabled allowSrfAttach, fixed and merged in https://github.com/PorktoberRevolution/ReStocked/pull/691
