### ISSUE TITLE
Thermal emissive blocker

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#651]
Create a module that disables the KSP basic 'overheat' glow on parts that have their own overheat animations.

**Comment by drewcassidy** [comment]
the `ModuleRestockHeatEffects` I wrote for the ISRUs does this as well as fixing some bugs I encountered with the stock colorchanger module

**Comment by ChrisAdderley** [comment]
Added in d21f4af4b221e334320635cd1ce7c7134865d7a2
