### ISSUE TITLE
[Restock+] Z-10K Battery available before Z-4K in the tech tree

### ISSUE THREAD

**Issue by xot1643** [PorktoberRevolution/ReStocked#652]
Z-10K is unlocked with High-Powered Electrics (lvl 7).
Z-4K is unlock with Specialized Electrics (lvl 8).
It would make sense that Z-10K be available with Z-4K or even one step further in the tech tree i.e. Experimental Electrics with RTGs (lvl 9).

Sorry if I missed something.

**Comment by ChrisAdderley** [comment]
Good catch.

**Comment by ChrisAdderley** [comment]
Addressed in `1-8-updates` branch

**Comment by Poodmund** [comment]
Fixed as of this time, also 2.5k battery moved to High-Powered Electrics (lvl 7) node.
