### ISSUE TITLE
Modular Girder Adapter: Top mounting surface is not centered 

### ISSUE THREAD

**Issue by drewcassidy** [PorktoberRevolution/ReStocked#654]
<img width="476" alt="Screen Shot 2019-08-30 at 10 58 31 PM" src="https://user-images.githubusercontent.com/3837797/64059902-c64e1c80-cb79-11e9-8642-e16fc51358b7.png">

**Comment by ChrisAdderley** [comment]
Fixed with feefaed1f44f48d0dd14f44c675d6229ab927e88
