### ISSUE TITLE
RE-J10 "Wolfhound": normal/specularity problem

### ISSUE THREAD

**Issue by drewcassidy** [PorktoberRevolution/ReStocked#665]
<img width="619" alt="Screen Shot 2019-09-22 at 10 45 24 PM" src="https://user-images.githubusercontent.com/3837797/65403877-d4631780-dd8a-11e9-805b-75644b0b6a30.png">
<img width="533" alt="Screen Shot 2019-09-22 at 10 17 34 PM" src="https://user-images.githubusercontent.com/3837797/65403876-d3ca8100-dd8a-11e9-8bd5-686c425b947f.png">
This is the RS+ version (MH is not installed) if it matters. some areas appear differently lit from others in the "classic" variant

**Comment by ChrisAdderley** [comment]
Was vertex colour issue, fixed in ed9f6232f69505bd6d8d6b69f9d726de4200e711
