### ISSUE TITLE
LV-N410 "Cherenkov" Issues (model and cfg)

### ISSUE THREAD

**Issue by omega489** [PorktoberRevolution/ReStocked#667]
Branch: Restock +
Part: LV-N410 "Cherenkov"

Issue 1: Incorrectly uses oxidizer as a propellant.

![image](https://user-images.githubusercontent.com/23028378/65518717-a4c42480-dedc-11e9-99f2-79e8e29515fc.png)

Issue2: Model has interesting seams as If the mesh edges aren't joined?
Very evident when the part is highlighted, but it is still visible in the unhighlighted model.

![image](https://user-images.githubusercontent.com/23028378/65518632-84946580-dedc-11e9-9610-dd4fb4c62d6a.png)

**Comment by ChrisAdderley** [comment]
Fixed in b524c82cf88c3eba26ad10ef2338152803c115a0

**Comment by ChrisAdderley** [comment]
Merged to `develop`
