### ISSUE TITLE
Aerodynamic nosecone: collider rotated 15°

### ISSUE THREAD

**Issue by drewcassidy** [PorktoberRevolution/ReStocked#675]
<img width="514" alt="Screen Shot 2019-10-07 at 5 33 37 PM" src="https://user-images.githubusercontent.com/3837797/66358647-9dfbcf80-e928-11e9-983b-d480a23c5ad9.png">

compared to the stock collider, the restock Aerodynamic Nosecone collider is rotated 15°

**Comment by ChrisAdderley** [comment]
Addressed in `1-8-updates` branch

**Comment by ChrisAdderley** [comment]
Merged to `develop`
