### ISSUE TITLE
Small claw radial attachment is backwards

### ISSUE THREAD

**Issue by GregroxMun** [PorktoberRevolution/ReStocked#678]
Attempting to place the small claw radially to a surface will have the claw facing inwards and the mounting plate facing outwards.

![image](https://user-images.githubusercontent.com/9667986/67161098-36c91c80-f325-11e9-8fc3-51cf3a463515.png)

**Comment by drewcassidy** [comment]
fixed in 663f57b7e76cb200517dde327a7d0386252dfc75

**Comment by ChrisAdderley** [comment]
Confirmed fixes
