### ISSUE TITLE
Experiment Return Unit description mismatch

### ISSUE THREAD

**Issue by Duck1998** [PorktoberRevolution/ReStocked#680]
https://github.com/PorktoberRevolution/ReStocked/blob/bf465c5ac067a4e029e1b39fbdea2ddb67749425/Distribution/RestockPlus/GameData/ReStockPlus/Parts/Science/restock-sciencebox-stack-1.cfg#L25
should be `#LOC_RestockPlus_restock-sciencebox-inline-1_description`

**Comment by ChrisAdderley** [comment]
Fixed with 40f926a7e0b03883d4ceab0ddd0fcb5463d3450f
