### ISSUE TITLE
[BUG] Kerbodyne S3-3600 nosecone model issues.

### ISSUE THREAD

**Issue by omega489** [PorktoberRevolution/ReStocked#682]
**Branch: Develop**

Issue:

Both variants are showing at the same time. The bulkhead is separated from the nosecone mesh.

![image](https://user-images.githubusercontent.com/23028378/67384911-fa4a2a80-f589-11e9-8887-1e348bc37bbc.png)

**Comment by Duck1998** [comment]
The lastest branch is _master_ and the S3-3600 nosecone  works fine.

**Comment by omega489** [comment]
Ah Okay, no issue here then.
