### ISSUE TITLE
S2-17 "Thoroughbred" Solid Fuel Booster - Texture Issues

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#685]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67512895-b0e50280-f691-11e9-8c75-88fd139560b7.png)

Weird banding transition at the top of the booster.

![Untitled-2](https://user-images.githubusercontent.com/10106634/67512909-b3dff300-f691-11e9-8563-6df33427f72f.png)

Small erroneous 'dot' featured on the underside of the side-pods.

**Comment by Poodmund** [comment]
Just noticed the small 'dot on underside of side-pod' blemish appears on the S2-33 "Clydesdale" Solid Fuel Booster also.

**Comment by ChrisAdderley** [comment]
Fixed in ca3293a

**Comment by Poodmund** [comment]
Checked and fixed in ca3293a
