### ISSUE TITLE
S2-17 "Thoroughbred" & S2-33 "Clydesdale" - Hole in mesh

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#687]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67513656-30bf9c80-f693-11e9-989c-c0b1c146d9b5.png)

On both new big SRBs, there is a portion on the inside of both of the side pods where you can see through the mesh.

**Comment by ChrisAdderley** [comment]
Fixed in ca3293a

**Comment by Poodmund** [comment]
Checked and fixed in ca3293a
