### ISSUE TITLE
S2-33 "Clydesdale" Solid Fuel Booster - FX Issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#688]
https://youtu.be/zuqH7qAHX30

When the booster has flamed out and run out of fuel, there is particle FX being emitted 90 degrees out of the side of the bell.

**Comment by ChrisAdderley** [comment]
Fixed in ca3293a

**Comment by Poodmund** [comment]
Checked and fixed in ca3293a
