### ISSUE TITLE
Vector SSME autoshroud issues with compact variant.

### ISSUE THREAD

**Issue by zorg2044** [PorktoberRevolution/ReStocked#689]
When the compact variant of the SSME is chosen, the autoshroud appears even when there is nothing attached. 

The behavior is inconsistent, launching, reverting and relaunching even the same craft with no change often results in the autoshrouds appearing on different engines.

Only reproduced with compact variant.

reproduced with current master 25/Oct/2019 on KSP 1.8 clean and has been encountered on 1.7.3 on a heavily modded game.

launched

![Screenshot 2019-10-25 00 24 40](https://user-images.githubusercontent.com/39182212/67518636-9d03c580-f6be-11e9-95df-076f50baf609.png)

revert and relaunch without touching anything else.

![Screenshot 2019-10-25 00 24 59](https://user-images.githubusercontent.com/39182212/67518654-a42ad380-f6be-11e9-8850-66a5bac0f7e9.png)

**Comment by ChrisAdderley** [comment]
Fixed in ca3293a
