### ISSUE TITLE
TVR-300L Stack Tri-Adapter - Model 180 degrees rotated 

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#690]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67526230-43929b00-f6ac-11e9-8d51-db6e83802321.png)

The model and collider mesh seem to be rotated 180 degrees off the Stock rotation. This is shown in the screenshot above and I checked both colliders in DebugStuff.

**Comment by drewcassidy** [comment]
Addressed in 32dabd30531a86a122dcabedc4bfccd27b412285

**Comment by Poodmund** [comment]
Fixed with 32dabd3
