### ISSUE TITLE
Modular Girder Segment XL - Attachment Issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#692]
I'm not sure if its a model issue or node placement issue but the Vanilla part seems to align so that there is no gap at the joint whereas the ReStock version has a gap between the part connection.

![Untitled-1](https://user-images.githubusercontent.com/10106634/67597339-dbeb5700-f762-11e9-9a80-75966629e61f.png)

![Untitled-2](https://user-images.githubusercontent.com/10106634/67597351-df7ede00-f762-11e9-9598-22e9c3b3fa5f.png)

![Untitled-3](https://user-images.githubusercontent.com/10106634/67597361-e1e13800-f762-11e9-976b-50633c2ce076.png)

It does stand off slightly from a completely flat surface; you can just about see the water tower through the gap.

![Untitled-4](https://user-images.githubusercontent.com/10106634/67597515-50be9100-f763-11e9-8271-a70146bfe204.png)

**Comment by ChrisAdderley** [comment]
Moved slightly in ea39b490a30d8f6a0a272b255b6914ac898a2374

**Comment by Poodmund** [comment]
Resolved with ea39b49
