### ISSUE TITLE
Radiator Panel (edge) - Model aesthetics issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#694]
The connecting struts clip into the parent part, as do the ones on the stock part, which is fine but on the ReStock model there are radiator pipes that traverse along the part down onto these strut regions which as a result are clipped into the parent part. I would suggest that maybe this greeble is moved upwards slightly so it does not clip halfway into the parent part. Finally, on one side, this radiator greeble seems offset on the strut and not centered.

![Untitled-1](https://user-images.githubusercontent.com/10106634/67619597-71cfc200-f7f5-11e9-9e65-7ae9473ba58d.png)

**Comment by ChrisAdderley** [comment]
Fixed in 819dc8a500316c62b2851d46022757c2d774ad82.

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/819dc8a500316c62b2851d46022757c2d774ad82
