### ISSUE TITLE
Radiator Panel (small/large) - Compact/Flat mount variant model issues

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#695]
The mounting truss structure for the 'Compact' variant of the small and large radiator parts doesn't seem to align well with the parent part at larger radii or small radii (it also sinks in a lot on a flat surface but that's why the flat mount variant exists so its not really an issue). Maybe it would be better to move the base of the mount outwards slightly towards to radiator panel so that it doesn't clip into the parent part as much.

![Untitled-1](https://user-images.githubusercontent.com/10106634/67620644-0db2fb00-f801-11e9-911c-ed33c9f0b1fe.png)

![Untitled-2](https://user-images.githubusercontent.com/10106634/67620651-13104580-f801-11e9-82f1-a2617b994ff3.png)

![Untitled-3](https://user-images.githubusercontent.com/10106634/67620652-160b3600-f801-11e9-8ca5-feee322b1c22.png)

![Untitled-4](https://user-images.githubusercontent.com/10106634/67620653-17d4f980-f801-11e9-97a3-5279f9719bb9.png)

![Untitled-5](https://user-images.githubusercontent.com/10106634/67620654-199ebd00-f801-11e9-9a52-0023fe60011a.png)

The above screenshots show the small radiator part but the same persists for the large version too.

Secondly, the large radiator's 'Flat' variant doesn't join to its parent part and is offset away from it. It only has a mount truss structure at one end of the radiator, I'm not sure if it was supposed to be also mirrored to the other end.

![Untitled-1](https://user-images.githubusercontent.com/10106634/67620798-91b9b280-f802-11e9-9536-9d504dea36df.png)

**Comment by ChrisAdderley** [comment]
Adjusted in 819dc8a500316c62b2851d46022757c2d774ad82.

**Comment by Poodmund** [comment]
All resolved with https://github.com/PorktoberRevolution/ReStocked/commit/819dc8a500316c62b2851d46022757c2d774ad82 .

The compact variant mounts look great now and the connections work well. The flat variant for the large radiator's connection against a flat surface is still 'floating' above the parent part but as we discussed elsewhere, these variants are intended to be options above the default variant that the user can then move around.
