### ISSUE TITLE
Kelus & Kelus-LV Bay Mobility Enhancer - Model structure issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#696]
With the addition of ModuleDepthMask the internal structure of the two animated ladders float within the housing shroud.

![Untitled-1](https://user-images.githubusercontent.com/10106634/67621969-0bef3480-f80d-11e9-8aa8-44ab92c49a9f.png)

**Comment by ChrisAdderley** [comment]
Fixed in 819dc8a500316c62b2851d46022757c2d774ad82.

**Comment by Poodmund** [comment]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67632505-e1988800-f89b-11e9-8340-d949382b497c.png)

![Untitled-2](https://user-images.githubusercontent.com/10106634/67632506-e3fae200-f89b-11e9-95d6-8b3f6a5db9ec.png)

One thing I didn't spot was that, I think, the ModuleDepthMask is causing rendering issues as you can see through the parts.

**Comment by ChrisAdderley** [comment]
d440bdcbab0032d16c2f4d8f1d39a0e9a393379c Fixed

**Comment by Poodmund** [comment]
Looking in-game and at the commit history, I don't think any changes were pushed to the Kelus-LV longer ladder at: GameData\ReStock\Assets\Utility\restock-ladder-extending-2.mu

**Comment by ChrisAdderley** [comment]
![screenshot18](https://user-images.githubusercontent.com/5642064/67710347-04e73400-f97d-11e9-9d91-0290daf4cef5.png)
Current master for me looks fine

**Comment by Poodmund** [comment]
Removed both RS and RS+ folders, MM cache files and PartDatabase file just for thoroughness. Still seeing the Depth Mask further out than it should be. You have to put the camera to quite an oblique angle to see it. Its easier to maneuver the camera in flight mode as you can focus the camera on that part.

![Untitled-1](https://user-images.githubusercontent.com/10106634/67711989-020b3400-f9bb-11e9-9858-f374d77f9636.png)

**Comment by ChrisAdderley** [comment]
1b6940843be848c5cd4031550da1cff6e1feb71d tried reexporting it again, got a different model file so maybe now?

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/1b6940843be848c5cd4031550da1cff6e1feb71d
