### ISSUE TITLE
Convert-O-Tron 125 - Emissive Texture Issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#698]
It seems that the UV layout for the grill portion pulls the easter egg contained within the emissive texture. 🤦‍♂  

![Untitled-1](https://user-images.githubusercontent.com/10106634/67625631-6fdb2280-f838-11e9-9b54-afbb3b61c629.png)

Haha, I'm not sure this is entirely as intended.

**Comment by drewcassidy** [comment]
Should be fixed with 64f21b12cc1d5b2ff904c87c5a79de96aa30ff0d

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/64f21b12cc1d5b2ff904c87c5a79de96aa30ff0d
