### ISSUE TITLE
FL-C1000 Fuel Tank - No particle FX or sound when in-built separator SRBs fire.

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#699]
These are the Soyuz-like side-tanks that have the in-built SRB located at the inside, top of the part. When firing the SRB there doesn't seem to be any particle FX or sound triggered.

The thrust transform and engine seem to be firing (albeit very weakly, but thats a stock issue).

**Comment by ChrisAdderley** [comment]
Fixed in 819dc8a500316c62b2851d46022757c2d774ad82 - RS+ version did not have changes propagated to the MH version.

**Comment by Poodmund** [comment]
https://www.youtube.com/watch?v=O3YB7ljxBfE

It seems the flameout FX on the lower nozzle are resolved but the running particle effect is not scaling properly.

On the top nozzle, there is no flameout effect and the running particle is also not scaling properly.

The sound effects seem to be working as intended.

**Comment by ChrisAdderley** [comment]
Created new FX, removed Squad garbage, also applied to RS+ version in d440bdcbab0032d16c2f4d8f1d39a0e9a393379c

**Comment by Poodmund** [comment]
The firing FX are sorted now. The top motor doesn't have flameout FX and the bottom flameout FX seem a little large but not sure that they can be scaled anyway(?)

https://youtu.be/htmW_5O4ER4

**Comment by ChrisAdderley** [comment]
Killed the flameout fx in 910b4a485267eb7423f253d839f7c9b6ab4b3035

**Comment by Poodmund** [comment]
Much nicer, resolved with https://github.com/PorktoberRevolution/ReStocked/commit/910b4a485267eb7423f253d839f7c9b6ab4b3035
