### ISSUE TITLE
Inside of linear RCS port clips into attached surface

### ISSUE THREAD

**Issue by blowfishpro** [PorktoberRevolution/ReStocked#70]
Of course you can offset it, but shouldn't the inside of the nozzle not clip into this surface at the default attachment?
![screenshot24](https://user-images.githubusercontent.com/10545461/49920981-e9f0fb80-fe60-11e8-8dec-86032c22963d.png)

**Comment by ChrisAdderley** [comment]
Mitigation applied in b9796bd

**Comment by blowfishpro** [comment]
Does appear to be fixed, thanks!
