### ISSUE TITLE
ModuleDepthMask Issue - Depth Masks not rendering correctly.

### ISSUE THREAD

**Issue by omega489** [PorktoberRevolution/ReStocked#700]
Branch: Master

Issue: Grey box inside the panel housing is causing unsightly z-fighting. Possible that something in the model is visible when it shouldn't be?

![image](https://user-images.githubusercontent.com/23028378/67678675-2517f280-f97f-11e9-9cce-cf53276e29db.png)

**Comment by Poodmund** [comment]
I cannot reproduce, using https://github.com/PorktoberRevolution/ReStocked/commit/5b8395824e916b56d409a81de0e780e88566b24c

![Untitled-1](https://user-images.githubusercontent.com/10106634/67681440-3c59de80-f985-11e9-9cbc-47565cbb1b1a.png)

**Comment by omega489** [comment]
Install issue, please ignore
