### ISSUE TITLE
FL-TX1800 Fuel Tank - Texture Issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#701]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67682976-682a9380-f988-11e9-90d6-1f2979f937aa.png)

On the 'White' variant there is a sharp, thin, black stripe running down the umbilical shroud on both sides of the tank.

Comparison shown with the smaller, FL-TX900 Fuel Tank tank for reference.

**Comment by ChrisAdderley** [comment]
Fixed in 910b4a485267eb7423f253d839f7c9b6ab4b3035

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/910b4a485267eb7423f253d839f7c9b6ab4b3035
