### ISSUE TITLE
FL-TX900 Fuel Tank - Texture Issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#702]
There is a slight alignment issue on all 3 variants on the umbilical shroud where a channel doesn't seem to line up across the faces of the shroud.

Apparent on Black and White, White and Orange and Gray variants.

![Untitled-2](https://user-images.githubusercontent.com/10106634/67683175-d2dbcf00-f988-11e9-90e2-72fe9ab0ba28.png)

**Comment by ChrisAdderley** [comment]
Fixed in 910b4a485267eb7423f253d839f7c9b6ab4b3035

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/910b4a485267eb7423f253d839f7c9b6ab4b3035
