### ISSUE TITLE
FL-TX900 Fuel Tank - Model Position Issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#703]
The bottom of the 1.875m 900 tank seems to cause Z-Fighting with the part it is attached to: https://youtu.be/hJqSav7BJrE. The top of the tank does not cause this issue.

The node position has to be retained with stock so its probably a case of the model extending a little too far or similar.

**Comment by ChrisAdderley** [comment]
Fixed in 910b4a485267eb7423f253d839f7c9b6ab4b3035

**Comment by Poodmund** [comment]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67713332-8b236a80-f9bd-11e9-94bd-0b1b9f8c4f7e.png)

The Z-Fighting is essentially resolved but the end cap has slipped down to produce a gap in the model.

**Comment by ChrisAdderley** [comment]
ffs

**Comment by ChrisAdderley** [comment]
See 1b6940843be848c5cd4031550da1cff6e1feb71d for fun times

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/1b6940843be848c5cd4031550da1cff6e1feb71d
