### ISSUE TITLE
FL-A150 Fuel Tank Adapter - Model Seams/Normal Issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#706]
![Untitled-3](https://user-images.githubusercontent.com/10106634/67687547-5fd65680-f990-11e9-9a0d-b767287cc0c5.png)

Similar to https://github.com/PorktoberRevolution/ReStocked/issues/697 and https://github.com/PorktoberRevolution/ReStocked/issues/626, the model seems to have seams at the mirrored joints. There are artifact lines running along the seam which are magnified when zoomed out.

**Comment by ChrisAdderley** [comment]
Fixed in 910b4a485267eb7423f253d839f7c9b6ab4b3035

**Comment by Poodmund** [comment]
It seems a little better with https://github.com/PorktoberRevolution/ReStocked/commit/910b4a485267eb7423f253d839f7c9b6ab4b3035

![Untitled-1](https://user-images.githubusercontent.com/10106634/67713832-7f847380-f9be-11e9-80b7-490b7948c400.png)

See above screenshot for current state. Please close if satisfied that its good enough or as good as can be.

**Comment by ChrisAdderley** [comment]
1b6940843be848c5cd4031550da1cff6e1feb71d is the maximum possible

**Comment by Poodmund** [comment]
Then with https://github.com/PorktoberRevolution/ReStocked/commit/1b6940843be848c5cd4031550da1cff6e1feb71d we shall venture forth!
