### ISSUE TITLE
MH Fuel Tank Adapters - Collider Issues

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#707]
Similar to the issue with the 1.875m Cylindrical Fuel Tanks, which was discussed and resolved outside of GitHub, the Making History Fuel Tank Adapaters are suffering from the same problem.

Video of the issue with the Cyclindrical Fuel Tanks: https://www.youtube.com/watch?v=5pEoYb6jhw0 just for reference as to what is occuring (albeit with different parts).

The same thing is occuring with the following conical adapters:

- FL-A150 Fuel Tank Adapter
- FL-A151L Fuel Tank Adapter
- FL-A151S Fuel Tank Adapter
- FL-A215 Fuel Tank Adapter

**Comment by ChrisAdderley** [comment]
Fixed in 910b4a485267eb7423f253d839f7c9b6ab4b3035

**Comment by Poodmund** [comment]
All resolved with https://github.com/PorktoberRevolution/ReStocked/commit/910b4a485267eb7423f253d839f7c9b6ab4b3035
