### ISSUE TITLE
Protective Rocket Nosecone Mk5A - Incorrect variant textures assigned in .mu

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#714]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67698624-9ae18580-f9a2-11e9-8358-651450fff5ea.png)

The configs are set up correctly but the BlackAndWhite texture is set for the White variant and vice-versa. I think it may need some UV re-kergigging or Game Object swapping etc. to resolve and get re-exported.

**Comment by ChrisAdderley** [comment]
Fixed in 910b4a485267eb7423f253d839f7c9b6ab4b3035

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/910b4a485267eb7423f253d839f7c9b6ab4b3035
