### ISSUE TITLE
Heat Shield (1.875m) - Shroud length too short

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#715]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67700565-17c22e80-f9a6-11e9-8a0f-1699170af574.png)

When connecting a part to the bottom node of the 1.875m Heatshield, the auto-shroud does not extend down to the child part fully.

**Comment by ChrisAdderley** [comment]
Fixed in 910b4a485267eb7423f253d839f7c9b6ab4b3035

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/910b4a485267eb7423f253d839f7c9b6ab4b3035
