### ISSUE TITLE
THK "Pollux" Solid Fuel Booster - Running FX running constantly

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#716]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67705666-590b0c00-f9af-11e9-8dd6-e66612a918ea.png)

The running particle FX are present before the motor is activated and still after the fuel has run out.

**Comment by ChrisAdderley** [comment]
Fixed in 910b4a485267eb7423f253d839f7c9b6ab4b3035

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/910b4a485267eb7423f253d839f7c9b6ab4b3035
