### ISSUE TITLE
Place-Anywhere 7 Linear RCS Port - Bare variant ModuleDepthMask issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#717]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67719663-28849b80-f9ca-11e9-8baf-1c2b5b7d56c7.png)

The depth mask requires some attention.

**Comment by ChrisAdderley** [comment]
Should be resolved by 418bf178c7357a5446b9662f5eab930a08788de9

**Comment by Poodmund** [comment]
Fixed with https://github.com/PorktoberRevolution/ReStocked/commit/418bf178c7357a5446b9662f5eab930a08788de9
