### ISSUE TITLE
LV-T45 "Swivel" Liquid Fuel Engine - Normal issue on boat-tail bells

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#721]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67723320-8964a180-f9d3-11e9-8738-458cfc58692f.png)

On the two boat-tail variants, the engine bells have a weird chequered issue going on.

**Comment by ChrisAdderley** [comment]
Should be resolved by 00b8e71a529fd67bc8b4aad8ec8a2973e89c85c0

**Comment by Poodmund** [comment]
Fixed in https://github.com/PorktoberRevolution/ReStocked/commit/00b8e71a529fd67bc8b4aad8ec8a2973e89c85c0
