### ISSUE TITLE
LV-T30 "Reliant" Liquid Fuel Engine - Boat-tail specular issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#722]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67723399-d6e10e80-f9d3-11e9-8a31-15f5f070666d.png)

Honestly not sure if this is an issue or not so thought that I'd ask the question anyway... there is a highly-reflective band that goes around the bottom of the boat-tail shroud on the boat-tail variants.

**Comment by ChrisAdderley** [comment]
Should be resolved by 00b8e71a529fd67bc8b4aad8ec8a2973e89c85c0

**Comment by Poodmund** [comment]
Fixed with https://github.com/PorktoberRevolution/ReStocked/commit/00b8e71a529fd67bc8b4aad8ec8a2973e89c85c0
