### ISSUE TITLE
RE-I2 "Skiff" Liquid Fuel Engine - 1.25m Shroud variant string needs improving/changing.

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#723]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67723477-1f003100-f9d4-11e9-84d3-186e9996b853.png)

Both 1.25m Shroud variants for the Skiff don't have an auto-shroud when the bottom node is in use.

**Comment by Poodmund** [comment]
I've just realised that the bell is wider than the 1.25m profile. In that case, its probably just the localization string of the variant that needs changing.

**Comment by Poodmund** [comment]
Hmmmmmmm, in light of discussion, potentially copy stock and put the 1.875m shroud around the 1.25m profile engine.

**Comment by ChrisAdderley** [comment]
Should be resolved by 418bf178c7357a5446b9662f5eab930a08788de9

**Comment by Poodmund** [comment]
Fixed with https://github.com/PorktoberRevolution/ReStocked/commit/418bf178c7357a5446b9662f5eab930a08788de9.
