### ISSUE TITLE
1.875m Stack Separator - Black and White variant model issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#724]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67723976-8cf92800-f9d5-11e9-8997-68c22ad87c63.png)

The Black and White variant of this stack separator doesn't have its outer shroud mesh enabled... and possibly the internal mesh is doubled as it looks like there is lighting issues in the editor (z-fighting?).

**Comment by ChrisAdderley** [comment]
Should be resolved by 418bf178c7357a5446b9662f5eab930a08788de9

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/418bf178c7357a5446b9662f5eab930a08788de9
