### ISSUE TITLE
RE-I2 "Skiff/Caravel" Liquid Fuel Engine - Emissive Animation Issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#726]
The heat up animation seems to be working correctly (the external heating ramp may be a little quick) but the cool down transition is instant on both inside the bell and externally. As soon as you cut the throttle the emissive reverts to the start of the animation i.e. disappears

**Comment by ChrisAdderley** [comment]
Should be resolved by 418bf178c7357a5446b9662f5eab930a08788de9

**Comment by Poodmund** [comment]
Perfect with https://github.com/PorktoberRevolution/ReStocked/commit/418bf178c7357a5446b9662f5eab930a08788de9
