### ISSUE TITLE
RE-I2 "Skiff/Caravel" Liquid Fuel Engine - Model & Texture Issues

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#727]
The Turbine Exhaust Manifold pipe has a noticeable seam/normal inconsistency:

![Untitled-1](https://user-images.githubusercontent.com/10106634/67808588-df4a4f80-fa8e-11e9-987d-b0efc1ccac31.png)

The large Gas Generator housing is white rather than a metallic colour, is this correct?:

![Untitled-2](https://user-images.githubusercontent.com/10106634/67808648-f8530080-fa8e-11e9-82f8-92f7f5818023.png)

The 1.875m, 1.25m and Compact variants have one of the linkage couplers at the gimbal connection point missing (seen here at the bottom of the screenshots):

![Untitled-3](https://user-images.githubusercontent.com/10106634/67808719-1d477380-fa8f-11e9-99af-1e78ced1d108.png)
![Untitled-4](https://user-images.githubusercontent.com/10106634/67808720-1d477380-fa8f-11e9-8611-3bca496e0431.png)
![Untitled-5](https://user-images.githubusercontent.com/10106634/67808721-1d477380-fa8f-11e9-872a-11c31b7c2288.png)

The Shrouded variant doesn't have this issue.

**Comment by ChrisAdderley** [comment]
Should be resolved by 418bf178c7357a5446b9662f5eab930a08788de9

**Comment by Poodmund** [comment]
All issues discussed above fixed with https://github.com/PorktoberRevolution/ReStocked/commit/418bf178c7357a5446b9662f5eab930a08788de9
