### ISSUE TITLE
RK-7 "Kodiak/Ursa" Liquid Fueled Engine - Emissive Animation issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#728]
Much like https://github.com/PorktoberRevolution/ReStocked/issues/726, the ramp up animation seems quick but the cool down animation is instantaneous.

**Comment by ChrisAdderley** [comment]
Should be resolved by 418bf178c7357a5446b9662f5eab930a08788de9 plus some other engines

**Comment by Poodmund** [comment]
Kodiak/Ursa fixed with https://github.com/PorktoberRevolution/ReStocked/commit/418bf178c7357a5446b9662f5eab930a08788de9
