### ISSUE TITLE
RK-7 "Kodiak/Ursa" Liquid Fueled Engine - Normal/Mesh Issue on End Caps

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#729]
One the underside of the 1.25m ring and on the top side of the 1.25m rings on the 1.25m and 1.25m Boattail variants there is that weird mesh/normal issue that popped up the other day. See screenshots below:

![Untitled-1](https://user-images.githubusercontent.com/10106634/67813379-4f5dd300-fa99-11e9-8bb9-64a682dc10f5.png)
![Untitled-2](https://user-images.githubusercontent.com/10106634/67813380-4ff66980-fa99-11e9-8dd4-c0493a3824f2.png)
![Untitled-3](https://user-images.githubusercontent.com/10106634/67813381-4ff66980-fa99-11e9-8652-56e21b70fd0f.png)

**Comment by ChrisAdderley** [comment]
Should be resolved by 00b8e71a529fd67bc8b4aad8ec8a2973e89c85c0

**Comment by Poodmund** [comment]
Fixed with https://github.com/PorktoberRevolution/ReStocked/commit/00b8e71a529fd67bc8b4aad8ec8a2973e89c85c0
