### ISSUE TITLE
RK-7 "Kodiak/Ursa" Liquid Fueled Engine - Autoshroud Z-Fighting issues

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#730]
I am getting Z-fighting between the autoshroud and connected parts at the top/bottom of the shroud on the following variants:

Top of 1.25m Boattail
![Untitled-1](https://user-images.githubusercontent.com/10106634/67813637-ed519d80-fa99-11e9-9d85-17f53e679ca2.png)

Top of 1.25m
![Untitled-2](https://user-images.githubusercontent.com/10106634/67813638-ed519d80-fa99-11e9-8599-969d1f19c380.png)

Bottom of 1.875m
![Untitled-3](https://user-images.githubusercontent.com/10106634/67813639-edea3400-fa99-11e9-8fb5-a83df2a7040d.png)

Top of 1.875m
![Untitled-4](https://user-images.githubusercontent.com/10106634/67813641-edea3400-fa99-11e9-81d9-f580d6cd92b4.png)

**Comment by ChrisAdderley** [comment]
Should be resolved by 00b8e71a529fd67bc8b4aad8ec8a2973e89c85c0

**Comment by Poodmund** [comment]
Fixed with https://github.com/PorktoberRevolution/ReStocked/commit/00b8e71a529fd67bc8b4aad8ec8a2973e89c85c0
