### ISSUE TITLE
Service Bay (1.875m) Colliders

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#733]
Service bay door colliders are non attachable and block internal attachment when open.

**Comment by ChrisAdderley** [comment]
Should be fixed with 7d6dd21fcafc912ebd1f87c9f9c51daecf3b418a

**Comment by Poodmund** [comment]
Fixed with https://github.com/PorktoberRevolution/ReStocked/commit/7d6dd21fcafc912ebd1f87c9f9c51daecf3b418a
