### ISSUE TITLE
RE-J10 "Wolfhound/Schnauzer" Liquid Fuel Engine AJ10 - Odd AO

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#735]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67978826-df735800-fc12-11e9-8786-c982f31440fd.png)

Some slightly odd Ambient Occlusion on the orange combustion chamber present on all variants.

**Comment by ChrisAdderley** [comment]
Fixed in a5cefc1b3d5d35f6ed3ab49d6534181ca1f9a932

**Comment by Poodmund** [comment]
Not really an issue because the gimbal mechanism was missing, which was the reason for the AO.
