### ISSUE TITLE
RE-J10 "Wolfhound/Schnauzer" Liquid Fuel Engine AJ10 - Compact variant autoshroud gap in mesh

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#736]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67979394-10a05800-fc14-11e9-869b-665f39bdd297.png)

Both of the 'Compact' variants have a small gap at the top of the autoshroud between the autoshroud and the part above.

**Comment by ChrisAdderley** [comment]
Fixed in a5cefc1b3d5d35f6ed3ab49d6534181ca1f9a932

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/a5cefc1b3d5d35f6ed3ab49d6534181ca1f9a932
