### ISSUE TITLE
FL-TX220-R Hemispherical Liquid Fuel Tank - 1.875m - Texture blemish

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#738]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67990174-fd4db680-fc2c-11e9-91f2-a803b0fc42b0.png)

On both sides of the 'White' variant there are some small blemishes down a UV edge.

**Comment by ChrisAdderley** [comment]
Fixed in a5cefc1b3d5d35f6ed3ab49d6534181ca1f9a932

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/a5cefc1b3d5d35f6ed3ab49d6534181ca1f9a932
