### ISSUE TITLE
FL-TX220-R Hemispherical Liquid Fuel Tank - 1.875m - Model mesh gap

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#739]
![Untitled-1](https://user-images.githubusercontent.com/10106634/67990440-d2179700-fc2d-11e9-84f1-713cc70a8c7d.png)

Theres a small gap between the tank and the end cap on all variants.

**Comment by ChrisAdderley** [comment]
Fixed in a5cefc1b3d5d35f6ed3ab49d6534181ca1f9a932

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/a5cefc1b3d5d35f6ed3ab49d6534181ca1f9a932
