### ISSUE TITLE
Vernor Engine - texture makes it look like sewn from cloth

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#74]
A combination of the rounded shape and the hash texture along the "seam" makes the part look like it's a sewn pillow versus a metal part. Suggest changing the highlight texture from that stitched look to something that doesn't accentuate that odd seam so much.

![screenshot6](https://user-images.githubusercontent.com/22890228/50265432-77d66480-03d4-11e9-941d-a5804762b226.png)

**Comment by ChrisAdderley** [comment]
Well, this is a really nasty squad part, yeah. That I haven't done yet ;).
