### ISSUE TITLE
1.875m Medium Reaction Wheel Assembly - Collider mesh offset

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#741]
![Untitled-1](https://user-images.githubusercontent.com/10106634/68053330-93dcaf00-fce3-11e9-87d6-c8973c3d8917.png)

The collider mesh is positioned incorrectly for the part. I can confirm, in flight mode when on the floor, the model hovers above the floor.

**Comment by ChrisAdderley** [comment]
Fixed in a5cefc1b3d5d35f6ed3ab49d6534181ca1f9a932

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/a5cefc1b3d5d35f6ed3ab49d6534181ca1f9a932
