### ISSUE TITLE
Advanced Grabbing Unit Junior - Pivot toggle option in PAW

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#742]
![Untitled-1](https://user-images.githubusercontent.com/10106634/68053857-e36faa80-fce4-11e9-970c-7d20ef7387ce.png)

The junior claw does not have a pivot function yet the PAW has a toggle button to free/lock the pivot (I presume the part module adds this option in by default). If there was a way to remove this toggle button from the PAW for this part it would be preferred behaviour.

**Comment by drewcassidy** [comment]
There’s no way to remove the option

**Comment by ChrisAdderley** [comment]
I think if there's no way, we should close this.
