### ISSUE TITLE
Service Bay (1.875m) - Shader issue in Editor

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#743]
![Untitled-1](https://user-images.githubusercontent.com/10106634/68054204-b8d22180-fce5-11e9-861b-b755e2d39517.png)

The 1.875m Service Bay goes translucent whenever your mouse cursor goes near it (just nearby, not mouseover) unlike the other two service bay parts which do not go translucent.

For reference, I just tested in 1.8.1 Vanilla and the 1.25m and 2.5m service bays do not go translucent.

**Comment by ChrisAdderley** [comment]
This is because Squad's new service bays in 1.8 lack this module. Will investigate which avenue we prefer.

**Comment by ChrisAdderley** [comment]
Fixed in a5cefc1b3d5d35f6ed3ab49d6534181ca1f9a932

**Comment by Poodmund** [comment]
The 2.5m Service Bay goes translucent with https://github.com/PorktoberRevolution/ReStocked/commit/a5cefc1b3d5d35f6ed3ab49d6534181ca1f9a932 but the 1.25m and 1.875m do not. See this video to show the current state: https://www.youtube.com/watch?v=r8hoZW89wNU

**Comment by ChrisAdderley** [comment]
Squad bug. Only the first placed one on a vessel will work wheeeee
