### ISSUE TITLE
FL-XA15 Adapter - Texture & Model Issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#744]
![Untitled-1](https://user-images.githubusercontent.com/10106634/68055857-85919180-fce9-11e9-8757-151993995311.png)

The mesh/normal issue is occuring on the outer edge segment faces of the 'Metal' variant.

![Untitled-2](https://user-images.githubusercontent.com/10106634/68055858-888c8200-fce9-11e9-990a-097642693e96.png)

There is a small hole in the model on all variants in the topside and underside of the end cap in the centre.

**Comment by ChrisAdderley** [comment]
Fixed in a5cefc1b3d5d35f6ed3ab49d6534181ca1f9a932

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/a5cefc1b3d5d35f6ed3ab49d6534181ca1f9a932
