### ISSUE TITLE
Heat Shield (10m) - Backfaces being culled

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#745]
![Untitled-1](https://user-images.githubusercontent.com/10106634/68059552-c7740500-fcf4-11e9-9c32-af3cae6d19f7.png)

Some backfaces on the expanded cover on the heatshield are being culled which allows you to see through it. This occurs all the way round the cover.

**Comment by ChrisAdderley** [comment]
Should be good with latest commit.

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/a5cefc1b3d5d35f6ed3ab49d6534181ca1f9a932
