### ISSUE TITLE
Basic Fin, AV-T1 Winglet & AV-R8 Winglet - Model issues

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#746]
The Basic Fin, AV-T1 Winglet & AV-R8 Winglet models seem to have their models positioned and/or shaped oddly in the .mu files which causes them to attached titled or banana-ed when putting them onto another part. Looked into the assets and it seems some parts are a bit wonky:

AV-T1:

![Untitled-1](https://user-images.githubusercontent.com/10106634/68071786-ef577d00-fd75-11e9-8f31-475d53ca1112.png)

AV-R8:

![Untitled-2](https://user-images.githubusercontent.com/10106634/68071794-f7afb800-fd75-11e9-80cb-1673c32bc5d9.png)

Basic Fin:

![Untitled-3](https://user-images.githubusercontent.com/10106634/68071795-fd0d0280-fd75-11e9-8df4-149bbe51994c.png)

In comparison, the Delta-Deluxe Wing seems to be fine:

![Untitled-4](https://user-images.githubusercontent.com/10106634/68071803-0d24e200-fd76-11e9-8a34-cf4e00993811.png)

**Comment by ChrisAdderley** [comment]
Fixed in a5cefc1b3d5d35f6ed3ab49d6534181ca1f9a932

**Comment by ChrisAdderley** [comment]
More minor improvements in 2e33fbc806ec38cc3eb8ed13cad9c70a40d570b6

**Comment by Poodmund** [comment]
I still have concerns with the AV-T1 Winglet primarily, it seems the model is lop-sided along the leading edge of the wing.

![Untitled-1](https://user-images.githubusercontent.com/10106634/68234904-276ef200-fffa-11e9-80e6-55dc3b52c9ff.png)

At this stage, not sure what can be done?

**Comment by ChrisAdderley** [comment]
I no longer care - the drag cubes are manually cloned so it doesn't really matter...
