### ISSUE TITLE
PRBE-4 & PRBE-9 Liquid Fuel Tanks - Origin offset from CoM

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#747]
The PRBE-4 & PRBE-9 Liquid Fuel Tanks both have their origins offset outside of the part so its really odd when rotating the parts as they do not rotate about their centre points.

**Comment by Poodmund** [comment]
I'm a dumbass, sorry.

**Comment by ChrisAdderley** [comment]
lol, np
