### ISSUE TITLE
ReStock Blacklist missing some parts

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#748]
I think that the blacklist file is missing some parts from being blacklisted, notably:

- Squad/Parts/Engine/liquidEngine24-77_v2
- Squad/Parts/Engine/liquidEngine48-7S
- Squad/Parts/Engine/liquidEngineLV-1_v2
- Squad/Parts/Utility/linearVernorRCS
- Squad/Parts/Aero/fairings (for some reason Squad/Parts/Aero/fairings/fairingSize2.mu is listed specifically)
- basicFin
- Squad/Parts/Aero/wingletAV-R8
- Squad/Parts/Aero/wingletAV-T1
- Squad/Parts/Aero/wingletDeltaDeluxe
- Squad/Parts/Electrical/1x6ShroudSolarPanels
- Squad/Parts/Electrical/1x6SolarPanels
- Squad/Parts/Electrical/3x2ShroudSolarPanels
- Squad/Parts/Electrical/3x2SolarPanels
- Squad/Parts/Electrical/gigantorXlSolarArray
- Squad/Parts/Electrical/radialFlatSolarPanel

The two nose cones below also aren't included in the blacklist but not sure if their assets are shared with non-ReStock replaced parts.

- Protective Rocket Nose Cone Mk7 (rocketNoseCone_v2)
- Protective Rocket Nose Cone Mk12A (rocketNoseConeSize3)

Does anyone know if there is any reason why these lines can't be added?

**Comment by ChrisAdderley** [comment]
> Protective Rocket Nose Cone Mk7 (rocketNoseCone_v2)
> Protective Rocket Nose Cone Mk12A (rocketNoseConeSize3)
> Fairings in general
These cannot be added as they are used in the the MH 5m nosecone and fairings. I'll add the rest after a short test.

**Comment by ChrisAdderley** [comment]
Changes made

**Comment by Poodmund** [comment]
Sweet, I'll close this off.
