### ISSUE TITLE
Lights not projecting any light

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#75]
The two new lights aren't projecting a light beam or lighting the surface they are pointing at.

![screenshot7](https://user-images.githubusercontent.com/22890228/50265537-ea474480-03d4-11e9-8a8c-07c5b9748b7e.png)

**Comment by ChrisAdderley** [comment]
Fixed with #78

**Comment by Poodmund** [comment]
Just tested this as of the integrated fixes in Master and I can confirm its been resolved for me and they noww emit light; tested on KSP 1.6.0.

How much light they emit is another story for balancing I guess. :D
