### ISSUE TITLE
please make compatibility patch for 1.7.3 ver ksp

### ISSUE THREAD

**Issue by Vannadin** [PorktoberRevolution/ReStocked#755]
most of mods are stable in 1.7.3. i want play this mod with many other mods

**Comment by Duck1998** [comment]
Use Restock 0.1.3

**Comment by blowfishpro** [comment]
Looking at the commit history, the last commit before the plugin was recompiled for 1.8 is 21fe47f, past that there are also 1.8-related part changes.

Fortunately you can download the entire repository as of a particular commit if you want: https://github.com/PorktoberRevolution/ReStocked/archive/21fe47fda32959d48fe9b9ccfeb1ba25ae8c0c45.zip , just be sure you install the correct things in the correct places (i.e. `GameData/Restocked` and ``GameData/RestockedPlus`)

**Comment by ChrisAdderley** [comment]
Take steps as mentioned.
