### ISSUE TITLE
New RCS plumes

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#76]
The RCS exhaust plumes on the quad RCS look like they're starting too far inside the nozzle so some of the plume is "leaking" through the nozzle sides

![screenshot8](https://user-images.githubusercontent.com/22890228/50265696-938e3a80-03d5-11e9-8fbd-3cc530f9e766.png)

It's less noticeable on the linear RCS port

![screenshot9](https://user-images.githubusercontent.com/22890228/50265782-f97ac200-03d5-11e9-87dd-01c1db197ade.png)

**Comment by ChrisAdderley** [comment]
I am working on a new, better RCS effect which will resolve this problem - I've edited the title to reflect this.

**Comment by Vladimir-csp** [comment]
Cool! 
May I suggest linking thrust to the opacity of particles, not quantity or speed or lifetime?  At least in vacuum.

**Comment by ChrisAdderley** [comment]
I don't believe that is possible with stock.

**Comment by ChrisAdderley** [comment]
75f8b41 should fix that.  Today I learned that there's a whole different category of FX configuration for sound for RCS!

**Comment by TykoTek** [comment]
All four directions have sound now, but one of the directions sounds different. I'm pretty sure it was the only direction that had sound before. It sounds higher pitched than the other three directions

**Comment by Poodmund** [comment]
Didn't realise this discussion was already happening, anyway, here's a video of it occuring for reference: https://www.youtube.com/watch?v=_5Bo3wyYMuA

**Comment by ChrisAdderley** [comment]
Still don't know what is going on, tried some things with the recent merge, don't know if it did anything.

**Comment by TykoTek** [comment]
Sounds are still inconsistent. In the current build the plumes are missing from 3 directions and the 4th only has a tiny plume. The nozzle with the tiny plume is not nozzle with a different sound. So there are two issues at work here.

https://youtu.be/y7tkC3C-20s

**Comment by ChrisAdderley** [comment]
Ok let's try again for #229. And if the sound is not right I have no goddamn clue and am closing the issue anyways

**Comment by TykoTek** [comment]
There are still sounds issues and those have been copied to the rest of the RCS blocks. Also new plume issues on the smaller blocks, off-center mostly.

I've built a test platform for you. On it each RCS block is tied to an action group, 1-10 and they're all off by default, so you can activate each one individually.

https://www.dropbox.com/s/19fntxah2f2ku9b/RCS%20test.craft?dl=0

**Comment by ChrisAdderley** [comment]
Sound fix as per Ensou at 95d10f4 (untested)

**Comment by TykoTek** [comment]
Tested and confirmed  :)
