### ISSUE TITLE
Illuminator stuck on when using Surface Lights

### ISSUE THREAD

**Issue by TedThompson** [PorktoberRevolution/ReStocked#761]
I find the two lights are stuck on. Neither the context menu or the light action group will toggle them on/off. 

The pivot is VERY welcome tho.

**Comment by frenchmarrow** [comment]
I, too have this problem. Interestingly, lights from AviationLights and SurfaceMounted seem to function alright. Thanks for the work, regardless, ReStock is beautiful. :)

**Comment by ChrisAdderley** [comment]
Are the lights attached to a part that has crew window lights? We discovered a stock bug when this happens - turning on and off the crew lights will fix it.

**Comment by TedThompson** [comment]
In my case, I too have surface lights. Reading older issues it seems that this happened before. Something about surface lights rebuilding some hierarchy in the game?  For color changing lenses?

**Comment by Taty095** [comment]
yep, Illuminator Mk1 dont work
![2019-12-01 (1)](https://user-images.githubusercontent.com/58377721/69908089-85250d00-13f3-11ea-997a-fcb3ed572226.png)
![2019-12-01](https://user-images.githubusercontent.com/58377721/69908090-85250d00-13f3-11ea-909e-b34c4adf1a96.png)

**Comment by TedThompson** [comment]
I should have also said, no "windows" it was on a fuel tank.

**Comment by ChrisAdderley** [comment]
Well, we don't see this is a basic install so going to need a modlist as it's certainly a conflict.

**Comment by Taty095** [comment]
KSP: 1.8.1 (Win64) - Unity: 2019.2.2f1 - OS: Windows 10  (10.0.0) 64bit
ClickThroughBlocker - 0.1.9.4
Filter Extensions - 3.2.4
Toolbar - 1.8.0.5
ToolbarControl - 0.1.9.4
AllYAllContinued - 0.11.18.3
Ambient Light Adjustment - 2.6.3.8
Astrogator - 0.10
AtmosphereAutopilot - 1.5.16
BD Animation Modules - 0.6.5.8
BetterTimeWarpContinued - 2.3.12.4
Bon Voyage - 1.0.1
Camera Focus Changer - 1.1
Community Category Kit - 5.0
Community Resource Pack - 1.3
Contract Configurator - 1.28
Contract Pack: RemoteTech - 2.1.4
CorrectCOL - 1.6.5.3
Crew Light - 1.20
CriticalTemperatureGauge - 1.8.1
DecouplerShroud - 0.7.2
RCSLandAid - 3.4.0.1
DistantObjectEnhancement - 2.0
DMagic Orbital Science - 1.4.3
CapCom Mission Control On The Go - 1.0.2.11
Contract Parser - 1.0.9
Contracts Window Plus - 1.0.9.4
Progress Parser - 1.0.11
Easy Vessel Switch - 2.0.7235.25545
EditorExtensionsRedux - 3.4.0.2
Engine Lighting Relit - 1.6.2.2
Environmental Visual Enhancements - 1.8.0.2
EVAFollowerFollowed - 1.1.1.3
EVAFuelContinued - 1.6.7.3
Firespitter - 7.14
Flexible Docking - 1.0.8
Interstellar Fuel Switch - 3.12.2.5
JanitorsCloset - 0.3.7
KAS - 1.5.7239.36651
Kerbal Engineer Redux - 1.1.7.1
Kerbal Inventory System - No Fun - 0.1.4.2
Kerbal Joint Reinforcement - 4.1.15
Kerbal Inventory System - 1.23.7234.41726
KSP-AVC Plugin - 1.4.0.3
XT Landertron - 1.1.2
Lights Out - 0.3.0.1
Infernal Robotics - 3.0.2
Infernal Robotics Sequencer - 3.0
MechJebForAll - 1.3.0.6
MoarFilterExtensionConfigs - 1.0.4.1
Docking Port Alignment Indicator - 6.8.3
NSS-OctoSat - 0.1.13.4
Olympic1's Icon Packs - 0.10.3
OPT Reconfig - 1.7
Kerbal Planetary Base Systems - 1.6.10
PlanetShine - 0.2.6.3
Precise Node - 1.2.11
RCS Build Aid - 0.10
RemoteTech - 1.9.4
AmpYear - 1.5.6
DeepFreeze Continued... - 0.27
ReStock - 1.0.1
ReStockPlus - 1.0.1
SCANsat - 1.1.8.14
Science Relay - 1.0.6
SmartStage - 2.9.12
KSP_ColorPicker - 0.1.0.1
KSP_Log - 0.1.0.1
PartHighlighter - 0.1.0.1
SpaceTuxLibrary - 0.0.2.3
StageRecovery - 1.9.2
StationKeeping - 0.2.2
Surface Mounted Lights - 1.14.7239.37956
TAC Fuel Balancer - 2.21.5
TAC Life Support - 0.14
TooManyOrbits - 1.1.6.2
Trajectories - 2.2.4.1
Kerbal Alarm Clock - 3.12
Alternate Resource Panel - 2.9.3
TweakScale - 2.4.3.10
Universal Storage 2 - 1.7.0.10
Waypoint Manager - 2.8.1
OSE Workshop - 1.2.13

**Comment by drewcassidy** [comment]
I wonder if this is a regression of #522. can you test again without Surface Lights?

**Comment by drewcassidy** [comment]
Looking at the [forums](https://forum.kerbalspaceprogram.com/index.php?/topic/139724-18-surface-mounted-lights-v114-incompatible-with-ksp-17/&do=findComment&comment=3702447), IgorZ seems to be already aware of an issue between surface lights and Restock, might have to do with the recent patch order change?

**Comment by Taty095** [comment]
> I wonder if this is a regression of #522. can you test again without Surface Lights?

No mod SurfaceLights all work. Thanks!

**Comment by TedThompson** [comment]
I have further discovered that within Surface Lights is a Module Manager cfg "MM-StockLights.cfg" that specifically addresses the ReStock mod.

Within it contains`// Stock parts need animation patching.
@PART[spotLight1,spotLight2]:NEEDS[!ReStock]
{
	@MODULE[ModuleLight]
	{
		@name = ModuleStockLightColoredLens
		%lightR = 1.0
		%lightG = 0.9
		%lightB = 0.8
		lensBrightness = 0.4
	}
	@tags ^= :^:cck-lights
}

// ReStock'ed parts can support colored lenses naturally.
// See: https://github.com/PorktoberRevolution/ReStocked
@PART[zspotLight1,zspotLight2]:NEEDS[ReStock]
{
	@MODULE[ModuleLight]
	{
		@name = ModuleColoredLensLight
		%lightR = 1.0
		%lightG = 0.9
		%lightB = 0.8
		lensBrightness = 0.4
	}
	@tags ^= :^:cck-lights
}
`

Removing this file makes ReStock's Illuminator Mk1 and Mk2 behave correctly, although it obviously makes the lens no longer change color.

**Comment by TedThompson** [comment]
Restock released an update addressing this issue.
