### ISSUE TITLE
Ant/Spider variant switch still exists

### ISSUE THREAD

**Issue by jimmymcgoochie** [PorktoberRevolution/ReStocked#762]
The LV-1 'Ant' engine shows two variants- metal and white- however the white version is the same as the metal one. Apparently this engine is not meant to have two versions.

The RE-I2 'Skiff' engine from Making History shows a 1.875m tank butt variant, however this is actually 2.5m wide and the other 1.875m versions of this engine actually are 1.875m wide.

The 10m inflatable heat shield has an issue with the bottom connecting node (the pointy end of the shield) as the shroud for this part doesn't reach the whole way down to the attachment node meaning that it 'floats' above whatever it's stacked on top of.

**Comment by ChrisAdderley** [comment]
Split skiff and heat shield issues to #766 and #765.

**Comment by ChrisAdderley** [comment]
Ok this actually seems fine. I was mistaken. Just put the engine in a stack and you'll see that the variants are for the shroud, as the tooltip indicates
