### ISSUE TITLE
Stayputnik references the wrong model

### ISSUE THREAD

**Issue by deimos790** [PorktoberRevolution/ReStocked#763]
```
  MODEL
  {
    model = ReStock/Assets/Command/restock-probe-sphere-1
  }
```
There is no "restock-probe-sphere-1" but there is a "restock-probe-stayputnik-1"

**Comment by ChrisAdderley** [comment]
Are you certain? Check here: https://github.com/PorktoberRevolution/ReStocked/tree/master/Distribution/Restock/GameData/ReStock/Assets/Command
You'll see `restock-probe-sphere-1.mu` towards the end of the folder.
