### ISSUE TITLE
restock-engine-panda-1 RK-1 config file should not be located in radial but 1875

### ISSUE THREAD

**Issue by xot1643** [PorktoberRevolution/ReStocked#764]
restock-engine-panda.cfg is located in ReStockPlus\Parts\Engine\radial.
As it is a 1.875m stackable part, it should be located in ReStockPlus\Parts\Engine\1875.

Please ignore this issue if not relevant enough.

**Comment by ChrisAdderley** [comment]
I don't think so, it's a radial vernier engine...
