### ISSUE TITLE
[1.6] Error with "Aerodynamic Nose Cone" texture

### ISSUE THREAD

**Issue by nagleaidan** [PorktoberRevolution/ReStocked#77]
In 1.6 is something strange going on with the 1.25 short nosecone. Attached is a video in a 1.6 install with just MH expansion, MM, and the latest pull of the git (on 20 Dec 2018) (not using Restock+) https://drive.google.com/file/d/1sL8ozip9VERiiu_33WEFoia1VMMKnmOB/view?usp=sharing

**Comment by ChrisAdderley** [comment]
1.6 replaced a lot of content because of the stack of part variants and this is absolutely not supported by restock at the moment because 1.6 is <6h old. It'll be supported when the `recolor` branch is merged.
