### ISSUE TITLE
Imported colliders are broken for all 1.25 and 1.875m SRBs

### ISSUE THREAD

**Issue by ccaviness** [PorktoberRevolution/ReStocked#779]
When attaching an Mk2-R parachute to the side of the larger SRBs, the parachute disappears, sometimes fully, under the skin of the model.
On some locations, the parachutes seem to attach normally, other places it's completely obscured.

Video: https://youtu.be/H8IrReFvYA4

The video was recorded running vanilla KSP 1.8.1 with ReStocked and ReStocked+ 1.0.2 only.

**Comment by ChrisAdderley** [comment]
Confirmed, investigating why. We had a problem where some of the MH colliders were horribly broken when imported despite visibly fine, so this may be related.

**Comment by ChrisAdderley** [comment]
This indeed appears to be the broken colliders issue again
Confirmed that this occurs with
- Flea
- Hammer
- Kickback
- Thumper
- Anvil/Castor/Pollux

**Comment by ChrisAdderley** [comment]
Fixed in d4547469f876811280f1b825c9eb7e107664de7d. Will be in 1.0.3

**Comment by ChrisAdderley** [comment]
Released w/1.0.3
