### ISSUE TITLE
Science Container Incompatability with Indicator Lights

### ISSUE THREAD

**Issue by NicholasZidel** [PorktoberRevolution/ReStocked#782]
The Science box is having a glitch where it only shows as four green vertical lines and cannot be clicked on once it has been placed on a vessel.

**Comment by drewcassidy** [comment]
can you attach a screenshot? what other mods are you using?

**Comment by NicholasZidel** [comment]
I'm going to attach a screenshot of my mods from Ckan because there are a lot. I don't think any of the other mods I have installed interact with the science container but I could be wrong. In some fiddling around I noticed that in game it doesn't interact with the ground or other parts, but it can explode if you hit the node where it connects to another part.

Running KSP 1.8.1 for Windows x64 with both DLC

Mods:
![Screenshot (3)](https://user-images.githubusercontent.com/32314100/72603234-a29c3080-38e6-11ea-9e07-ad141c80d81e.png)
![Screenshot (4)](https://user-images.githubusercontent.com/32314100/72603235-a29c3080-38e6-11ea-927c-66129ef33400.png)

Here the canister should be showing on the to the left but instead it is just lines.
![Screenshot (6)](https://user-images.githubusercontent.com/32314100/72603443-06bef480-38e7-11ea-9807-a0909c724c9b.png)

Here is the canister in the VAB. It is attached to the Mk1 command pod and the tool tip is the stock canister tool tip with the wrong texture.
![screenshot7](https://user-images.githubusercontent.com/32314100/72603517-26eeb380-38e7-11ea-94b9-b4c3baf16494.png)

Let me know if you need anything else

**Comment by drewcassidy** [comment]
Try it without indicator lights

**Comment by NicholasZidel** [comment]
That fixed it!

**Comment by drewcassidy** [comment]
Looks like [This PR](https://github.com/KSPSnark/IndicatorLightsCommunityExtensions/pull/6) on Indicator Lights will fix the issue, will close this when that gets merged by Snark

**Comment by Poodmund** [comment]
As above, we're now waiting on the other mod to accept the PR to update so I'll move this to 'In Verification'.

**Comment by Poodmund** [comment]
Resolved in the latest release of IL:CE with this commit: https://github.com/KSPSnark/IndicatorLightsCommunityExtensions/commit/a191839058597a052185493f6a25f9e70ccb51ae
