### ISSUE TITLE
Structural Tube Enhancements

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#789]
Provide a patch in Restock+ to make the tubes behave correctly:

1. Custom drag cubes so the system doesn't treat them as hollow (like every other cargo bay)
2. Content-shielding like every other cargo bay

**Comment by theonegalen** [comment]
pretend that I've left the gif of Citizen Kane applauding

**Comment by ChrisAdderley** [comment]
It turns out that having variants that change drag cubes *and* cargo bays on a part is really bad, so only the drag fix will be implemented.
