### ISSUE TITLE
TT18-A Launch Stability Enhancer Trusses - No support for older OpenGL versions

### ISSUE THREAD

**Issue by Wulfrank** [PorktoberRevolution/ReStocked#790]
**Describe the bug**
TT18-A Launch Stability Enhancer trusses are invisible in both builder and flight scenes.

**Screenshots**
![screenshot83](https://user-images.githubusercontent.com/12776220/73586678-93c88880-4465-11ea-80b3-245c92bdfa27.png)
![screenshot84](https://user-images.githubusercontent.com/12776220/73586679-94611f00-4465-11ea-9aae-3641d5be255d.png)

**List of mods installed:**
 - Restock 1.0.3
 - Restock Plus 1.0.3
 - Module Manager 4.1.3

**Logs**
[KSP.log](https://github.com/PorktoberRevolution/ReStocked/files/4142132/KSP.log)

**Comment by drewcassidy** [comment]
I have absolutely no idea how, but you are somehow running KSP on macOS 10.11 using OpenGL 3.3, which does not support instancing. Honestly I was working under the assumption nobody would do that, and never provided a fallback to the instancing for the girders.

I'll add a fallback to a slower non-instanced method for the launch clamps in the next update

**Comment by drewcassidy** [comment]
Can you try replacing your restock.dll file with [this version](https://github.com/PorktoberRevolution/ReStocked/raw/instancing-fallback/Distribution/Restock/GameData/ReStock/Plugins/Restock.dll)?

**Comment by Wulfrank** [comment]
I tested the new .dll file and can confirm the launch clamp trusses are now visible in both building and flight scenes.

![screenshot85](https://user-images.githubusercontent.com/12776220/73603363-60a1fa00-4536-11ea-9fb5-f950064677e2.png)
![screenshot87](https://user-images.githubusercontent.com/12776220/73603364-60a1fa00-4536-11ea-8df0-19a3ae4ec3f7.png)
