### ISSUE TITLE
Fairing procedural side colliders are rotates 5 degrees and have a large hole in each side.

### ISSUE THREAD

**Issue by Avera9eJoe** [PorktoberRevolution/ReStocked#797]
**Describe the bug**
Fairing procedural side colliders are rotates 5 degrees and have a large hole in each side. This causes some issues with building around fairings. I haven't tested if it effects aero.

**Screenshots**
Default fairing behaviour; fairing is straight/aligned with the base, side colliders connect:
![Default fairing behaviour; fairing is straight and aligned with the base, side colliders connect.](https://i.imgur.com/qJBRRe1.png)

Restock fairing behaviour; fairing is twisted/not aligned with the base, side colliders have a gap:
![Restock fairing behaviour; fairing is twisted and not aligned with the base, side colliders have a gap between each.](https://i.imgur.com/ODJu6nN.png)

Valentina (and parts) pass right through the gap while still colliding with the rest:
![Valentina falls right through the gap though she can walk on the rest.](https://i.imgur.com/TN3Tir1.png)

**List of mods installed:**
 - Restock
 - Collide-O-Scope

**Logs**
N/A

**Comment by Avera9eJoe** [comment]
Craft bug, not ReStock

**Comment by drewcassidy** [comment]
To be fair, the fairing module is extremely cursed
