### ISSUE TITLE
Size 2 nose cone orange variant normal issues

### ISSUE THREAD

**Issue by blowfishpro** [PorktoberRevolution/ReStocked#80]
As always they are much more visible under part highlighting

1) Something weird going on at the cap, can't quite tell what
2) Few sharp edges that should be smooth

![image](https://user-images.githubusercontent.com/10545461/50581760-73b53880-0e11-11e9-8539-b3ed3d8aa276.png)

**Comment by ChrisAdderley** [comment]
That's this:

https://forum.unity.com/threads/seams-apparent-in-unity-when-i-put-on-my-mesh-s.96239/

I've never found an actual workaround. I'll keep trying

**Comment by ChrisAdderley** [comment]
More mitigations applied in b647efb, looks pretty good now

**Comment by blowfishpro** [comment]
Yep, looks better now
