### ISSUE TITLE
Adapter cluster thing - Part selector preview issues

### ISSUE THREAD

**Issue by drewcassidy** [PorktoberRevolution/ReStocked#802]
**Describe the bug**
The MH adapter thingy shows all the variants at once in the part selection menu. All variants except the 4x should be marked IconHidden

**Screenshots**
<img width="1136" alt="Screen Shot 2020-02-17 at 10 01 00 PM" src="https://user-images.githubusercontent.com/3837797/74709100-2fcaf180-51d3-11ea-8359-6a0d83f4149e.png">

**Comment by ChrisAdderley** [comment]
All fixed in latest.
