### ISSUE TITLE
Wolfhound/schnauzer engine 2.5m variant emissive issue

### ISSUE THREAD

**Issue by omega489** [PorktoberRevolution/ReStocked#805]
**Describe the bug**
Art bug. Minor.
Emissive Issue with Wolfhound/schnauzer engine 2.5m variants. At max heat small areas on the support ring glow.

**Screenshots**

![image](https://user-images.githubusercontent.com/23028378/75802822-3f227100-5d75-11ea-9d35-d9ab5be60be1.png)

**Comment by ChrisAdderley** [comment]
Fixed in f8095eb

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/f8095ebf829b640b42ea98406cfe0657275eaabd
