### ISSUE TITLE
Restock RoveMate not aligned to center

### ISSUE THREAD

**Issue by Rodg88** [PorktoberRevolution/ReStocked#807]
The model of the RoveMate rover core is offset a little to the +X.

Screenshot of one wheel being flush with the surface...
![screenshot630](https://user-images.githubusercontent.com/2611674/77540617-81b01700-6ef7-11ea-804b-38e032278091.png)
while the opposite wheel is floating off the surface:
![screenshot631](https://user-images.githubusercontent.com/2611674/77540631-8674cb00-6ef7-11ea-9f71-7d922d6f31f1.png)

Without Restock, the model is centered:
![screenshot632](https://user-images.githubusercontent.com/2611674/77540650-92f92380-6ef7-11ea-89a5-00c7c4b6a4e1.png)
![screenshot633](https://user-images.githubusercontent.com/2611674/77540653-942a5080-6ef7-11ea-8815-0f5789e5faac.png)

**Comment by ChrisAdderley** [comment]
Fixed in d9bd0b6b59a6cc27d22149a0cb414156cf2fb3c0

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/d9bd0b6b59a6cc27d22149a0cb414156cf2fb3c0
