### ISSUE TITLE
Caravel Engine balance

### ISSUE THREAD

**Issue by Porkjet** [PorktoberRevolution/ReStocked#808]
Seems a bit OP to me, compared to other engines it has very high ISP at both ASL and VAC at the same time, extremely good TWR, and it's CHEAP. Caravel clusters for launchers are easily outperforming most other engines in my career playthrough, especially in terms of cost efficiency.
There are some other parts, mostly stock, where one might question balancing, but this one sticks out to me right now.

**Comment by ChrisAdderley** [comment]
Change in latest commit

**Comment by Poodmund** [comment]
https://github.com/PorktoberRevolution/ReStocked/commit/7cdb73d0a35fd310874cacd45c6f5f19cb99933e - Reduced Caravel vacuum Isp to 265/320s from 285/340s, increased mass to 2.0t from 1.6t.

@Porkjet could you please review this adjustment?

**Comment by Poodmund** [comment]
The above change puts it right around the balance level of the Spark and Swivel when plotting Isp Vac against TWR. Plotting Isp Vac against cost it sits almost directly on the trendline and TWR against Cost it sits slightly under the trendline so I'd say its pretty average now. I think this is worth saying, "It's okay to close this" and then see if any further comments/adjustments are required in future playing as the update is used.
