### ISSUE TITLE
Suggestion: extra attach nodes on hemispherical tanks

### ISSUE THREAD

**Issue by Porkjet** [PorktoberRevolution/ReStocked#809]
Big fan of these, I like to use em for orbital crafts external modular tanks and often prefer their appearance to the conical adapter parts when tapering tanks down to smaller attachments.
To do this, I have to surface attach a docking port or similar to the center of the tank dome, and then center it with the move tool snap. 
That works, but for ease of use could you add some attach nodes to the top of the tank domes? thanks!

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/9a2edc59b16ba831ee00f69d9cd8f441167ee146
