### ISSUE TITLE
X200-32 - smoothing issues

### ISSUE THREAD

**Issue by blowfishpro** [PorktoberRevolution/ReStocked#810]
Visible at low lighting angles

![image](https://user-images.githubusercontent.com/10545461/79154441-62810880-7d84-11ea-9b01-efddb98aa8bd.png)

Probably worth checking other sizes too

**Comment by drewcassidy** [comment]
![image0](https://user-images.githubusercontent.com/3837797/79168326-75a0d200-7d9e-11ea-953e-868a2c374f54.jpg)
Also some small UV errors

**Comment by ChrisAdderley** [comment]
Adjusted in d9bd0b6b59a6cc27d22149a0cb414156cf2fb3c0

**Comment by Poodmund** [comment]
![Untitled-1](https://user-images.githubusercontent.com/10106634/80154581-c3e07d00-85b7-11ea-920a-8b985bf368d1.png)

I think there's still some funkiness going on here with these.

**Comment by ChrisAdderley** [comment]
Another attempt at fixing was added.

**Comment by Poodmund** [comment]
![Untitled-1](https://user-images.githubusercontent.com/10106634/80253269-dd91cb00-8670-11ea-8bfd-5bb26271e99b.png)

https://github.com/PorktoberRevolution/ReStocked/commit/c0fbc1d996e3f81579296ae37a871cd1374d768b has resolved the issue for me.

@blowfishpro would you like to confirm its fixed the issue for yourself and then we can call this sorted, if so. 😄

**Comment by blowfishpro** [comment]
You were able to reproduce so if you can't see it anymore we'll call it resolved.
