### ISSUE TITLE
RE-M3 "Mainsail" Liquid Engine - Bell tip UV/Texture issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#811]
![Untitled-1](https://user-images.githubusercontent.com/10106634/79462496-73818200-7fef-11ea-8072-f20cb82b1374.png)

A couple of quads on the tip of the bell are a bit odd, not sure if they've been atlased correctly or if its a texture issue.

**Comment by ChrisAdderley** [comment]
Fixed in f8095eb

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/f8095ebf829b640b42ea98406cfe0657275eaabd
