### ISSUE TITLE
RE-M3 "Mainsail" Liquid Engine - Smoothing Group inside Gas Generator Exhaust Pipe

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#812]
![Untitled-1](https://user-images.githubusercontent.com/10106634/79462784-e25edb00-7fef-11ea-9b2e-5af60d14827d.png)

I think there is a missing smoothing group on the inside of the GG exhaust pipe which, as a result, shows some funky lighting.

**Comment by ChrisAdderley** [comment]
Fixed in f8095eb

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/f8095ebf829b640b42ea98406cfe0657275eaabd
