### ISSUE TITLE
RE-M3 "Mainsail" Liquid Engine - Thrust Transform direction misalignment/rotated

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#813]
![Untitled-1](https://user-images.githubusercontent.com/10106634/79462963-218d2c00-7ff0-11ea-8c1c-a0889200be97.png)

They say a picture says a thousand words. 😅 

Persists through all variants.

**Comment by ChrisAdderley** [comment]
Fixed in f8095eb

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/f8095ebf829b640b42ea98406cfe0657275eaabd
