### ISSUE TITLE
RE-M3 "Mainsail" Liquid Engine - Gas Generator Plumbing on Compact Variants clipping issue.

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#814]
![Untitled-1](https://user-images.githubusercontent.com/10106634/79463332-9eb8a100-7ff0-11ea-985b-e0de6558a7d4.png)

For both of the compact variants, due to the node location the Gas Generator plumbing can end up clipping into a part stacked above it as the depth that the truss structure usually gives does not offset the plumbing.

The Gimbal mounts are nice and almost flush which is perfect, I guess what was intended, so some discussion/thought may be required as to how this can be resolved easily.

**Comment by ChrisAdderley** [comment]
As discussed, this isn't solveable.
