### ISSUE TITLE
RE-M3 "Mainsail" Liquid Engine - Shroud mesh blemish

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#815]
![Untitled-1](https://user-images.githubusercontent.com/10106634/79464192-aaf12e00-7ff1-11ea-930d-af82e1b51d87.png)

Much more noticeable on the white shroud variant, when you view the shroud from a specific range of angles you can spot the mesh seam running top to bottom on the shroud. On the gray variant it blends in with the texture a fair bit.

**Comment by ChrisAdderley** [comment]
af3d8b525a77740d1e7ad8f8144e4bea9356b272 has possible fix

**Comment by Poodmund** [comment]
This _seems_ to have been resolved with https://github.com/PorktoberRevolution/ReStocked/commit/af3d8b525a77740d1e7ad8f8144e4bea9356b272
