### ISSUE TITLE
RE-M3 "Mainsail" Liquid Engine - Main plume FX bleed outside of the bell.

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#816]
![Untitled-1](https://user-images.githubusercontent.com/10106634/79464562-1f2bd180-7ff2-11ea-85ce-3929961daf3c.png)

When the plume FX is active, you can see some of the whiter plume particles bleed outside of the engine bell towards the throat and down the sides of the bell.

**Comment by ChrisAdderley** [comment]
Fixed in f8095eb

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/f8095ebf829b640b42ea98406cfe0657275eaabd
