### ISSUE TITLE
RE-I5 "Skipper" Liquid Fuel Engine - Hole/Gap in plumbing mesh

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#817]
![Untitled-1](https://user-images.githubusercontent.com/10106634/79563977-b30aa580-80a5-11ea-9bd9-a642f11d24fc.png)

Plumbing mesh is disconnected allowing a gap to be seen through the model.

**Comment by ChrisAdderley** [comment]
Fixed in f8095eb

**Comment by Poodmund** [comment]
The area in question has been resolved in https://github.com/PorktoberRevolution/ReStocked/commit/f8095ebf829b640b42ea98406cfe0657275eaabd but, my apologies, I missed another pipe that is experiencing similar issues:

![Untitled-1](https://user-images.githubusercontent.com/10106634/80009594-33c00c00-84c1-11ea-9fc2-c7672f90c956.png)

**Comment by ChrisAdderley** [comment]
Fixed that one too now

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/f22e837cba6a9a83a79ee8c3c25e8d865780c1f7
