### ISSUE TITLE
RE-I5 "Skipper" Liquid Fuel Engine - 1.25m variant actuator piston issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#818]
![Untitled-1](https://user-images.githubusercontent.com/10106634/79564164-067cf380-80a6-11ea-8102-0dbc39482e37.png)

The 1.25m variants have a slight issue with one of the pistons clipping through the damper housing, when gimballing the issue gets accentuated. Screenshot shows actuator in default position.

The far side actuator here is the offending one in the image above.

**Comment by ChrisAdderley** [comment]
Fixed in f8095eb. Maybe not the best but....

**Comment by Poodmund** [comment]
With https://github.com/PorktoberRevolution/ReStocked/commit/f8095ebf829b640b42ea98406cfe0657275eaabd it doesn't bleed outside of the piston housing. Resolved!
