### ISSUE TITLE
RE-I5 "Skipper" Liquid Fuel Engine - Compact variants node placement issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#819]
![Untitled-1](https://user-images.githubusercontent.com/10106634/79564626-eef23a80-80a6-11ea-858f-26e5c0dc4875.png)

Both compact variants have their top attachment node positioned too high which can cause gaps when attachment them in a stack.

**Comment by ChrisAdderley** [comment]
Fixed in f8095eb

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/f8095ebf829b640b42ea98406cfe0657275eaabd
