### ISSUE TITLE
RE-I5 "Skipper" Liquid Fuel Engine - Shroud issues

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#820]
![Untitled-1](https://user-images.githubusercontent.com/10106634/79564936-835c9d00-80a7-11ea-818e-76340efa3c2e.png)

The White/Black and Orange/Grey 1.25m variant shrouds both have a small texture blemish on the shroud.

![Untitled-1](https://user-images.githubusercontent.com/10106634/79566034-c3248400-80a9-11ea-85f3-c2e9f2b852f8.png)

Similar to the issue regarding the Mainsail shrouds, you can see small mesh seams in the shrouds running top to bottom at specific camera angles. Much more noticeable on the white shrouds but also visible on the Orange/Grey shrouds.

**Comment by ChrisAdderley** [comment]
af3d8b525a77740d1e7ad8f8144e4bea9356b272 has possible fix

**Comment by Poodmund** [comment]
With https://github.com/PorktoberRevolution/ReStocked/commit/af3d8b525a77740d1e7ad8f8144e4bea9356b272 its much better. Still slightly apparent when you zoom out further, I guess due to anti-aliasing trying to resolve it but its definitely a lot better. Better enough to be considered resolved.
