### ISSUE TITLE
RE-I5 "Skipper" Liquid Fuel Engine - Main plume FX bleed outside of the bell.

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#821]
![Untitled-1](https://user-images.githubusercontent.com/10106634/79571346-f7e90900-80b2-11ea-80b8-ddbb8a84d5a1.png)

Similar to the Mainsail issue, when the plume FX is active, you can see some of the whiter plume particles bleed outside of the engine bell towards the throat and down the sides of the bell. More noticeable at lower throttle amounts.

**Comment by ChrisAdderley** [comment]
Fixed in f8095eb

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/f8095ebf829b640b42ea98406cfe0657275eaabd
