### ISSUE TITLE
Kerbodyne S4-128/256/512 Fuel Tank - Texture/UV issue on internal tank walls

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#824]
![Untitled-1](https://user-images.githubusercontent.com/10106634/79892092-e167e800-83f9-11ea-8343-a9b00ba29714.png)

It looks as though the UV atlasing on the strengthening ribs on the insides of the tank walls are positioned incorrectly as there are random bits of texture appearing on them and/or mis-aligned.

This occurs on the 128, 256 and 512 tanks but not the 64 tank.

**Comment by ChrisAdderley** [comment]
Fixed in d9bd0b6b59a6cc27d22149a0cb414156cf2fb3c0

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/d9bd0b6b59a6cc27d22149a0cb414156cf2fb3c0
