### ISSUE TITLE
Kerbodyne S4-128/256 Fuel Tank - Texture UV blemish on top of stringer

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#825]
![Untitled-1](https://user-images.githubusercontent.com/10106634/79893883-926f8200-83fc-11ea-9ade-b46a90b42be6.png)

The top face of the pointed stringers seems to be referencing an orange part of the texture which is bleeding out to the external faces of the part slightly.

This affects the 128 and 256 tanks.

**Comment by ChrisAdderley** [comment]
Fixed in d9bd0b6b59a6cc27d22149a0cb414156cf2fb3c0

**Comment by Poodmund** [comment]
It appears that https://github.com/PorktoberRevolution/ReStocked/commit/d9bd0b6b59a6cc27d22149a0cb414156cf2fb3c0 resolved the issue on the 128 tank but not the 256 tank.

**Comment by ChrisAdderley** [comment]
Added more fixes in 6a4d577a181f462de07f446b02fd9fd795f3a38d

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/6a4d577a181f462de07f446b02fd9fd795f3a38d
