### ISSUE TITLE
Kerbodyne S3-S4 Adapter Tank - Greeble needs smoothing group applied

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#827]
![Untitled-1](https://user-images.githubusercontent.com/10106634/79907846-33b50300-8412-11ea-9b6b-05b320af6b44.png)

I think that this greeble might has escaped having a smooth being applied to the faces, repeated 4 times around the part.

**Comment by ChrisAdderley** [comment]
Fixed in d9bd0b6b59a6cc27d22149a0cb414156cf2fb3c0

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/d9bd0b6b59a6cc27d22149a0cb414156cf2fb3c0
