### ISSUE TITLE
Kerbodyne S3-S4 Adapter Tank - Mesh hole on lower tank butt centre.

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#828]
![Untitled-1](https://user-images.githubusercontent.com/10106634/79908091-90182280-8412-11ea-95ec-43d87fab8195.png)

There is a gap in the mesh on the bottom tank in the centre where the 'plug' meets the 'tank walls'.

**Comment by ChrisAdderley** [comment]
Fixed now

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/0ca921bb0517c6300fb4e2570935f04d8cf47626
