### ISSUE TITLE
Kerbodyne S3-S4 Adapter Tank - Top of part appears to be less than 3.75m diameter

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#829]
![Untitled-1](https://user-images.githubusercontent.com/10106634/79908272-d5d4eb00-8412-11ea-86fe-e73819fc1b09.png)

I expect this may be too far down the line to resolve(?) but the diameter at the top of the part seems to be slightly less than the 3.75m intended, here it is shown against a 24 sided 3.75m cylinder and also against the ReStock 3.75m tank.

**Comment by ChrisAdderley** [comment]
Fixed in d9bd0b6b59a6cc27d22149a0cb414156cf2fb3c0

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/d9bd0b6b59a6cc27d22149a0cb414156cf2fb3c0... nice!
