### ISSUE TITLE
Kerbodyne S3-S4 Adapter Tank - Potential black colour mismatch

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#830]
![Untitled-1](https://user-images.githubusercontent.com/10106634/79911671-a45f1e00-8418-11ea-8191-c00b0be69ebc.png)

Black colouring appears to be of a different shade to the tanks. Rotated the part vertically to see if its the lighting and it still seems a little different so might be worth a confirmation.

**Comment by ChrisAdderley** [comment]
Not really different but the noise pattern might have been affecting it, reduced the strength of noise in  d9bd0b6b59a6cc27d22149a0cb414156cf2fb3c0

**Comment by Poodmund** [comment]
A bit better with the graduation between the parts. Good enough to be resolved with https://github.com/PorktoberRevolution/ReStocked/commit/d9bd0b6b59a6cc27d22149a0cb414156cf2fb3c0
