### ISSUE TITLE
T-12 & T-18 Structural Tube - Variant Collider Issues

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#831]
![Untitled-1](https://user-images.githubusercontent.com/10106634/80104786-91129680-856f-11ea-94eb-3d90edce0453.png)

The Medium variants of the 1.25m tubes seem to be using the collider for the Medium-Short variants. Doesn't seem to occur in Vanilla so I predict its a ReStock .mu issue.

![Untitled-2](https://user-images.githubusercontent.com/10106634/80104841-a687c080-856f-11ea-91bd-68914f3446dd.png)

The Medium variants' collider does not extend down to the bottom of the part model mesh. In Vanilla the visual mesh and collider mesh align at the bottom edge so either the visual mesh might be too long or the collider is not the same length as the Vanilla one.

**Comment by ChrisAdderley** [comment]
Should be addressed in 6a4d577a181f462de07f446b02fd9fd795f3a38d

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/6a4d577a181f462de07f446b02fd9fd795f3a38d
