### ISSUE TITLE
AE-FF5 Airstream Protective Shell (5m) - Texture blemish/UV bleed on fairing panels

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#832]
![Untitled-1](https://user-images.githubusercontent.com/10106634/80114895-01271980-857c-11ea-96ce-20e52cba0c97.png)

There seems to be a small bit of, possibly, UV bleeding at the top half of the fairing panels on all variants resulting in a thin, aliased line/band.

**Comment by ChrisAdderley** [comment]
This is the result of BEEEEG stretching on wider fairing textures. Those blobs on investigation are the tiny fairing bolt holes. 6a4d577a181f462de07f446b02fd9fd795f3a38d adds a new texture for 5m which has less (ie no) detail to be stretched - no detail, no problem

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/6a4d577a181f462de07f446b02fd9fd795f3a38d. Black & White variant needs removing as per discussion off GitHub but that will be taken care of in due course.
