### ISSUE TITLE
AE-FF5 Airstream Protective Shell (5m) - Erroneous duplicate part showing in part catalogue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#833]
![Untitled-1](https://user-images.githubusercontent.com/10106634/80115790-1781a500-857d-11ea-8188-415cda1a7b56.png)

There is a rogue duplicate part of the 5m fairing appearing in the part catalogue. This is with MH installed.

With MH uninstalled, the rogue part still persists but the "good" 5m Fairing part disappears.

**Comment by ChrisAdderley** [comment]
6a4d577a181f462de07f446b02fd9fd795f3a38d fixed the loc strings (this is the RS+ part)

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/6a4d577a181f462de07f446b02fd9fd795f3a38d
