### ISSUE TITLE
Protective Nose Cone Mk16A - Orange tint on internal structure for Orange variant

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#834]
![Untitled-1](https://user-images.githubusercontent.com/10106634/80117762-79dba500-857f-11ea-9855-0f7cf02379ad.png)

Please refer to the screenshot above, the orange variant has an orange tint being applied to the metal areas of the internal structure.

**Comment by ChrisAdderley** [comment]
6a4d577a181f462de07f446b02fd9fd795f3a38d changes mesh to be separate

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/6a4d577a181f462de07f446b02fd9fd795f3a38d
