### ISSUE TITLE
Protective Nose Cone Mk16A - Orange variant nose cap normals issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#835]
![Untitled-1](https://user-images.githubusercontent.com/10106634/80119732-fc656400-8581-11ea-8805-6275025156ec.png)

Issue with bumps appearing on the nose cap.

**Comment by ChrisAdderley** [comment]
6a4d577a181f462de07f446b02fd9fd795f3a38d fix yay

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/6a4d577a181f462de07f446b02fd9fd795f3a38d
