### ISSUE TITLE
Engine Plates 1.25m thru 5m - Boatail variants lower stack node

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#836]
![Untitled-1](https://user-images.githubusercontent.com/10106634/80120764-60d4f300-8583-11ea-85ce-13ac194f7b25.gif)

The boattail variants of the engine plates don't exist in Vanilla so we have the creative liberty to make changes depending on our intent. With the boattail variants of the plates, should they have lower stack attach nodes as, if used, there is no connecting structure formed between the engine plate above and whatever is stacked below? If removed, can the jettison module be disabled per variant?

Would appreciate feedback/thoughts for anyone involved.

**Comment by drewcassidy** [comment]
the 1.875m one is aligned to the Titan launch stand in Modular Launch Pads, others are just the bottom node position of the second smallest shrouded variant. Honestly I just wanted it far enough away to not get in the way of placing engines inside

**Comment by drewcassidy** [comment]
Looks like I got the node size on the 5m one wrong though

**Comment by Poodmund** [comment]
> the 1.875m one is aligned to the Titan launch stand in Modular Launch Pads, others are just the bottom node position of the second smallest shrouded variant. Honestly I just wanted it far enough away to not get in the way of placing engines inside

Can I move the 1.875m node to where it should be with reference to the 2nd shortest shroud and then add a compatibility patch for Modular Launch Pads to move it back to where it is now? That would seem to me like the best way to handle it.

**Comment by Poodmund** [comment]
Supplment to implmenting the above change, there is a difference in the lower node position between the MH patched 1.875m Engine Plate and the RS+ 1.875m engine plate.

https://github.com/PorktoberRevolution/ReStocked/blob/master/Distribution/Restock/GameData/ReStock/PatchesMH/Coupling/restock-mh-engineplates.cfg#L94

https://github.com/PorktoberRevolution/ReStocked/blob/master/Distribution/RestockPlus/GameData/ReStockPlus/Parts/Coupling/1875/restock-engineplate-1875-1.cfg

Is this difference supposed to exist or are they intended to be the same? As someone who has no experience with Modular Launch Pads, could you specify which value to use?

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/1d5ae52fed386a60c4fe9cf7f982a45821ae48f2. To note, I also changed the 5m node size to '4' and have sinced, locally, revised the ModularLanuchPads.cfg patch so that the RS+ engine plate needs RS+ and not RS base. Will push in due course.

**Comment by drewcassidy** [comment]
the 0.05m difference is because the RS+ versions have the model moved slightly so the origin is not on the lower face of the engine plate. otherwise radial attachment behaves strangely (like it does in the MH version)
