### ISSUE TITLE
Engine Plates 1.25m thru 5m - Normals striping/banding on top face

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#837]
![Untitled-1](https://user-images.githubusercontent.com/10106634/80151276-adcfbe00-85b1-11ea-8389-9059533474ab.png)

The top, grey face on the Engine Plates have a stripey normals(?) issue occurring. The 1.25m plate is small enough that the issue is not as noticeable but you can still see the same issue if its an easy fix.

**Comment by drewcassidy** [comment]
That just looks like Unity's shadow engine having trouble? I don't see this in the editor

**Comment by Poodmund** [comment]
The stripes don't follow any of the model topology or correlate to anything on the normal map so I would guess you're likely right on that.. I'll mark this as closed for now.
