### ISSUE TITLE
Engine Plate 5m - Orientation of tracking decals on boattail variants

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#838]
![Untitled-1](https://user-images.githubusercontent.com/10106634/80153661-e1144c00-85b5-11ea-818a-93d840220876.png)

I'm not sure if the tracking marker decals on the boattail variants are all supposed to be oriented in the same direction.

Feel free to close this issue if this is not the case.

**Comment by drewcassidy** [comment]
as intended
