### ISSUE TITLE
Kerbodyne KE-1 "Mastodon" LF Engine - Engine Bell clips with 2.5m Boattail variant

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#839]
![Untitled-1](https://user-images.githubusercontent.com/10106634/80221665-87effb00-863d-11ea-8c41-e70798c7ffdb.png)

When fully gimballed, the engine bell clips slightly into the 2.5m Boattail shroud.

**Comment by ChrisAdderley** [comment]
Moved ring up somewhat, clears better now.

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/c0fbc1d996e3f81579296ae37a871cd1374d768b and subsequently https://github.com/PorktoberRevolution/ReStocked/commit/8cb7a6818114b9cf8201b07bf4ffca220549a3c8
