### ISSUE TITLE
Kerbodyne KE-1 "Mastodon" LF Engine - 2.5m Truss variant truss smaller than 2.5m

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#840]
![Untitled-1](https://user-images.githubusercontent.com/10106634/80221842-c4bbf200-863d-11ea-98e8-3f90dea34d5a.png)

The 2.5m circular truss mounting ring is quite a bit smaller than 2.5m in diameter. Not an issue other than visually a little odd in stack.

**Comment by ChrisAdderley** [comment]
This is done with most of the engines to some degree to stop the shroud from clipping.

**Comment by ChrisAdderley** [comment]
Increased the diameter a bit

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/c0fbc1d996e3f81579296ae37a871cd1374d768b
