### ISSUE TITLE
Kerbodyne KE-1 "Mastodon" LF Engine - 2.5 Truss, 3.75 Boat & Compact Top Node issues

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#841]
![Untitled-1](https://user-images.githubusercontent.com/10106634/80222273-7d823100-863e-11ea-9491-a147c4152556.png)

The 2.5m Truss mount has a small gap between the top mounting ring and a part stacked above.

![Untitled-2](https://user-images.githubusercontent.com/10106634/80222280-807d2180-863e-11ea-99ba-596b63bec16f.png)

The 3.75m Boattail has a gap between the top of the shroud and a part stacked above.

![Untitled-3](https://user-images.githubusercontent.com/10106634/80222288-82df7b80-863e-11ea-9c8f-e8434af075d2.png)

The Compact variant has its gimbal and mounting structure clipped into when stacking a part above (not sure this can be resolved easily without some big reworking).

**Comment by ChrisAdderley** [comment]
Fixed a., your change fixed b., and c. is not fixable.

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/c0fbc1d996e3f81579296ae37a871cd1374d768b and https://github.com/PorktoberRevolution/ReStocked/commit/8cb7a6818114b9cf8201b07bf4ffca220549a3c8. Agreed that c) cannot be fixed as it would take redoing the mesh topography and layout for that single variant.

**Comment by ChrisAdderley** [comment]
Also a note: this was a choice that was made to make the engine as beefy as possible and still fit within the footprint.

**Comment by Poodmund** [comment]
I remember the lengthy discussions and diagrams. I think we've got a great outcome.
