### ISSUE TITLE
Main directory name change

### ISSUE THREAD

**Issue by Rodg88** [PorktoberRevolution/ReStocked#844]
Making a fresh install with the currant master branch, the main restock directory is called "Restock" while the install checker is expecting "ReStock", so you get an error. 
![unknown](https://user-images.githubusercontent.com/2611674/80302259-46ea1900-87ec-11ea-9ead-c1eababbfbae.png)

**Comment by ChrisAdderley** [comment]
There was no name change.
![image](https://user-images.githubusercontent.com/5642064/80311720-19728080-8796-11ea-8017-e52a124799da.png)
