### ISSUE TITLE
New Mainsail gimbal on wrong axis

### ISSUE THREAD

**Issue by Rodg88** [PorktoberRevolution/ReStocked#845]
![screenshot792](https://user-images.githubusercontent.com/2611674/80303654-d8f61f80-87f4-11ea-9dd4-c41374431b0e.png)
The new mainsail gimbals on roll and pitch, not pitch and yaw.

**Comment by Poodmund** [comment]
Can confirm that its not functioning correctly in pitch or yaw, see the attached video with on-screen display when first pitching, then yawing, then rolling the array of motors: https://www.youtube.com/watch?v=zak2fCU_yvE

**Comment by ChrisAdderley** [comment]
Fixed in latest commit

**Comment by Poodmund** [comment]
Gimbal fixed with https://github.com/PorktoberRevolution/ReStocked/commit/7cdb73d0a35fd310874cacd45c6f5f19cb99933e and thrustTransform zeroed out as much as possible with https://github.com/PorktoberRevolution/ReStocked/commit/3c58876a4f38c332521ff0d2dc1a4f9944ac0859
