### ISSUE TITLE
Investigating lights showing through tanks

### ISSUE THREAD

**Issue by Rodg88** [PorktoberRevolution/ReStocked#848]
Issue most noticeable with engine lighting installed, but also occurs with stock lights. Lights positioned under a tank will show up through the tank walls. More visable on SOFI or darker tank colours.

![screenshot799](https://user-images.githubusercontent.com/2611674/80305246-03e57100-87ff-11ea-81cb-62a1e7e12720.png)

![screenshot809](https://user-images.githubusercontent.com/2611674/80305359-9c7bf100-87ff-11ea-8a31-f31435313d3b.png)

The 1.875m tanks seem to have less of a problem with this
![screenshot811](https://user-images.githubusercontent.com/2611674/80305411-cb926280-87ff-11ea-90f0-26ea8a3d70c8.png)

The structural plate doesn't exhibit this behavior. Capsules also seem unaffected.
![screenshot805](https://user-images.githubusercontent.com/2611674/80305203-c97bd400-87fe-11ea-9f6c-4a64c96f6df6.png)

No post-processing mods installed, just EVE/SVE, and scatterer.
![lighting bugmods](https://user-images.githubusercontent.com/2611674/80305088-fda2c500-87fd-11ea-8244-50c261161e6c.png)

Not seen in stock tanks:
![screenshot808](https://user-images.githubusercontent.com/2611674/80305192-b8cb5e00-87fe-11ea-9041-73d50e6608b7.png)

**Comment by Porkjet** [comment]
Huh odd one. Perhaps related to shadow settings?
Do these stock tanks even use specularity?

**Comment by ChrisAdderley** [comment]
Investigation reveals nothing to be done.
