### ISSUE TITLE
Advanced grabbing unit - Crash to desktop when placing back in part menu

### ISSUE THREAD

**Issue by drewcassidy** [PorktoberRevolution/ReStocked#852]
**Describe the bug**
> deleting the Restock claw by dropping it back into the part catalog crashes KSP to desktop. Pressing the delete key works just fine. 

[from the forum](https://forum.kerbalspaceprogram.com/index.php?/topic/182679-19x-restock-revamping-ksps-art-may-2ndth-2020/&do=findComment&comment=3782113)

**List of mods installed:**
 - Restock

**Comment by drewcassidy** [comment]
I'm unable to reproduce this bug

**Comment by ChrisAdderley** [comment]
I think we can close it then.
