### ISSUE TITLE
Restock makes variants of the Making History's have mass ≤ 0.000t

### ISSUE THREAD

**Issue by iGGnite** [PorktoberRevolution/ReStocked#853]
Per title, 
Mods: restock
![screenshot27](https://user-images.githubusercontent.com/36937528/81719493-6edcac00-947d-11ea-8573-c39aee17e037.png)
![screenshot26](https://user-images.githubusercontent.com/36937528/81719500-700dd900-947d-11ea-944f-223821d93733.png)

**Comment by drewcassidy** [comment]
What version of the game are you using?

**Comment by iGGnite** [comment]
1.8.1 with the 1.1.1 release

**Comment by drewcassidy** [comment]
ugh, I forgot 1.8 has different masses for the engine plates, will have to figure... something out

**Comment by drewcassidy** [comment]
would it be ok if the engine plates got the 1.9 masses?

**Comment by iGGnite** [comment]
Yes that would be fine
