### ISSUE TITLE
Service Bay 1.25m Texture Clipping

### ISSUE THREAD

**Issue by SkiRich** [PorktoberRevolution/ReStocked#854]
Quick report.  The Service Bay Part is a touch too small.  When putting it over a part and sliding it down over the same part, the texture in some parts is clipping.
Use the Service Bay 1,25m and the MK1 Liquid Fuel fuselage as a test.

**Comment by ChrisAdderley** [comment]
Can you clarify this? It should be clipping, all parts of the same size category should be identical (or very close) to the same size.

**Comment by SkiRich** [comment]
The original service bay has two attach points, allowing it to slide over the same size parts, like a cover.  While its technically listed as 1.25, it clearly looks a slight bit larger to facilitate that coverup.
While the Restock asset appear exactly 1.25, so when you slide it over like a cover, some of the artwork of the compionent, such as the liquid fuel fuselage pop through and the graphics card begins to toggle of cycle between textures.  That point looks to be flickering.
If you made the service bay 1.28 or something like that, it would fix the texture bleed.

**Comment by ChrisAdderley** [comment]
I'm pretty sure the vast size inconsistency of stock is a bug, not a feature, at least, it's something we have tried to fix.

If you really need this you can create a moduleManager patch to adjust the X and Y scales of the part by 1.01 or something similar, that should be pretty easy.

**Comment by Poodmund** [comment]
At the danger of sounding combative, what has been pointed out here as a 'feature' of Vanilla KSP gameplay is actually considered to be the most popular, upvoted 'bug' on their Issue Tracker.

![Untitled-1](https://user-images.githubusercontent.com/10106634/82078513-1dc8f400-96d9-11ea-8018-11222b2010c9.png)

**Comment by SkiRich** [comment]
> 
> 
> I'm pretty sure the vast size inconsistency of stock is a bug, not a feature, at least, it's something we have tried to fix.
> 
> If you really need this you can create a moduleManager patch to adjust the X and Y scales of the part by 1.01 or something similar, that should be pretty easy.

I mod for other games but I havent modded for this one.
If you could provide a sample code snipet I will do that, thank you for the suggestion.
