### ISSUE TITLE
1.875m heat shield - undersized and offset

### ISSUE THREAD

**Issue by drewcassidy** [PorktoberRevolution/ReStocked#856]
**Describe the bug**
The top surface of the 1.875m heat shield is offset and undersized when compared to other 1.875m parts

**Screenshots**
<img width="639" alt="Screen Shot 2020-05-17 at 11 07 55 PM" src="https://user-images.githubusercontent.com/3837797/82179548-73490080-9893-11ea-9eae-7e2186439ba5.png">
<img width="667" alt="Screen Shot 2020-05-17 at 11 07 40 PM" src="https://user-images.githubusercontent.com/3837797/82179574-81971c80-9893-11ea-848c-ca598c17ee8c.png">

**List of mods installed:**
 - Restock

**Comment by ChrisAdderley** [comment]
done
