### ISSUE TITLE
Engine Plates having crossfeed added please

### ISSUE THREAD

**Issue by theJesuit** [PorktoberRevolution/ReStocked#857]
I like to use engine plates for many things, but recently a second stage began draining a third stage whilst circularising.  Investigation shows that (with enhanced tweakables on) engine plates in both Making History and ReStockPlus have no cross feed toggle like the decouples do.

I believe that this would be an enhancement that would benefit both the Squad and Restock parts if ReStockPlus was installed.

The engine plates cfg would need this added:

MODULE
	{
		name = ModuleToggleCrossfeed
		crossfeedStatus = false
		toggleEditor = true
		toggleFlight = true
	}

**Comment by drewcassidy** [comment]
Crossfeed is disabled on the lower node in the next version. The toggle won't actually work because squad

**Comment by theJesuit** [comment]
Ah... I see why.  Thank you for looking into it.
