### ISSUE TITLE
OKTO2 Probe Core - Smoothed mesh normals affecting surface attachment

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#865]
The chamfered edges on the Vanilla collider are hard edges whereas the ones on the ReStock collider mesh normals are smoothed. This is causing users issues when trying to surface attach parts to the thin sides of the probe core.

![Untitled-1](https://user-images.githubusercontent.com/10106634/84014475-48256e80-a972-11ea-8041-4d076096eab4.png)

Top collider is Vanilla, bottom collider is ReStock.

Most recent report from a user can be found here: https://forum.kerbalspaceprogram.com/index.php?/topic/182679-19x-restock-revamping-ksps-art-may-29-2020/&do=findComment&comment=3798903

**Comment by ChrisAdderley** [comment]
fcafab306fde1e92913b3b0ab56755351d25f56a has the normal fix applied to all the cores including this one.

**Comment by Poodmund** [comment]
![Untitled-1](https://user-images.githubusercontent.com/10106634/86458981-06dc7080-bd1e-11ea-9c1a-d1b1b9d081ae.png)

I'm seeming to be unable to now srfattach parts to the central areas of the side of the OKTO2 without them being slightly angled off normal.

**Comment by ChrisAdderley** [comment]
Closing in favour of #886 to put all these issues in the same place.
