### ISSUE TITLE
Surface attachment issues

### ISSUE THREAD

**Issue by c-lipka** [PorktoberRevolution/ReStocked#866]
Surface attachment for Kerbodyne ADTP-2-3 (`Size3To2Adapter.v2`) is seriously borked; the collider isn't anywhere near where it should be.

Also, as reported a few weeks ago already, issue #862 still persists in 1.1.2.

**Comment by ChrisAdderley** [comment]
Looks like it's another one of those Squad colliders that is broken when imported but not visibly so. 
Replaced it with one of our own making in  d34d2021d70ed4fa9c8ae4f647ae8e05a83b0673

**Comment by ChrisAdderley** [comment]
Closing in favour of #886 to put all these issues in the same place.
