### ISSUE TITLE
X200-64 - smoothing issues

### ISSUE THREAD

**Issue by blowfishpro** [PorktoberRevolution/ReStocked#867]
Revenge of #810

![screenshot201](https://user-images.githubusercontent.com/10545461/85956944-f1420200-b93d-11ea-947c-ef504980d14c.png)

**Comment by ChrisAdderley** [comment]
I fixed this by just changing the smoothing algorithm completely. Now the edges are a little sharper but the whole thing works better.

**Comment by blowfishpro** [comment]
I see.

Yep, that fixes it.
