### ISSUE TITLE
SC-9001R doesn't count as a Materials Bay in the contracts. 

### ISSUE THREAD

**Issue by auden100** [PorktoberRevolution/ReStocked#868]
I have a contract that requires the Materials Bay. I installed the radial science jr. It doesn't count as a Materials Bay for the contract. 

**List of mods installed:**
 - Restock, x Science, Click through Blocker, B9 Part Switch, Boulder CO, Chatterer, Community Cat Kit, Community Res Pack, Community Tech Tree, EVE, KAS, Kerbal Engineer, KIS, KSP Rescue Pod Fix, Maneuver Node Evolved, MechJeb2, NavyFish, NearFutureProps, Planetary Base Inc, Restock, Restock Rigid Legs, Scansat, Scatterer, Squad, Squad Expansion, Station Parts Expansion Metal, STation Parts Expansion Redux, Surface Lights, Time Control, Tracking Station Evolved, Trigger Tech, Mod Manager, KSP File Localizer

**Comment by Poodmund** [comment]
@auden100 what contract was this for? The only Stock contracts that require these two parts are the Satellite contracts which we cater for with this file: https://github.com/PorktoberRevolution/ReStocked/blob/master/Distribution/RestockPlus/GameData/ReStockPlus/Patches/Science/satellite-contracts.cfg

If you were using a mod that added this contract into the game then that mod would require a patch to allow it to consider the ReStock+ parts as substitutes. A little more information here is required, I think. :D

**Comment by auden100** [comment]
Thanks for the quick attention. 
Hopefully this screenshot shows what's going on a little: 
![KSPMaterialsBay](https://user-images.githubusercontent.com/67606651/86286526-e4940700-bbe6-11ea-8f37-19f5d9194041.jpg)

I have checked and verified that I have that cfg file. I don't believe that my mods have added this contract, but I'm not entirely sure. I have checked and verified that a normal Science Jr. fulfills the criteria, but not the radial version. If there something else I can do, let me know.

**Comment by Poodmund** [comment]
Would you mind uploading your ModuleManager.ConfigCache file found in the GameData folder from this install, please?

**Comment by Poodmund** [comment]
I've just tested this and its working as intended on a Vanilla KSP 1.9.1 with ReStock and ReStock+, see screenshot:

![Untitled-1](https://user-images.githubusercontent.com/10106634/86295467-9b47b580-bbee-11ea-98f1-3e062d66d93e.png)

So I think another mod is either interferring with the Satellite contract generation (which will show up in the Module Manager cache file) or possibly this contract was accepted in your playthrough prior to ReStocked 0.1.4/10th May 2019?

**Comment by auden100** [comment]
I wasn't playing KSP before May 2019. It could be some kind of mod conflict. 
[ModuleManagerConfigCache.zip](https://github.com/PorktoberRevolution/ReStocked/files/4863052/ModuleManagerConfigCache.zip)

**Comment by Poodmund** [comment]
The ReStock+ parts are correctly showing up in your Module Manager config cache file as valid parts to use in the completion of the Satellite contracts offered... so I am not sure as to what is going on. Did you accept/take on this contract prior to installing ReStock+?

**Comment by auden100** [comment]
Okay. It is very possible that I accepted the contract prior to installing Restock+. I can accept that. 

Thanks for checking it out, and all the hard work in developing this mod.

**Comment by drewcassidy** [comment]
Can this be closed now?

**Comment by Poodmund** [comment]
Yep, sorry. I think its probably due to Auden100 accepting the contract prior to installing RS+, I cannot think of any other case where this behaviour could occur.
