### ISSUE TITLE
Rigid Landing Legs deploy animation is faulty

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#869]
The deploy animations for the restock-leg-1-rigid, restock-leg-2-rigid and restock-leg-3-rigid parts all go from undeployed to immediately fully deployed. The retract animations are fine, however.

Reproduction Steps: Put any/all 3 of the 'rigid' leg parts on a craft starting retracted, launch the vessel and press 'G' on the pad and the legs will all immediately deploy to their fully deployed state.

**Comment by drewcassidy** [comment]
Should be fixed in e5adf30e709e828cffd1201280e5eef11be69903

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/e5adf30e709e828cffd1201280e5eef11be69903
