### ISSUE TITLE
1.10 All fairings are gone. Can't build or edit. 

### ISSUE THREAD

**Issue by auden100** [PorktoberRevolution/ReStocked#870]
Since 1.10 I have had no fairings. They cannot be built or edited, and do not appear on saved crafts. 

**List of mods installed:**
 - Restock
 - Making History and Breaking Ground DLCs 
 - Module Manager
 - No other mods installed.

**Comment by blowfishpro** [comment]
Thanks for the report.  1.10 contained a lot of changes to the fairings and something definitely broke.  We will have to look into this.

**Comment by blowfishpro** [comment]
On a brighter note, we may be able to remove the Restock module that modifies the fairing materials, the stock variant module should handle that now.

**Comment by TjhVarga** [comment]
Is it possible to edit that file myself, or do I need to wait for an update? I have attempted to remove the fairing texture file and the restock-payload-fairing.cfg file, but I that doesnt fix it at all

**Comment by blowfishpro** [comment]
Wait for now.  We don't really understand the scope of the problem yet, and we don't want to guess at quick fixes that might just mess up your install more.

**Comment by darchambault** [comment]
Disabling/removing both the {{Patches\Payload\restock-fairing-bases.cfg}} and {{PatchesMH\Payload\restock-mh-fairing-bases.cfg}} files makes the fairings behave correctly again, although it also means fairings are now the stock versions again.

**Comment by TjhVarga** [comment]
thats fine, thanks

**Comment by TjhVarga** [comment]
![Screen Shot 2020-07-03 at 8 08 20 pm](https://user-images.githubusercontent.com/61438870/86460358-95c3aa00-bd6b-11ea-8416-2bd7123c8a2d.png)
mine looks like this after removing the files that you specified

**Comment by blowfishpro** [comment]
So it's looking like this is a wider issue that affects more than Restock.  Fortunately the devs have indicated that it will be fixed in KSP 1.10.1.  No guarantee of course that the fairings will "just work" then, they might still require some adjustments on our end.

**Comment by TjhVarga** [comment]
Does anyone have an idea as to when KSP 1.10.1 will be released?

**Comment by blowfishpro** [comment]
There has been no information other than Squad confirming a few bugs like this.  But the lack of information should tell you approximately what stage of the development process it's in

**Comment by BoboSpr** [comment]
In the image that @TjhVarga just posted, you can see that the 2.5m fairing is gone. I had the same problem, as I couldn't use the fairing in any rockets. I tried whitelisting the three fairing parts from Squad and that seemed to do the trick!

**Comment by Anysdora** [comment]
> In the image that @TjhVarga just posted, you can see that the 2.5m fairing is gone. I had the same problem, as I couldn't use the fairing in any rockets. I tried whitelisting the three fairing parts from Squad and that seemed to do the trick!

Can you tell me how to join the part to whitelist？

**Comment by TjhVarga** [comment]
Tutorial on how to whitelist parts:

https://github.com/PorktoberRevolution/ReStocked/wiki/Restoring-Stock-Parts

KSP 1.10.1 came out and still hasn't fixed anything. The magnometer boom is gone as well (as in its not even on the parts list). Any idea as to when restock for 1.10 will come out?

**Comment by Poodmund** [comment]
@ChrisAdderley can we now close this issue with all the fixes that have been made for the upcoming 1.2.0 update?

I did not encounter any issues in my KSP 1.10.1 test install.

**Comment by theonegalen** [comment]
I don't have any fairing issues  in 1.10.1 either.

**Comment by TjhVarga** [comment]
Have you whitelisted the parts, and does the magneometer boom show up?

**Comment by theonegalen** [comment]
> Have you whitelisted the parts, and does the magnetometer boom show up? And does Restock+ work with 1.10.1?

I did have to mess around with some things to get it to work. I didn't bother whitelisting the magnetometer because I'm using the one from DMagic's Orbital Science.

**Comment by TjhVarga** [comment]
OK, am I better off waiting for the next version of restock, considering it is almost done? or can you share what you did?

**Comment by theonegalen** [comment]
There definitely could be more issues that I'm not aware of, so it's probably best to wait.

**Comment by Poodmund** [comment]
@theonegalen and @TjhVarga, could you both please confirm that following ReStock v1.2.0 release that this is no longer an issue for you?

**Comment by TjhVarga** [comment]
Yes, It works amazingly. I did encounter one small problem when loading up
the making history rosetta mission, however. It's only small, and the
problem is that the fairing base sinks into the second stage tanks, and the
tall launch stability enhancer didn't render the truss, and the solar
panels on the rosetta craft stick out of the fairings. I'm not too sure if
that is a KSP problem though. That's all.

Thanks for the new release!

**Comment by Poodmund** [comment]
> I did encounter one small problem when loading up the making history rosetta mission, however. It's only small, and the problem is that the fairing base sinks into the second stage tanks, and the tall launch stability enhancer didn't render the truss, and the solar panels on the rosetta craft stick out of the fairings. I'm not too sure if that is a KSP problem though.
Yeah that's due to the KSP Stock craft being part clipped. Due to Stock parts being of random sizes i.e. they don't adhere to their size profiles, when parts are clipped they don't Z-fight as you can have, like, a 1.30m diameter decoupler clipped into a 1.20m diamter tank (exaggeration). ReStock actually adheres to size profile so part clipping sometimes causes Z-fighting.

Anyway, as the original issue is resolved I'll close this issue.
