### ISSUE TITLE
Twin Boar mesh issues

### ISSUE THREAD

**Issue by Rodg88** [PorktoberRevolution/ReStocked#887]
The Twin Boar has some seams in the normals:
![image](https://user-images.githubusercontent.com/2611674/89708601-e908c800-d9bb-11ea-9d43-8e401a5b1e8e.png)

And the flag mesh is floating above the tank
![image](https://user-images.githubusercontent.com/2611674/89708638-266d5580-d9bc-11ea-9575-956d349b3af2.png)

Using the master branch from Aug 7

**Comment by ChrisAdderley** [comment]
All should be fixed in latest commit.

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/f81a038f8f287cb10c11cbaf4bc227a0f084ebe5
