### ISSUE TITLE
Decouplers and Separators - Texture/UV Layout/Model rotation issues

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#890]
This affects both Decoupers and Separators indentically.

The 5m MH and RS+ parts could do with rotating 45 degrees so that the indentification symbols line up with the other sized parts, see images on left side below.

The external face texture on the 3.75m Classic variant on both parts could do with rotating through 90 degrees so that the indentification symbols align with the other parts (to verify the issue, switch between the classic and default variant and see how the pattern layout switches through 90 degrees). See the images on the right side below.

![Untitled-1](https://user-images.githubusercontent.com/10106634/90334023-78b50480-dfc2-11ea-8434-5b8a2898a6a0.png)

Also, it seems that the 5m Decoupler and Separator do not have a 'Classic' variant. Not sure if this is intended or not.

**Comment by ChrisAdderley** [comment]
d5b4212d86c1da37c1ef098c56d6cbfbfe3d4d73

**Comment by Poodmund** [comment]
![Untitled-1](https://user-images.githubusercontent.com/10106634/90557256-190d5380-e192-11ea-9c41-52f98511cecc.png)

The separator is resolved but the decoupler seems to be pulling the orange colour from the orange/grey variant and doesn't seem to be rotated around to the correct alignment as the separator part was.

**Comment by ChrisAdderley** [comment]
54c9fcc342436a9f7bbd69299b4c5e055ec5d47d best it will get

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/54c9fcc342436a9f7bbd69299b4c5e055ec5d47d
