### ISSUE TITLE
KV-1, KV-2 & KV-3 Reentry Modules - Texture Seam Issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#891]
![Untitled-1](https://user-images.githubusercontent.com/10106634/90342143-d31f8680-dffd-11ea-9457-ec87905900eb.png)

Apparent in all 3 command pods on the opposite side to the decoupling arm, here (where the arm is not present) the tiles do not tesselate and a visible seam is present. Could, maybe, a verticle seam joint be introduced to break up the tesselation at this point to visually hide what is happening here?

**Comment by AstroWell** [comment]
UV Mirror Issue, i've solved a lot of those, but don't see how to fix this one.
1024x1024 for all those 3 Pod have needed too much mirroring, and with those tiles everywhere, difficult to match on all side.
Not sure this visual issue could be fixed.

**Comment by Poodmund** [comment]
I suggest that a visual joint be introduced running vertically down from the top circular seam down to the bottom connecting ring. It could be as simple as a protruding ridge like a metal covering strip with the tiling pattern feeding into the underside. This would visually hide the issue with the tesselation.

Unfortunately this issue was the first thing I spotted when I opened the part in the editor so I would presume that a large amount of users would spot it too.

**Comment by AstroWell** [comment]
i have eventually a fix, but this is made on the asset i have on my side, no idea if the fix could be send to Andrew without problem, but i suppose that not too complex. 
![screen_5120x2880_2020-08-18_14-57-57](https://user-images.githubusercontent.com/30159391/90516411-3cb9a500-e164-11ea-8086-4ba2e4821d59.jpg)

**Comment by Poodmund** [comment]
That looks superb. Okay I guess at this point it's probably worth waiting for some clarification from @drewcassidy as to the state of the assets before moving forward with a fix.

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/f43be054523a6d13ab9f21ac5eda28484ed20627
