### ISSUE TITLE
SM-6A Service Module - Top node stack attachment & model mesh issues

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#892]
This is the Vanilla Making History part:

![Untitled-1](https://user-images.githubusercontent.com/10106634/90343134-a8393080-e005-11ea-9852-3129561a74ef.png)

You can see that when a part is connected to the top node, the model mesh doesn't actually extend up to the part attached above.

Unfortunately this stock issue has persisted through to our RS part too:

![Untitled-2](https://user-images.githubusercontent.com/10106634/90343150-c6069580-e005-11ea-8494-ad52471ec062.png)

Seeing as we cannot change the collider, one suggestion could be to change the profile/slope angle of the part to extend it up to the height of the top node so that any part stacked above visually connects properly... Nertea has had to do lots of things like this with a lot of other parts too. I think however there may be a better easier solution below.

The reason for this issue in stock is that the origin of the model Size1to0ServiceBay.001 game object is actually -0.015m lower than the .mu's world origin point... so the whole model is shifted down 0.015m lower than it is supposed to be I guess which accounts for the gap.

As supplementary investigation, here is the origin of the root game object in Blender of the part:

![Untitled-1](https://user-images.githubusercontent.com/10106634/90343390-dc155580-e007-11ea-8dfd-ae61bf68522c.png)

Here's the relative root of the child mesh game object, see that it is 0.015m lower:

![Untitled-2](https://user-images.githubusercontent.com/10106634/90343399-ee8f8f00-e007-11ea-8046-826aeed5eee3.png)

The position of the center of the top face of the part with respect to its own origin is 0.3125m which is the same distance as the top node in the config:

![Untitled-3](https://user-images.githubusercontent.com/10106634/90343408-05ce7c80-e008-11ea-8230-2911d0d0fce4.png)

But as the model mesh is offset 0.015m downwards, the node would 'appear' higher at the top and bottom in game. Here is a profile shot with the cursor set 0.015m above the center of the top face of the model, this simulates the node gap in game that we see and it seems to correlate:

![Untitled-4](https://user-images.githubusercontent.com/10106634/90343429-3f06ec80-e008-11ea-8f45-172eae4990bd.png)

**!!! It might be easier just to shift our model's visual meshes (not colliders) up by 0.015m and see whether everything is rectified...?**

Nertea, I'm tagging you in this because of your experience with similar issues in the past if you have any input.

**Comment by Poodmund** [comment]
![Untitled-1](https://user-images.githubusercontent.com/10106634/90344602-0c162600-e013-11ea-90e7-3127c8885bd6.png)

Quick a dirty test of the above proposed solution and it seems to work fine upon initial viewing. This is with all visual mesh game objected raised by 0.015m and both end caps in the config raised by the same amount.

**Comment by AstroWell** [comment]
Noticed that in game, i've just keeped everything like the Stock Part, That could be nice to fix, but can we ? isn't out of rules ?

**Comment by Poodmund** [comment]
These kind of things cropped up quite a bit during the project. As long as we keep the colliders in the same position with respect to the origin we can shift the visual mesh around where we like i.e. fix SQUAD's issues

**Comment by AstroWell** [comment]
Perfect, so if Nertea validate that ? i'm ok to fix this, did you have already a fix for it or did you want for me to take a look ? tbh like more to have model that match top and bottom node. not like the Stock part.

**Comment by Poodmund** [comment]
I did essentially 'fix' the part but I did so by importing the current .mu into Blender using Taniwha's plugin, translate all the visual mesh objects up and then export it to a new .mu. This is probably not best practice as the import process can sometimes introduce errors so I would say it would be best to do this with the original assets/scene.

**Comment by AstroWell** [comment]
Ok, i've thinked to fix that by config, but that not really clean. so like all other parts i've made, Andrew need to take a look at this ( he have all assets )

**Comment by Poodmund** [comment]
The problem is we can just offset the nodes or root game object in the config as it affects collider position with respect to the Vanilla part so I think it just has.to be tweaked prior to export. Like the issue with the KV pods, it's probably worth holding fire before you've received clarification from Andrew.

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/cdf4708208eb0e4eb91bdd0cbd8c6d77087ef04c
