### ISSUE TITLE
KV-1, KV-2 & KV-3 Reentry Modules - Potential specular improvement to tiling

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#893]
Spoke with Well about this earlier today about the possibility to introduce some random distribution to the tiling's specular value in the texture to create a sense of randomness in manufacture i.e.

![Untitled-1](https://user-images.githubusercontent.com/10106634/90343732-2f3cd780-e00b-11ea-8d1f-ba96a9a781da.png)

It has a nice subtle effect in game: https://www.youtube.com/watch?v=6OIpgXBJm-M

Andrew, Well said that you were 'in-charge' of the asset files for these parts now that you made some further changes to his original work and now worked it into 'Master', is this correct?

**Comment by Poodmund** [comment]
This got a look at in https://github.com/PorktoberRevolution/ReStocked/commit/f43be054523a6d13ab9f21ac5eda28484ed20627 but a little more work could be done in the far distant future I think to enhance the effect.

Adding deferred tag and removing from 1.2.0 project.

**Comment by drewcassidy** [comment]
I never touched the specular, I just replaced the textures with what Well gave me

**Comment by Poodmund** [comment]
Yeah I saw that from the files Well sent over. I think a more randomised distribution and higher contrast between tiles could have a nice effect but like the tag said, we'll defer this to a later date in favour of more pertinent issues.

**Comment by AstroWell** [comment]
yeah sorry at first i don't have thinked Andrew could take the full psd without editing, so in my mind that was useless to edit the specular ( i think i've maybe changed 5 or 6 tiles ) We could do that later

**Comment by Poodmund** [comment]
Due to the loss of the source PSD textures, and following the experiment with re-exporting the current DDS, it seems that too much compression artifacts would be introduced and therefore is not worthwhile. 

Closing for now.
