### ISSUE TITLE
RE-L10 "Poodle" Liquid Fuel Engine - Model mesh holes and normal/smoothing issues.

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#894]
Excuse the bluntness of the descriptions, I'm just trying to be very short and sweet.

Texture blemish on cowling of quad bell variants.

![Untitled-1](https://user-images.githubusercontent.com/10106634/90445590-d1c28c80-e0d7-11ea-851b-8513ab6bf4bc.png)

Normal/smoothing issue on cowling on quad bell variants.

![Untitled-2](https://user-images.githubusercontent.com/10106634/90445651-e56df300-e0d7-11ea-855c-c233c6e04db2.png)

Hole in mesh on piping connection on quad bell variants.

![Untitled-3](https://user-images.githubusercontent.com/10106634/90445686-f7e82c80-e0d7-11ea-8fcf-44e01c4aa35b.png)

Hole appears in one of the flexible pipe meshes when gimballing on all quad bell variants.

![Untitled-4](https://user-images.githubusercontent.com/10106634/90445784-20702680-e0d8-11ea-8042-7452fa80dd62.png)

![Untitled-5](https://user-images.githubusercontent.com/10106634/90445786-2239ea00-e0d8-11ea-93bd-2919f13655c3.png)

Normal/smoothing issue on cowling of single bell variants.

![Untitled-6](https://user-images.githubusercontent.com/10106634/90445804-2f56d900-e0d8-11ea-9483-7f6adcad99b1.png)

Hole in mesh of turbine assembly of single bell variants.

![Untitled-7](https://user-images.githubusercontent.com/10106634/90445850-44336c80-e0d8-11ea-9004-9a3167257db2.png)

Mesh clipping occurs when gimballing between piping and turbine housing... I think this one can probably slide. Not sure how it'd be rectified without a lot of work for such an edge case.

![Untitled-8](https://user-images.githubusercontent.com/10106634/90445931-62996800-e0d8-11ea-99dc-eb663cdf7d57.png)

**Comment by ChrisAdderley** [comment]
d5b4212d86c1da37c1ef098c56d6cbfbfe3d4d73

**Comment by Poodmund** [comment]
All are resolved except for the hole in the mesh where a pipe meets the central turbine assembly, see screenshots below:

![Untitled-1](https://user-images.githubusercontent.com/10106634/90558253-ab622700-e193-11ea-9037-501e07bd63dc.png)

**Comment by ChrisAdderley** [comment]
54c9fcc342436a9f7bbd69299b4c5e055ec5d47d best it's going to get.

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/54c9fcc342436a9f7bbd69299b4c5e055ec5d47d
