### ISSUE TITLE
RE-L10 "Poodle" Liquid Fuel Engine - Single bell variants' mesh at tope node connection

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#895]
![Untitled-1](https://user-images.githubusercontent.com/10106634/90446229-efdcbc80-e0d8-11ea-8f3b-29324034a257.png)

The mesh of the single bell variants' top connecting faces could be extended up ever so slightly to alleviate the small air gap that occurs when stacking on the top node.

**Comment by ChrisAdderley** [comment]
d5b4212d86c1da37c1ef098c56d6cbfbfe3d4d73
