### ISSUE TITLE
RE-L10 "Poodle" Liquid Fuel Engine - Shroud Issues

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#896]
I'm seeing these odd seams in the mesh again from certain angles, more noticeable in the white variants.

![Untitled-1](https://user-images.githubusercontent.com/10106634/90446603-90cb7780-e0d9-11ea-8036-a717793accbc.png)

![Untitled-2](https://user-images.githubusercontent.com/10106634/90446613-932dd180-e0d9-11ea-9209-faded1c05a1c.png)

![Untitled-3](https://user-images.githubusercontent.com/10106634/90446615-94f79500-e0d9-11ea-8465-f3fb51194135.png)

The Orange/Grey variant shrouds have quite a noticeable joint, not sure if it could be transitioned a little smoother.

![Untitled-4](https://user-images.githubusercontent.com/10106634/90446660-accf1900-e0d9-11ea-943f-830db46d4abd.png)

The single bell, compact variants' shrouds are the same length as the non-compact version I think, causing them to protrude through the top of the part above.

![Untitled-5](https://user-images.githubusercontent.com/10106634/90446739-cd976e80-e0d9-11ea-8952-74b638e757d5.png)

![Untitled-6](https://user-images.githubusercontent.com/10106634/90446742-cf613200-e0d9-11ea-9e2c-b6cfc0040139.png)

**Comment by ChrisAdderley** [comment]
d5b4212d86c1da37c1ef098c56d6cbfbfe3d4d73

**Comment by Poodmund** [comment]
The two Quad Variants (white & orange/grey) seem to have their normal map missing for the top portion of half of their top ring. Comparison with the Quad Compact variants is shown below where they are appearing correctly.

![Untitled-1](https://user-images.githubusercontent.com/10106634/90558807-9a65e580-e194-11ea-9d56-8228a11642bf.png)

On the Single Bell Compact variants there is an apparant, visible gap between the top of the shroud and the part stacked above (see below). I think this is due to https://github.com/PorktoberRevolution/ReStocked/issues/895 potentially being unresolved.

![Untitled-2](https://user-images.githubusercontent.com/10106634/90559118-0ba59880-e195-11ea-8f61-afd4d6fa862d.png)

**Comment by ChrisAdderley** [comment]
Pood, when i close an issue without actually fixing things it means NO MORE GO AWAY :P 54c9fcc342436a9f7bbd69299b4c5e055ec5d47d

**Comment by Poodmund** [comment]
Yeah but how else will I incite that feeling of pure hatred and loathing? 

I refer back to this...

![Untitled-1](https://user-images.githubusercontent.com/10106634/90567623-55e14680-e1a2-11ea-9d5e-157b97abb0fd.png)

😄 

Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/54c9fcc342436a9f7bbd69299b4c5e055ec5d47d
