### ISSUE TITLE
T-1 Toroidal Aerospike "Dart" Liquid Fuel Engine

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#90]
Aerospike is pretty good so will be deferred until later

- [x] Model
- [ ] Unwrap
- [ ] Texture
- [ ] Integration
- [ ] FX

**Comment by ChrisAdderley** [comment]
Moving this to 0.3.0 'cause I don't want to.

**Comment by Poodmund** [comment]
Done by Kavaeric as part of 1.4.5
