### ISSUE TITLE
Mk-55 "Thud" Liquid Fuel Engine

### ISSUE THREAD

**Issue by ChrisAdderley** [PorktoberRevolution/ReStocked#91]
Thud is deferred until later, but should be based off the RS-27A

- [ ] Model
- [ ] Unwrap
- [ ] Texture
- [ ] Integration
- [ ] FX

**Comment by ChrisAdderley** [comment]
Moving this to 0.3.0 'cause I don't want to.

**Comment by Poodmund** [comment]
Done by Kavaeric as part of 1.5.0
