### ISSUE TITLE
Compatibility: Connected Living Spaces

### ISSUE THREAD

**Issue by Fumblesneeze** [PorktoberRevolution/ReStocked#912]
The FL-X Adapter series, among others parts, do not have the modules for Connected Living Spaces. I think this should be handled by the mod adding the parts, as other mods explicitly state that they are compatible.

Adding compatibility shouldn't be more work than copy-pasting the module code from similar vanilla parts out of CLS.

Parts missing CLS modules:
- FLX-A15 Adapter
- FLX-A30 Adapter
- BZ-26 Radial Attachment Point Jr. 
- BZ-78 Radial Attachment Point

**List of mods installed:**
- Restock
- Connected Living Spaces

**Comment by ChrisAdderley** [comment]
Feel free to submit a pull request :) that will accelerate things getting done.

**Comment by Poodmund** [comment]
CLS takes control patches for other modded parts, see: https://github.com/codepoetpbowden/ConnectedLivingSpace/tree/master/Distribution/GameData/ConnectedLivingSpace/Configs

So the best best would be to submit a pull request to the CLS repo so they can add support.

**Comment by Poodmund** [comment]
@Fumblesneeze I've done this for you here: https://github.com/codepoetpbowden/ConnectedLivingSpace/pull/113
