### ISSUE TITLE
1.25m heat shield - Collider in the wrong place

### ISSUE THREAD

**Issue by drewcassidy** [PorktoberRevolution/ReStocked#914]
**Describe the bug**
1.25m heat shield is offset compared to stock

**Screenshots**

<img width="1033" alt="Screen Shot 2020-10-04 at 8 45 25 PM" src="https://user-images.githubusercontent.com/3837797/95038282-97f71680-0682-11eb-8cc2-2b693050a432.png">

**Comment by ChrisAdderley** [comment]
Was fixed in 1.3.1
