### ISSUE TITLE
Restock SRBs not working or basically any engine (KSP Version: 1.10.1) 

### ISSUE THREAD

**Issue by TR-hydra** [PorktoberRevolution/ReStocked#916]
The problem I have is weird I basically started a new career with 102 mods and somehow my SRBs dont produce any thrust, I checked my thrust limiter and it was on 100. The only thing I noticed starting my engine was that the nozzle started gettting heat but nothing else happend, no plume and no thrust my vessel wasnt moving a meter.

![Screenshot_2020-10-13_214513 (1)](https://user-images.githubusercontent.com/72828522/95922036-b069de00-0db2-11eb-943d-0925f2c9cfd1.png)

List of the mods I installed:
 - Restock
 - ModuleManager
 - 666_ModuleManagerWatchDog
 - KSPModFileLocalizer
 - 999_Scale_Redist
 - [ x ] Science!
 - 000_ClickThroughBlocker
 - 000_FilterExtensions
 - 000_FilterExtensions_Configs
 - 000_TexturesUnlimited
 - 000_USITools
 - 001_ToolbarControl
 - 3LB (Low Light Levels Blue)
 - 3LR (Low Light Levels Red)
 - 999_KSP-Recall
 - Agencies
 - ASET_Avionics
 - ASET_Props
 - Astrogator
 - B2L (Blinding Light Levels)
 - B9_Aerospace
 - B9_Aerospace_HX
 - B9_Aerospace_Legacy
 - B9AnimationModules
 - B9Partswitch
 - BetterTimeWarp
 - Beyond Home
 - Camera Tools
 - CommunityCategoryKit
 - CommunityRescourcePack
 - ContractConfigurator
 - CryoTanks
 - CTTP
 - DecayingRTGs
 - DecouplerShroud
 - Deployable Engines
 - DistantObject (Distant Object Enhancements)
 - DynamicBatteryStorage
 - EasyVesselSwitch
 - EnvironmentalVisualEnhancements
 - ExtraplanetaryLaunchpads
 - Firespitter
 - FShangarExtended
 - GU (Galaxies Unbound: Nova Kirbani)
 - HLAirships
 - INSTANTIATOR
 - InterstellarFuelSwitch
 - JSI
 - KAS (Kerbal Attachment System)
 - KerbalAtomics
 - KerbalEngineer
 - KerbalFoundries
 - KerbalJointReinforcement
 - KIS (Kerbal Inventory System)
 - Kopernicus
 - Kopernicus Expansion
 - KS3P
 - KSPWheel
 - KWRocketry
 - LLL (Lack Luster Labs)
 - LLL -Extra (Lack Luster Labs Extras)
 - MagicSmokeIndustries
 - MiningExpansion
 - ModularFlightIntegrator
 - ModuleManagerWatchDog
 - NavyFish (Docking Port Alignment Indicator)
 - NearFutureAeronautics
 - NearFutureConstruction
 - NearFutureElectrical
 - NearFutureExploration
 - NearFutureLaunchVehicles
 - NearFutureMethalox
 - NearFutureProps
 - NearFuturePropulsion
 - NearFutureSolar
 - NearFutureSpacecraft
- OPT (OPT Spaceplane)
- OrbitalLFOEngines
- Parallax
- PersistantThrust
- PhotonSail
- PlanetaryBaseInc (Kerbal Planetary Base Systems)
- PoodsSkyboxes
- RasterPropMonitor
- RationalRescources
- RationalRescoucesParts
- RealPlume
- RealPlume-Stock
- REPOSoftTech
- RestockRigidLegs
- RPMPodPatches
- scatterer
- Sigma
- SmokeScreen
- Squad (Of course)
- Squad Expansion (Of course)
- SurfaceLights
- TrackingStationEvolved
- Trajectories
- TweakScale
- UmbraSpaceIndustries (From USI I Installed: Modular Kolonization System and USILifesupport)
- WarpPlugin
- WildBlueIndustries (001KerbalActuators)
- XenonHallThrusters
- ZeroMiniAVC

(This was pain to write all that down Pheew done now)

[KSP.log](https://github.com/PorktoberRevolution/ReStocked/files/5374558/KSP.log)

**Comment by Mort1ck01** [comment]
hi, I have the same problem, you can write to me how you solved it (if you solved it of course :))

**Comment by TR-hydra** [comment]
> 

I am so sorry, but this happend so long ago that I forgot. As far as I remember, Persistent Thrust made some trouble, I think.
