### ISSUE TITLE
While in Mk3 cockpit there is a square were the ocean is broken

### ISSUE THREAD

**Issue by beanb101** [PorktoberRevolution/ReStocked#918]
**Describe the bug**
This mod was recommended in the description of AVP and when I tried using my shuttle with it the cockpit had a see-thru box and inside the box the ocean was glitched

**Screenshots**

**List of mods installed:**
 - Restock
 - Astronomers visual pack

**Logs**
Attach logs if you think they are relevant. The log file is named "KSP.log" and is found in the same folder as your KSP executable

**Comment by drewcassidy** [comment]
Restock doesnt affect the mk3 cockpit at all. can you post a screenshot of the problem?

**Comment by beanb101** [comment]
sure
