### ISSUE TITLE
commDish nodes are inset

### ISSUE THREAD

**Issue by lpgagnon** [PorktoberRevolution/ReStocked#919]
**Describe the bug**
Communotron 88-88's nodes (both bottom and surface-attach) are inset a little inside the model; presumably because the replacement model doesn't have its origin in exactly the right place, and Restock only replaces the model without updating the nodes.

**Screenshots**
https://drive.google.com/file/d/1XdwczMVaKMbv7wlRjahBGqvliYpLsI7b/view?usp=sharing

**List of mods installed:**
 - Restock
 - RP-1 etc

Problem first seen with RO's rescaled part; RO expected to be able to just apply a rescaleFactor and not touch the nodes.
Worked around here <https://github.com/KSP-RO/RealismOverhaul/pull/2378> but those values won't work without the rescaling. Might just need to use 0.245/2.2326 = 0.11; though perhaps a model change makes more sense

**Comment by drewcassidy** [comment]
This is as intended
