### ISSUE TITLE
Changing root part to a radially attached part in stock KSP will end up with a different result in restock.

### ISSUE THREAD

**Issue by anth1256** [PorktoberRevolution/ReStocked#921]
**Video Proof**
Craft created in 1.10.1 stock
https://youtu.be/r2SPVnIVEGE

Same Craft loaded in 1.10.1 restock
https://youtu.be/JtuLD1fllMA

How to have it happen in 1.10.1 restock (using undo)
Or you can just reload the file after
https://youtu.be/1NWnL9p4K7g

**List of mods installed:**
 - Restock

**Comment by drewcassidy** [comment]
is this with just the ore tanks?

**Comment by anth1256** [comment]
I just tested it on ore tanks and fuel tanks, but I assume it happens on anything that is radially attached first.

**Comment by anth1256** [comment]
if it had happened in stock I wouldnt have reported it here
