### ISSUE TITLE
1.875 Heat Shield protection

### ISSUE THREAD

**Issue by eberkain** [PorktoberRevolution/ReStocked#923]
**Describe the bug**
when playing with JNSQ the heat shield does not provide enough coverage for the pod due to the higher reentry speeds and extended heating period.  

**Screenshots**
https://youtu.be/nQY2J3R90GY

restoring the stock heat shields with the whitelist feature does allow the exact same test craft to survive reentry without issue. 

**List of mods installed:**
plenty of mods, should be detailed in logs.  JNSQ + FAR + Restock seems to be deadly for at least 1.25 and 1.875, possibly more. 

**Logs**
https://drive.google.com/file/d/1livnUVdpd-TXiXXF7dpkPtAxKn7o0kRM/view?usp=sharing
https://drive.google.com/file/d/1iLDR7GiHMIW52ds1y5s1r_vOZSMsRXpL/view?usp=sharing

**Comment by ChrisAdderley** [comment]
Does this also occur with FAR not present?

**Comment by eberkain** [comment]
According to forum user ble210 it does, but I have not personally tested without FAR.

https://forum.kerbalspaceprogram.com/index.php?/topic/184880-181-jnsq-090-03-feb-2020/&do=findComment&comment=3889935

He also did a recording https://youtu.be/_AdcAbvqfyc?t=228

**Comment by eberkain** [comment]
ble210 posted more information about his tests
https://forum.kerbalspaceprogram.com/index.php?/topic/184880-181-jnsq-090-03-feb-2020/&do=findComment&comment=3890447

**Comment by Poodmund** [comment]
Note to self: EXPLICIT DRAG CUBES; RS PatchesMH and RS+ part.
