### ISSUE TITLE
Couple of problems

### ISSUE THREAD

**Issue by whydoihavetosignuptoaskaquestion** [PorktoberRevolution/ReStocked#926]
-Restock added a couple parts, but did not change the existing parts. I might have downloaded something wrong, or maybe the mod isn't updated to 1.11. LMK which one it is.
-I asked when Restock will be updated to 1.11 yesterday and my question was closed by a mod without even answering. That is a problem. Don't be a dick please.
Edit: please actually make an attempt to help me out before closing my issue without even trying like last time, thank you

**Comment by ChrisAdderley** [comment]
It's considering poor etiquette to demand release dates for updates in volunteer projects, particular since the new version of KSP has been out for less than a week.

**Comment by eberkain** [comment]
> -Restock added a couple parts, but did not change the existing parts. I might have downloaded something wrong, or maybe the mod isn't updated to 1.11. LMK which one it is.

If you are having issues then you should be more specific about the problem. 
https://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/

ReStock will get updated, until then. If you are using any mod on an unsupported game version, you should expect bugs and be prepared to deal with it yourself. 
https://forum.kerbalspaceprogram.com/index.php?/topic/135596-psa-dont-poke-the-bears-translation-dont-pester-the-modmakers-for-updates/
