### ISSUE TITLE
RV-105 RCS Thruster Block | Last 4 variants textures do not load

### ISSUE THREAD

**Issue by RJ2003001** [PorktoberRevolution/ReStocked#930]
When selecting any of the last 4 thruster variants, their textures do not load it sticks to the "Angled 4-Horn"

https://user-images.githubusercontent.com/77000386/103638252-557cf880-4f55-11eb-8ae4-0c8f42d6f9b5.mp4

**Comment by drewcassidy** [comment]
KSP 1.11 isnt supported yet
