### ISSUE TITLE
Engine Plate procedural drag issue

### ISSUE THREAD

**Issue by sovetskysoyuz** [PorktoberRevolution/ReStocked#931]
Bug Description:
KSP 1.10.1 included a fix for a stock bug with drag cubes for engine plates (bug # 25712 in the KSP Bug Tracker). The fix was to add "useProceduralDragCubes = true" in the config for each engine plate, inside ModulePartVariants. Because ReStock overwrites the stock ModulePartVariants with its own information for the engine plates, but does not include useProceduralDragCubes in the new ModulePartVariants, the ReStock engine plates are still affected by the drag bug.

I confirmed that an additional ModuleManager patch to add "useProceduralDragCubes = true" back in fixes the issue and restores the correct drag behaviour for engine plates.

Steps to reproduce: build a craft including an engine plate, then observe that the drag occlusion numbers go to zero when switching engine plate variants or on launching. The drag debug tools also show that the parts above and below the engine plate are not occluded at all.

**Comment by Poodmund** [comment]
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/e6389c80b30da1b5c8be87001e52587fcd2dedd5

@sovetskysoyuz can you please confirm that this is the same fix that you applied yourself?
