### ISSUE TITLE
restock-rcs-linear-mini-1.mu is missing its collider

### ISSUE THREAD

**Issue by frencrs** [PorktoberRevolution/ReStocked#937]
Minor issue, restock-rcs-linear-mini-1.mu needs a collider added to the model. It can't be selected in the Editor after being attached, de-selected, etc.

**Comment by Poodmund** [comment]
Fixed with https://github.com/PorktoberRevolution/ReStocked/commit/2cceb95dac1c8c90edf50378111ada03ba4f0549
