### ISSUE TITLE
Place Anywhere 1 RCS Thruster Unselectable After Use

### ISSUE THREAD

**Issue by GHrynk** [PorktoberRevolution/ReStocked#939]
The Place Anywhere 1 RCS Thruster cannot be selected again in the VAB workspace after pulling it from the parts selection bar.  After attachment to the craft, or dropping in mid-air, the part cannot be selected again to either adjust properties, move, or remove.

This is in Restock/Restock+ v1.3.0 in KSP 1.11.0 Win x64, with KSP Expansions installed.  See forum posts 22 and 24 Jan 2021.

**Comment by Poodmund** [comment]
https://github.com/PorktoberRevolution/ReStocked/issues/937
