### ISSUE TITLE
Quad Angled Mini RCS has same thrust as full-size Quad RCS

### ISSUE THREAD

**Issue by GHrynk** [PorktoberRevolution/ReStocked#940]
The RV-1X-A (quad angled mini) has the same thruster power as the much larger RV-105-A and RV-105.  The RV-1X (regular quad mini) seems to be scaled appropriate at 1/10th thrust power.  In the VAB part properties, the RV-1X has a Thruster Power of 0.1, but the RV-1X-A (same mass as RV-1X) has a Thruster Power of 1.0.  Not sure how to explain it, as "restock-rcs-block-quad-mini-1.cfg" and "restock-rcs-block-quad-angled-mini-1.cfg" both have the same thrusterPower = 0.25.

I'm not sure how the calculations in the properties are getting calculated, but I confirmed it in flight and with RCS Build Aid, that the RV-1X-A has the same thrust as the RV-105-A and RV-105, and the RV-1X has one tenth the thrust of either.

The Place Anywhere 1 (the part that's unselectable after drop or placement, see Issue #939) seems to match the thrust displayed in its properties (0.2), as confirmed by RCS Build Aid.  The Place Anywhere 7 seems to match its listed thrust as well.

This was done with Restock/Restock+ v1.3.0 in KSP 1.11.0 Win x64 with Expansions.

MORE: Tried out the quads in 3-way configuration.  Same result.

**Comment by GarwelGarwel** [comment]
I confirm it. The RV-1X-A part is `restock-rcs-block-multi-mini-2`. It has `thrusterPower = 1` in its config. It's in ReStock+.

The scaled RV-1X part is `RCSblock_01_small, it is patched by ReStock.

On a related note, why are all 0.25 kN RCS thrusters now hidden? They were a very good middle ground between the weak 0.1 kN thrusters and the excessively strong 1 kN ones.

**Comment by ChrisAdderley** [comment]
> Not sure how to explain it, as "restock-rcs-block-quad-mini-1.cfg" and "restock-rcs-block-quad-angled-mini-1.cfg" both have the same thrusterPower = 0.25 
That would probably be because those aren't the right files to look at :). 

> On a related note, why are all 0.25 kN RCS thrusters now hidden? They were a very good middle ground between the weak 0.1 kN thrusters and the excessively strong 1 kN ones.
Model was used for the new Squad ones, don't want to make and configure a bunch of new models.

**Comment by Poodmund** [comment]
Fixed with https://github.com/PorktoberRevolution/ReStocked/commit/be632e1a5129953ff97dff5c1e657f761db0425f
