### ISSUE TITLE
Z Fighting on Solar panels and weird RCS textures

### ISSUE THREAD

**Issue by Shelnut** [PorktoberRevolution/ReStocked#941]
![20210127143533_1](https://user-images.githubusercontent.com/73136949/106044255-785e8080-60ad-11eb-9aa2-6861e1477f48.jpg)

**Comment by Poodmund** [comment]
I presume you're using ReStock 1.3.0 on KSP 1.10.1 or some earlier version of KSP?

**Comment by Shelnut** [comment]
Mods Installed:

- Click Through Blocker
- Textures Unlimited
- Toolbar Control
- Animated Decouplers
- B9 Part Switch
- Chatterer
- Community Resource Pack
- Community Tech Tree
- Deployable Engines
- Destruction Effects
- DiRT
- Dynamic Battery Storae
- E.V.E
- FMRS
- Hide Empty Tech Tree Nodes
- Kerbal Engineer
- Kerbal Reusablity Expansion
- Kopernicus
- Magi Core
- Mark IV Sytem
- Modular Flight Integrator
- Near Future Aeronautics
- Near Future Construction
- Near Future Electrical
- Near Future Exploration
- Near Future Launch Vehicles
- Near Future Props
- Near Future Propulsion
- Near Future Spacecraft
- Planet Shine
- Real Plume
- Real Plume - Stock
- Recorvery Controller
- Reentry Particle Effects Renewed
- Rescale 2.5x
- ReStock
- ReStockPlus
- Retractable Lifting Surface
- Scatterer
- Sigma Dimensions
- Smoke Screen
- SpaceX Legs
- Spectra
- Station Parts Expansion Redux
- Trigger Tech
- Tundra Exploration
- Waterfall
- Waterfall Restock
- Wild Blue Industries 
- Zero Mini Ave

**Comment by Shelnut** [comment]
> I presume you're using ReStock 1.3.0 on KSP 1.10.1 or some earlier version of KSP?

Yes, I also tried setting the version back to 1.2.1

**Comment by Shelnut** [comment]
> I presume you're using ReStock 1.3.0 on KSP 1.10.1 or some earlier version of KSP?

Wait Nvm, It did fix it when I set it back to 1.2.1, Ckan was being weird. Although now on all my ships it says "Unknown part modules", anyway to fix this? Btw thanks for the very fast response time, I was not expecting that lmao

**Comment by Poodmund** [comment]
Please try completely removing ReStock and ReStock+ from your install and then install ReStock 1.2.1 and ReStock+ 1.2.1 again from afresh, then please report back whether the issue still persists.
