### ISSUE TITLE
Spontaneous Unwanted Disassembly

### ISSUE THREAD

**Issue by ThomasWarChild** [PorktoberRevolution/ReStocked#943]
**Describe the bug**
Okay,

   I have the latest and greatest KSP version and I have the following Mods.

**List of mods installed:**

[CKAN 1.2 Mod Lisk.txt](https://github.com/PorktoberRevolution/ReStocked/files/5939330/CKAN.1.2.Mod.Lisk.txt)

Issue:  Just about everything my engineer attempts to disassemble or attach blows up everything.

I was trying to use the Konstruction mod so that I can build cranes or tow something or heck salvage.  But the winches don't connect to the ports half the time, you can't store a port take it up to a ship without one add it so that you can refuel or salvage it.  First you can't put it in a container so I add it to the side of my ship.  Go to remove it and Boom.  Light Scanner, touch it... Boom.   IF the log doesn't show it... Let me know and I'll recreate it... it happens constantly.

**Logs**
Attach logs if you think they are relevant. The log file is named "KSP.log" and is found in the same folder as your KSP executable
[KSP.log](https://github.com/PorktoberRevolution/ReStocked/files/5939326/KSP.log)

**Comment by Poodmund** [comment]
This is a ReStock issue? From your log, you don't have ReStock installed.
