### ISSUE TITLE
Science Return Experiment Unit can't be right clicked when placed and has a green highlighter.

### ISSUE THREAD

**Issue by TR-hydra** [PorktoberRevolution/ReStocked#946]
The "Science Return Experiment Unit" can't be right clicked and it's highlighted green, I just placed the part nothing else. I also run on the KSP version: 1.10.1

![Screenshot 2021-04-02 200822](https://user-images.githubusercontent.com/72828522/113445972-1d237400-93f7-11eb-9c84-0556b9c8dffd.png)

**List of mods installed:**
 - ModuleManager
 - B9PartSwitch
 - CommunityRescourcePack
 - CommunityTechTree
 - CryoEngines
 - CryoEnginesRestock
 - CryoTanks
 - DecayingRTGs
 - DeployableEngines
 - DynamicBatteryStorage
 - EdgeOfEternity
 - EnvironmentalVisualEnhancements
 - HeatControl
 - HideEmptyTechTreeNodes
 - KerbalAtomics
 - KerbalAtmoicsLH2NTRModSupport
 - Kopernicus
 - ModularFlightIntegrator
 - Near Future Technologies (all mods)
 - OrbitalLFOEngines
 - ReStockPlus
 - ReStock
 - scatterer
 - Sigma Replacements: Skybox
 - StationPartsExpansionMetal
 - StationPartsExpansionRedux
 - Waterfall
 - WaterfallRestock
 - WildBlueIndustries Kerbal Actuators

[KSP.log](https://github.com/PorktoberRevolution/ReStocked/files/6250959/KSP.log)

It would be great to be helped out or this issue to be fixed I had no logspams but just for the sake I will attach my logs here.

**Comment by drewcassidy** [comment]
What version of restock are you using? 1.3.1 won't work in KSP 1.10

**Comment by TR-hydra** [comment]
Okay that might be the issue then. I am indeed using 1.3.1 I found a temporary fix though if I launch it with the part attached and go back into the VAB i can adjust it. It is really just this part.

**Comment by TR-hydra** [comment]
Okay, I just tested this with 1.11.1 and it still doesn't work.

**Comment by drewcassidy** [comment]
Im not able to reproduce this. can you post a log from it in 1.11.1?

**Comment by TR-hydra** [comment]
> Im not able to reproduce this. can you post a log from it in 1.11.1?

Will do!

**Comment by TR-hydra** [comment]
Oh no, I am stupid. When I tested it on 1.11.1 I downloaded 1.2.0 and actually came to my mind to see if this works out while me thinking im loading in 1.10.1, I am very sorry that this is false alarm. So my issue is apparently just a wrong version. Im sorry for wasting your time
