### ISSUE TITLE
Several Parts not functional

### ISSUE THREAD

**Issue by JajajTec** [PorktoberRevolution/ReStocked#949]
The Bug:
The 1.25m and 2.5m service bays are not able to open (not in editor, not in flight and also not in the hotkey manegment). The button is just not there.
The game version is 1.10.1
Hope you guys still do offer support for that version.

![grafik](https://user-images.githubusercontent.com/49282599/118372638-02761a80-b5b3-11eb-9230-3422de7311d5.png)
there is no button here

scine i dont want to be here for hours trying to write the mods out i just give the installed-portable.ckan file. Hope this works to.
[mods.zip](https://github.com/PorktoberRevolution/ReStocked/files/6487848/mods.zip)

That is the KSP log. Hope that helps
[KSP log.zip](https://github.com/PorktoberRevolution/ReStocked/files/6487853/KSP.log.zip)

**Comment by drewcassidy** [comment]
Does it happen with just restock installed? Your log has a bunch of errors from other mods being installed incorrectly or not playing nice with each other

**Comment by JajajTec** [comment]
ok imma try that out
also i found out that more parts are affected
so far i only found out the 10m heatshield. 
but i am testing every single block right now and i am also removing all duplicants in the hope that will fix it...

**Comment by JajajTec** [comment]
Btw. just curios, wich mods are fighting against each other?

**Comment by JajajTec** [comment]
ok it works with just restock!
well, that means a mod is messing with things it shouldn't.
Can you maybe find out wich mod that could be? Because testing that threw whould litherly take 2 days when i did my math correctly.
oh and btw. how do you delete duplicate parts exactly? Because when i try it they just vanish...

**Comment by JajajTec** [comment]
wait wat? i can show you how to reproduce! I can give you the pack and then you can test it!
Wait lemme upload it...

**Comment by JajajTec** [comment]
[Test-Restock-bug-modpack.zip](https://github.com/PorktoberRevolution/ReStocked/files/6489157/Test-Restock-bug-modpack.zip)
You have to install 3 mods manually:
AT Utils: v1.9.6
Throttle Controlled Avionics: v3.7.2
OPT Spaceplane Continued: v1.2.1
after you have done that you can import that .ckan file into ckan and everything should get loaded. After that, you can start KSP and reproduce the problem.

**Comment by JajajTec** [comment]
Ok i have isolated the error from the KSP.log.
That is the error that is getting thrown when i try to place one such broken modules:
[ERR 14:01:43.032] [ModuleCargoBay]: Module ModuleCargoBay is not an IScalarModule

[ERR 14:01:43.092] [ModuleSeeThroughObject]: Module at index 0 is not an IScalarModule on part Part

[ERR 14:01:48.109] [ModuleCargoBay]: Module ModuleCargoBay is not an IScalarModule

[ERR 14:01:48.109] [ModuleSeeThroughObject]: Module at index 0 is not an IScalarModule on part Part

[LOG 14:01:49.042] ServiceBay.250.v2 added to ship - part count: 2
[LOG 14:03:45.994] deleting part ServiceBay.250.v2
[ERR 14:03:47.409] [ModuleCargoBay]: Module ModuleCargoBay is not an IScalarModule

[ERR 14:03:47.409] [ModuleSeeThroughObject]: Module at index 0 is not an IScalarModule on part Part
hope that helps isolating the problem.

**Comment by JajajTec** [comment]
oke oke. i found the problem out!
a broken mod caused the problems!
it was the mod: Realistic Power Draw!
so that problem is now fixed!
Hope that helps other people in teh future!
