### ISSUE TITLE
0.5 size separator decoupling bug

### ISSUE THREAD

**Issue by Le-Cacatoes** [PorktoberRevolution/ReStocked#950]
The 0.5 separator decouple in the wrong direction.the paylaod is ejected on the side instead of going straight

![Capture d’écran (1323)](https://user-images.githubusercontent.com/84480340/118893833-69713780-b903-11eb-82ba-2ccca78a21c2.png)

**Comment by ChrisAdderley** [comment]
Can't reproduce this. 
![screenshot122](https://user-images.githubusercontent.com/5642064/122330029-47a9a700-cee7-11eb-8a65-aee11c63fc0c.png)
