### ISSUE TITLE
1.8m THK "Pollux" SRB lacks gimbal

### ISSUE THREAD

**Issue by fipachu** [PorktoberRevolution/ReStocked#951]
With Restock+ installed, Pollux shows in the context menu as having a 3 degrees gimbal. However, the nozzle does not move when pressing direction controls, nor does the SRB provide any torque. Tested by disabling torque in the crew capsule.

I am running Making History and Breaking Ground.

**Screenshots**
![image](https://user-images.githubusercontent.com/80906036/120922068-6a59e580-c6c7-11eb-89d2-510443f1c81b.png)

**List of mods installed:**
ReStock (ReStock 1.3.1)
ReStock+ (ReStockPlus 1.3.1)
BetterTimeWarpContinued (BetterTimeWarpCont 2.3.12.6)
Breaking Ground (BreakingGround-DLC 1.6.0)
Chatterer (Chatterer 0.9.99)
ClickThrough Blocker (ClickThroughBlocker 1:0.1.10.15)
Crowd Sourced Science (CrowdSourcedScience v6.0)
Distant Object Enhancement Continued (DistantObject v2.0.2.0)
Distant Object Enhancement Continued default config (DistantObject-default v2.0.2.0)
Docking Port Alignment Indicator (DockingPortAlignmentIndicator 6.9.2.2)
Kerbal Alarm Clock (KerbalAlarmClock v3.13.0.0)
Kerbal Engineer Redux (KerbalEngineerRedux 1.1.8.3)
Making History (MakingHistory-DLC 1.11.0)
Module Manager (ModuleManager 4.1.4)
PlanetShine (PlanetShine 0.2.6.3)
PlanetShine - Default configuration (PlanetShine-Config-Default 0.2.6.3)
scatterer (Scatterer 3:v0.0770)
Scatterer Default Config (Scatterer-config 3:v0.0770)
Scatterer Sunflare (Scatterer-sunflare 3:v0.0770)
ScienceAlert ReAlerted (ScienceAlert 1.9.9)
Toolbar Controller (ToolbarController 1:0.1.9.4)
TriggerAu Flags (TriggerAu-Flags v2.10.0.0)
Zero MiniAVC (ZeroMiniAVC 1:1.1.0.1)

**Comment by fipachu** [comment]
Just in case I did the same test with Restock, Restock+, MH, and BG only. Same results.

**Comment by ChrisAdderley** [comment]
Was fixed in 1.3.1
