### ISSUE TITLE
Missing Textures on Poodle Shroud

### ISSUE THREAD

**Issue by Arandorn** [PorktoberRevolution/ReStocked#953]
**Describe the bug**
In Release 1.32 the Poodle Shroud is missing its texture for all quad bell variants as well as for the orange/grey variants of the single bell version

4 Engine Shroud Texture Missing
![Screenshot (96)](https://user-images.githubusercontent.com/42143977/122510579-1d9ad680-d006-11eb-8059-3be4b7dbb4ce.png)
Single Compact (+Full) White Texture Working
![Screenshot (98)](https://user-images.githubusercontent.com/42143977/122510587-212e5d80-d006-11eb-8ca1-534266ca58d6.png)

**List of mods installed:**
 - Restock
 - DLC MH + BG

**Comment by JoshuaDalton520** [comment]
I have the same issue, but with 1.5 size parts:
![a](https://user-images.githubusercontent.com/78283809/123519104-49a5ff80-d677-11eb-9785-71061cf74efa.jpg)
![a1](https://user-images.githubusercontent.com/78283809/123519105-4b6fc300-d677-11eb-89a1-6ec240e7fc89.jpg)
![a2](https://user-images.githubusercontent.com/78283809/123519107-4e6ab380-d677-11eb-8633-2f62ca24baf4.jpg)
![a3](https://user-images.githubusercontent.com/78283809/123519111-50cd0d80-d677-11eb-8cf2-fbc79b2a61c3.jpg)

**Comment by Arandorn** [comment]
It has nothing to do with the size of the part the engine is attached to.

You can grab the fixed .mu file [here](https://github.com/PorktoberRevolution/ReStocked/blob/7b2e0a277bb7f6539f752aeac8b124ca0d14e252/Distribution/Restock/GameData/ReStock/Assets/Engine/restock-engine-poodle-2.mu) and replace the broken file with it, until a new version of ReStock is released

**Comment by ChrisAdderley** [comment]
Was fixed in 1.3.1
