### ISSUE TITLE
Mk7 cone texture glitch

### ISSUE THREAD

**Issue by that-on** [PorktoberRevolution/ReStocked#957]
The MK7 nose cone always seems gray in the B/W and White variants 

![image](https://user-images.githubusercontent.com/86991197/124526326-7a510c00-ddd0-11eb-84d1-86d81c80e511.png)
![image](https://user-images.githubusercontent.com/86991197/124526412-b6846c80-ddd0-11eb-8877-a0d71bcce659.png)

List of mods installed:
 - Restock
- Waterfall

**Comment by ChrisAdderley** [comment]
This is due to you using Restock for 1.11 in 1.12. The mod is not compatible with 1.12 yet.
