### ISSUE TITLE
Reentry modules not dethatching when staged conflict/bug

### ISSUE THREAD

**Issue by NightShift10125** [PorktoberRevolution/ReStocked#964]
There's a conflict with Restock and some other mod that cause the reentry modules to not detach when staged, however they will detach if trigged by a action group.
What I mean when I say they wouldn't detach is that they still act as one vessel which also means you can still detach them using a action group, I am unsure what causes the bug as the logs don't proved any information on the matter.

Testing ground.
![Kerbal Space Program Screenshot 2021 07 23 - 12 29 16 62](https://user-images.githubusercontent.com/42304378/126825878-df746192-5eb2-4c96-a358-2652ff926f57.png)
Detach using staging.
![Kerbal Space Program Screenshot 2021 07 23 - 12 29 20 67](https://user-images.githubusercontent.com/42304378/126825883-4db50e37-88ea-45eb-a418-753bdfa84a31.png)
Detach using "Abort".
![Kerbal Space Program Screenshot 2021 07 23 - 12 31 41 72](https://user-images.githubusercontent.com/42304378/126827683-f927a983-d063-4809-b93c-c8aba2217fbc.png)

List of suspected mods.

Flight Manager for Reusable Stages (FMRS) Continued (FMRSContinued 1.2.9.1)
4kSP_Expanded (4kSPExpanded 0.2.1.6)
Astrogator (Astrogator v0.10.2)
AtmosphereAutopilot (Fly-By-Wire) (AtmosphereAutopilot v1.5.16)
B9 Part Switch (B9PartSwitch v2.18.0)
Bureaucracy (Bureaucracy 1.4)
Community Category Kit (CommunityCategoryKit v5.2.0.0)
Community Parts Titles (CommunityPartsTitles 0.8.2)
Community Resource Pack (CommunityResourcePack 1.4.2)
Cryo Tanks (CryoTanks 1.6.0)
Cryo Tanks Core (CryoTanks-Core 1.6.0)
Cryogenic Engines (CryoEngines 1:2.0.1)
Custom Barn Kit (CustomBarnKit 1.1.21.0)
Deployable Engines Plugin (DeployableEngines 1.3.1)
Destruction Effects (DestructionEffects 2:v1.12.0)
Editor Extensions Redux (EditorExtensionsRedux 3.4.3.4)
Ferram Aerospace Research Continued (FerramAerospaceResearchContinued 3:0.16.0.3)
Flight Tracker (FlightTracker 3.0.0.2)
FuelEfficientPilots (FuelEfficientPilots 0.2)
Heat Control (HeatControl 0.6.0)
Kerbal Attachment System (KAS 1.9)
Kerbal Changelog (KerbalChangelog v1.4.2)
Kerbal Construction Time (KerbalConstructionTime 1:1.4.11)
Kerbal Engineer Redux (KerbalEngineerRedux 1.1.9.0)
Kerbal Joint Reinforcement Continued (KerbalJointReinforcementContinued v3.5.2)
Kerbal Space Transport System (KSTS 2.0.2)
KRASH - Kerbal Ramification Artifical Simulation Hub (simulation mod for KSP) (KRASH 0.5.33.3)
MagiCore (MagiCore 1.3.2.3)
Making History (MakingHistory-DLC 1.12.0)
ModularFlightIntegrator (ModularFlightIntegrator 1.2.10.0)
Module Manager (ModuleManager 4.1.4)
Rational HydroDynamics (RationalHydroDynamics 1.1)
ReCoupler (ReCoupler 1:1.3.5)
RecoveryController (RecoveryController 0.0.4)
REPOSoftTech-Agencies (REPOSoftTech-Agencies V1.5.9.0)
Routine Mission Manager (RoutineMissionManager 1:0.4.0.1)
SpaceTux Library (SpaceTuxLibrary 0.0.6)
Spectra (Spectra v1.4.0)
Speed Unit Annex (SpeedUnitAnnex 1.4.0)
Staged Animation (StagedAnimation v2.0)
Station Keeping (StationKeeping 1:0.2.2.1)
Stockalike Station Parts Expansion Redux (StationPartsExpansionRedux 1.4.0)
Stockalike Station Parts Expansion Redux - Metal Surfaces (StationPartsExpansionRedux-Metal 1.4.0)
StockNoContracts (StockNoContracts v1.03)
Strategia (Strategia 1.8.0)
System Heat (SystemHeat 0.4.3)
Zero MiniAVC (ZeroMiniAVC 1:1.1.0.2)

Full mod list.

Flight Manager for Reusable Stages (FMRS) Continued (FMRSContinued 1.2.9.1)
4kSP_Expanded (4kSPExpanded 0.2.1.6)
AlphaMensae's Modular Launch Pads (ModularLaunchPads 2.2.0.b)
Approved Popular Pre-Launch Experiment (APPLE 1:1.1.9.1)
Astrogator (Astrogator v0.10.2)
AtmosphereAutopilot (Fly-By-Wire) (AtmosphereAutopilot v1.5.16)
B9 Part Switch (B9PartSwitch v2.18.0)
Benjee10 Suits (Benjee10Suits v1.0.1)
Better SR Bs (BetterSRBs 1.2.6)
BetterBurnTime (BetterBurnTime 1.10)
BetterTimeWarpContinued (BetterTimeWarpCont 2.3.12.9)
BonVoyage (BonVoyage 1:1.4.0)
Breaking Ground (BreakingGround-DLC 1.7.0)
Bureaucracy (Bureaucracy 1.4)
Chatterer (Chatterer 0.9.99)
Chatterer Extended (ChattererExtended 0.6.2)
ClickThrough Blocker (ClickThroughBlocker 1:0.1.10.17)
CommNet Relays (ContractConfigurator-CommNetRelays v2.1.0)
Community Category Kit (CommunityCategoryKit v5.2.0.0)
Community Delta-V Maps (CommunityDeltaVMaps 2:2.8)
Community Parts Titles (CommunityPartsTitles 0.8.2)
Community Resource Pack (CommunityResourcePack 1.4.2)
Community Tech Tree (CommunityTechTree 1:3.4.4)
Community Terrain Texture Pack (CommunityTerrainTexturePack 1:1.0.4)
Contract Configurator (ContractConfigurator 1.30.5)
Contract Pack: Bases and Stations Reborn (ContractConfigurator-KerbinSpaceStation 2:3.7.2.5)
Contract Pack: Clever Sats (ContractConfigurator-CleverSats 1.4)
Contract Pack: Exploration Plus (ContractConfigurator-ExplorationPlus 2.0.1)
Contract Pack: Tourism Plus (ContractConfigurator-Tourism 1.5.2)
Cryo Tanks (CryoTanks 1.6.0)
Cryo Tanks Core (CryoTanks-Core 1.6.0)
Cryogenic Engines (CryoEngines 1:2.0.1)
Custom Barn Kit (CustomBarnKit 1.1.21.0)
Custom Pre Launch Checks (CustomPreLaunchChecks 1.8.1)
Deployable Engines Plugin (DeployableEngines 1.3.1)
Destruction Effects (DestructionEffects 2:v1.12.0)
Distant Object Enhancement Continued (DistantObject v2.0.2.0)
Distant Object Enhancement Continued default config (DistantObject-default v2.0.2.0)
Docking Port Sound FX (DockingPortSoundFX v2.1.12)
Dynamic Battery Storage (DynamicBatteryStorage 2:2.2.4.0)
Earn Your Stripes! (EarnYourStripes 4.1)
Easy Vessel Switch (EVS) (EasyVesselSwitch 2.3)
Editor Extensions Redux (EditorExtensionsRedux 3.4.3.4)
Engine Lighting Relit (EngineLightRelit 1.6.3)
Environmental Visual Enhancements Redux (EnvironmentalVisualEnhancements 3:1.11.3.1)
EvaFollower (EvaFollower 1:1.1.1.12)
Far Future Technologies (FarFutureTechnologies 1.1.4)
Ferram Aerospace Research Continued (FerramAerospaceResearchContinued 3:0.16.0.3)
Flight Tracker (FlightTracker 3.0.0.2)
FuelEfficientPilots (FuelEfficientPilots 0.2)
Hangar Extender (HangerExtenderExtended 3.6.0)
Harmony 2 (Harmony2 2.0.4.0)
Heat Control (HeatControl 0.6.0)
Hide Empty Tech Tree Nodes (HideEmptyTechNodes 1.3.0)
Hot Spot (HotSpot 0.9.0)
Keep It Straight (KeepItStraight 1.3.0)
Kerbal Actuators (KerbalActuators v1.8.3)
Kerbal Atomics (KerbalAtomics 1:1.2.1)
Kerbal Atomics - Other Mod Support (KerbalAtomics-NTRModSupport 1.2.1)
Kerbal Attachment System (KAS 1.9)
Kerbal Changelog (KerbalChangelog v1.4.2)
Kerbal Construction Time (KerbalConstructionTime 1:1.4.11)
Kerbal Engineer Redux (KerbalEngineerRedux 1.1.9.0)
Kerbal Joint Reinforcement Continued (KerbalJointReinforcementContinued v3.5.2)
Kerbal Reusability Expansion (SpaceXLegs 2.9.1)
Kerbal Space Transport System (KSTS 2.0.2)
Kerbalism (Kerbalism 3.14)
Kerbalism - Default Config (Kerbalism-Config-Default 3.14)
Kerbalism Companion Calculator (KerbalismCompanionCalculator v1.3.0)
Kerbal-Konstructs (KerbalKonstructs 1.8.1.15)
Kerbin Side Remastered (KerbinSideRemastered 1.0.1)
Kerbin Side Remastered GAP (KerbinSideRemasteredGAP 1:v2.1.0)
Kiwi Tech Tree Overhaul (KiwiTechTree 1.4.0)
Kopernicus Planetary System Modifier (Kopernicus 2:release-1.12.1-55)
kOS: Scriptable Autopilot System (kOS 1:1.3.2.0)
KRASH - Kerbal Ramification Artifical Simulation Hub (simulation mod for KSP) (KRASH 0.5.33.3)
LoadingTipsPlus (LoadingTipsPlus V1.9)
MagiCore (MagiCore 1.3.2.3)
Making History (MakingHistory-DLC 1.12.0)
ManeuverNodeSplitter (NodeSplitter 1.8.0.2)
Minor Planets Expansion (MinorPlanetsExpansion 1.0.5)
ModularFlightIntegrator (ModularFlightIntegrator 1.2.10.0)
Module Manager (ModuleManager 4.1.4)
Navball Docking Alignment Indicator CE-2 (NavballDockAlignIndCE 1.1.1)
Near Future Aeronautics (NearFutureAeronautics 2.1.1)
Near Future Construction (NearFutureConstruction 1.3.1)
Near Future Electrical (NearFutureElectrical 1.2.3)
Near Future Electrical Core (NearFutureElectrical-Core 1.2.3)
Near Future Exploration (NearFutureExploration 1.1.2)
Near Future IVA Props (NearFutureProps 1:0.6.5)
Near Future Launch Vehicles (NearFutureLaunchVehicles 2.2.0)
Near Future Propulsion (NearFuturePropulsion 1.3.4)
Near Future Solar (NearFutureSolar 1.3.2)
Near Future Solar Core (NearFutureSolar-Core 1.3.2)
Near Future Spacecraft (NearFutureSpacecraft 1.4.2)
OPT Reconfig (OPTReconfig 3.4.1)
OPT Spaceplane Continued (OPTSpacePlaneMain 1:3.1.1)
Outer Planets Mod (OuterPlanetsMod 2:2.2.9)
Parallax (Parallax 1.3.0)
Parallax - Stock Planet Textures (Parallax-StockTextures 1.3.0)
PersistentRotation Upgraded (PersistentRotationUpgraded 1.9.1.4)
Planes With Purposes (ContractConfigurator-PlanesWithPurposes 1.4)
PlanetShine (PlanetShine 0.2.6.3)
PlanetShine - Default configuration (PlanetShine-Config-Default 0.2.6.3)
Precise Maneuver (PreciseManeuver 2:2.4.4)
Rational HydroDynamics (RationalHydroDynamics 1.1)
Rational Resources (RationalResources 1.19)
RCS Build Aid (RCSBuildAid v1.0.6)
RealHeat (RealHeat v5.1)
Realistic Atmospheres (RealisticAtmospheres 1.3.2)
ReCoupler (ReCoupler 1:1.3.5)
RecoveryController (RecoveryController 0.0.4)
Reentry Particle Effect Renewed (ReentryParticleEffect 1.9.1.1)
REPOSoftTech-Agencies (REPOSoftTech-Agencies V1.5.9.0)
ResearchBodies (ResearchBodies 2:V1.12.0)
ReStock (ReStock 1.4.1)
ReStock+ (ReStockPlus 1.4.1)
Rocket Sound Enhancement (RocketSoundEnhancement 0.5.4)
Rocket Sound Enhancment - Default Configs (RocketSoundEnhancement-Config-Default 0.5.3)
Routine Mission Manager (RoutineMissionManager 1:0.4.0.1)
RVE64k Kerbin Clouds for Spectra (RVE64kKerbinCloudsforSpectra 1.1)
SCANsat (SCANsat v20.4)
scatterer (Scatterer 3:v0.0772)
Scatterer Default Config (Scatterer-config 3:v0.0772)
Scatterer Sunflare (Scatterer-sunflare 3:v0.0772)
Smart Docking Aid (SmartDockingAid v1.1.0)
Smart Parts (SmartParts 1.9.16.1)
SmokeScreen - Extended FX Plugin (SmokeScreen 2.8.14.0)
Space Dust (SpaceDust 0.4.1)
SpaceTux Library (SpaceTuxLibrary 0.0.6)
Spectra (Spectra v1.4.0)
Speed Unit Annex (SpeedUnitAnnex 1.4.0)
Staged Animation (StagedAnimation v2.0)
Station Keeping (StationKeeping 1:0.2.2.1)
Stockalike Station Parts Expansion Redux (StationPartsExpansionRedux 1.4.0)
Stockalike Station Parts Expansion Redux - Metal Surfaces (StationPartsExpansionRedux-Metal 1.4.0)
StockNoContracts (StockNoContracts v1.03)
Strategia (Strategia 1.8.0)
System Heat (SystemHeat 0.4.3)
System Heat - Nuclear Engine Configuration (SystemHeat-FissionEngines 0.4.3)
System Heat - Nuclear Reactor Configuration (SystemHeat-FissionReactors 0.4.3)
System Heat - Resource Converter Configuration (SystemHeat-Converters 0.4.3)
System Heat - Resource Harvester Configuration (SystemHeat-Harvesters 0.4.3)
Toolbar (Toolbar 1:1.8.0.5)
Toolbar Controller (ToolbarController 1:0.1.9.4)
Tracking Station Evolved (TrackingStationEvolved 6.0)
Trajectories (Trajectories v2.4.1)
Waterfall - Restock (WaterfallRestock 0.2.2)
Waterfall Core (Waterfall 0.6.7)
Waypoint Manager (WaypointManager 2.8.3.1)
Zero MiniAVC (ZeroMiniAVC 1:1.1.0.2)

**Comment by ChrisAdderley** [comment]
We can't reasonably go through and figure this out- that's too many mods. I'll leave this open, please let us know if you can narrow it down.
