### ISSUE TITLE
Communotron 88 solar array default mesh as extended

### ISSUE THREAD

**Issue by Alewx** [PorktoberRevolution/ReStocked#965]
The Gigantor XL Solar Array starts as extended rather than retracted since 1.4.1.
This can be observed directly when launching a vessel including the part.
It can already be seen in the part explorer of the VAB AND SPH.

![20210723213652_1](https://user-images.githubusercontent.com/8604505/126833068-901236e5-ea6c-4651-8485-9b34c86aaf97.jpg)

[ksp 1.12 mods.txt](https://github.com/PorktoberRevolution/ReStocked/files/6870888/ksp.1.12.mods.txt)

**Comment by parthp7** [comment]
The same issue is also observed with other collapsible items such as Comunotron 88-88 which remains in extended position by default. Even if we close both of these (Communotron 88-88 and Gigantor XL Solar Array) during build and hit launch, the ship on launch pad spawns with both of these in open state. This is very annoying to fix before launch, especially when they are enclosed in payload fairing. 

One more thing to note here is that in it's default state, if we right click them, the first option comes out as "Extend solar panel" when the part already is in extended state. If clicked, it goes on to extend it again, then after clicking retract, does it actually go back to retracted state.

![20210806172706_1](https://user-images.githubusercontent.com/16664710/128507147-d4c69f56-1b69-43d9-99e2-e43e7ae743fe.jpg)
![20210806172715_1](https://user-images.githubusercontent.com/16664710/128507407-01d0b632-8740-43eb-bea8-eb60baa59657.jpg)
Attaching an example image in daylight. Eg. I've made a satellite with the solar arrays and a communotron 88-88 both of which show up outside the fairing when I try to launch the vehicle. If they had been extended during build, I wouldn't have been able to close the fairing :P .

Please fix this issue to keep both of these retracted by default.

**Comment by RyanRising** [comment]
With 1.4.2, it appears the Gigantor XL has had this issue corrected, but not the Communotron 88-88. With the latter part, the behavior is the same as it was during 1.4.1

**Comment by BendoZ** [comment]
Any news about this bug ? i have the same issues with the Communotron 88, and its killing me.
If not just tell me how can i use the squad skin just for the Communotron, and keep restock for the other parts ? 
Thk u

**Comment by Gordon-Dry** [comment]
I guess you mean Squad/Parts/Utility/commDish88-88/

**Comment by BendoZ** [comment]
Yeah i think ur right, my bad i dont remember, the process is the same you have to target the part you want to have the squad skin

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/eb3f3227d95ddc7ad2bcad51d01aee21327e7b8f
