### ISSUE TITLE
Oscar B volume fix

### ISSUE THREAD

**Issue by jdmj** [PorktoberRevolution/ReStocked#967]
ReStockPlus/Patches/FuelTanks/restock-oscar-b-volume-fix.cfg
The patch doesn't work if there's a fuel switch mod installed. Encountered with InterstellarFuelSwitch but I'm sure it will happen with any mod which uses resource values for its own calculations and loads before Restock. It happens because IFS loads first and generates tank configs from stock values, then Restock loads, then the patch is applied (which doesn't change a thing because IFS configs are already in place). Not sure why there's :AFTER directive at all, :FIRST would be more appropriate for this patch, I think, since it's supposed to fix stock values.

**Comment by ChrisAdderley** [comment]
I await your tested pull request.

**Comment by Poodmund** [comment]
Fixed with https://github.com/PorktoberRevolution/ReStocked/commit/305416c10259f357dc6508bdba90829df87dac5a
