### ISSUE TITLE
Missing IVA textures

### ISSUE THREAD

**Issue by shahidsp** [PorktoberRevolution/ReStocked#971]
The IVA textures for the SP-1 'Clementine' Reentry Module, SP-2 'Tangerine' Reentry Module, SP-3 'Mandarin' Reentry Module, and the Mk2 "Acorn" Command Pod are missing. The IVAs are just black. I tried reinstalling both restock and restock+ but that didn't help

![screenshot0](https://user-images.githubusercontent.com/73202126/128959980-9f9afc7b-1825-45b1-84b5-e9b638349bd7.png)
interior overlay and portraits

![screenshot1](https://user-images.githubusercontent.com/73202126/128959982-bf7769b5-fdcc-43ce-b193-ee871f574839.png)
Mk2 "Acorn" Command Pod

![screenshot2](https://user-images.githubusercontent.com/73202126/128959983-d43d9260-c888-4d3d-88ef-f83892bbc5b5.png)
SP-2 'Tangerine' Reentry Module

![screenshot22](https://user-images.githubusercontent.com/73202126/128959985-38ab584f-817c-4cd8-95fd-3a43d0a5c0fb.png)
SP-3 'Mandarin' Reentry Module

![screenshot23](https://user-images.githubusercontent.com/73202126/128959986-dd2b52d5-cb5e-429d-8ee3-5db4c08fa568.png)
SP-1 'Clementine' Reentry Module

Mods List (sorry its long)
 - Restock
 - Restock Plus
 - click through blocker
 - toolbar control
 - Astronomers visual pack
 - b9 part switch
 - better time warp
 - community category kit
 - community resource pack
 - contract configurator
 - contract packs
 - deployable engines
 - environmental visual enhancements
 - Kerbal attachment system
 -  Kerbal engineer
 - Kerbal inventory for all
 - Kerbal inventory system
 - Near future construction
 - near future electrical
 - near future launch vehicles
 - near future props
 - near future propulsion
 - near future solar
 - near future spacecraft
 - planetary base inc
 - planet shine
 - scatterer
 - Sigma
 - station parts expansion redux
 - tarsier space tech
 - waypoint manager
 - kspmodfilelocalizer.dll
 - module manager 4.1.4
 - module manager.configcache
 - module manger. configSHA
 - modulemanager.physics
 - modulemanager.techtree

log
[KSP.log](https://github.com/PorktoberRevolution/ReStocked/files/6965544/KSP.log)

**Comment by ChrisAdderley** [comment]
These IVAs use the Making History ones which we can't redistribute for obvious reasons. Maybe far in the future someone will make a custom one, but this is working as intended.
