### ISSUE TITLE
Restock's Mystery Goo texture animation causes SEVERE FPS drops

### ISSUE THREAD

**Issue by Alexsys** [PorktoberRevolution/ReStocked#977]
I love the new textures of the science things, they are absolutely golden, amazing how restock does a much better job at that than even squad could.

The mystery goo though causes severe frame drops when the animation plays of it opening or closing, or restoring, it can absolutely kill a vessel if you suddenly decide to get some science while moving, the drops are severe.

**Comment by ChrisAdderley** [comment]
Can't reproduce this.

**Comment by Alexsys** [comment]
> Can't reproduce this.

Real odd actually.

i just returned to play KSP today, and saw your message,
surprisingly the goos cause a stutter lag whenever they are on a certain ship (objects in the world) for me.

They just either stutter due to just existing, even if being closed, or caused this severe fps drops during opening (which is what it used to be, doesnt seem to be anymore though.)

Do you not experience frame stutters when having, lets say 2 bin of mystery goo just on your ship?
it gets worse the bigger the ship, doesnt have to be immensly huge though.

**Comment by Alexsys** [comment]
Do let me know if you'd need any specific additional stuff, like log or whatever, that might help

**Comment by Alexsys** [comment]
Withdrawing,
after removing restock and testing without restock the lag of the goo still remains
my bad, wasnt associated with restock
