### ISSUE TITLE
[request] Add part connection node to the 1.25m chute and drogue chute for easier use with escape tower.

### ISSUE THREAD

**Issue by truehunterethan** [PorktoberRevolution/ReStocked#979]
What I assume most people do is place the 1.25m chute to the top of the 2.5m capsule, but this takes up the space for the escape tower. I am requesting to either add a node to the top of the chute so we can put the escape tower AND the chute on the capsule. :)

**Comment by ChrisAdderley** [comment]
You can do this with module manager.
