### ISSUE TITLE
Suggestion, Paraglider part(s)

### ISSUE THREAD

**Issue by NightShift10125** [PorktoberRevolution/ReStocked#981]
This is a suggestion to add the kerbal's parachute as a part for restock.
Turns out NASA has attempted to use paragliders in the past so it not totally crazy, I can see such a part being used as a form of landing assist or to make Eve/Duna/Laythe paragliders which would be cheaper and lighter than normal drones.

https://www.youtube.com/watch?v=jub8y6WSI8M

https://www.youtube.com/watch?v=0OkiRt5Etbw

**Comment by Poodmund** [comment]
Closed and moved to Wishlist.
