### ISSUE TITLE
Restock Inflatable Heat Shield does not protect all its 10m diameter

### ISSUE THREAD

**Issue by yalov** [PorktoberRevolution/ReStocked#983]
**Describe the bug**
KSP 1.12.3, Collide-O-Scope shows that the "Mesh" of the part (blue thingy) cover and protect only a half of the diameter of the heat shield in the restock.

**Screenshots**

* Stock:
   ![image](https://user-images.githubusercontent.com/12796450/147668341-58724a27-e6f5-418d-82da-33eb074c506b.png)

* Restock: 
  ![image](https://user-images.githubusercontent.com/12796450/147668360-e9e9fd52-ebd9-4b0f-a625-c5c840abb7fd.png)

**List of mods installed:**
 - Restock
 - Collide-O-Scope

@Poodmund have confirmed this issue.

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/4f8eaf639e51da0778938f4eba4810bc09d21f3a
