### ISSUE TITLE
Integrate the ReStock Plus 1.25m Engine plate into ReStock base due to addition of Making History SQUAD part

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#985]
KSP Version 1.12.0 added a 1.25m Engine Plate to Making History of which RS currently caters for in ReStock Plus. This causes the Making History 1.25m Engine Plate to appear alongside the ReStock Plus version.

There is a pull request that can be referred to with a suggestion for the patching (https://github.com/PorktoberRevolution/ReStocked/pull/984/files) but colliders and bits will need to be checked to make sure everything lines up etc.

**Comment by ChrisAdderley** [comment]
PR was merged.

**Comment by Poodmund** [comment]
All resolved as per https://github.com/PorktoberRevolution/ReStocked/commit/66f3d8c9fbdef61d2aa7262bfcad7496b8852266 and the handful of commits before that.
