### ISSUE TITLE
Mainsail 1.875m variants still using 2.5m shroud.

### ISSUE THREAD

**Issue by fadedparadox** [PorktoberRevolution/ReStocked#989]
Mainsail variants 1.875 (White Shroud) and 1.875 (Orange/Grey Shroud) use a 2.5m shroud.

**Comment by Poodmund** [comment]
The variant names of 1.875m refer to the diameter of the mounting truss at the top of the part, not the diameter of the fairing shroud. The plumbing of the engine exceeds the bounds of a 1.875m diameter cylinder and so a 1.875m fairing shroud would not actually fit around the engine (you can prove this by clipping a 1.875m tank into the engine and seeing the plumbing clipping through the outside).

Maybe a slightly confusing variant name but its the intended behaviour.
