### ISSUE TITLE
RestockPlus throws a bunch of "Variable MHReplacement not found in Part"

### ISSUE THREAD

**Issue by Alexsys** [PorktoberRevolution/ReStocked#990]
Greetings legendary restock devs!

I was wondering if all those warnings / exceptions are nothing to worry about or perhaps are some kind of an issue?
Do let me know whether its all fine and dandy or a kerbal kraken :)

[ed.log](https://github.com/PorktoberRevolution/ReStocked/files/8553276/ed.log

**Comment by drewcassidy** [comment]
What is "ed" in this context?

**Comment by drewcassidy** [comment]
Can you post the full log?

**Comment by Alexsys** [comment]
Certainly!
[KSP.log](https://github.com/PorktoberRevolution/ReStocked/files/8565316/KSP.log)


Ed is Exceptions detector mod

**Comment by drewcassidy** [comment]
Looks like you have some missing folders in the gamedata/squad folder and the blacklister is complaining. Those errors are harmless

**Comment by Alexsys** [comment]
Thanks for letting me know.

I am surprised about the missing folders in the gamedata/squad folder part, since every time I verify the game I'm prisitine, not a thing missing.

Could it be the fact maybe that some restock/restock+ items are automatically blacklisted once a KSP DLC is loaded, and something as such that I've read, that may be the origin of those processes?
