### ISSUE TITLE
Landing legs, launch clamps & fairing bases are broken.

### ISSUE THREAD

**Issue by made-this-acct-bc-i-had-to** [PorktoberRevolution/ReStocked#994]
Title says it all. The animations for the landing legs and launch clamps are broken as they show both the 'deployed' and 'stowed' versions at the same time. The mesh for the fairing base also shows the metallic gold one overlapping whatever colour I select. All of these bugs are present both in-game and in the VAB, no idea what could be causing them and I haven't found anyone else with the same problem.

**List of mods installed:**
- Animated Decouplers
- B9 Part Switch
- Planetside Exploration Tech
- Chatterer
- KAS
- Kerbal Engineer
- Restock & Restock +
- Scatterer
- Trajectories
- Waterfall
- Module Manager 4.2.2

![whydoyoudothistomerestock](https://user-images.githubusercontent.com/109252826/178855345-f9d27b27-0b96-4559-bf80-1aead8858da8.jpg)

Any help is greatly appreciated, thank you!

**Comment by H4m4k** [comment]
I had the same issue - what I did to fix is below:
Installations are managed by CKAN
- remove Restock
- install Ven Stock Revamp ( Vehicles get obsolete when you do that , so watch it! ) 
- run KSP
- remove Ven Stock Revamp
- install Restock + Restock +
- solved
