### ISSUE TITLE
Engine plates have a weight issue

### ISSUE THREAD

**Issue by Alex-1248** [PorktoberRevolution/ReStocked#996]
1: EP-25, EP-37 and EP-50 from Restock+ are lighter than EP-18. The problem disappears if Making History is instaled.
2: When changing the length of the shroud, the EP-12 from Restock+ changes its weight in 5 kg increments, just like the EP-18. For comparison, the EP-12 from Making History changes its weight in 2.5 kg increments. The variant from Restock is used even if Making History is installed and Restock+ is not installed. I don't know if this is a bug, but I think the EP-12 and EP-18 should change weight in different increments.

**Comment by Poodmund** [comment]
I can see the issue. Just to confirm, none of this. I'll take a look into the ReStock part variants and try to align them to Making History and look at ReStock+ and align them to Making History.

**Comment by Poodmund** [comment]
@Alex-1248 this should be resolved with commit: https://github.com/PorktoberRevolution/ReStocked/commit/26bd8939b0f5867b6efe3cb17a44c0dc02738f17 

If you have the means to verify and confirm, please do.

**Comment by Alex-1248** [comment]
I see an error in this commit: restock-engineplate-125-2.cfg, line 582, should be -0.0025 instead of -0.00025. The rest of the edits look correct.

**Comment by Poodmund** [comment]
Good eyes. Thank you. I'll now mark this as resolved and will be fixed whenever the next release is made. For now, you can use the files affect by the recent commits if you want to fix this early. :D
