### ISSUE TITLE
Incorrect location of engine mount points on Kerbodyne Engine Cluster Adapter Tank

### ISSUE THREAD

**Issue by Alex-1248** [PorktoberRevolution/ReStocked#997]
If Restock is installed, the engine mount points on the Kerbodyne Engine Cluster Adapter Tank from Making History are not symmetrical in all variants. The center of thrust does not coincide with the center of mass and a symmetrical rocket cannot fly straight without the help of SAS. The problem also occurs if Restock+ is installed and Making History is not installed.

**Comment by Poodmund** [comment]
Yeah I can see that the node attach transforms in the .mu are not evenly spaced around the origin which would result in thrust torque.

This fix would require work within the model itself and a re-export.

**Comment by Poodmund** [comment]
Putting in here for future reference, the coordinate location values for the node transforms need to be as follows:

N2/N4 attach node setup: 1.76777
N3/N6 attach node setup: 1.3, 2.5 & 2.16506, 1.25

**Comment by Poodmund** [comment]
@Alex-1248, I attempted to fix the .mu model by relocating the engine node transforms to the correct positions but upon export using Taniwha's .mu Import/Export plugin it was causing the file size to balloon to over twice the size... so I came up with a great temporary solution without needing the original source file, I've created a new .mu that ONLY contains the engine node transforms and edited the part config file to also load this .mu into the part, and subsequently switched all the engine node transform references over to the additional .mu.

You can see the changes here: https://github.com/PorktoberRevolution/ReStocked/commit/dd2bbade5b4959fb7c7725fd5be8d360b4cd4e80

Can you download the new .mu and updated config and give it a test? I loaded it in alongside Kerbal Engineer Redux and also RCS Build Aid and it appeared to resolve the issue and reduce thrust torque to near-zero (I expect floating point error induces extremely slight transform differences).

**Comment by Alex-1248** [comment]
I tested it.

The problem no longer appears if Making History is installed.

But the problem still appears if Making History is not installed and Restock+ is installed.

**Comment by Poodmund** [comment]
Thank you for confirming (after all this time 😅), I did push an additional commit to cover RS+ but will go back and test it.

**Comment by Poodmund** [comment]
Just checked myself, all sorted with MH not installed using the RS+ version with this commit: https://github.com/PorktoberRevolution/ReStocked/commit/d0aabec3d439ef9a5135afc89d9a133f3a3849bb

Closing for now.
